import { useEffect, useMemo, useState } from 'react'
import { BarChart3, BriefcaseBusiness, CircleDollarSign, FileText, FlaskConical, TrendingUp, Users } from 'lucide-react'
import { PageShell } from '../../components/ui/PageShell'
import { UserAvatar } from '../../components/users/UserAvatar'
import { supabase } from '../../services/supabase'

type Proposal={id:string;cliente_id:string|null;responsavel_comercial_id:string|null;valor:number|null;status:string|null;created_at:string;data_envio:string|null}
type Opportunity={id:string;estagio:string|null;status:string|null;valor_estimado:number|null;created_at:string;responsavel_id:string|null}
type Client={id:string;segmento:string|null;ativo:boolean}
type Profile={id:string;nome:string|null;avatar_url:string|null}
type RepRow={id:string;nome:string;avatar_url:string|null;propostas:number;valor:number;aprovadas:number;conversao:number}
type QueryResult<T>={data:T[]|null;error:{message:string}|null}
type Pair=[string,number]
type AnalyticReport={services?:Pair[]}
const PAGE_SIZE=1000
async function fetchAll<T>(makeQuery:(from:number,to:number)=>PromiseLike<QueryResult<T>>){const rows:T[]=[];for(let from=0;;from+=PAGE_SIZE){const result=await makeQuery(from,from+PAGE_SIZE-1);if(result.error)return{data:rows,error:result.error};const batch=(result.data??[]) as T[];rows.push(...batch);if(batch.length<PAGE_SIZE)return{data:rows,error:null}}}
const months=['Todos os meses','Janeiro','Fevereiro','Março','Abril','Maio','Junho','Julho','Agosto','Setembro','Outubro','Novembro','Dezembro']
const isApproved=(status:string|null)=>/ACEIT|APROV|FECHAD/i.test(status??'')

export function Inteligencia(){
 const[p,setP]=useState<Proposal[]>([]);const[o,setO]=useState<Opportunity[]>([]);const[c,setC]=useState<Client[]>([]);const[profiles,setProfiles]=useState<Profile[]>([]);const[services,setServices]=useState<Pair[]>([]);const[error,setError]=useState('');const[serviceError,setServiceError]=useState('');const[year,setYear]=useState('TODOS');const[month,setMonth]=useState('0');const[repFilter,setRepFilter]=useState('TODOS')
 useEffect(()=>{void(async()=>{const[a,b,d,f]=await Promise.all([
  fetchAll<Proposal>((from,to)=>supabase.from('propostas').select('id,cliente_id,responsavel_comercial_id,valor,status,created_at,data_envio').is('deleted_at',null).order('created_at',{ascending:false}).range(from,to)),
  fetchAll<Opportunity>((from,to)=>supabase.from('oportunidades').select('id,estagio,status,valor_estimado,created_at,responsavel_id').is('deleted_at',null).order('created_at',{ascending:false}).range(from,to)),
  fetchAll<Client>((from,to)=>supabase.from('clientes').select('id,segmento,ativo').is('deleted_at',null).order('id',{ascending:true}).range(from,to)),
  fetchAll<Profile>((from,to)=>supabase.from('profiles').select('id,nome,avatar_url').order('nome').range(from,to))
 ]);const err=a.error||b.error||d.error||f.error;if(err)setError(err.message);else{setError('');setP(a.data);setO(b.data);setC(d.data);setProfiles(f.data)}})()},[])
 useEffect(()=>{let active=true;void(async()=>{const{data,error}=await supabase.rpc('crm_relatorios_analitico',{p_year:year==='TODOS'?null:Number(year),p_month:month==='0'?null:Number(month)});if(!active)return;if(error){setServices([]);setServiceError(error.message)}else{const raw=(data??{}) as AnalyticReport;setServices((raw.services??[]) as Pair[]);setServiceError('')}})();return()=>{active=false}},[year,month])
 const years=useMemo(()=>{const set=new Set<string>();p.forEach(x=>{const y=new Date(x.data_envio||x.created_at).getFullYear();if(Number.isFinite(y))set.add(String(y))});return ['TODOS',...Array.from(set).sort().reverse()]},[p])
 const filteredP=useMemo(()=>p.filter(x=>{const d=new Date(x.data_envio||x.created_at);if(year!=='TODOS'&&String(d.getFullYear())!==year)return false;if(month!=='0'&&d.getMonth()+1!==Number(month))return false;if(repFilter!=='TODOS'&&x.responsavel_comercial_id!==repFilter)return false;return true}),[p,year,month,repFilter])
 const filteredO=useMemo(()=>o.filter(x=>{const d=new Date(x.created_at);return(year==='TODOS'||String(d.getFullYear())===year)&&(month==='0'||d.getMonth()+1===Number(month))&&(repFilter==='TODOS'||x.responsavel_id===repFilter)}),[o,year,month,repFilter])
 const total=filteredP.reduce((s,x)=>s+Number(x.valor??0),0);const accepted=filteredP.filter(x=>isApproved(x.status)).length;const conversion=filteredP.length?accepted/filteredP.length*100:0
 const stages=useMemo(()=>Object.entries(filteredO.reduce<Record<string,number>>((m,x)=>{const k=x.estagio||x.status||'Sem estágio';m[k]=(m[k]||0)+1;return m},{})).sort((a,b)=>b[1]-a[1]) as Pair[],[filteredO]);const classifiedClients=c.filter(x=>x.segmento&&x.segmento.trim());const segments=useMemo(()=>Object.entries(classifiedClients.reduce<Record<string,number>>((m,x)=>{const k=String(x.segmento).trim();m[k]=(m[k]||0)+1;return m},{})).sort((a,b)=>b[1]-a[1]).slice(0,10) as Pair[],[c]);const profileNames=useMemo(()=>Object.fromEntries(profiles.map(x=>[x.id,x])),[profiles])
 const reps=useMemo(()=>{const map:Record<string,{propostas:number;valor:number;aprovadas:number}>={};filteredP.forEach(row=>{const id=row.responsavel_comercial_id||'SEM_RESPONSAVEL';const cur=map[id]??{propostas:0,valor:0,aprovadas:0};cur.propostas++;cur.valor+=Number(row.valor??0);if(isApproved(row.status))cur.aprovadas++;map[id]=cur});return Object.entries(map).map(([id,v]):RepRow=>{const person=profileNames[id];return{id,nome:id==='SEM_RESPONSAVEL'?'Sem responsável':person?.nome||`Usuário ${id.slice(0,8)}`,avatar_url:person?.avatar_url||null,propostas:v.propostas,valor:v.valor,aprovadas:v.aprovadas,conversao:v.propostas?v.aprovadas/v.propostas*100:0}}).sort((a,b)=>b.propostas-a.propostas)},[filteredP,profileNames])
 const openOpportunities=filteredO.filter(x=>!['GANHO','PERDIDO'].includes((x.estagio||'').toUpperCase())&&!['CANCELADA'].includes((x.status||'').toUpperCase())).length
 const conversionStages=[['Oportunidades',filteredO.length],['Oportunidades abertas',openOpportunities],['Propostas',filteredP.length],['Propostas aprovadas',accepted]] as Pair[]
 const monthly=useMemo(()=>Array.from({length:12},(_,i)=>{const rows=filteredP.filter(x=>new Date(x.data_envio||x.created_at).getMonth()===i);const approvedRows=rows.filter(x=>isApproved(x.status));return{label:new Date(2025,i,1).toLocaleDateString('pt-BR',{month:'short'}),sent:rows.length,approved:approvedRows.length,value:rows.reduce((s,x)=>s+Number(x.valor??0),0),approvedValue:approvedRows.reduce((s,x)=>s+Number(x.valor??0),0)}}),[filteredP]);const maxMonth=Math.max(1,...monthly.map(x=>Math.max(x.sent,x.approved)))
 const activeClients=c.filter(x=>x.ativo).length;const clientsInProposals=new Set(filteredP.map(x=>x.cliente_id).filter(Boolean)).size
 return <PageShell title="Inteligência Comercial" description="Transforme dados de clientes, propostas e serviços em decisões comerciais.">
  {error&&<div className="rounded-xl bg-red-50 p-3 text-sm text-red-700">{error}</div>}{serviceError&&<div className="rounded-xl bg-amber-50 p-3 text-sm text-amber-800">Serviços: {serviceError}</div>}
  <div className="flex flex-wrap gap-2"><select value={year} onChange={e=>setYear(e.target.value)} className="rounded-xl border bg-white px-4 py-2.5 text-sm font-semibold">{years.map(x=><option key={x} value={x}>{x==='TODOS'?'Todos os anos':x}</option>)}</select><select value={month} onChange={e=>setMonth(e.target.value)} className="rounded-xl border bg-white px-4 py-2.5 text-sm font-semibold">{months.map((label,i)=><option key={i} value={String(i)}>{label}</option>)}</select><select value={repFilter} onChange={e=>setRepFilter(e.target.value)} className="rounded-xl border bg-white px-4 py-2.5 text-sm font-semibold"><option value="TODOS">Responsável: Todos</option>{profiles.map(x=><option key={x.id} value={x.id}>{x.nome||'Sem nome'}</option>)}</select></div>
  <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-5"><Metric icon={Users} label="Clientes ativos" value={activeClients}/><Metric icon={BriefcaseBusiness} label="Oportunidades" value={filteredO.length}/><Metric icon={FileText} label="Propostas no período" value={filteredP.length}/><Metric icon={CircleDollarSign} label="Valor proposto" value={money(total)}/><Metric icon={TrendingUp} label="Aprovação sobre enviadas" value={`${conversion.toFixed(1)}%`}/></section>
  <section className="grid gap-5 xl:grid-cols-[1.25fr_.7fr_1fr]"><article className="rounded-3xl border bg-white p-6 shadow-sm"><h3 className="font-bold">Evolução comercial</h3><p className="mt-1 text-xs text-slate-500">Passe o mouse sobre cada barra para ver quantidade e valor.</p><div className="mt-6 flex h-64 items-end gap-3">{monthly.map((m,i)=><div key={i} className="flex h-full flex-1 flex-col justify-end"><div className="flex flex-1 items-end justify-center gap-1"><div title={`Propostas enviadas: ${m.sent} · Valor enviado: ${money(m.value)}`} className="w-4 rounded-t bg-blue-500" style={{height:`${Math.max(4,m.sent/maxMonth*100)}%`}}/><div title={`Propostas aprovadas: ${m.approved} · Valor aprovado: ${money(m.approvedValue)}`} className="w-4 rounded-t bg-teal-600" style={{height:`${Math.max(4,m.approved/maxMonth*100)}%`}}/></div><div className="mt-2 text-center text-xs text-slate-500">{m.label}</div></div>)}</div><div className="mt-4 flex gap-5 text-xs text-slate-500"><span>■ Propostas enviadas</span><span className="text-teal-700">■ Propostas aprovadas</span></div></article><article className="rounded-3xl border bg-white p-6 shadow-sm"><h3 className="font-bold">Conversão por etapa</h3><div className="mt-5 space-y-4">{conversionStages.map(([label,value])=><div key={label}><div className="flex justify-between text-sm"><span>{label}</span><strong>{value}</strong></div><div className="mt-1 h-3 rounded-full bg-slate-100"><div className="h-3 rounded-full bg-teal-600" style={{width:`${Math.min(100,conversionStages[0][1]?value/conversionStages[0][1]*100:0)}%`}}/></div></div>)}</div><div className="mt-5 rounded-xl border p-3 text-center text-sm">Aprovação sobre enviadas: <strong className="text-teal-700">{conversion.toFixed(1)}%</strong></div></article><article className="rounded-3xl border bg-white p-6 shadow-sm"><h3 className="font-bold">Desempenho por representante</h3><p className="mt-1 text-xs leading-5 text-slate-500">A porcentagem é a <strong>taxa de aprovação das propostas</strong>: propostas aprovadas ÷ propostas do representante no filtro selecionado.</p><div className="mt-4 divide-y">{reps.length?reps.slice(0,8).map((r,i)=><div key={r.id} className="grid grid-cols-[24px_40px_1fr_auto] items-center gap-2 py-3 text-sm"><span>{i+1}</span><UserAvatar name={r.nome} avatarUrl={r.avatar_url} size="sm"/><div><div className="font-medium">{r.nome}</div><div className="text-xs text-slate-500">{r.aprovadas} aprovada(s) de {r.propostas} · {money(r.valor)}</div></div><strong>{r.conversao.toFixed(1)}%</strong></div>):<p className="py-6 text-center text-sm text-slate-500">Sem propostas no filtro.</p>}</div></article></section>
  <section className="grid gap-5 xl:grid-cols-3"><Rank title="Pipeline observado" rows={stages.slice(0,5)}/><article className="rounded-3xl border bg-white p-6 shadow-sm"><h3 className="font-bold">Clientes por segmento — Top 10</h3>{segments.length?<RankBody rows={segments}/>:<div className="mt-5 rounded-2xl bg-slate-50 p-5 text-sm text-slate-600"><strong>Segmentos ainda não classificados.</strong><p className="mt-2">Os clientes existentes estão sem o campo Segmento preenchido. O ranking começará a funcionar automaticamente conforme esse cadastro for informado.</p></div>}</article><Rank title="Serviços mais demandados" rows={services.slice(0,8)} icon={<FlaskConical className="h-5 w-5 text-teal-700"/>} note="Baseado nos serviços efetivamente executados nas amostras/resultados do período. Este ranking não depende de itens de proposta e, por isso, continua funcionando com o histórico importado."/></section>
  <section className="rounded-3xl border bg-white p-6 shadow-sm"><div className="flex items-center gap-2"><BarChart3 className="h-5 w-5 text-teal-700"/><h3 className="font-bold">Sinais de oportunidade</h3></div><div className="mt-5 grid gap-4 md:grid-cols-3"><Signal title="Segmento líder" text={segments[0]?`${segments[0][0]} possui ${segments[0][1]} cliente(s) classificados.`:'Ainda não é possível calcular: o campo Segmento não está preenchido nos clientes.'}/><Signal title="Clientes sem proposta no período" text={`${Math.max(0,activeClients-clientsInProposals)} cliente(s) ativo(s) não aparecem nas propostas filtradas.`}/><Signal title="Serviço mais demandado" text={services[0]?`${services[0][0]} aparece em ${services[0][1]} execução(ões) analítica(s) no período.`:'Não há serviços executados para o período selecionado.'}/></div></section>
 </PageShell>
}
function money(v:number){return v.toLocaleString('pt-BR',{style:'currency',currency:'BRL'})}
function Metric({icon:Icon,label,value}:{icon:typeof Users;label:string;value:string|number}){return <article className="flex h-20 items-center gap-3 rounded-3xl border bg-white p-4 shadow-sm"><span className="grid h-11 w-11 shrink-0 place-items-center rounded-full bg-teal-50 text-teal-700"><Icon className="h-5 w-5"/></span><div className="min-w-0"><div className="text-xs text-slate-500">{label}</div><strong className="mt-1 block truncate text-xl text-slate-900">{value}</strong></div></article>}
function Rank({title,rows,icon,note}:{title:string;rows:Pair[];icon?:React.ReactNode;note?:string}){return <article className="rounded-3xl border bg-white p-6 shadow-sm"><div className="flex items-center gap-2">{icon}<h3 className="font-bold">{title}</h3></div>{note&&<p className="mt-1 text-xs leading-5 text-slate-500">{note}</p>}<RankBody rows={rows}/></article>}
function RankBody({rows}:{rows:Pair[]}){const max=Math.max(1,...rows.map(x=>x[1]));return <div className="mt-5 space-y-4">{rows.length===0?<p className="text-sm text-slate-500">Sem dados.</p>:rows.map(([k,v],i)=><div key={k}><div className="mb-1 flex justify-between gap-3 text-sm"><span className="truncate"><strong className="mr-2 text-teal-700">{i+1}</strong>{k}</span><strong>{v}</strong></div><div className="h-2 rounded-full bg-slate-100"><div className="h-2 rounded-full bg-teal-600" style={{width:`${v/max*100}%`}}/></div></div>)}</div>}
function Signal({title,text}:{title:string;text:string}){return <article className="rounded-2xl border border-teal-100 bg-teal-50/30 p-5"><h4 className="font-bold text-slate-900">{title}</h4><p className="mt-2 text-sm leading-6 text-slate-600">{text}</p></article>}
