import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import{createClient}from"https://esm.sh/@supabase/supabase-js@2.45.0";
const J=Deno.env.get("ML_JWT_SECRET")||"",U=Deno.env.get("SUPABASE_URL")!,K=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;const sb=createClient(U,K,{auth:{persistSession:false,autoRefreshToken:false}});const enc=new TextEncoder(),dec=new TextDecoder();const cors={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization, content-type","Access-Control-Allow-Methods":"POST, OPTIONS"};const json=(b:any,s=200)=>new Response(JSON.stringify(b),{status:s,headers:{...cors,"Content-Type":"application/json","Cache-Control":"no-store"}});const dig=(v:any)=>String(v||"").replace(/\D/g,"");const txt=(v:any)=>String(v??"").trim();const err=(e:any)=>e instanceof Error?e.message:(e?.message||e?.details||e?.hint||e?.code||String(e));
function b64u(s:string){s=s.replace(/-/g,"+").replace(/_/g,"/");while(s.length%4)s+="=";const b=atob(s),o=new Uint8Array(b.length);for(let i=0;i<b.length;i++)o[i]=b.charCodeAt(i);return o}async function auth(req:Request){const t=(req.headers.get("authorization")||"").replace(/^Bearer\s+/i,"");if(!t||!J)return null;const p=t.split(".");if(p.length!==3)return null;try{const k=await crypto.subtle.importKey("raw",enc.encode(J),{name:"HMAC",hash:"SHA-256"},false,["verify"]);if(!await crypto.subtle.verify("HMAC",k,b64u(p[2]),enc.encode(`${p[0]}.${p[1]}`)))return null;const x=JSON.parse(dec.decode(b64u(p[1])));if(x.sis!=="minaslab"||(x.exp&&x.exp<Math.floor(Date.now()/1000))||txt(x.papel)!=="direcao")return null;return x}catch{return null}}
Deno.serve(async req=>{if(req.method==="OPTIONS")return new Response("ok",{headers:cors});if(!await auth(req))return json({erro:"Sessão inválida ou sem permissão."},401);try{const b=await req.json(),a=txt(b.action);if(a==="listar"){const q=await sb.from("clientes_financeiro").select("*").order("ativo",{ascending:false}).order("nome").limit(3000);if(q.error)throw q.error;const s=txt(b.busca).toLowerCase();return json({itens:s?(q.data||[]).filter((x:any)=>[x.nome,x.nome_fantasia,x.cnpj_cpf,x.id_omie].some(v=>txt(v).toLowerCase().includes(s))):q.data||[]})}
if(a==="cep"){const cep=dig(b.cep);if(cep.length!==8)return json({erro:"CEP inválido."},400);const r=await fetch(`https://viacep.com.br/ws/${cep}/json/`,{headers:{Accept:"application/json"}});if(!r.ok)return json({erro:"Não foi possível consultar o CEP."},502);const d=await r.json();if(d.erro)return json({erro:"CEP não encontrado."},404);return json({cep,logradouro:d.logradouro||"",complemento:d.complemento||"",bairro:d.bairro||"",cidade:d.localidade||"",uf:d.uf||""})}
if(a==="salvar"){const r=b.registro||{};if(!txt(r.nome))return json({erro:"Nome/Razão Social é obrigatório."},400);const doc=dig(r.cnpj_cpf);let existente:any=null;if(doc){const q=await sb.from("clientes_financeiro").select("*").not("cnpj_cpf","is",null).limit(5000);if(q.error)throw q.error;existente=(q.data||[]).find((x:any)=>dig(x.cnpj_cpf)===doc&&x.id!==r.id&&!x.mesclado_para)||null;if(existente&&!r.id)return json({erro:`Já existe um cliente com este CPF/CNPJ: ${existente.nome}. Edite ou mescle o cadastro em vez de criar outro.`,duplicado:existente},409)}const id=r.id||null;const p={nome:txt(r.nome),nome_fantasia:txt(r.nome_fantasia)||null,cnpj_cpf:txt(r.cnpj_cpf)||null,inscricao_estadual:txt(r.inscricao_estadual)||null,inscricao_municipal:txt(r.inscricao_municipal)||null,email:txt(r.email)||null,telefone:txt(r.telefone)||null,cep:dig(r.cep)||null,logradouro:txt(r.logradouro)||null,numero:txt(r.numero)||null,complemento:txt(r.complemento)||null,bairro:txt(r.bairro)||null,cidade:txt(r.cidade)||null,uf:txt(r.uf).toUpperCase()||null,origem:txt(r.origem)||"MANUAL",id_omie:txt(r.id_omie)||null,usa_minaslab:!!r.usa_minaslab,usa_mlab:!!r.usa_mlab,ativo:r.ativo!==false,updated_at:new Date().toISOString()};const q=id?await sb.from("clientes_financeiro").update(p).eq("id",id).select().single():await sb.from("clientes_financeiro").insert({...p,created_at:new Date().toISOString()}).select().single();if(q.error)throw q.error;return json({item:q.data,reutilizado:false})}
if(a==="setAtivo"){const id=txt(b.id);const q=await sb.from("clientes_financeiro").update({ativo:!!b.ativo,updated_at:new Date().toISOString()}).eq("id",id).is("mesclado_para",null).select("*").maybeSingle();if(q.error)throw q.error;if(!q.data)return json({erro:"Cliente não encontrado ou já mesclado."},404);return json({item:q.data})}
if(a==="mesclar"){const origem=txt(b.origemId),destino=txt(b.destinoId);if(!origem||!destino||origem===destino)return json({erro:"Selecione dois clientes diferentes."},400);const q=await sb.rpc("mesclar_cliente_financeiro",{p_origem:origem,p_destino:destino});if(q.error)throw q.error;return json(q.data||{ok:true})}
return json({erro:"Ação inválida."},400)}catch(e){return json({erro:err(e)},500)}});