import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import {createClient} from "https://esm.sh/@supabase/supabase-js@2.45.0";
const U=Deno.env.get("SUPABASE_URL")!,K=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!,J=Deno.env.get("ML_JWT_SECRET")||"";
const sb=createClient(U,K,{auth:{persistSession:false,autoRefreshToken:false}}),enc=new TextEncoder(),dec=new TextDecoder();
const cors={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization, content-type","Access-Control-Allow-Methods":"POST, OPTIONS"};
const json=(b:any,s=200)=>new Response(JSON.stringify(b),{status:s,headers:{...cors,"Content-Type":"application/json","Cache-Control":"no-store"}}),txt=(v:any)=>String(v??"").trim(),num=(v:any)=>Number.isFinite(Number(v))?Number(v):0,iso=()=>new Date().toISOString();
function b64u(s:string){s=s.replace(/-/g,"+").replace(/_/g,"/");while(s.length%4)s+="=";const b=atob(s),o=new Uint8Array(b.length);for(let i=0;i<b.length;i++)o[i]=b.charCodeAt(i);return o}
async function auth(req:Request){const t=(req.headers.get("authorization")||"").replace(/^Bearer\s+/i,"");if(!t||!J)return null;const p=t.split(".");if(p.length!==3)return null;try{const k=await crypto.subtle.importKey("raw",enc.encode(J),{name:"HMAC",hash:"SHA-256"},false,["verify"]);if(!await crypto.subtle.verify("HMAC",k,b64u(p[2]),enc.encode(`${p[0]}.${p[1]}`)))return null;const x=JSON.parse(dec.decode(b64u(p[1])));if(x.sis!=="minaslab"||(x.exp&&x.exp<Math.floor(Date.now()/1000))||txt(x.papel)!=="direcao")return null;return x}catch{return null}}
const permitR=["cliente","cnpj_cpf","descricao","valor_previsto","valor_recebido","valor_pendente","data_vencimento","data_pagamento","status","categoria_id","conta_bancaria_id","categoria_texto","conta_bancaria_texto","forma_pagamento","numero_nf","observacao"];
const permitD=["fornecedor","cnpj_cpf","descricao","valor_original","valor_pago","valor_pendente","data_lancamento","data_vencimento","data_pagamento","status","categoria_id","conta_bancaria_id","centro_custo_id","centro_custo","categoria_texto","conta_bancaria_texto","forma_pagamento","observacao"];
function pick(x:any,keys:string[]){const o:any={};for(const k of keys)if(Object.prototype.hasOwnProperty.call(x,k))o[k]=x[k]===""?null:x[k];return o}
Deno.serve(async req=>{if(req.method==="OPTIONS")return new Response("ok",{headers:cors});const u=await auth(req);if(!u)return json({erro:"Sessão inválida ou sem permissão."},401);try{const b=await req.json(),a=txt(b.action),tipo=txt(b.tipo).toUpperCase(),tabela=tipo==="RECEBIMENTO"?"recebimentos":tipo==="DESPESA"?"despesas":"",id=txt(b.id),usuario=txt(u.sub)||"direcao";if(a==="candidatos"){if(!tabela||!id)return json({erro:"Título inválido."},400);const t=await sb.from(tabela).select("id,empresa_id,valor_previsto,valor_original,valor_conciliado,data_vencimento,numero_nf").eq("id",id).maybeSingle();if(t.error)throw t.error;if(!t.data)return json({erro:"Título não encontrado."},404);const movTipo=tipo==="RECEBIMENTO"?"CREDITO":"DEBITO";const q=await sb.from("movimentos_bancarios").select("id,data_movimento,descricao,documento,valor,tipo,origem,conciliado,conta:contas_bancarias(nome),conciliacoes(valor_conciliado)").eq("empresa_id",t.data.empresa_id).eq("tipo",movTipo).order("data_movimento",{ascending:false}).limit(500);if(q.error)throw q.error;const itens=(q.data||[]).map((m:any)=>({...m,disponivel:Math.max(0,num(m.valor)-(m.conciliacoes||[]).reduce((s:number,c:any)=>s+num(c.valor_conciliado),0))})).filter((m:any)=>m.disponivel>0.004);return json({itens});}
if(a==="conciliarTitulo"){if(!tabela||!id||!b.movimentoId)return json({erro:"Conciliação incompleta."},400);const valor=num(b.valor);if(valor<=0)return json({erro:"Valor inválido."},400);const payload:any={movimento_id:b.movimentoId,valor_conciliado:valor,conciliado_por:usuario};if(tipo==="RECEBIMENTO")payload.recebimento_id=id;else payload.despesa_id=id;const r=await sb.from("conciliacoes").insert(payload);if(r.error)throw r.error;return json({ok:true});}
if(a==="ajustarOmie"){if(!tabela||!id)return json({erro:"Título inválido."},400);const ex=await sb.from(tabela).select("*").eq("id",id).maybeSingle();if(ex.error)throw ex.error;if(!ex.data||ex.data.origem!=="OMIE")return json({erro:"Ajuste manual é exclusivo para título Omie."},409);const dados=pick(b.dados||{},tipo==="RECEBIMENTO"?permitR:permitD);const original:any={};for(const k of Object.keys(dados))original[k]=ex.data[k];const r=await sb.from(tabela).update({...dados,omie_override_manual:true,omie_override_dados:{original,ajuste:dados,motivo:txt(b.motivo)||null},omie_override_em:iso(),omie_override_por:usuario,updated_by:usuario,updated_at:iso()}).eq("id",id).select("*").single();if(r.error)throw r.error;return json({item:r.data});}
if(a==="restaurarOmie"){if(!tabela||!id)return json({erro:"Título inválido."},400);const ex=await sb.from(tabela).select("omie_override_dados,origem").eq("id",id).maybeSingle();if(ex.error)throw ex.error;if(!ex.data||ex.data.origem!=="OMIE")return json({erro:"Título Omie não encontrado."},404);const original=ex.data.omie_override_dados?.original||{};const r=await sb.from(tabela).update({...original,omie_override_manual:false,omie_override_dados:null,omie_override_em:null,omie_override_por:null,updated_by:usuario,updated_at:iso()}).eq("id",id).select("*").single();if(r.error)throw r.error;return json({item:r.data});}
return json({erro:"Ação inválida."},400)}catch(e){return json({erro:e instanceof Error?e.message:String(e)},500)}});