import { useEffect, useMemo, useState } from 'react'
import { Building2, ChevronLeft, ChevronRight, FlaskConical, Microscope, Search, TestTubes } from 'lucide-react'
import { Link } from 'react-router-dom'
import { PageShell } from '../../components/ui/PageShell'
import { supabase } from '../../services/supabase'

type Row={id:string;amostra_id:string;sample:string;barcode:string;description:string;group_name:string;service_name:string;order_id:string|null;order_number:string;client_name:string;sample_date:string|null;parameter_name:string;method:string;lq:string;ld:string;unit:string;execution:string;lab_name:string;catalog_linked:boolean;total_count:number;sample_count:number;order_count:number;linked_count:number;internal_count:number}
type FilterRow={tipo:'GRUPO'|'SERVICO'|'LABORATORIO';valor:string}
type Stats={total:number;samples:number;orders:number;linked:number;internal:number}
const PAGE_SIZE=100
const EMPTY_STATS:Stats={total:0,samples:0,orders:0,linked:0,internal:0}
const MONTHS=['Todos os meses','Janeiro','Fevereiro','Março','Abril','Maio','Junho','Julho','Agosto','Setembro','Outubro','Novembro','Dezembro']

export function AmostrasParametros(){
 const[rows,setRows]=useState<Row[]>([]);const[query,setQuery]=useState('');const[debouncedQuery,setDebouncedQuery]=useState('');const[group,setGroup]=useState('TODOS');const[service,setService]=useState('TODOS');const[lab,setLab]=useState('TODOS');const[year,setYear]=useState('TODOS');const[month,setMonth]=useState('0');const[page,setPage]=useState(1);const[stats,setStats]=useState<Stats>(EMPTY_STATS);const[groups,setGroups]=useState<string[]>([]);const[services,setServices]=useState<string[]>([]);const[labs,setLabs]=useState<string[]>([]);const[years,setYears]=useState<string[]>([]);const[loading,setLoading]=useState(true);const[error,setError]=useState('')
 useEffect(()=>{const id=window.setTimeout(()=>setDebouncedQuery(query.trim()),300);return()=>window.clearTimeout(id)},[query])
 useEffect(()=>{setPage(1)},[debouncedQuery,group,service,lab,year,month])
 useEffect(()=>{void(async()=>{const[{data,error},{data:dateRows}]=await Promise.all([supabase.rpc('crm_amostras_parametros_filtros'),supabase.from('amostras').select('data_entrada').is('deleted_at',null).not('data_entrada','is',null)]);if(!error){const values=(data??[]) as FilterRow[];setGroups(values.filter(x=>x.tipo==='GRUPO').map(x=>x.valor));setServices(values.filter(x=>x.tipo==='SERVICO').map(x=>x.valor));setLabs(values.filter(x=>x.tipo==='LABORATORIO').map(x=>x.valor))}const ys=Array.from(new Set((dateRows??[]).map(x=>String(new Date(x.data_entrada).getFullYear())).filter(x=>x!=='NaN'))).sort().reverse();setYears(ys)})()},[])
 useEffect(()=>{let active=true;void(async()=>{try{setLoading(true);setError('');const{data,error}=await supabase.rpc('crm_amostras_parametros_busca',{p_page:page,p_page_size:PAGE_SIZE,p_query:debouncedQuery||null,p_group:group==='TODOS'?null:group,p_service:service==='TODOS'?null:service,p_lab:lab==='TODOS'?null:lab,p_year:year==='TODOS'?null:Number(year),p_month:month==='0'?null:Number(month)});if(error)throw error;if(!active)return;const result=(data??[]) as Row[];setRows(result);const first=result[0];setStats(first?{total:Number(first.total_count),samples:Number(first.sample_count),orders:Number(first.order_count),linked:Number(first.linked_count),internal:Number(first.internal_count)}:EMPTY_STATS)}catch(e){if(active){setRows([]);setStats(EMPTY_STATS);setError(e instanceof Error?e.message:'Erro ao carregar histórico analítico.')}}finally{if(active)setLoading(false)}})();return()=>{active=false}},[page,debouncedQuery,group,service,lab,year,month])
 const pageCount=Math.max(1,Math.ceil(stats.total/PAGE_SIZE));const start=stats.total?((page-1)*PAGE_SIZE)+1:0;const end=Math.min(page*PAGE_SIZE,stats.total);const filterOptions=useMemo(()=>({groups:['TODOS',...groups],services:['TODOS',...services],labs:['TODOS',...labs]}),[groups,services,labs])
 return <PageShell title="Amostras e Parâmetros" description="Histórico analítico do GerenciaLab para consulta comercial e operacional, sem substituir o LIMS.">
  {error&&<div className="rounded-xl border border-red-200 bg-red-50 p-3 text-sm text-red-700">{error}</div>}
  <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-5"><K icon={TestTubes} label="Amostras" value={stats.samples}/><K icon={Microscope} label="Parâmetros" value={stats.total}/><K icon={FlaskConical} label="OS com análise" value={stats.orders}/><K icon={Building2} label="Execuções internas" value={stats.internal}/><K icon={Microscope} label="Vínculos com catálogo" value={stats.linked}/></section>
  <section className="rounded-3xl border bg-white shadow-sm"><div className="flex flex-wrap gap-3 border-b p-4"><div className="relative min-w-[280px] flex-1"><Search className="absolute left-3 top-3 h-4 w-4 text-slate-400"/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar amostra, OS, cliente, parâmetro, método, serviço ou laboratório..." className="w-full rounded-xl border py-2.5 pl-9 pr-3 text-sm"/></div><Filter value={year} set={setYear} options={['TODOS',...years]} label="Ano"/><MonthFilter value={month} set={setMonth}/><Filter value={group} set={setGroup} options={filterOptions.groups} label="Grupo"/><Filter value={service} set={setService} options={filterOptions.services} label="Serviço"/><Filter value={lab} set={setLab} options={filterOptions.labs} label="Laboratório"/></div>
   {loading?<div className="p-10 text-center text-slate-500">Carregando registros...</div>:!rows.length?<div className="p-10 text-center text-slate-500">Nenhum registro analítico disponível para os filtros selecionados.</div>:<><div className="overflow-x-auto"><table className="min-w-[1500px] w-full text-sm"><thead className="bg-slate-50 text-left text-xs uppercase text-slate-500"><tr><th className="px-4 py-3">Amostra</th><th>OS / Cliente</th><th>Grupo / Serviço</th><th>Parâmetro</th><th>Método</th><th>LQ</th><th>LD</th><th>Unidade</th><th>Execução</th><th>Laboratório</th></tr></thead><tbody className="divide-y">{rows.map(r=><tr key={r.id} className="hover:bg-slate-50"><td className="px-4 py-3"><b>{r.sample}</b><div className="text-xs text-slate-500">{r.barcode} · {r.description}</div></td><td>{r.order_id?<Link className="font-semibold text-blue-700" to={`/ordens-servico/${r.order_id}`}>{r.order_number}</Link>:r.order_number}<div className="text-xs text-slate-500">{r.client_name}</div></td><td><b>{r.group_name}</b><div className="text-xs text-slate-500">{r.service_name}</div></td><td className="font-medium">{r.parameter_name}</td><td>{r.method}</td><td>{r.lq}</td><td>{r.ld}</td><td>{r.unit}</td><td>{r.execution}</td><td>{r.lab_name}</td></tr>)}</tbody></table></div><div className="flex flex-wrap items-center justify-between gap-3 border-t p-3 text-xs text-slate-500"><span>Exibindo {start.toLocaleString('pt-BR')}–{end.toLocaleString('pt-BR')} de {stats.total.toLocaleString('pt-BR')} registros</span><div className="flex items-center gap-2"><button type="button" disabled={page<=1||loading} onClick={()=>setPage(p=>Math.max(1,p-1))} className="inline-flex items-center gap-1 rounded-lg border px-2.5 py-1.5 disabled:opacity-40"><ChevronLeft className="h-3.5 w-3.5"/>Anterior</button><span>Página {page.toLocaleString('pt-BR')} de {pageCount.toLocaleString('pt-BR')}</span><button type="button" disabled={page>=pageCount||loading} onClick={()=>setPage(p=>Math.min(pageCount,p+1))} className="inline-flex items-center gap-1 rounded-lg border px-2.5 py-1.5 disabled:opacity-40">Próxima<ChevronRight className="h-3.5 w-3.5"/></button></div></div></>}
  </section>
 </PageShell>
}
function K({icon:Icon,label,value}:{icon:typeof TestTubes;label:string;value:number}){return <article className="flex h-20 items-center gap-3 rounded-3xl border bg-white p-4 shadow-sm"><span className="grid h-11 w-11 shrink-0 place-items-center rounded-full bg-teal-50 text-teal-700"><Icon className="h-5 w-5"/></span><div className="min-w-0"><span className="text-xs text-slate-500">{label}</span><b className="mt-1 block truncate text-xl text-slate-900">{value.toLocaleString('pt-BR')}</b></div></article>}
function Filter({label,value,set,options}:{label:string;value:string;set:(v:string)=>void;options:string[]}){return <label className="text-xs font-semibold text-slate-500"><span className="mb-1 block">{label}</span><select value={value} onChange={e=>set(e.target.value)} className="min-w-36 rounded-xl border bg-white px-3 py-2.5 text-sm font-normal text-slate-700">{options.map(x=><option key={x} value={x}>{x==='TODOS'?'Todos':x}</option>)}</select></label>}
function MonthFilter({value,set}:{value:string;set:(v:string)=>void}){return <label className="text-xs font-semibold text-slate-500"><span className="mb-1 block">Mês</span><select value={value} onChange={e=>set(e.target.value)} className="min-w-36 rounded-xl border bg-white px-3 py-2.5 text-sm font-normal text-slate-700">{MONTHS.map((x,i)=><option key={x} value={String(i)}>{x}</option>)}</select></label>}
