import { FINANCEIRO_SERVICOS, FINANCEIRO_SERVICOS_LISTAR, FINANCEIRO_SERVICOS_IMPORT, FINANCEIRO_SERVICOS_EMPRESA, FINANCEIRO_SERVICOS_FATURAR, FINANCEIRO_SERVICOS_SYNC, FINANCEIRO_SERVICOS_GRUPAR, FINANCEIRO_SERVICOS_NFSE_VINCULAR } from "../lib/api.js";
import { comCracha, mensagemDoStatus } from "../lib/sessao.js";

function erroTexto(v){if(v==null)return"";if(typeof v==="string")return v.trim();if(typeof v==="number"||typeof v==="boolean")return String(v);if(v instanceof Error)return v.message||String(v);if(Array.isArray(v))return v.map(erroTexto).filter(Boolean).join(" ");if(typeof v==="object"){for(const k of["erro","message","mensagem","error_description","details","hint","code"]){const s=erroTexto(v[k]);if(s)return s}try{return JSON.stringify(v)}catch{return"Falha inesperada no Financeiro."}}return String(v)}
async function chamarUrl(url,corpo={}){const resp=await comCracha(url,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(corpo)});const body=await resp.json().catch(()=>null);if(!resp.ok)throw new Error(erroTexto(body)||mensagemDoStatus(resp.status));return body||{}}
const chamar=(action,corpo={})=>chamarUrl(FINANCEIRO_SERVICOS,{action,...corpo});
export const servicosGeradosListar=(filtros={})=>chamarUrl(FINANCEIRO_SERVICOS_LISTAR,{filtros});
export const servicoGeradoSalvar=registro=>chamar("salvar",{registro}).then(r=>r.item);
export const servicoParticularidadeSalvar=registro=>chamar("particularidadeSalvar",{registro}).then(r=>r.item);
export const servicosGeradosSincronizar=()=>chamarUrl(FINANCEIRO_SERVICOS_SYNC,{});
export const servicosGeradosAgrupar=(servicoIds,referenciaPagamento="")=>chamarUrl(FINANCEIRO_SERVICOS_GRUPAR,{servicoIds,referenciaPagamento});
export const servicoGeradoHistorico=id=>chamar("historico",{id}).then(r=>r.itens||[]);
export const servicoGeradoEmpresa=(id,empresaId,lembrar=false)=>chamarUrl(FINANCEIRO_SERVICOS_EMPRESA,{id,empresaId:empresaId||null,lembrar}).then(r=>r.item);
export const servicoGeradoConcluirFaturamento=id=>chamarUrl(FINANCEIRO_SERVICOS_FATURAR,{id});
export const servicoGeradoVincularNfse=(servicoId,notaFiscalId)=>chamarUrl(FINANCEIRO_SERVICOS_NFSE_VINCULAR,{servicoId,notaFiscalId});
export async function servicosGeradosImportar(arquivo){const base64=await new Promise((resolve,reject)=>{const fr=new FileReader();fr.onload=()=>resolve(String(fr.result||"").split(",")[1]||"");fr.onerror=()=>reject(new Error("Não foi possível ler o arquivo."));fr.readAsDataURL(arquivo)});return chamarUrl(FINANCEIRO_SERVICOS_IMPORT,{arquivoNome:arquivo.name,base64});}
export async function servicosGeradosBaixarModelo(){const r=await chamarUrl(FINANCEIRO_SERVICOS_IMPORT,{action:"modelo"});if(!r.base64)throw new Error("O modelo não foi retornado pelo servidor.");const bin=atob(r.base64),bytes=new Uint8Array(bin.length);for(let i=0;i<bin.length;i++)bytes[i]=bin.charCodeAt(i);const blob=new Blob([bytes],{type:r.mime||"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"}),url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download=r.arquivoNome||"MODELO_Importacao_ServicosGerados.xlsx";document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);return r.arquivoNome||"MODELO_Importacao_ServicosGerados.xlsx";}