import "jsr:@supabase/functions-js/edge-runtime.d.ts";
const BASE_URL=Deno.env.get("SUPABASE_URL")||"";
const SR=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")||"";
const JWT_SECRET=Deno.env.get("ML_JWT_SECRET")||"";
/* O hash do token do agendamento mora num segredo do Supabase, não no código:
   este repositório é PÚBLICO e o hash nunca esteve nele (auditoria de 28/09/2026).
   O token em si fica no cofre do banco (vault) e é o agendamento de 15 min que o manda.
   Sem o segredo, a comparação falha e a função RECUSA o agendamento — falha fechada. */
const ROTINA_HASH=Deno.env.get("ML_OMIE_AUTO_ROTINA_HASH")||"";
const enc=new TextEncoder(),dec=new TextDecoder();
const cors={"access-control-allow-origin":"*","access-control-allow-headers":"authorization, content-type, x-rotina-token","access-control-allow-methods":"GET, POST, OPTIONS"};
function json(b:any,s=200){return new Response(JSON.stringify(b),{status:s,headers:{...cors,"content-type":"application/json","cache-control":"no-store"}})}
function pad(s:string){return s.replace(/-/g,"+").replace(/_/g,"/")+"===".slice((s.length+3)%4)}
function b64u(b:Uint8Array){let s="";for(const x of b)s+=String.fromCharCode(x);return btoa(s).replace(/=/g,"").replace(/\+/g,"-").replace(/\//g,"_")}
async function sha256(s:string){const h=new Uint8Array(await crypto.subtle.digest("SHA-256",enc.encode(s)));return Array.from(h).map(x=>x.toString(16).padStart(2,"0")).join("")}
async function db(path:string,init:any={}){const r=await fetch(`${BASE_URL}/rest/v1/${path}`,{...init,headers:{apikey:SR,authorization:`Bearer ${SR}`,"content-type":"application/json",prefer:init.prefer||"return=representation",...(init.headers||{})}});const x=await r.json().catch(()=>null);if(!r.ok)throw new Error(`Estado Omie: ${x?.message||r.status}`);return x}
async function verificarUsuario(req:Request){const a=req.headers.get("authorization")||"";if(!a.toLowerCase().startsWith("bearer ")||!JWT_SECRET)return false;try{const p=a.slice(7).trim().split(".");if(p.length!==3)return false;const key=await crypto.subtle.importKey("raw",enc.encode(JWT_SECRET),{name:"HMAC",hash:"SHA-256"},false,["verify"]);const sig=Uint8Array.from(atob(pad(p[2])),c=>c.charCodeAt(0));if(!await crypto.subtle.verify("HMAC",key,sig,enc.encode(`${p[0]}.${p[1]}`)))return false;const x=JSON.parse(dec.decode(Uint8Array.from(atob(pad(p[1])),c=>c.charCodeAt(0))));return x?.sis==="minaslab"&&x?.papel==="direcao"&&Number(x?.exp||0)>Math.floor(Date.now()/1000)}catch{return false}}
async function verificarRotina(req:Request){const t=req.headers.get("x-rotina-token")||"";return !!t&&(await sha256(t))===ROTINA_HASH}
async function jwt(){const h=b64u(enc.encode(JSON.stringify({alg:"HS256",typ:"JWT"})));const n=Math.floor(Date.now()/1000);const p=b64u(enc.encode(JSON.stringify({sis:"minaslab",papel:"direcao",sub:"omie-auto",iat:n,exp:n+900})));const d=`${h}.${p}`;const key=await crypto.subtle.importKey("raw",enc.encode(JWT_SECRET),{name:"HMAC",hash:"SHA-256"},false,["sign"]);const sig=new Uint8Array(await crypto.subtle.sign("HMAC",key,enc.encode(d)));return `${d}.${b64u(sig)}`}
const ymd=(d:Date)=>d.toISOString().slice(0,10);
async function call(t:string,b:any){const r=await fetch(`${BASE_URL}/functions/v1/ml-financeiro-omie-v2`,{method:"POST",headers:{"content-type":"application/json",authorization:`Bearer ${t}`},body:JSON.stringify(b)});const x=await r.json().catch(()=>({}));if(!r.ok)throw new Error(x?.erro||`HTTP ${r.status}`);return x}
async function estado(){const x=await db("financeiro_omie_auto_estado?chave=eq.MINASLAB&select=chave,em_execucao,iniciado_em,finalizado_em,status,mensagem,detalhes,updated_at",{method:"GET"});return x?.[0]||null}
async function patchEstado(p:any){await db("financeiro_omie_auto_estado?chave=eq.MINASLAB",{method:"PATCH",body:JSON.stringify({...p,updated_at:new Date().toISOString()})})}
async function lock(){const lim=new Date(Date.now()-8*60*1000).toISOString();const agora=new Date().toISOString();await db(`financeiro_omie_auto_estado?chave=eq.MINASLAB&em_execucao=eq.true&updated_at=lt.${encodeURIComponent(lim)}`,{method:"PATCH",body:JSON.stringify({em_execucao:false,status:"RECUPERADO_TIMEOUT",mensagem:"Execução anterior sem heartbeat por mais de 8 minutos.",updated_at:agora})});const x=await db("financeiro_omie_auto_estado?chave=eq.MINASLAB&em_execucao=eq.false&select=chave,detalhes",{method:"PATCH",body:JSON.stringify({em_execucao:true,iniciado_em:agora,status:"EXECUTANDO",mensagem:null,updated_at:agora})});return x?.[0]||null}
async function paginas(t:string,a:string,de:string,ate:string,fase:string){let p=1,l=0,i=0,u=0,ig=0,total=1;for(let g=0;g<100;g++){const r=await call(t,{action:a,pagina:p,de,ate});l+=Number(r.lidos||0);i+=Number(r.inseridos||0);u+=Number(r.atualizados||0);ig+=Number(r.ignorados||0);total=Number(r.paginas||total||1);await patchEstado({status:"EXECUTANDO",mensagem:`${fase}: página ${p}/${total}`,detalhes:{fase,pagina:p,total_paginas:total,lidos:l,inseridos:i,atualizados:u,ignorados:ig}});if(!r.proxima)break;p=Number(r.proxima)}return{lidos:l,inseridos:i,atualizados:u,ignorados:ig,paginas:total}}
async function fim(status:string,mensagem:string|null,detalhes:any){await patchEstado({em_execucao:false,finalizado_em:new Date().toISOString(),status,mensagem,detalhes})}
function proxima(f:string){return f==="RECEBER"?"PAGAR":f==="PAGAR"?"NOTAS":f==="NOTAS"?"EXTRATO":"RECEBER"}
async function executar(){const lk=await lock();if(!lk)return{ok:true,ignorado:true,motivo:"Sincronização Omie já em execução."};const anterior=lk?.detalhes||{};const fase=["RECEBER","PAGAR","NOTAS","EXTRATO"].includes(String(anterior?.proxima_fase||""))?String(anterior.proxima_fase):"RECEBER";try{const t=await jwt(),a=new Date();const deT=new Date(a),ateT=new Date(a);deT.setUTCDate(deT.getUTCDate()-120);ateT.setUTCDate(ateT.getUTCDate()+365);const nd=new Date(a);nd.setUTCDate(nd.getUTCDate()-45);const ed=new Date(a);ed.setUTCDate(ed.getUTCDate()-7);let resultado:any={};if(fase==="RECEBER")resultado=await paginas(t,"receberPagina",ymd(deT),ymd(ateT),fase);else if(fase==="PAGAR")resultado=await paginas(t,"pagarPagina",ymd(deT),ymd(ateT),fase);else if(fase==="NOTAS"){const nfe=await paginas(t,"nfePagina",ymd(nd),ymd(a),"NFE");const nfse=await paginas(t,"nfsePagina",ymd(nd),ymd(a),"NFSE");resultado={nfe,nfse}}else resultado=await call(t,{action:"extrato",de:ymd(ed),ate:ymd(a)});const prox=proxima(fase);const detalhes={fase_concluida:fase,proxima_fase:prox,resultado,janelaTitulos:{de:ymd(deT),ate:ymd(ateT)},janelaNotas:{de:ymd(nd),ate:ymd(a)},janelaExtrato:{de:ymd(ed),ate:ymd(a)},clientes:{automatico:false,motivo:"Sincronização de clientes preservada no ml-financeiro-omie-v2 e retirada do ciclo de 15 minutos para não bloquear o Financeiro."}};await fim("CONCLUIDO",null,detalhes);return{ok:true,...detalhes}}catch(e){const m=e instanceof Error?e.message:String(e);await fim("ERRO",m,{fase_concluida:null,proxima_fase:fase});throw e}}
Deno.serve(async(req:Request)=>{try{if(req.method==="OPTIONS")return new Response("ok",{headers:cors});const rotina=await verificarRotina(req),usuario=await verificarUsuario(req);if(!rotina&&!usuario)return json({erro:"Não autorizado"},401);if(!JWT_SECRET||!BASE_URL||!SR)return json({erro:"Configuração interna ausente"},500);let action="executar";try{const b=await req.json();action=b?.action||action}catch{}const u=new URL(req.url);action=u.searchParams.get("action")||action;if(action==="estado")return json({ok:true,estado:await estado()});if(action!=="executar")return json({erro:"Ação inválida"},400);return json(await executar())}catch(e){console.error("omie-auto",e);return json({erro:e instanceof Error?e.message:String(e)},500)}});
