import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2";
const sb=createClient(Deno.env.get("SUPABASE_URL")||"",Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")||"");
const cid=Deno.env.get("GOOGLE_DRIVE_CLIENT_ID")||"",sec=Deno.env.get("GOOGLE_DRIVE_CLIENT_SECRET")||"",root=Deno.env.get("GOOGLE_DRIVE_ROOT_FOLDER_ID")||"";
const cors={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization,content-type","Access-Control-Allow-Methods":"POST,OPTIONS"};
const out=(x:any,s=200)=>new Response(JSON.stringify(x),{status:s,headers:{...cors,"content-type":"application/json"}});
async function token(){const {data,error}=await sb.rpc("ml_google_drive_obter_refresh_token");if(error||!data)throw new Error("Google Drive não autorizado.");const r=await fetch("https://oauth2.googleapis.com/token",{method:"POST",headers:{"content-type":"application/x-www-form-urlencoded"},body:new URLSearchParams({client_id:cid,client_secret:sec,refresh_token:String(data),grant_type:"refresh_token"})});const j=await r.json();if(!r.ok||!j.access_token)throw new Error("Falha ao renovar autorização do Google Drive.");return String(j.access_token)}
async function pasta(id:string,t:string){const r=await fetch("https://www.googleapis.com/drive/v3/files/"+encodeURIComponent(id)+"?fields=id,name,mimeType,trashed,webViewLink&supportsAllDrives=true",{headers:{authorization:"Bearer "+t}});const j=await r.json();if(!r.ok||j.trashed||j.mimeType!=="application/vnd.google-apps.folder")throw new Error("Pasta não encontrada ou sem permissão.");return j}
async function fornecedor(id:string){const {data,error}=await sb.from("ml_registros").select("registro,apagado").eq("colecao","estoque_fornecedores").eq("id",id).maybeSingle();if(error)throw error;if(!data||data.apagado)throw new Error("Fornecedor não localizado.");return data.registro as Record<string,any>}
async function salvar(id:string,r:Record<string,any>,pid:string,url:string){const agora=new Date().toISOString(),novo={...r,pastaDriveId:pid,pastaDriveUrl:url,PASTA_DRIVE_ID:pid,PASTA_DRIVE_URL:url,atualizadoEm:agora};const {error}=await sb.from("ml_registros").update({registro:novo,atualizado_em:agora}).eq("colecao","estoque_fornecedores").eq("id",id).eq("apagado",false);if(error)throw error;return novo}
Deno.serve(async req=>{if(req.method==="OPTIONS")return new Response("ok",{headers:cors});if(req.method!=="POST")return out({erro:"Use POST."},405);
// Só a ml-sync chama (token interno do servidor); a permissão do usuário é conferida lá. Sem isto, qualquer um com o endereço criaria pastas no Drive.
if(!Deno.env.get("ML_TOKEN")||req.headers.get("x-token")!==Deno.env.get("ML_TOKEN"))return out({erro:"Não autorizado."},401);
try{const b=await req.json(),action=String(b.action||""),id=String(b.fornecedorId||"").trim();if(!id)return out({erro:"Fornecedor obrigatório."},400);const reg=await fornecedor(id),t=await token();
if(action==="vincular"){const pid=String(b.pastaId||"").trim();if(!pid)return out({erro:"Pasta obrigatória."},400);const p=await pasta(pid,t),url=String(p.webViewLink||("https://drive.google.com/drive/folders/"+pid));return out({ok:true,registro:await salvar(id,reg,pid,url),pastaId:pid,pastaUrl:url})}
if(action==="criar"){if(reg.pastaDriveId||reg.PASTA_DRIVE_ID)return out({erro:"PASTA JÁ VINCULADA. Abra a pasta existente ou altere o vínculo explicitamente."},409);await pasta(root,t);const nome=(id+" - "+String(reg.nome||"FORNECEDOR")).replace(/[\\/:*?"<>|]+/g," ").replace(/\s+/g," ").trim().slice(0,150);const r=await fetch("https://www.googleapis.com/drive/v3/files?supportsAllDrives=true&fields=id,webViewLink",{method:"POST",headers:{authorization:"Bearer "+t,"content-type":"application/json"},body:JSON.stringify({name:nome,mimeType:"application/vnd.google-apps.folder",parents:[root]})}),p=await r.json();if(!r.ok||!p.id)throw new Error("Não foi possível criar a pasta no Google Drive.");const url=String(p.webViewLink||("https://drive.google.com/drive/folders/"+p.id));return out({ok:true,registro:await salvar(id,reg,String(p.id),url),pastaId:String(p.id),pastaUrl:url})}
return out({erro:"Ação inválida."},400)}catch(e){return out({erro:e instanceof Error?e.message:"Erro inesperado."},500)}});
