import { useCallback, useEffect, useState } from 'react'
import { Check, ExternalLink, RefreshCw, SearchCheck, X } from 'lucide-react'
import { Badge, Button, Card, CardBody } from '../../components/ui/DesignSystem'
import { supabase } from '../../services/supabase'
import { useAuth } from '../../hooks/useAuth'

type Opportunity={id:string;numero_controle_pncp:string;numero_compra:string|null;processo:string|null;orgao:string;municipio:string|null;uf:string|null;modalidade:string|null;objeto:string;data_publicacao:string|null;data_abertura_proposta:string|null;data_encerramento_proposta:string|null;valor_estimado:number|null;portal_url:string|null;pncp_url:string;palavras_encontradas:string[];prioridade:'ALTA'|'MEDIA';status:'NOVA'|'APROVADA'|'DESCARTADA'}
const brl=new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'})
const modality=(value:string|null)=>{const v=(value||'').toLowerCase();if(v.includes('pregão')&&v.includes('eletr'))return'Pregão eletrônico';if(v.includes('pregão'))return'Pregão presencial';if(v.includes('concorrência')&&v.includes('eletr'))return'Concorrência eletrônica';if(v.includes('concorrência'))return'Concorrência presencial';if(v.includes('dispensa')&&v.includes('eletr'))return'Dispensa eletrônica';if(v.includes('dispensa'))return'Dispensa de licitação';if(v.includes('inexigibilidade'))return'Inexigibilidade';if(v.includes('credenciamento'))return'Credenciamento';if(v.includes('concurso'))return'Concurso';if(v.includes('leilão'))return'Leilão';if(v.includes('diálogo'))return'Diálogo competitivo';return'Outra'}

export function PncpOpportunities({onConverted}:{onConverted:()=>Promise<void>}){
 const{hasPermission,session}=useAuth(),canWrite=hasPermission('crm.write');const[rows,setRows]=useState<Opportunity[]>([]),[loading,setLoading]=useState(true),[syncing,setSyncing]=useState(false),[message,setMessage]=useState('')
 const load=useCallback(async()=>{setLoading(true);const{data,error}=await supabase.from('licitacao_oportunidades').select('*').eq('status','NOVA').order('prioridade').order('data_encerramento_proposta',{ascending:true,nullsFirst:false}).limit(100);if(error)setMessage(error.message);else setRows((data??[]) as Opportunity[]);setLoading(false)},[])
 useEffect(()=>{void load()},[load])
 async function sync(){setSyncing(true);setMessage('');const{data,error}=await supabase.functions.invoke('pncp-opportunities-sync',{body:{}});if(error)setMessage(error.message);else setMessage(`Busca concluída: ${Number(data?.compativeis??0)} oportunidade(s) compatível(is) entre ${Number(data?.processadas??0)} publicação(ões) analisada(s).`);await load();setSyncing(false)}
 async function discard(id:string){const{error}=await supabase.from('licitacao_oportunidades').update({status:'DESCARTADA',revisada_em:new Date().toISOString(),revisada_por:session?.user.id??null}).eq('id',id);if(error)setMessage(error.message);else await load()}
 async function convert(o:Opportunity){const{data,error}=await supabase.from('licitacoes').insert({empresa:'MINASLAB',numero:o.numero_compra||o.processo||o.numero_controle_pncp,orgao:o.orgao,modalidade:modality(o.modalidade),objeto:o.objeto,portal_url:o.portal_url||o.pncp_url,municipio:o.municipio,uf:o.uf,status:'ANALISE',data_publicacao:o.data_publicacao?.slice(0,10)||null,data_sessao:o.data_encerramento_proposta,valor_estimado:o.valor_estimado,created_by:session?.user.id??null,updated_by:session?.user.id??null}).select('id').single();if(error){setMessage(error.code==='23505'?'Essa oportunidade já foi cadastrada como licitação.':error.message);return}const review=await supabase.from('licitacao_oportunidades').update({status:'APROVADA',licitacao_id:data.id,revisada_em:new Date().toISOString(),revisada_por:session?.user.id??null}).eq('id',o.id);if(review.error){await supabase.from('licitacoes').delete().eq('id',data.id);setMessage(review.error.message);return}await Promise.all([load(),onConverted()])}
 return <Card><CardBody><div className="flex flex-col justify-between gap-3 sm:flex-row sm:items-center"><div><div className="flex items-center gap-2 font-bold text-slate-900"><SearchCheck className="h-5 w-5 text-teal-700"/>Oportunidades encontradas no PNCP</div><p className="mt-1 text-sm text-slate-500">Publicações de Montes Claros e Norte de Minas compatíveis com o escopo da MinasLab. Revise antes de cadastrar.</p></div>{canWrite?<Button variant="secondary" disabled={syncing} onClick={()=>void sync()}><RefreshCw className={`h-4 w-4 ${syncing?'animate-spin':''}`}/>{syncing?'Consultando PNCP...':'Buscar agora'}</Button>:null}</div>{message?<div role="status" className="mt-3 rounded-lg bg-slate-50 p-3 text-sm text-slate-700">{message}</div>:null}<div className="mt-4 space-y-3">{loading?<div className="p-5 text-center text-sm text-slate-500">Carregando oportunidades...</div>:rows.length===0?<div className="rounded-xl border border-dashed border-slate-300 p-5 text-center text-sm text-slate-500">Nenhuma oportunidade nova encontrada. A busca automática ocorre diariamente.</div>:rows.map(o=><article key={o.id} className="rounded-xl border border-slate-200 p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><Badge variant={o.prioridade==='ALTA'?'danger':'warning'}>{o.prioridade}</Badge><b>{o.orgao}</b><span className="text-xs text-slate-500">{o.municipio}/{o.uf}</span></div><p className="mt-2 text-sm leading-relaxed text-slate-700">{o.objeto}</p><div className="mt-2 flex flex-wrap gap-2 text-xs text-slate-500"><span>{o.modalidade||'Modalidade não informada'}</span><span>Prazo: {o.data_encerramento_proposta?new Date(o.data_encerramento_proposta).toLocaleString('pt-BR'):'não informado'}</span><span>{o.valor_estimado==null?'Valor não informado':brl.format(o.valor_estimado)}</span></div>{o.palavras_encontradas.length?<div className="mt-2 text-xs text-teal-700">Correspondências: {o.palavras_encontradas.join(', ')}</div>:null}</div><a href={o.portal_url||o.pncp_url} target="_blank" rel="noreferrer" className="inline-flex items-center gap-1 text-sm font-semibold text-teal-700"><ExternalLink className="h-4 w-4"/>Abrir edital</a></div>{canWrite?<div className="mt-4 flex justify-end gap-2"><Button variant="secondary" onClick={()=>void discard(o.id)}><X className="h-4 w-4"/>Descartar</Button><Button onClick={()=>void convert(o)}><Check className="h-4 w-4"/>Criar licitação</Button></div>:null}</article>)}</div></CardBody></Card>
}
