import { useEffect,useState } from 'react'
import { AlertTriangle,CalendarDays,CircleDollarSign,FileText,Handshake,ListTodo,RefreshCw,Repeat2,Users,Wrench } from 'lucide-react'
import { Link } from 'react-router-dom'
import { PageShell } from '../../components/ui/PageShell'
import { supabase } from '../../services/supabase'

type Person={id:string;nome:string|null}
type Agenda={id:string;titulo:string|null;inicio:string;status:string|null}
type Task={id:string;titulo:string;prazo:string|null;prioridade:string|null}
type Quality={empresa_definir:number;atendimento_sem_responsavel:number;oportunidade_sem_numero:number;proposta_sem_data_decisao:number}
type Monthly={key:string;label:string;proposal:number;orders:number}
type DashboardData={metrics:{atendimentos:number;oportunidades_abertas:number;valor_propostas:number;conversao:number;contratos_ativos:number;os_em_andamento:number};volume:{atendimentos:number;oportunidades:number;propostas:number;aprovadas:number};alerts:{contratos_vencendo:number;os_pendentes:number;coletas_atrasadas:number;clientes_sem_contato:number};results:{valor_os:number;ticket_os:number;clientes_atendidos:number;coletas_registradas:number};agenda_today:Agenda[];priority_tasks:Task[];os_statuses:[string,number][];monthly:Monthly[]}
const EMPTY:DashboardData={metrics:{atendimentos:0,oportunidades_abertas:0,valor_propostas:0,conversao:0,contratos_ativos:0,os_em_andamento:0},volume:{atendimentos:0,oportunidades:0,propostas:0,aprovadas:0},alerts:{contratos_vencendo:0,os_pendentes:0,coletas_atrasadas:0,clientes_sem_contato:0},results:{valor_os:0,ticket_os:0,clientes_atendidos:0,coletas_registradas:0},agenda_today:[],priority_tasks:[],os_statuses:[],monthly:[]}
const monthsFull=['Todos os meses','Janeiro','Fevereiro','Março','Abril','Maio','Junho','Julho','Agosto','Setembro','Outubro','Novembro','Dezembro']

export function Dashboard(){
 const[data,setData]=useState<DashboardData>(EMPTY);const[quality,setQuality]=useState<Quality>({empresa_definir:0,atendimento_sem_responsavel:0,oportunidade_sem_numero:0,proposta_sem_data_decisao:0});const[people,setPeople]=useState<Person[]>([]);const[period,setPeriod]=useState('ANO');const[month,setMonth]=useState(String(new Date().getMonth()+1));const[owner,setOwner]=useState('TODOS');const[loading,setLoading]=useState(true);const[error,setError]=useState('')
 async function load(){setLoading(true);setError('');const[{data:rpcData,error:rpcError},{data:profiles,error:profilesError},{data:qualityData,error:qualityError}]=await Promise.all([supabase.rpc('crm_dashboard_executivo',{p_period:period,p_month:month==='0'?null:Number(month),p_owner:owner==='TODOS'?null:owner}),supabase.from('profiles').select('id,nome').eq('ativo',true).order('nome'),supabase.rpc('crm_data_quality_counts')]);if(rpcError)setError(rpcError.message);else setData((rpcData??EMPTY) as DashboardData);if(profilesError||qualityError)setError(v=>[v,profilesError?.message,qualityError?.message].filter(Boolean).join(' | '));else{setPeople((profiles??[]) as Person[]);setQuality((qualityData??{empresa_definir:0,atendimento_sem_responsavel:0,oportunidade_sem_numero:0,proposta_sem_data_decisao:0}) as Quality)}setLoading(false)}
 useEffect(()=>{void load()},[period,month,owner])
 const m=data.metrics,v=data.volume,a=data.alerts,r=data.results,monthly=data.monthly??[],statuses=data.os_statuses??[],totalStatuses=statuses.reduce((n,[,q])=>n+Number(q),0),maxProposal=Math.max(1,...monthly.map(x=>Number(x.proposal)||0)),maxOrders=Math.max(1,...monthly.map(x=>Number(x.orders)||0));const periodLabel=month!=='0'?monthsFull[Number(month)]:period==='90'?'últimos 90 dias':period==='ANO'?'ano atual':'todo o período'
 return <PageShell title="Dashboard Executivo" description="Visão consolidada do comercial, contratos e operação.">
  <div className="flex flex-wrap justify-end gap-2"><select value={period} onChange={e=>setPeriod(e.target.value)} className="rounded-xl border bg-white px-4 py-2.5"><option value="ANO">Este ano</option><option value="90">Últimos 90 dias</option><option value="TODOS">Todo período</option></select><select value={month} onChange={e=>setMonth(e.target.value)} className="rounded-xl border bg-white px-4 py-2.5">{monthsFull.map((label,i)=><option key={i} value={String(i)}>{label}</option>)}</select><select value={owner} onChange={e=>setOwner(e.target.value)} className="rounded-xl border bg-white px-4 py-2.5"><option value="TODOS">Todos os responsáveis</option>{people.map(x=><option key={x.id} value={x.id}>{x.nome}</option>)}</select><button onClick={()=>void load()} disabled={loading} className="rounded-xl border bg-white p-2.5 disabled:opacity-50" aria-label="Atualizar dashboard"><RefreshCw className={`h-5 w-5 ${loading?'animate-spin':''}`}/></button></div>
  {error&&<div className="rounded-xl bg-red-50 p-3 text-red-700">Parte do dashboard não carregou: {error}</div>}
  <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-6"><K i={Users} l="Atendimentos" v={m.atendimentos}/><K i={Handshake} l="Oportunidades abertas" v={m.oportunidades_abertas}/><K i={CircleDollarSign} l="Valor em propostas" v={money(m.valor_propostas)}/><K i={Repeat2} l="Conversão de propostas" v={`${Number(m.conversao).toFixed(1)}%`}/><K i={FileText} l="Contratos ativos" v={m.contratos_ativos}/><K i={Wrench} l="OS em andamento" v={m.os_em_andamento}/></section>
  <section className="grid gap-5 xl:grid-cols-[1.5fr_.8fr_.8fr]"><article className="rounded-3xl border bg-white p-5 shadow-sm"><h3 className="font-bold">Evolução comercial e operacional</h3><div className="mt-6 flex h-56 items-end gap-3">{monthly.map(x=><div key={x.key} className="flex flex-1 flex-col items-center gap-1"><div className="flex h-44 items-end gap-1"><span title={`Propostas ${money(x.proposal)}`} className="w-4 rounded-t bg-blue-500" style={{height:`${Math.max(3,Number(x.proposal)/maxProposal*100)}%`}}/><span title={`OS ${x.orders}`} className="w-4 rounded-t bg-teal-600" style={{height:`${Math.max(3,Number(x.orders)/maxOrders*100)}%`}}/></div><small>{x.label}</small></div>)}</div><div className="mt-2 flex gap-4 text-xs"><span className="text-blue-600">■ Valor de propostas</span><span className="text-teal-700">■ Quantidade de OS</span></div></article><article className="rounded-3xl border bg-white p-5 shadow-sm"><h3 className="font-bold">Volume comercial</h3><div className="mt-5 space-y-3"><F l="Atendimentos" v={v.atendimentos}/><F l="Oportunidades" v={v.oportunidades}/><F l="Propostas" v={v.propostas}/><F l="Aprovadas" v={v.aprovadas}/></div><p className="mt-4 text-xs leading-5 text-slate-500">Os volumes respeitam o período, mês e responsável selecionados.</p></article><article className="rounded-3xl border bg-white p-5 shadow-sm"><h3 className="font-bold">Status das OS no filtro</h3><div className="mt-5 space-y-3">{statuses.map(([k,q])=><div key={k}><div className="flex justify-between text-sm"><span>{k}</span><b>{q}</b></div><div className="h-2 rounded bg-slate-100"><div className="h-2 rounded bg-teal-600" style={{width:`${totalStatuses?Number(q)/totalStatuses*100:0}%`}}/></div></div>)}</div></article></section>
  <section className="grid gap-5 xl:grid-cols-3"><Panel title="Agenda de hoje" icon={CalendarDays}>{data.agenda_today.length?data.agenda_today.map(x=><Item key={x.id} title={x.titulo||'Agendamento'} detail={`${new Date(x.inicio).toLocaleTimeString('pt-BR',{hour:'2-digit',minute:'2-digit'})} · ${x.status||'Sem status'}`}/>):<Empty/>}<Link to="/agenda" className="text-sm font-semibold text-teal-700">Ver agenda completa →</Link></Panel><Panel title="Tarefas prioritárias" icon={ListTodo}>{data.priority_tasks.length?data.priority_tasks.map(x=><Item key={x.id} title={x.titulo} detail={`${x.prazo?new Date(x.prazo).toLocaleDateString('pt-BR'):'Sem prazo'} · ${x.prioridade||'Normal'}`}/>):<Empty/>}<Link to="/tarefas" className="text-sm font-semibold text-teal-700">Ver todas as tarefas →</Link></Panel><Panel title="Alertas gerenciais" icon={AlertTriangle}><Alert v={a.contratos_vencendo} t="contratos vencem em 30 dias"/><Alert v={a.os_pendentes} t="OS pendentes"/><Alert v={a.coletas_atrasadas} t="coletas atrasadas"/><Alert v={a.clientes_sem_contato} t="clientes sem atendimento há 90 dias"/></Panel></section>
  <section className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm"><div className="mb-4 flex items-center gap-2"><AlertTriangle className="h-5 w-5 text-amber-600"/><h3 className="font-bold">Pendências de cadastro</h3></div><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Link to="/atendimentos" className="rounded-2xl border border-slate-200 bg-slate-50 p-4 hover:bg-slate-100"><span className="text-xs text-slate-500">Empresa a definir</span><b className="mt-1 block text-xl">{quality.empresa_definir}</b></Link><Link to="/atendimentos" className="rounded-2xl border border-slate-200 bg-slate-50 p-4 hover:bg-slate-100"><span className="text-xs text-slate-500">Atendimentos sem responsável</span><b className="mt-1 block text-xl">{quality.atendimento_sem_responsavel}</b></Link><Link to="/oportunidades" className="rounded-2xl border border-slate-200 bg-slate-50 p-4 hover:bg-slate-100"><span className="text-xs text-slate-500">Oportunidades sem nº GerenciaLab</span><b className="mt-1 block text-xl">{quality.oportunidade_sem_numero}</b></Link><Link to="/propostas" className="rounded-2xl border border-slate-200 bg-slate-50 p-4 hover:bg-slate-100"><span className="text-xs text-slate-500">Decisões de proposta sem data</span><b className="mt-1 block text-xl">{quality.proposta_sem_data_decisao}</b></Link></div></section>
  <section className="rounded-3xl border bg-white p-5 shadow-sm"><h3 className="font-bold">Resultados — {periodLabel}</h3><div className="mt-3 grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><D l="Valor em OS" v={money(r.valor_os)}/><D l="Ticket médio de OS" v={money(r.ticket_os)}/><D l="Clientes atendidos em OS" v={String(r.clientes_atendidos)}/><D l="Coletas registradas" v={String(r.coletas_registradas)}/></div></section>
 </PageShell>
}
function K({i:I,l,v}:{i:typeof Users;l:string;v:string|number}){return <article className="flex h-20 items-center gap-3 rounded-3xl border bg-white p-4 shadow-sm"><span className="grid h-11 w-11 shrink-0 place-items-center rounded-full bg-teal-50 text-teal-700"><I className="h-5 w-5"/></span><div className="min-w-0"><span className="text-xs text-slate-500">{l}</span><b className="mt-1 block truncate text-xl text-slate-900">{v}</b></div></article>}
function F({l,v}:{l:string;v:number}){return <div className="flex items-center justify-between rounded-xl bg-slate-50 px-3 py-2.5 text-sm"><span>{l}</span><b>{v}</b></div>}
function Panel({title,icon:I,children}:{title:string;icon:typeof Users;children:React.ReactNode}){return <article className="rounded-3xl border bg-white p-5 shadow-sm"><div className="mb-4 flex items-center gap-2"><I className="h-5 w-5 text-teal-700"/><h3 className="font-bold">{title}</h3></div><div className="space-y-3">{children}</div></article>}
function Item({title,detail}:{title:string;detail:string}){return <div className="rounded-xl bg-slate-50 p-3"><b className="block text-sm">{title}</b><span className="text-xs text-slate-500">{detail}</span></div>}
function Alert({v,t}:{v:number;t:string}){return <div className="flex items-center justify-between rounded-xl bg-slate-50 px-3 py-2.5 text-sm"><span>{t}</span><b>{v}</b></div>}
function D({l,v}:{l:string;v:string}){return <div className="rounded-2xl bg-slate-50 p-4"><span className="text-xs text-slate-500">{l}</span><b className="mt-1 block text-xl">{v}</b></div>}
function Empty(){return <p className="text-sm text-slate-400">Nenhum item.</p>}
function money(v:number){return Number(v||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'})}
