import { useEffect, useState } from 'react'
import { Box, CalendarDays, CheckCircle2, ChevronLeft, ChevronRight, ClipboardList, Eye, FlaskConical, LayoutGrid, List, PackageOpen, Pencil, RefreshCw, Search } from 'lucide-react'
import { Link } from 'react-router-dom'
import { PageShell } from '../../components/ui/PageShell'
import { Modal } from '../../components/ui/Modal'
import { supabase } from '../../services/supabase'
import { useAuth } from '../../hooks/useAuth'

type Order={id:string;contrato_id:string|null;cliente_id:string|null;numero_os:string|null;status_os:string|null;data_agendamento:string|null;data_recepcao:string|null;data_vencimento:string|null;source_system:string|null;external_id:string|null;valor:number|null;observacoes:string|null;origem_cadastro:string|null;updated_at:string}
type Client={id:string;nome_fantasia:string|null;razao_social:string|null;responsavel_comercial_id:string|null}
type Contract={id:string;numero_contrato:string|null}
type Person={id:string;nome:string|null}
type Row=Order&{client:string;contract:string;owner:string;samples:number;received:number;params:number}
type Stats={openCount:number;scheduled:number;progress:number;waiting:number;completedMonth:number;conclusion:number;week:number;waitSamples:number;paramTotal:number}
type RpcResult={rows:Row[];total:number;stats:Stats}
type QueryResult<T>={data:T[]|null;error:{message:string}|null}
const PAGE=10,PAGE_SIZE=1000,statuses=['PRÉ-CADASTRO','AGENDADA','EM ANDAMENTO','CONCLUÍDA','CANCELADA']
const empty={numero_os:'',cliente_id:'',contrato_id:'',valor:'',status_os:'PRÉ-CADASTRO',data_agendamento:'',data_recepcao:'',data_vencimento:'',origem_cadastro:'CRM',observacoes:''}
const emptyStats:Stats={openCount:0,scheduled:0,progress:0,waiting:0,completedMonth:0,conclusion:0,week:0,waitSamples:0,paramTotal:0}
async function fetchAll<T>(makeQuery:(from:number,to:number)=>PromiseLike<QueryResult<T>>){const rows:T[]=[];for(let from=0;;from+=PAGE_SIZE){const result=await makeQuery(from,from+PAGE_SIZE-1);if(result.error)return{data:rows,error:result.error};const batch=(result.data??[]) as T[];rows.push(...batch);if(batch.length<PAGE_SIZE)return{data:rows,error:null}}}

export function OrdensServico(){
 const{hasPermission}=useAuth();const canWrite=hasPermission('crm.write')
 const[rows,setRows]=useState<Row[]>([]);const[total,setTotal]=useState(0);const[stats,setStats]=useState<Stats>(emptyStats)
 const[clients,setClients]=useState<Client[]>([]);const[contracts,setContracts]=useState<Contract[]>([]);const[people,setPeople]=useState<Person[]>([])
 const[query,setQuery]=useState('');const[status,setStatus]=useState('TODOS');const[period,setPeriod]=useState('TODOS');const[origin,setOrigin]=useState('TODAS');const[owner,setOwner]=useState('TODOS');const[mode,setMode]=useState<'list'|'cards'>('list');const[page,setPage]=useState(1)
 const[form,setForm]=useState(empty);const[editing,setEditing]=useState<string|null>(null);const[open,setOpen]=useState(false);const[saving,setSaving]=useState(false);const[error,setError]=useState('');const[loading,setLoading]=useState(false)

 async function loadMeta(){const[c,ct,u]=await Promise.all([
  fetchAll<Client>((from,to)=>supabase.from('clientes').select('id,nome_fantasia,razao_social,responsavel_comercial_id').is('deleted_at',null).order('id',{ascending:true}).range(from,to)),
  fetchAll<Contract>((from,to)=>supabase.from('contratos').select('id,numero_contrato').is('deleted_at',null).order('id',{ascending:true}).range(from,to)),
  fetchAll<Person>((from,to)=>supabase.from('profiles').select('id,nome').order('nome').range(from,to))
 ]);const e=c.error||ct.error||u.error;if(e)setError(e.message);else{setClients(c.data);setContracts(ct.data);setPeople(u.data)}}
 async function loadRows(){setLoading(true);const{data,error:rpcError}=await supabase.rpc('crm_ordens_servico_list',{p_query:query,p_status:status,p_period:period,p_origin:origin,p_owner:owner,p_page:page,p_page_size:PAGE});setLoading(false);if(rpcError){setError(rpcError.message);return}const result=(data??{}) as unknown as Partial<RpcResult>;setError('');setRows(Array.isArray(result.rows)?result.rows:[]);setTotal(Number(result.total??0));setStats({...emptyStats,...(result.stats??{})})}
 useEffect(()=>{void loadMeta()},[])
 useEffect(()=>{const timer=window.setTimeout(()=>{void loadRows()},query?250:0);return()=>window.clearTimeout(timer)},[query,status,period,origin,owner,page])
 useEffect(()=>setPage(1),[query,status,origin,owner,period,mode])
 const pages=Math.max(1,Math.ceil(total/PAGE));const paged=rows
 function start(r?:Row){if(r){setEditing(r.id);setForm({numero_os:r.numero_os||'',cliente_id:r.cliente_id||'',contrato_id:r.contrato_id||'',valor:String(r.valor??''),status_os:r.status_os||'PRÉ-CADASTRO',data_agendamento:localInput(r.data_agendamento),data_recepcao:localInput(r.data_recepcao),data_vencimento:r.data_vencimento||'',origem_cadastro:r.origem_cadastro||'CRM',observacoes:r.observacoes||''})}else{setEditing(null);setForm(empty)}setOpen(true)}
 async function save(e:React.FormEvent){e.preventDefault();if(!form.numero_os.trim()||!form.cliente_id){setError('Informe o número da OS e o cliente.');return}setSaving(true);const payload={...form,contrato_id:form.contrato_id||null,valor:form.valor?Number(form.valor):null,data_agendamento:form.data_agendamento?new Date(form.data_agendamento).toISOString():null,data_recepcao:form.data_recepcao?new Date(form.data_recepcao).toISOString():null,data_vencimento:form.data_vencimento||null};const result=editing?await supabase.from('ordens_servico').update(payload).eq('id',editing):await supabase.from('ordens_servico').insert(payload);setSaving(false);if(result.error)setError(result.error.message);else{setOpen(false);await loadRows()}}
 const ownerOptions=['TODOS','Sem responsável',...Array.from(new Set(people.map(p=>p.nome).filter((x):x is string=>Boolean(x))))]
 return <PageShell title="Ordens de Serviço" description="Acompanhe execução, coleta, recepção, amostras e andamento analítico."><section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-5"><Kpi icon={ClipboardList} label="OS abertas" value={stats.openCount}/><Kpi icon={CalendarDays} label="Agendadas" value={stats.scheduled}/><Kpi icon={FlaskConical} label="Em andamento" value={stats.progress} orange/><Kpi icon={PackageOpen} label="Aguardando recepção" value={stats.waiting} purple/><Kpi icon={CheckCircle2} label="Concluídas no mês" value={stats.completedMonth} green/></section>
 <section className="rounded-3xl border bg-white shadow-sm"><div className="flex flex-wrap items-end gap-3 border-b p-4"><div className="relative min-w-[280px] flex-1"><Search className="absolute left-3 top-3 h-4 w-4 text-slate-400"/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar nº OS, cliente, contrato ou amostra..." className="w-full rounded-xl border py-2.5 pl-9 pr-3 text-sm"/></div><Filter label="Status" value={status} set={setStatus} options={['TODOS',...statuses]}/><Filter label="Período" value={period} set={setPeriod} options={['TODOS','HOJE','7 DIAS','30 DIAS','ESTE MÊS','ATRASADAS']}/><Filter label="Origem" value={origin} set={setOrigin} options={['TODAS','CRM','GERENCIALAB']}/><Filter label="Responsável" value={owner} set={setOwner} options={ownerOptions}/><button onClick={()=>void loadRows()} className="rounded-xl border p-2.5" title="Atualizar"><RefreshCw className={`h-4 w-4 ${loading?'animate-spin':''}`}/></button><div className="flex rounded-xl border p-1"><button onClick={()=>setMode('list')} className={`inline-flex items-center gap-2 rounded-lg px-3 py-2 text-sm ${mode==='list'?'bg-teal-700 text-white':'text-slate-500'}`}><List className="h-4 w-4"/>Lista</button><button onClick={()=>setMode('cards')} className={`inline-flex items-center gap-2 rounded-lg px-3 py-2 text-sm ${mode==='cards'?'bg-teal-700 text-white':'text-slate-500'}`}><LayoutGrid className="h-4 w-4"/>Cards</button></div>{canWrite&&<button onClick={()=>start()} className="rounded-xl bg-teal-700 px-4 py-2.5 text-sm font-semibold text-white">+ Nova OS</button>}</div>{error&&<div className="m-4 rounded-xl bg-red-50 p-3 text-sm text-red-700">{error}</div>}
 {mode==='list'?<div className="overflow-x-auto"><table className="w-full min-w-[1200px] text-left text-sm"><thead className="bg-slate-50 text-xs uppercase text-slate-500"><tr><th className="px-5 py-3">OS / Cliente</th><th>Contrato</th><th>Coleta prevista</th><th>Recepção</th><th>Amostras</th><th>Parâmetros</th><th>Valor</th><th>Status</th><th>Origem</th><th>Ações</th></tr></thead><tbody className="divide-y">{paged.map(r=><tr key={r.id} className="hover:bg-slate-50"><td className="px-5 py-3"><Link to={`/ordens-servico/${r.id}`} className="font-bold text-blue-700">{r.numero_os||'Sem número'}</Link><div className="text-xs text-slate-500">{r.client}</div></td><td>{r.contract}</td><td className={isLate(r)?'text-red-600':''}>{dateTime(r.data_agendamento)}<div className="text-xs">{deadline(r.data_agendamento)}</div></td><td>{dateTime(r.data_recepcao)}</td><td><b>{r.received} / {r.samples}</b></td><td><b>{r.params}</b></td><td>{money(Number(r.valor||0))}</td><td><Status value={r.status_os}/></td><td>{source(r)}</td><td><div className="flex gap-2"><Link to={`/ordens-servico/${r.id}`} className="rounded-lg border p-2"><Eye className="h-4 w-4"/></Link>{canWrite&&<button onClick={()=>start(r)} className="rounded-lg border p-2"><Pencil className="h-4 w-4"/></button>}</div></td></tr>)}</tbody></table></div>:<div className="grid gap-4 p-4 md:grid-cols-2 xl:grid-cols-3">{paged.map(r=><article key={r.id} className="rounded-2xl border p-5"><div className="flex justify-between"><div><Link to={`/ordens-servico/${r.id}`} className="font-bold text-blue-700">{r.numero_os}</Link><p className="text-sm text-slate-500">{r.client}</p></div><Status value={r.status_os}/></div><div className="mt-4 grid grid-cols-2 gap-3"><Small label="Coleta prevista" value={dateTime(r.data_agendamento)}/><Small label="Recepção" value={dateTime(r.data_recepcao)}/><Small label="Amostras" value={`${r.received}/${r.samples}`}/><Small label="Parâmetros" value={String(r.params)}/></div><Link to={`/ordens-servico/${r.id}`} className="mt-4 block rounded-xl border py-2 text-center text-sm font-semibold text-teal-700">Abrir OS</Link></article>)}</div>}
 {!loading&&!total&&<div className="p-10 text-center text-slate-500">Nenhuma ordem de serviço encontrada.</div>}<div className="flex items-center justify-between border-t px-5 py-3 text-sm text-slate-500"><span>Mostrando {total?(page-1)*PAGE+1:0} a {Math.min(page*PAGE,total)} de {total}</span><div className="flex items-center gap-2"><button disabled={page===1||loading} onClick={()=>setPage(p=>p-1)} className="rounded-lg border p-2 disabled:opacity-40"><ChevronLeft className="h-4 w-4"/></button><span>{page} / {pages}</span><button disabled={page===pages||loading} onClick={()=>setPage(p=>p+1)} className="rounded-lg border p-2 disabled:opacity-40"><ChevronRight className="h-4 w-4"/></button></div></div><Summary conclusion={stats.conclusion} week={stats.week} waiting={stats.waitSamples} params={stats.paramTotal}/></section>
 <Modal open={open} onClose={()=>setOpen(false)} title={editing?'Editar ordem de serviço':'Nova ordem de serviço'}><form onSubmit={save} className="grid gap-4 sm:grid-cols-2"><Input label="Nº OS *" value={form.numero_os} set={v=>setForm({...form,numero_os:v})}/><SelectField label="Cliente *" value={form.cliente_id} set={v=>setForm({...form,cliente_id:v})} options={clients.map(c=>({value:c.id,label:c.nome_fantasia||c.razao_social||'Cliente'}))}/><SelectField label="Contrato" value={form.contrato_id} set={v=>setForm({...form,contrato_id:v})} options={contracts.map(c=>({value:c.id,label:c.numero_contrato||'Contrato'}))}/><Input label="Valor" type="number" value={form.valor} set={v=>setForm({...form,valor:v})}/><SelectField label="Status" value={form.status_os} set={v=>setForm({...form,status_os:v})} options={statuses.map(x=>({value:x,label:x}))}/><SelectField label="Origem" value={form.origem_cadastro} set={v=>setForm({...form,origem_cadastro:v})} options={['CRM','GERENCIALAB'].map(x=>({value:x,label:x}))}/><Input label="Coleta prevista" type="datetime-local" value={form.data_agendamento} set={v=>setForm({...form,data_agendamento:v})}/><Input label="Recepção" type="datetime-local" value={form.data_recepcao} set={v=>setForm({...form,data_recepcao:v})}/><Input label="Vencimento" type="date" value={form.data_vencimento} set={v=>setForm({...form,data_vencimento:v})}/><label className="sm:col-span-2"><span className="mb-1 block text-sm font-medium">Observações</span><textarea value={form.observacoes} onChange={e=>setForm({...form,observacoes:e.target.value})} rows={3} className="w-full rounded-xl border px-3 py-2.5"/></label><div className="sm:col-span-2 flex justify-end gap-2"><button type="button" onClick={()=>setOpen(false)} className="rounded-xl border px-4 py-2.5">Cancelar</button><button disabled={saving} className="rounded-xl bg-teal-700 px-5 py-2.5 font-semibold text-white">{saving?'Salvando...':'Salvar OS'}</button></div></form></Modal></PageShell>}

function Kpi({icon:Icon,label,value,orange=false,purple=false,green=false}:{icon:typeof Box;label:string;value:number;orange?:boolean;purple?:boolean;green?:boolean}){return <article className="h-20 rounded-3xl border bg-white p-4 shadow-sm"><div className="flex items-center gap-3"><span className={`grid h-11 w-11 shrink-0 place-items-center rounded-full ${orange?'bg-orange-50 text-orange-600':purple?'bg-violet-50 text-violet-700':green?'bg-emerald-50 text-emerald-700':'bg-teal-50 text-teal-700'}`}><Icon className="h-5 w-5"/></span><div><p className="text-xs text-slate-500">{label}</p><b className="mt-1 block text-xl text-slate-900">{value}</b></div></div></article>}
function Filter({label,value,set,options}:{label:string;value:string;set:(v:string)=>void;options:string[]}){return <label><span className="mb-1 block text-xs font-semibold text-slate-500">{label}</span><select value={value} onChange={e=>set(e.target.value)} className="rounded-xl border bg-white px-3 py-2.5 text-sm">{options.map(x=><option key={x}>{x}</option>)}</select></label>}
function Summary({conclusion,week,waiting,params}:{conclusion:number;week:number;waiting:number;params:number}){return <div className="border-t p-5"><h3 className="mb-3 font-bold">Resumo operacional</h3><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><Small label="Taxa de conclusão" value={`${conclusion}%`}/><Small label="Coletas esta semana" value={String(week)}/><Small label="Aguardando amostras" value={String(waiting)}/><Small label="Parâmetros em execução" value={String(params)}/></div></div>}
function Small({label,value}:{label:string;value:string}){return <div className="rounded-2xl bg-slate-50 p-3"><p className="text-xs text-slate-500">{label}</p><b>{value}</b></div>}
function Status({value}:{value:string|null}){const v=value||'SEM STATUS';return <span className={`rounded-full px-2.5 py-1 text-[11px] font-bold ${v==='CONCLUÍDA'?'bg-emerald-100 text-emerald-700':v==='CANCELADA'?'bg-red-100 text-red-700':v==='EM ANDAMENTO'?'bg-orange-100 text-orange-700':'bg-blue-100 text-blue-700'}`}>{v}</span>}
function Input({label,value,set,type='text'}:{label:string;value:string;set:(v:string)=>void;type?:string}){return <label><span className="mb-1 block text-sm font-medium">{label}</span><input type={type} value={value} onChange={e=>set(e.target.value)} className="w-full rounded-xl border px-3 py-2.5"/></label>}
function SelectField({label,value,set,options}:{label:string;value:string;set:(v:string)=>void;options:{value:string;label:string}[]}){return <label><span className="mb-1 block text-sm font-medium">{label}</span><select value={value} onChange={e=>set(e.target.value)} className="w-full rounded-xl border bg-white px-3 py-2.5"><option value="">Selecione</option>{options.map(x=><option key={x.value} value={x.value}>{x.label}</option>)}</select></label>}
function source(r:Order){return String(r.origem_cadastro||r.source_system||'CRM').toUpperCase().replace('GERENCIA_LAB','GERENCIALAB')}
function dateTime(v:string|null){return v?new Date(v).toLocaleDateString('pt-BR'):'—'}
function localInput(v:string|null){if(!v)return'';const d=new Date(v);return new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,16)}
function money(v:number){return v.toLocaleString('pt-BR',{style:'currency',currency:'BRL'})}
function isLate(r:Order){return !!r.data_agendamento&&!['CONCLUÍDA','CANCELADA'].includes(r.status_os||'')&&new Date(r.data_agendamento).getTime()<Date.now()}
function deadline(v:string|null){if(!v)return'';const days=Math.ceil((new Date(v).getTime()-Date.now())/86400000);return days<0?`atrasada ${Math.abs(days)} dia(s)`:days===0?'hoje':days===1?'amanhã':`em ${days} dias`}
