import { createClient } from "https://esm.sh/@supabase/supabase-js@2.45.0";
const U=Deno.env.get("SUPABASE_URL")!,K=Deno.env.get("SB_SECRET_KEY")??Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!,T=Deno.env.get("ML_TOKEN")??"",J=Deno.env.get("ML_JWT_SECRET")??"",RH="5f9143e3fb561d5cc8230032392c96a9743645ea1054d436974ea5f4a989da18";
const sb=createClient(U,K,{auth:{persistSession:false,autoRefreshToken:false}}),enc=new TextEncoder(),dec=new TextDecoder();
const C={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type, x-token, x-rotina-token","Access-Control-Allow-Methods":"POST, OPTIONS"};
const out=(d:any,s=200)=>new Response(JSON.stringify(d),{status:s,headers:{...C,"Content-Type":"application/json; charset=utf-8","Cache-Control":"no-store"}}),txt=(v:any)=>String(v??"").trim(),num=(v:any)=>Number.isFinite(Number(v))?Number(v):0,now=()=>new Date().toISOString();
const doc=(v:any)=>txt(v).replace(/\D/g,""); const clienteKey=(x:any)=>doc(x?.cnpj_cpf)||txt(x?.cliente).toUpperCase();
function b64u(s:string){s=s.replace(/-/g,"+").replace(/_/g,"/");while(s.length%4)s+="=";const b=atob(s),o=new Uint8Array(b.length);for(let i=0;i<b.length;i++)o[i]=b.charCodeAt(i);return o}
async function sha(s:string){const h=new Uint8Array(await crypto.subtle.digest("SHA-256",enc.encode(s)));return Array.from(h).map(x=>x.toString(16).padStart(2,"0")).join("")}
async function jwt(t:string){if(!J||!t)return null;const p=t.split(".");if(p.length!==3)return null;try{const k=await crypto.subtle.importKey("raw",enc.encode(J),{name:"HMAC",hash:"SHA-256"},false,["verify"]);if(!await crypto.subtle.verify("HMAC",k,b64u(p[2]),enc.encode(`${p[0]}.${p[1]}`)))return null;const x=JSON.parse(dec.decode(b64u(p[1])));if(x.sis!=="minaslab"||(typeof x.exp==="number"&&x.exp<Math.floor(Date.now()/1000)))return null;return x}catch{return null}}
const chaveRef=(v:any)=>{const s=txt(v).toUpperCase().replace(/\s+/g,"");return /^\d+$/.test(s)?s.replace(/^0+(?=\d)/,""):s};
const pedido=(r:any)=>chaveRef(r?.dados_omie?.numero_pedido??r?.dados_omie?.numeroPedido??r?.dados_omie?.nNumeroPedido??r?.dados_omie?.codigo_pedido??r?.codigo_lancamento_integracao);
const adicionar=(map:Map<string,any[]>,chave:string,item:any)=>{if(!chave)return;map.set(chave,[...(map.get(chave)||[]),item])};
const unicos=(itens:any[])=>[...new Map(itens.map((x:any)=>[x.id,x])).values()];
async function audit(id:string,campo:string,a:any,n:any,u:string){if(String(a??"")===String(n??""))return;const q=await sb.from("servicos_gerados_historico").insert({servico_id:id,campo,valor_anterior:a==null?null:String(a),valor_novo:n==null?null:String(n),origem:"AUTOMATICO",usuario:u});if(q.error)console.error("audit",q.error)}
function statusRecebimento(r:any){const rs=txt(r?.status).toUpperCase();if(r?.origem==="OMIE"&&txt(r?.status_omie).toUpperCase()==="RECEBIDO")return"PAGO";if(rs==="PAGO")return"PAGO";if(rs==="PARCIAL")return"PARCIAL";if(rs==="VENCIDO")return"VENCIDO";if(rs==="CANCELADO")return"CANCELADO";return"A RECEBER"}
Deno.serve(async req=>{if(req.method==="OPTIONS")return new Response("ok",{headers:C});if(req.method!=="POST")return out({erro:"Use POST."},405);const m=txt(req.headers.get("authorization")).match(/^Bearer\s+(.+)$/i),cr=m?await jwt(m[1]):null,maq=!!T&&req.headers.get("x-token")===T,rot=!!req.headers.get("x-rotina-token")&&(await sha(req.headers.get("x-rotina-token")||""))===RH;if(!cr&&!maq&&!rot)return out({erro:"Entre no sistema.",semSessao:true},401);if(!maq&&!rot&&txt(cr?.papel)!=="direcao"){if(txt(cr?.papel)!=="equipe")return out({erro:"Esta ação é exclusiva da equipe autorizada e da direção.",semPermissao:true},403);const acesso=await sb.from("ml_contas").select("ativo,paginas_consulta").eq("usuario",txt(cr?.sub)).maybeSingle();if(acesso.error||!acesso.data?.ativo||!Array.isArray(acesso.data.paginas_consulta)||!acesso.data.paginas_consulta.includes("financas/servicos-gerados"))return out({erro:"Sem acesso a Serviços Gerados.",semPermissao:true},403);}const usuario=rot?"rotina-servicos":maq?"maquina":txt(cr?.sub)||"direcao";
try{
 const qs=await sb.from("servicos_gerados").select("id,empresa_id,cliente,cnpj_cpf,numero_nf,referencia_pagamento,pagamento_referencia,status_pagamento,valor_faturar,valor_original,data_vencimento,pagamento_manual,recebimento_id,empresa:empresas(nome,usa_omie)").eq("apagado",false).eq("status_faturamento","FATURADO").limit(5000);if(qs.error)throw qs.error;
 const qr=await sb.from("recebimentos").select("id,empresa_id,cliente,cnpj_cpf,origem,status_omie,status,valor_previsto,valor_recebido,data_pagamento,data_vencimento,numero_nf,codigo_lancamento_integracao,dados_omie").eq("apagado",false).limit(10000);if(qr.error)throw qr.error;
 const qi=await sb.from("servicos_gerados_grupos_itens").select("grupo_id,servico_id").limit(10000);if(qi.error)throw qi.error;
 const serv=qs.data??[],recs=qr.data??[],itens=qi.data??[],recById=new Map(recs.map((r:any)=>[r.id,r])),grupoByServico=new Map(itens.map((i:any)=>[i.servico_id,i.grupo_id]));
 const porPedido=new Map<string,any[]>(),porNf=new Map<string,any[]>();for(const r of recs){const p=pedido(r),nf=chaveRef(r.numero_nf);adicionar(porPedido,`${r.empresa_id}|${p}`,r);adicionar(porNf,`${r.empresa_id}|${nf}`,r)}
 const grupos=new Map<string,{usaOmie:boolean,empresaId:string,ref:string,cliente:string,itens:any[]}>();let semRef=0;
 for(const s of serv){const emp=Array.isArray(s.empresa)?s.empresa[0]:s.empresa,usaOmie=!!emp?.usa_omie,ref=txt(usaOmie?(s.referencia_pagamento||s.pagamento_referencia):(s.numero_nf||s.referencia_pagamento||s.pagamento_referencia));if(!ref){if(!s.pagamento_manual)semRef++;continue}const gid=grupoByServico.get(s.id),ck=clienteKey(s),k=gid?`G|${gid}`:`${usaOmie?"O":"M"}|${s.empresa_id}|${ref}|${ck}`,g=grupos.get(k)??{usaOmie,empresaId:s.empresa_id,ref,cliente:ck,itens:[]};g.itens.push(s);grupos.set(k,g)}
 let atualizados=0,naoEncontrados=0,ambiguos=0,inalterados=0,gruposCompartilhados=0;
 for(const [groupKey,g] of grupos){
   let automaticos=g.itens.filter((s:any)=>!s.pagamento_manual);
   const linked=[...new Set(g.itens.map((s:any)=>s.recebimento_id).filter(Boolean))],totalGrupo=g.itens.reduce((a:number,x:any)=>a+num(x.valor_faturar??x.valor_original),0);let arr:any[]=[];
   if(linked.length===1&&recById.has(linked[0]))arr=[recById.get(linked[0])];else{
    const refs=[...new Set(g.itens.flatMap((s:any)=>[s.referencia_pagamento,s.pagamento_referencia]).map(chaveRef).filter(Boolean))],nfs=[...new Set(g.itens.map((s:any)=>chaveRef(s.numero_nf)).filter(Boolean))];
    const buscar=(map:Map<string,any[]>,chaves:string[])=>unicos(chaves.flatMap(chave=>map.get(`${g.empresaId}|${chave}`)||[]));
    arr=g.usaOmie?buscar(porPedido,refs):buscar(porNf,nfs);
    if(!arr.length)arr=g.usaOmie?buscar(porNf,nfs):buscar(porPedido,refs);
    if(arr.length>1){const mesmoCliente=arr.filter((r:any)=>clienteKey(r)===g.cliente);if(mesmoCliente.length)arr=mesmoCliente}
    if(arr.length>1&&totalGrupo>0){const mesmoValor=arr.filter((r:any)=>Math.abs(num(r.valor_previsto)-totalGrupo)<=0.01);if(mesmoValor.length)arr=mesmoValor}
   }
   if(arr.length===0){naoEncontrados+=automaticos.length;continue}if(arr.length>1){ambiguos+=automaticos.length;continue}
   const r=arr[0];if(r.origem==="OMIE"&&txt(r.status_omie).toUpperCase()==="RECEBIDO")automaticos=g.itens.filter((s:any)=>!s.pagamento_manual||s.recebimento_id===r.id||chaveRef(s.referencia_pagamento||s.pagamento_referencia)===pedido(r));if(!automaticos.length)continue;const docRec=doc(r.cnpj_cpf),docsGrupo=[...new Set(g.itens.map((s:any)=>doc(s.cnpj_cpf)).filter(Boolean))];if(r.empresa_id!==g.empresaId||!docRec||docsGrupo.length!==1||docsGrupo[0]!==docRec){ambiguos+=automaticos.length;continue}const nfsGrupo=[...new Set(g.itens.map((s:any)=>chaveRef(s.numero_nf)).filter(Boolean))];if(r.numero_nf&&nfsGrupo.length&&nfsGrupo.some((nf:string)=>nf!==chaveRef(r.numero_nf))){ambiguos+=automaticos.length;continue}let st=statusRecebimento(r);const vr=num(r.valor_previsto);if(st!=="PAGO"&&totalGrupo>0&&vr>0&&Math.abs(totalGrupo-vr)>0.01)st="DIVERGENCIA";if(g.itens.length>1)gruposCompartilhados++;
   for(const s of automaticos){const p:any={status_pagamento:st,pagamento_origem:g.usaOmie?"OMIE (numero_pedido)":"FINANCEIRO M LAB (NF)",pagamento_referencia:g.ref,pagamento_identificado_em:now(),recebimento_id:r.id,updated_at:now(),updated_by:usuario};if(s.pagamento_manual&&st==="PAGO"&&r.origem==="OMIE"&&txt(r.status_omie).toUpperCase()==="RECEBIDO")p.pagamento_manual=false;if(!s.numero_nf&&r.numero_nf)p.numero_nf=r.numero_nf;if(!s.data_vencimento&&r.data_vencimento)p.data_vencimento=r.data_vencimento;const mudou=st!==s.status_pagamento||(!s.numero_nf&&!!r.numero_nf)||(!s.data_vencimento&&!!r.data_vencimento)||s.recebimento_id!==r.id||p.pagamento_manual===false;if(!mudou){inalterados++;continue}const u=await sb.from("servicos_gerados").update(p).eq("id",s.id);if(u.error)throw u.error;await audit(s.id,"status_pagamento",s.status_pagamento,st,usuario);atualizados++}if(groupKey.startsWith("G|")&&st==="PAGO"&&automaticos.length===g.itens.length){const ug=await sb.from("servicos_gerados_grupos_faturamento").update({status_pagamento:"PAGO",updated_at:now()}).eq("id",groupKey.slice(2));if(ug.error)throw ug.error}
 }
 return out({ok:true,atualizados,semReferencia:semRef,naoEncontrados,ambiguos,inalterados,gruposCompartilhados,chaveMinasLab:"recebimento vinculado; fallback por empresa + referência/pedido; depois NF; cliente e valor resolvem duplicidades",mLab:"recebimento vinculado; fallback por empresa + NF; depois referência; cliente e valor resolvem duplicidades. A baixa usa o status financeiro do recebimento.",regraGrupo:"Grupo explícito tem prioridade e, havendo um único recebimento já vinculado ao grupo, ele é a fonte de verdade. Divergência compara o total do grupo com esse recebimento."});
}catch(e:any){console.error(e);return out({erro:e?.message||JSON.stringify(e)||String(e)},500)}});
