import { useEffect, useState } from 'react'
import { ArrowLeft, Plus, Trash2 } from 'lucide-react'
import { Link, useParams } from 'react-router-dom'
import { PageShell } from '../../components/ui/PageShell'
import { Modal } from '../../components/ui/Modal'
import { supabase } from '../../services/supabase'
import { useAuth } from '../../hooks/useAuth'

type OS={id:string;numero_os:string|null;status_os:string|null;cliente_id:string|null;contrato_id:string|null;data_agendamento:string|null;data_recepcao:string|null;clientes?:{razao_social:string|null;nome_fantasia:string|null}|null}
type Sample={id:string;referencia_amostra:string|null;codigo_barra:string|null;descricao:string|null;grupo_snapshot:string|null;servico_snapshot:string|null;data_entrada:string|null}
type Param={id:string;parametro_rotulo_snapshot:string|null;metodo:string|null;lq:string|null;ld:string|null;unidade:string|null;tipo_execucao:string|null;laboratorios_parceiros?:{nome:string|null}|null}
export function OrdemServicoDetalhe(){const{id}=useParams();const{hasPermission}=useAuth();const canImport=hasPermission('operational.import');const[os,setOs]=useState<OS|null>(null);const[samples,setSamples]=useState<Sample[]>([]);const[selected,setSelected]=useState<string|null>(null);const[params,setParams]=useState<Param[]>([]);const[sampleOpen,setSampleOpen]=useState(false);const[paramOpen,setParamOpen]=useState(false);const[error,setError]=useState('');const[sf,setSf]=useState({referencia_amostra:'',codigo_barra:'',descricao:'',grupo_snapshot:'',servico_snapshot:'',data_entrada:''});const[pf,setPf]=useState({parametro_rotulo_snapshot:'',metodo:'',lq:'',ld:'',unidade:''})
async function load(){if(!id)return;const[{data:o,error:e1},{data:s,error:e2}]=await Promise.all([supabase.from('ordens_servico').select('id,numero_os,status_os,cliente_id,contrato_id,data_agendamento,data_recepcao,clientes(razao_social,nome_fantasia)').eq('id',id).single(),supabase.from('amostras').select('id,referencia_amostra,codigo_barra,descricao,grupo_snapshot,servico_snapshot,data_entrada').eq('ordem_servico_id',id).is('deleted_at',null).order('created_at',{ascending:true})]);if(e1||e2)setError(e1?.message||e2?.message||'Erro');else{setOs(o as unknown as OS);setSamples((s??[]) as Sample[]);if(!selected&&s?.[0])setSelected(String(s[0].id))}}
async function loadParams(sampleId:string|null){if(!sampleId){setParams([]);return}const{data,error}=await supabase.from('amostra_parametros').select('id,parametro_rotulo_snapshot,metodo,lq,ld,unidade,tipo_execucao,laboratorios_parceiros(nome)').eq('amostra_id',sampleId).is('deleted_at',null).order('created_at',{ascending:true});if(error)setError(error.message);else setParams((data??[]) as unknown as Param[])}
useEffect(()=>{void load()},[id]);useEffect(()=>{void loadParams(selected)},[selected])
async function addSample(e:React.FormEvent){e.preventDefault();if(!canImport||!id)return;const payload={ordem_servico_id:id,...sf,data_entrada:sf.data_entrada?new Date(sf.data_entrada).toISOString():null};const{error}=await supabase.from('amostras').insert(payload);if(error)setError(error.message);else{setSampleOpen(false);setSf({referencia_amostra:'',codigo_barra:'',descricao:'',grupo_snapshot:'',servico_snapshot:'',data_entrada:''});await load()}}
async function addParam(e:React.FormEvent){e.preventDefault();if(!canImport||!selected)return;const{error}=await supabase.from('amostra_parametros').insert({amostra_id:selected,...pf});if(error)setError(error.message);else{setParamOpen(false);setPf({parametro_rotulo_snapshot:'',metodo:'',lq:'',ld:'',unidade:''});await loadParams(selected)}}
async function softDelete(table:string,itemId:string){if(!canImport)return;const{error}=await supabase.from(table).update({deleted_at:new Date().toISOString()}).eq('id',itemId);if(error)setError(error.message);else if(table==='amostras'){if(selected===itemId)setSelected(null);await load()}else await loadParams(selected)}
return <PageShell title={os?.numero_os?`OS ${os.numero_os}`:'Detalhes da OS'} description="Execução operacional, amostras e contexto técnico dos parâmetros." action={<Link to="/ordens-servico" className="inline-flex items-center gap-2 rounded-xl border bg-white px-4 py-2.5 text-sm font-semibold text-slate-600"><ArrowLeft className="h-4 w-4"/>Voltar</Link>}>
{error&&<div className="rounded-xl border border-red-200 bg-red-50 p-3 text-sm text-red-700">{error}</div>}{os&&<section className="grid gap-4 md:grid-cols-3"><Info label="Cliente" value={os.clientes?.nome_fantasia||os.clientes?.razao_social||'—'}/><Info label="Status" value={os.status_os||'—'}/><Info label="Recepção" value={os.data_recepcao?new Date(os.data_recepcao).toLocaleString('pt-BR'):'—'}/></section>}
<section className="grid gap-5 xl:grid-cols-[1fr_1.2fr]"><article className="rounded-3xl border bg-white shadow-sm"><div className="flex items-center justify-between border-b p-5"><div><h3 className="font-semibold">Amostras</h3><p className="text-sm text-slate-500">Uma OS pode possuir várias amostras.</p></div>{canImport&&<button onClick={()=>setSampleOpen(true)} className="inline-flex items-center gap-2 rounded-xl bg-teal-700 px-3 py-2 text-sm font-semibold text-white"><Plus className="h-4 w-4"/>Amostra</button>}</div><div className="divide-y">{samples.length===0?<div className="p-8 text-center text-sm text-slate-500">Sem amostras.</div>:samples.map(s=><button key={s.id} onClick={()=>setSelected(s.id)} className={`flex w-full items-start justify-between gap-3 p-4 text-left ${selected===s.id?'bg-teal-50':'hover:bg-slate-50'}`}><div><div className="font-semibold text-slate-800">{s.referencia_amostra||s.codigo_barra||'Amostra'}</div><div className="mt-1 text-xs text-slate-500">{s.descricao||'Sem descrição'} · {s.servico_snapshot||'Serviço não informado'}</div></div>{canImport&&<span onClick={e=>{e.stopPropagation();void softDelete('amostras',s.id)}} className="rounded-lg border bg-white p-2 text-slate-400 hover:text-red-600"><Trash2 className="h-4 w-4"/></span>}</button>)}</div></article>
<article className="rounded-3xl border bg-white shadow-sm"><div className="flex items-center justify-between border-b p-5"><div><h3 className="font-semibold">Parâmetros da amostra</h3><p className="text-sm text-slate-500">Método, limites e laboratório responsável pela execução.</p></div>{canImport&&<button disabled={!selected} onClick={()=>setParamOpen(true)} className="inline-flex items-center gap-2 rounded-xl bg-teal-700 px-3 py-2 text-sm font-semibold text-white disabled:opacity-40"><Plus className="h-4 w-4"/>Parâmetro</button>}</div><div className="overflow-x-auto"><table className="min-w-full text-sm"><thead className="bg-slate-50 text-left text-xs uppercase text-slate-500"><tr><th className="px-4 py-3">Parâmetro</th><th className="px-4 py-3">Método</th><th className="px-4 py-3">LQ</th><th className="px-4 py-3">LD</th><th className="px-4 py-3">Unidade</th><th className="px-4 py-3">Execução</th><th className="px-4 py-3">Laboratório</th><th/></tr></thead><tbody className="divide-y">{params.length===0?<tr><td colSpan={8} className="p-8 text-center text-slate-500">{selected?'Sem parâmetros.':'Selecione uma amostra.'}</td></tr>:params.map(p=><tr key={p.id}><td className="px-4 py-3 font-medium">{p.parametro_rotulo_snapshot||'—'}</td><td className="px-4 py-3">{p.metodo||'—'}</td><td className="px-4 py-3">{p.lq||'—'}</td><td className="px-4 py-3">{p.ld||'—'}</td><td className="px-4 py-3">{p.unidade||'—'}</td><td className="px-4 py-3"><span className="rounded-full bg-teal-50 px-2 py-1 text-xs font-semibold text-teal-800">{/TERCEIR/i.test(p.tipo_execucao||'')?'Terceirizada':'Interna'}</span></td><td className="px-4 py-3">{p.laboratorios_parceiros?.nome||'MinasLab'}</td><td className="px-4 py-3">{canImport&&<button onClick={()=>void softDelete('amostra_parametros',p.id)} className="rounded-lg border p-2 text-slate-400 hover:text-red-600"><Trash2 className="h-4 w-4"/></button>}</td></tr>)}</tbody></table></div></article></section>
<Modal open={sampleOpen} onClose={()=>setSampleOpen(false)} title="Nova amostra"><form onSubmit={addSample} className="grid gap-4 sm:grid-cols-2">{Object.entries({referencia_amostra:'Referência',codigo_barra:'Código de barras',descricao:'Descrição',grupo_snapshot:'Grupo',servico_snapshot:'Serviço'}).map(([k,l])=><label key={k}><span className="mb-1 block text-sm font-medium">{l}</span><input value={(sf as any)[k]} onChange={e=>setSf({...sf,[k]:e.target.value})} className="w-full rounded-xl border px-3 py-2.5"/></label>)}<label><span className="mb-1 block text-sm font-medium">Data de entrada</span><input type="datetime-local" value={sf.data_entrada} onChange={e=>setSf({...sf,data_entrada:e.target.value})} className="w-full rounded-xl border px-3 py-2.5"/></label><Actions cancel={()=>setSampleOpen(false)}/></form></Modal>
<Modal open={paramOpen} onClose={()=>setParamOpen(false)} title="Novo parâmetro"><form onSubmit={addParam} className="grid gap-4 sm:grid-cols-2">{Object.entries({parametro_rotulo_snapshot:'Parâmetro',metodo:'Método',lq:'LQ',ld:'LD',unidade:'Unidade'}).map(([k,l])=><label key={k}><span className="mb-1 block text-sm font-medium">{l}</span><input value={(pf as any)[k]} onChange={e=>setPf({...pf,[k]:e.target.value})} className="w-full rounded-xl border px-3 py-2.5"/></label>)}<Actions cancel={()=>setParamOpen(false)}/></form></Modal></PageShell>}
function Info({label,value}:{label:string;value:string}){return <article className="rounded-3xl border bg-white p-5 shadow-sm"><div className="text-xs font-semibold uppercase text-slate-400">{label}</div><div className="mt-2 font-semibold text-slate-900">{value}</div></article>}
function Actions({cancel}:{cancel:()=>void}){return <div className="sm:col-span-2 flex justify-end gap-2"><button type="button" onClick={cancel} className="rounded-xl border px-4 py-2">Cancelar</button><button className="rounded-xl bg-teal-700 px-4 py-2 font-semibold text-white">Salvar</button></div>}
