import { useEffect, useMemo, useRef, useState } from 'react'
import { ArrowRight, CheckCircle2, Clock3, Eye, Headphones, PhoneCall, RefreshCw, Search, UsersRound } from 'lucide-react'
import { Link } from 'react-router-dom'
import { PageShell } from '../../components/ui/PageShell'
import { TimelinePanel } from '../../components/timeline/TimelinePanel'
import { UserAvatar } from '../../components/users/UserAvatar'
import { supabase } from '../../services/supabase'
import { useAuth } from '../../hooks/useAuth'

type Match={id:string;razao_social:string|null;nome_fantasia:string|null;cpf_cnpj_original:string|null;telefone_principal:string|null;email_principal:string|null}
type Option={value:string;label:string}
type User={id:string;nome:string|null;avatar_url:string|null;ativo:boolean}
type Lead={id:string;nome:string|null;telefone_whatsapp:string|null;origem:string|null;assunto:string|null;tipo_analise:string|null;status:string|null;data_primeiro_atendimento:string|null;resumo:string|null;responsavel_id:string|null}
type LastInteraction={lead_id:string|null;ocorrido_em:string;descricao:string}
const statuses=['EM ATENDIMENTO','QUALIFICADO','CONVERTIDO','ENCERRADO']
export function PrimeiroAtendimento(){
 const {profile,hasPermission}=useAuth();const canWrite=hasPermission('crm.write')
 const[term,setTerm]=useState('');const[matches,setMatches]=useState<Match[]>([]);const[loading,setLoading]=useState(false);const[error,setError]=useState('');
 const[origins,setOrigins]=useState<Option[]>([]);const[analysisTypes,setAnalysisTypes]=useState<Option[]>([]);const[users,setUsers]=useState<User[]>([]);const[leads,setLeads]=useState<Lead[]>([]);const[interactions,setInteractions]=useState<LastInteraction[]>([]);const[selected,setSelected]=useState<Lead|null>(null);const[saving,setSaving]=useState(false)
 const[listTerm,setListTerm]=useState('');const[statusFilter,setStatusFilter]=useState('TODOS');const[originFilter,setOriginFilter]=useState('TODAS');const[userFilter,setUserFilter]=useState('TODOS');const[from,setFrom]=useState('');const[to,setTo]=useState('')
 const[form,setForm]=useState({nome:'',telefone_whatsapp:'',origem:'',assunto:'',status:'EM ATENDIMENTO',tipos:[] as string[],resumo:'',responsavel_id:''});const panelRef=useRef<HTMLDivElement|null>(null);const normalized=useMemo(()=>term.trim(),[term])
 async function loadBase(){const[originResult,groupResult,userResult,leadResult,interactionResult]=await Promise.all([
   supabase.from('crm_listas').select('valor').eq('tipo','ORIGEM_ATENDIMENTO').eq('ativo',true).order('ordem'),
   supabase.from('grupos').select('nome').eq('ativo',true).is('deleted_at',null).order('nome'),
   supabase.from('profiles').select('id,nome,avatar_url,ativo').order('nome'),
   supabase.from('leads').select('id,nome,telefone_whatsapp,origem,assunto,tipo_analise,status,data_primeiro_atendimento,resumo,responsavel_id').is('deleted_at',null).order('data_primeiro_atendimento',{ascending:false}).limit(1000),
   supabase.from('interacoes').select('lead_id,ocorrido_em,descricao').not('lead_id','is',null).order('ocorrido_em',{ascending:false}).limit(2000),
  ]);const err=originResult.error||groupResult.error||userResult.error||leadResult.error||interactionResult.error;if(err){setError(err.message);return}setOrigins((originResult.data??[]).map(x=>({value:String(x.valor),label:String(x.valor)})));setAnalysisTypes((groupResult.data??[]).map(x=>({value:String(x.nome),label:String(x.nome)})));setUsers((userResult.data??[]) as User[]);const loadedLeads=(leadResult.data??[]) as Lead[];setLeads(loadedLeads);setSelected(current=>current?loadedLeads.find(item=>item.id===current.id)??loadedLeads[0]??null:loadedLeads[0]??null);setInteractions((interactionResult.data??[]) as LastInteraction[])}
 useEffect(()=>{void loadBase()},[]);useEffect(()=>{if(!form.responsavel_id&&profile?.id)setForm(f=>({...f,responsavel_id:profile.id}))},[profile?.id])
 async function search(){setLoading(true);setError('');if(!normalized){setMatches([]);setLoading(false);return}const safe=normalized.replace(/[%_,()]/g,' ');const{data,error}=await supabase.from('clientes').select('id,razao_social,nome_fantasia,cpf_cnpj_original,telefone_principal,email_principal').is('deleted_at',null).or(`cpf_cnpj_original.ilike.%${safe}%,telefone_principal.ilike.%${safe}%,email_principal.ilike.%${safe}%,razao_social.ilike.%${safe}%,nome_fantasia.ilike.%${safe}%`).limit(20);if(error)setError(error.message);else setMatches((data??[]) as Match[]);setLoading(false)}
 useEffect(()=>{const t=setTimeout(()=>{if(normalized.length>=3)void search();else setMatches([])},350);return()=>clearTimeout(t)},[normalized])
 function toggleType(value:string){setForm(c=>({...c,tipos:c.tipos.includes(value)?c.tipos.filter(x=>x!==value):[...c.tipos,value]}))}
 function resetForm(){setForm({nome:'',telefone_whatsapp:'',origem:'',assunto:'',status:'EM ATENDIMENTO',tipos:[],resumo:'',responsavel_id:profile?.id??''})}
 async function createLead(e:React.FormEvent){e.preventDefault();if(!canWrite)return;setError('');if(!form.nome.trim()){setError('Informe o nome do interessado.');return}if(!form.telefone_whatsapp.trim()){setError('Informe telefone ou WhatsApp.');return}if(!form.origem){setError('Selecione a origem.');return}if(!form.responsavel_id){setError('Selecione o responsável.');return}if(form.tipos.length===0){setError('Assinale ao menos um item do Escopo Analítico.');return}setSaving(true);const{data,error}=await supabase.from('leads').insert({nome:form.nome.trim(),telefone_whatsapp:form.telefone_whatsapp.trim(),origem:form.origem,assunto:form.assunto.trim()||null,tipo_analise:form.tipos.join(', '),resumo:form.resumo.trim()||null,status:form.status,responsavel_id:form.responsavel_id,data_primeiro_atendimento:new Date().toISOString(),created_by:profile?.id??null}).select('id,nome,telefone_whatsapp,origem,assunto,tipo_analise,status,data_primeiro_atendimento,resumo,responsavel_id').single();if(error)setError(error.message);else{resetForm();setSelected(data as Lead);await loadBase()}setSaving(false)}
 const today=new Date().toDateString();const stats={hoje:leads.filter(l=>l.data_primeiro_atendimento&&new Date(l.data_primeiro_atendimento).toDateString()===today).length,triagem:leads.filter(l=>String(l.status).toUpperCase().includes('QUALIFIC')).length,andamento:leads.filter(l=>String(l.status).toUpperCase().includes('ATENDIMENTO')).length,concluidos:leads.filter(l=>String(l.status).toUpperCase().includes('ENCERR')).length,convertidos:leads.filter(l=>String(l.status).toUpperCase().includes('CONVERT')).length}
 const userInfo=(id:string|null)=>users.find(u=>u.id===id)||{id:'',nome:'Sem responsável',avatar_url:null,ativo:false};const userName=(id:string|null)=>userInfo(id).nome||'Sem responsável';const lastInteraction=(leadId:string)=>interactions.find(i=>i.lead_id===leadId)
 function viewLead(lead:Lead){setSelected(lead);window.requestAnimationFrame(()=>panelRef.current?.scrollIntoView({behavior:'smooth',block:'start'}))}
 const filtered=leads.filter(l=>{const q=listTerm.toLowerCase().trim();const text=`${l.nome||''} ${l.telefone_whatsapp||''} ${l.origem||''} ${l.assunto||''} ${userName(l.responsavel_id)}`.toLowerCase();const d=l.data_primeiro_atendimento?new Date(l.data_primeiro_atendimento):null;const after=!from||!!d&&d>=new Date(from+'T00:00:00');const before=!to||!!d&&d<=new Date(to+'T23:59:59');return(!q||text.includes(q))&&(statusFilter==='TODOS'||l.status===statusFilter)&&(originFilter==='TODAS'||l.origem===originFilter)&&(userFilter==='TODOS'||l.responsavel_id===userFilter)&&after&&before})
 const activeUsers=users.filter(u=>u.ativo);const filterUsers=users.filter(u=>u.ativo||leads.some(l=>l.responsavel_id===u.id))
 return <PageShell title="Comercial / Atendimentos" description="Operação comercial completa: entrada, triagem, responsável, acompanhamento e evolução em uma única tela.">
  {error&&<div className="rounded-2xl border border-red-200 bg-red-50 p-4 text-sm text-red-700">{error}</div>}
  <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-5"><Kpi icon={PhoneCall} label="Atendimentos hoje" value={stats.hoje}/><Kpi icon={Clock3} label="Em triagem" value={stats.triagem}/><Kpi icon={UsersRound} label="Em andamento" value={stats.andamento}/><Kpi icon={CheckCircle2} label="Concluídos" value={stats.concluidos}/><Kpi icon={ArrowRight} label="Convertidos" value={stats.convertidos}/></section>
  <section className="grid gap-5 xl:grid-cols-[440px_1fr]">
   <form onSubmit={createLead} className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm"><div className="mb-5 flex items-center gap-3 border-b pb-4"><span className="grid h-10 w-10 place-items-center rounded-full bg-teal-50 text-teal-700"><Headphones className="h-5 w-5"/></span><div><h3 className="font-bold text-slate-900">Novo atendimento</h3><p className="text-xs text-slate-500">Registre e encaminhe o primeiro contato comercial</p></div></div><div className="space-y-4"><F required label="Nome do interessado" value={form.nome} set={v=>setForm({...form,nome:v})} placeholder="Razão Social / Nome Completo"/><F required label="Telefone / WhatsApp" value={form.telefone_whatsapp} set={v=>setForm({...form,telefone_whatsapp:v})} placeholder="(00) 00000-0000"/><div className="grid grid-cols-2 gap-3"><S label="Origem" value={form.origem} set={v=>setForm({...form,origem:v})} options={origins}/><F label="Assunto" value={form.assunto} set={v=>setForm({...form,assunto:v})} placeholder="Dúvida / Escopo"/></div><S label="Responsável" value={form.responsavel_id} set={v=>setForm({...form,responsavel_id:v})} options={activeUsers.map(u=>({value:u.id,label:u.nome||'Usuário'}))}/><S label="Status operacional" value={form.status} set={v=>setForm({...form,status:v})} options={statuses.map(v=>({value:v,label:v}))}/><label><span className="mb-1 block text-xs font-semibold uppercase text-slate-600">Observações iniciais</span><textarea value={form.resumo} onChange={e=>setForm({...form,resumo:e.target.value})} placeholder="Notas iniciais sobre o contato..." className="min-h-24 w-full rounded-xl border border-slate-200 px-3 py-2.5 text-sm outline-none focus:border-teal-500 focus:ring-2 focus:ring-teal-100"/></label><div className="rounded-2xl border border-slate-200 bg-slate-50/60 p-4"><div className="mb-3 text-xs font-bold uppercase tracking-wide text-slate-700">Escopo analítico</div><div className="grid grid-cols-2 gap-3">{analysisTypes.map(o=><label key={o.value} className="flex items-center gap-2 text-sm text-slate-700"><input type="checkbox" checked={form.tipos.includes(o.value)} onChange={()=>toggleType(o.value)} className="h-4 w-4 rounded border-slate-300 accent-teal-700"/>{o.label}</label>)}</div></div>{canWrite?<div className="grid grid-cols-2 gap-3"><button type="button" onClick={resetForm} className="rounded-xl border border-teal-600 px-4 py-3 text-sm font-bold text-teal-700">Limpar</button><button disabled={saving} className="rounded-xl bg-teal-700 px-4 py-3 text-sm font-bold text-white shadow-sm hover:bg-teal-800 disabled:opacity-50">{saving?'Salvando...':'Salvar atendimento'}</button></div>:<div className="rounded-xl bg-slate-50 p-3 text-sm text-slate-500">Acesso somente leitura.</div>}</div></form>
   <div ref={panelRef} className="scroll-mt-24 space-y-5"><section className="flex min-h-[530px] flex-col rounded-3xl border border-slate-200 bg-white p-6 shadow-sm"><div className="flex flex-col gap-3 border-b border-slate-100 pb-4 sm:flex-row sm:items-center sm:justify-between"><h3 className="font-bold text-slate-900">Painel de triagem & Timeline</h3><select value={selected?.id??''} onChange={e=>setSelected(leads.find(item=>item.id===e.target.value)??null)} className="rounded-xl border border-slate-200 bg-white px-3 py-2 text-sm sm:min-w-56"><option value="">Todos os atendimentos</option>{leads.map(item=><option key={item.id} value={item.id}>{item.nome||'Atendimento'} · {item.status||'Sem status'}</option>)}</select></div>{selected?<div className="flex flex-1 flex-col"><div className="flex-1 py-2"><TimelinePanel compact leadId={selected.id} lead={selected}/></div><Link to={`/leads/${selected.id}`} className="mt-4 flex w-full items-center justify-center gap-2 rounded-xl border border-slate-200 px-4 py-3 text-sm font-bold text-teal-700 hover:border-teal-300 hover:bg-teal-50">Ver timeline completa <ArrowRight className="h-4 w-4"/></Link></div>:<div className="grid flex-1 place-items-center p-8 text-center"><div><Headphones className="mx-auto h-10 w-10 text-teal-200"/><p className="mt-3 max-w-md text-sm text-slate-500">Selecione um atendimento no histórico abaixo para carregar a Timeline e continuar o acompanhamento.</p></div></div>}</section><section className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm"><div className="text-sm font-bold">Pesquisar cliente já cadastrado</div><div className="relative mt-3"><Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-slate-400"/><input value={term} onChange={e=>setTerm(e.target.value)} placeholder="CPF/CNPJ, telefone, e-mail ou nome..." className="w-full rounded-xl border border-slate-200 bg-slate-50 py-2.5 pl-9 pr-3 text-sm outline-none focus:border-teal-500"/></div>{loading&&<div className="mt-3 text-sm text-slate-500">Buscando...</div>}{matches.length>0&&<div className="mt-3 space-y-2">{matches.map(c=><Link key={c.id} to={`/clientes/${c.id}`} className="flex items-center justify-between rounded-xl border p-3 text-sm hover:border-teal-200 hover:bg-teal-50/40"><span><strong>{c.nome_fantasia||c.razao_social||'Cliente'}</strong><span className="ml-2 text-slate-500">{c.cpf_cnpj_original||c.telefone_principal||''}</span></span><ArrowRight className="h-4 w-4 text-teal-700"/></Link>)}</div>}</section></div>
  </section>
  <section className="rounded-3xl border border-slate-200 bg-white shadow-sm"><div className="border-b p-5"><div className="flex items-center justify-between gap-3"><div><h3 className="font-bold">Pesquisar atendimentos</h3><p className="mt-1 text-xs text-slate-500">Filtros operacionais para localizar e continuar qualquer atendimento.</p></div><button onClick={()=>void loadBase()} className="inline-flex items-center gap-2 rounded-xl bg-teal-700 px-4 py-2.5 text-sm font-bold text-white"><RefreshCw className="h-4 w-4"/>Atualizar</button></div><div className="mt-4 grid gap-3 lg:grid-cols-6"><div className="relative lg:col-span-2"><Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-slate-400"/><input value={listTerm} onChange={e=>setListTerm(e.target.value)} placeholder="Nome, telefone, origem, assunto..." className="w-full rounded-xl border border-slate-200 py-2.5 pl-9 pr-3 text-sm"/></div><select value={statusFilter} onChange={e=>setStatusFilter(e.target.value)} className="rounded-xl border bg-white px-3 py-2.5 text-sm"><option value="TODOS">Todos os status</option>{statuses.map(s=><option key={s}>{s}</option>)}</select><select value={originFilter} onChange={e=>setOriginFilter(e.target.value)} className="rounded-xl border bg-white px-3 py-2.5 text-sm"><option value="TODAS">Todas as origens</option>{origins.map(o=><option key={o.value} value={o.value}>{o.label}</option>)}</select><select value={userFilter} onChange={e=>setUserFilter(e.target.value)} className="rounded-xl border bg-white px-3 py-2.5 text-sm"><option value="TODOS">Todos responsáveis</option>{filterUsers.map(u=><option key={u.id} value={u.id}>{u.nome||'Usuário'}{!u.ativo?' (inativo)':''}</option>)}</select><button onClick={()=>{setListTerm('');setStatusFilter('TODOS');setOriginFilter('TODAS');setUserFilter('TODOS');setFrom('');setTo('')}} className="rounded-xl border px-3 py-2.5 text-sm font-semibold text-slate-600">Limpar filtros</button></div><div className="mt-3 flex flex-wrap items-center gap-3 text-sm"><span className="font-semibold text-slate-600">Período:</span><input type="date" value={from} onChange={e=>setFrom(e.target.value)} className="rounded-xl border px-3 py-2"/><span className="text-slate-400">até</span><input type="date" value={to} onChange={e=>setTo(e.target.value)} className="rounded-xl border px-3 py-2"/><span className="ml-auto text-xs text-slate-500">{filtered.length} atendimento(s)</span></div></div>
   <div className="overflow-x-auto"><table className="min-w-full text-sm"><thead className="bg-slate-50 text-left text-xs uppercase text-slate-500"><tr><th className="px-5 py-3">Data</th><th className="px-5 py-3">Interessado</th><th className="px-5 py-3">Telefone</th><th className="px-5 py-3">Origem</th><th className="px-5 py-3">Assunto</th><th className="px-5 py-3">Responsável</th><th className="px-5 py-3">Última interação</th><th className="px-5 py-3">Status</th><th className="px-5 py-3">Ações</th></tr></thead><tbody className="divide-y">{filtered.length===0?<tr><td colSpan={9} className="p-10 text-center text-slate-500">Sem atendimentos neste filtro.</td></tr>:filtered.map(l=>{const last=lastInteraction(l.id);const u=userInfo(l.responsavel_id);const name=u.nome||'Sem responsável';return <tr key={l.id} className={selected?.id===l.id?'bg-teal-50/50':'hover:bg-slate-50'}><td className="px-5 py-4">{l.data_primeiro_atendimento?new Date(l.data_primeiro_atendimento).toLocaleDateString('pt-BR'):'—'}</td><td className="px-5 py-4 font-semibold">{l.nome||'—'}</td><td className="px-5 py-4">{l.telefone_whatsapp||'—'}</td><td className="px-5 py-4">{l.origem||'—'}</td><td className="px-5 py-4">{l.assunto||'—'}</td><td className="px-5 py-4"><div className="flex items-center gap-2"><UserAvatar name={name} avatarUrl={u.avatar_url} size="sm"/><span>{name}{u.id&&!u.ativo?' (inativo)':''}</span></div></td><td className="max-w-[220px] px-5 py-4"><div className="truncate">{last?.descricao||'Sem interação'}</div>{last&&<div className="mt-1 text-xs text-slate-400">{new Date(last.ocorrido_em).toLocaleString('pt-BR')}</div>}</td><td className="px-5 py-4"><span className="rounded-full bg-teal-50 px-2.5 py-1 text-xs font-bold text-teal-700">{l.status||'—'}</span></td><td className="px-5 py-4"><div className="flex items-center gap-2"><button onClick={()=>viewLead(l)} className="inline-flex items-center gap-1 rounded-lg border border-teal-200 px-3 py-1.5 text-xs font-bold text-teal-700 hover:bg-teal-50"><Eye className="h-3.5 w-3.5"/>Visualizar</button><Link to={`/leads/${l.id}`} className="rounded-lg border px-3 py-1.5 text-xs font-bold text-slate-600 hover:bg-slate-50">Acompanhar</Link></div></td></tr>})}</tbody></table></div>
  </section>
 </PageShell>
}
function Kpi({icon:Icon,label,value}:{icon:typeof PhoneCall;label:string;value:number}){return <article className="flex h-20 items-center gap-3 rounded-3xl border border-slate-200 bg-white p-4 shadow-sm"><span className="grid h-11 w-11 shrink-0 place-items-center rounded-full bg-teal-50 text-teal-700"><Icon className="h-5 w-5"/></span><div className="min-w-0"><span className="text-xs text-slate-500">{label}</span><strong className="mt-1 block truncate text-xl text-slate-900">{value}</strong></div></article>}
function F({label,value,set,placeholder,required=false}:{label:string;value:string;set:(v:string)=>void;placeholder?:string;required?:boolean}){return <label><span className="mb-1 block text-xs font-semibold uppercase text-slate-600">{label}{required?' *':''}</span><input required={required} value={value} onChange={e=>set(e.target.value)} placeholder={placeholder} className="w-full rounded-xl border border-slate-200 px-3 py-2.5 text-sm outline-none focus:border-teal-500 focus:ring-2 focus:ring-teal-100"/></label>}
function S({label,value,set,options}:{label:string;value:string;set:(v:string)=>void;options:Option[]}){return <label><span className="mb-1 block text-xs font-semibold uppercase text-slate-600">{label}</span><select required value={value} onChange={e=>set(e.target.value)} className="w-full rounded-xl border border-slate-200 bg-white px-3 py-2.5 text-sm"><option value="">Selecione</option>{options.map(o=><option key={o.value} value={o.value}>{o.label}</option>)}</select></label>}
