import { createClient } from "https://esm.sh/@supabase/supabase-js@2.45.0";
const U=Deno.env.get("SUPABASE_URL")!,K=Deno.env.get("SB_SECRET_KEY")??Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!,J=Deno.env.get("ML_JWT_SECRET")??"";
const sb=createClient(U,K,{auth:{persistSession:false,autoRefreshToken:false}}),enc=new TextEncoder(),dec=new TextDecoder();
const C={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type","Access-Control-Allow-Methods":"POST, OPTIONS"};
const out=(d:any,s=200)=>new Response(JSON.stringify(d),{status:s,headers:{...C,"Content-Type":"application/json; charset=utf-8","Cache-Control":"no-store"}}),txt=(v:any)=>String(v??"").trim(),now=()=>new Date().toISOString();
function b64u(s:string){s=s.replace(/-/g,"+").replace(/_/g,"/");while(s.length%4)s+="=";const b=atob(s),o=new Uint8Array(b.length);for(let i=0;i<b.length;i++)o[i]=b.charCodeAt(i);return o}
async function jwt(t:string){if(!J||!t)return null;const p=t.split(".");if(p.length!==3)return null;try{const k=await crypto.subtle.importKey("raw",enc.encode(J),{name:"HMAC",hash:"SHA-256"},false,["verify"]);if(!await crypto.subtle.verify("HMAC",k,b64u(p[2]),enc.encode(`${p[0]}.${p[1]}`)))return null;const x=JSON.parse(dec.decode(b64u(p[1])));if(x.sis!=="minaslab"||(typeof x.exp==="number"&&x.exp<Math.floor(Date.now()/1000)))return null;return x}catch{return null}}
async function audit(id:string,campo:string,a:any,n:any,u:string){if(String(a??"")===String(n??""))return;await sb.from("servicos_gerados_historico").insert({servico_id:id,campo,valor_anterior:a==null?null:String(a),valor_novo:n==null?null:String(n),origem:"NFSE_MLAB",usuario:u})}
Deno.serve(async req=>{if(req.method==="OPTIONS")return new Response("ok",{headers:C});if(req.method!=="POST")return out({erro:"Use POST."},405);const m=txt(req.headers.get("authorization")).match(/^Bearer\s+(.+)$/i),cr=m?await jwt(m[1]):null;if(!cr)return out({erro:"Entre no sistema.",semSessao:true},401);if(txt(cr?.papel)!=="direcao")return out({erro:"O financeiro é somente da direção.",semPermissao:true},403);let b:any={};try{b=await req.json()}catch{return out({erro:"JSON inválido."},400)}const origemId=txt(b.servicoId),notaId=txt(b.notaFiscalId);if(!origemId||!notaId)return out({erro:"Serviço/grupo e nota fiscal são obrigatórios."},400);const usuario=txt(cr?.sub)||"direcao";
try{const gn=await sb.from("servicos_gerados_grupos_faturamento").select("id,empresa_id,status").eq("id",origemId).maybeSingle();if(gn.error)throw gn.error;let ids:string[]=[];let grupo:any=gn.data;if(grupo){const qi=await sb.from("servicos_gerados_grupos_itens").select("servico_id").eq("grupo_id",grupo.id);if(qi.error)throw qi.error;ids=(qi.data||[]).map((x:any)=>x.servico_id)}else ids=[origemId];if(!ids.length)throw new Error("O grupo não possui OS.");const [{data:ss,error:es},{data:n,error:en}]=await Promise.all([sb.from("servicos_gerados").select("*,empresa:empresas(id,nome,usa_omie)").in("id",ids).eq("apagado",false),sb.from("notas_fiscais").select("id,empresa_id,numero_nf,data_emissao,data_vencimento,valor_total,recebimento_id,status_fiscal,origem").eq("id",notaId).eq("apagado",false).maybeSingle()]);if(es)throw es;if(en)throw en;if(!ss?.length||ss.length!==ids.length)throw new Error("Uma ou mais OS não foram encontradas.");if(!n)throw new Error("NFS-e não encontrada.");if(ss.some((s:any)=>{const e=Array.isArray(s.empresa)?s.empresa[0]:s.empresa;return e?.usa_omie!==false}))throw new Error("Esta vinculação é exclusiva da M Lab.");if(ss.some((s:any)=>n.empresa_id!==s.empresa_id))throw new Error("A NFS-e pertence a outra empresa.");if(n.origem!=="NFSE_NACIONAL"||n.status_fiscal!=="AUTORIZADA"||!txt(n.numero_nf))throw new Error("A NFS-e ainda não está autorizada em produção.");let status="A RECEBER",rec:any=null;if(n.recebimento_id){const q=await sb.from("recebimentos").select("id,status,data_vencimento,numero_nf").eq("id",n.recebimento_id).maybeSingle();if(q.error)throw q.error;rec=q.data;if(rec?.status==="PAGO")status="PAGO";else if(rec?.status==="PARCIAL")status="PARCIAL";else if(rec?.status==="VENCIDO")status="VENCIDO";else if(rec?.status==="CANCELADO")status="CANCELADO"}
const atualizados:any[]=[];for(const s of ss){const p:any={numero_nf:n.numero_nf,data_emissao:n.data_emissao,status_faturamento:"FATURADO",status_pagamento:status,referencia_pagamento:n.numero_nf,pagamento_referencia:n.numero_nf,pagamento_origem:"NFSE M LAB",nota_fiscal_id:n.id,recebimento_id:n.recebimento_id||null,tipo_emissao:"NFSE_NACIONAL",faturamento_manual:false,pagamento_manual:false,updated_at:now(),updated_by:usuario};if(!s.data_vencimento&&(n.data_vencimento||rec?.data_vencimento))p.data_vencimento=n.data_vencimento||rec.data_vencimento;const u=await sb.from("servicos_gerados").update(p).eq("id",s.id).select("*").single();if(u.error)throw u.error;for(const c of ["numero_nf","data_emissao","status_faturamento","status_pagamento","referencia_pagamento","nota_fiscal_id","recebimento_id","tipo_emissao"])await audit(s.id,c,s[c],p[c],usuario);atualizados.push(u.data)}if(grupo){const ug=await sb.from("servicos_gerados_grupos_faturamento").update({status:"FATURADO",nota_fiscal_id:n.id,recebimento_id:n.recebimento_id||null,referencia_pagamento:n.numero_nf,updated_at:now()}).eq("id",grupo.id);if(ug.error)throw ug.error}return out({ok:true,item:atualizados[0],itens:atualizados,quantidade:atualizados.length,numeroNf:n.numero_nf,recebimentoId:n.recebimento_id||null,statusPagamento:status});}catch(e:any){console.error(e);return out({erro:e?.message||"Falha interna."},409)}});
