import { useEffect, useMemo, useState } from 'react'
import { CalendarDays, CheckCircle2, CircleDollarSign, Clock3, Columns3, List, Plus, RefreshCw, Search, TrendingUp, UserRound } from 'lucide-react'
import { Link } from 'react-router-dom'
import { PageShell } from '../../components/ui/PageShell'
import { Modal } from '../../components/ui/Modal'
import { Badge, Button, Card, FieldLabel, Input, Select } from '../../components/ui/DesignSystem'
import { InlineAlert, TableEmpty, TableShell, Toolbar } from '../../components/ui/DataDisplay'
import { UserAvatar } from '../../components/users/UserAvatar'
import { supabase } from '../../services/supabase'
import { formatValue } from '../../lib/format'
import { useAuth } from '../../hooks/useAuth'

type Opp={id:string;titulo:string;estagio:string|null;status:string|null;valor_estimado:number|null;previsao_fechamento:string|null;cliente_id:string;responsavel_id:string|null;created_at:string;updated_at:string|null;clientes?:{razao_social:string|null;nome_fantasia:string|null}|null}
type Profile={id:string;nome:string|null;avatar_url:string|null;ativo:boolean}
type Task={id:string;oportunidade_id:string|null;titulo:string;prazo:string|null;status:string|null}
type ViewMode='kanban'|'table'
type PendingMove={id:string;stage:string}|null

const stages=['NOVO CONTATO','QUALIFICAÇÃO','PROPOSTA','NEGOCIAÇÃO','GANHO','PERDIDO']
const terminalStages=['GANHO','PERDIDO']
const stageTone:Record<string,string>={
  'NOVO CONTATO':'border-slate-200 bg-blue-50/55 text-blue-700','QUALIFICAÇÃO':'border-cyan-200 bg-cyan-50/55 text-cyan-700','PROPOSTA':'border-amber-200 bg-amber-50/55 text-amber-700','NEGOCIAÇÃO':'border-violet-200 bg-violet-50/55 text-violet-700','GANHO':'border-emerald-200 bg-emerald-50/55 text-emerald-700','PERDIDO':'border-red-200 bg-red-50/55 text-red-700',
}
function money(value:number){return formatValue(value,'currency')}
function dateLabel(value:string|null){if(!value)return'Sem previsão';const date=new Date(`${value}T12:00:00`);return Number.isNaN(date.getTime())?'Sem previsão':date.toLocaleDateString('pt-BR')}
function daysSince(value:string|null|undefined){if(!value)return 0;const date=new Date(value);if(Number.isNaN(date.getTime()))return 0;return Math.max(0,Math.floor((Date.now()-date.getTime())/86400000))}

export function Pipeline(){
  const {profile,hasPermission}=useAuth();const canWrite=hasPermission('crm.write')
  const[items,setItems]=useState<Opp[]>([]);const[profiles,setProfiles]=useState<Profile[]>([]);const[tasks,setTasks]=useState<Task[]>([]);const[loading,setLoading]=useState(true);const[error,setError]=useState('');const[moving,setMoving]=useState('')
  const[query,setQuery]=useState('');const[responsibleFilter,setResponsibleFilter]=useState('TODOS');const[stageFilter,setStageFilter]=useState('TODAS');const[periodFilter,setPeriodFilter]=useState('TODOS');const[view,setView]=useState<ViewMode>('kanban')
  const[pendingMove,setPendingMove]=useState<PendingMove>(null);const[reason,setReason]=useState('');const[confirming,setConfirming]=useState(false)
  async function load(){setLoading(true);setError('');const[oppRes,profileRes,taskRes]=await Promise.all([
    supabase.from('oportunidades').select('id,titulo,estagio,status,valor_estimado,previsao_fechamento,cliente_id,responsavel_id,created_at,updated_at,clientes(razao_social,nome_fantasia)').is('deleted_at',null).order('created_at',{ascending:false}),
    supabase.from('profiles').select('id,nome,avatar_url,ativo').order('nome'),
    supabase.from('tarefas').select('id,oportunidade_id,titulo,prazo,status').is('deleted_at',null).in('status',['PENDENTE','EM ANDAMENTO']).order('prazo',{ascending:true}),
  ]);const loadError=oppRes.error||profileRes.error||taskRes.error;if(loadError)setError(loadError.message);setItems((oppRes.data??[]) as unknown as Opp[]);setProfiles((profileRes.data??[]) as Profile[]);setTasks((taskRes.data??[]) as Task[]);setLoading(false)}
  useEffect(()=>{void load()},[])
  function currentStage(item:Opp){const stage=String(item.estagio||'').toUpperCase();const status=String(item.status||'').toUpperCase();if(stages.includes(stage))return stage;if(status==='GANHA')return'GANHO';if(status==='PERDIDA'||status==='CANCELADA')return'PERDIDO';return'NOVO CONTATO'}
  const profileInfo=(id:string|null)=>profiles.find(item=>item.id===id)||{id:'',nome:'Sem responsável',avatar_url:null,ativo:false}
  const profileName=(id:string|null)=>profileInfo(id).nome||'Sem responsável';const nextTask=(id:string)=>tasks.find(task=>task.oportunidade_id===id)
  const filtered=useMemo(()=>items.filter(item=>{const text=`${item.titulo} ${item.clientes?.nome_fantasia||''} ${item.clientes?.razao_social||''} ${profileName(item.responsavel_id)}`.toLocaleLowerCase('pt-BR');const matchesQuery=!query.trim()||text.includes(query.trim().toLocaleLowerCase('pt-BR'));const matchesResponsible=responsibleFilter==='TODOS'||item.responsavel_id===responsibleFilter;const matchesStage=stageFilter==='TODAS'||currentStage(item)===stageFilter;const date=item.previsao_fechamento?new Date(`${item.previsao_fechamento}T12:00:00`):null;const now=new Date();const matchesPeriod=periodFilter==='TODOS'||(periodFilter==='MES'&&!!date&&date.getMonth()===now.getMonth()&&date.getFullYear()===now.getFullYear())||(periodFilter==='ATRASADAS'&&!!date&&date<new Date(now.getFullYear(),now.getMonth(),now.getDate())&&!terminalStages.includes(currentStage(item)));return matchesQuery&&matchesResponsible&&matchesStage&&matchesPeriod}),[items,profiles,query,responsibleFilter,stageFilter,periodFilter])
  const openItems=items.filter(item=>!terminalStages.includes(currentStage(item)));const won=items.filter(item=>currentStage(item)==='GANHO').length;const lost=items.filter(item=>currentStage(item)==='PERDIDO').length;const openValue=openItems.reduce((sum,item)=>sum+Number(item.valor_estimado??0),0);const now=new Date();const monthForecast=openItems.filter(item=>{if(!item.previsao_fechamento)return false;const date=new Date(`${item.previsao_fechamento}T12:00:00`);return date.getMonth()===now.getMonth()&&date.getFullYear()===now.getFullYear()}).reduce((sum,item)=>sum+Number(item.valor_estimado??0),0);const conversion=won+lost?Math.round(won/(won+lost)*100):0
  async function persistMove(id:string,stage:string,moveReason=''){if(!canWrite)return;const item=items.find(value=>value.id===id);if(!item)return;const previousStage=currentStage(item);if(previousStage===stage)return;const previousItems=items;const status=stage==='GANHO'?'GANHA':stage==='PERDIDO'?'PERDIDA':'ABERTA';setMoving(id);setItems(list=>list.map(value=>value.id===id?{...value,estagio:stage,status,updated_at:new Date().toISOString()}:value));const{error:updateError}=await supabase.from('oportunidades').update({estagio:stage,status,updated_by:profile?.id??null}).eq('id',id);if(updateError){setItems(previousItems);setError(updateError.message);setMoving('');return}const description=[`Oportunidade movida de ${previousStage} para ${stage}`,moveReason?`Motivo: ${moveReason}`:''].filter(Boolean).join(' · ');const{error:timelineError}=await supabase.from('interacoes').insert({oportunidade_id:id,cliente_id:item.cliente_id,usuario_id:profile?.id??null,tipo:'STATUS',descricao:description});if(timelineError)setError(`Etapa atualizada, mas o histórico não pôde ser registrado: ${timelineError.message}`);else setError('');await load();setMoving('')}
  function requestMove(id:string,stage:string){if(terminalStages.includes(stage)){setReason('');setPendingMove({id,stage});return}void persistMove(id,stage)}
  function onDrop(e:React.DragEvent,stage:string){e.preventDefault();const id=e.dataTransfer.getData('text/plain');if(id.startsWith('opp:'))requestMove(id.slice(4),stage)}
  async function confirmTerminalMove(e:React.FormEvent){e.preventDefault();if(!pendingMove||!reason.trim())return;setConfirming(true);await persistMove(pendingMove.id,pendingMove.stage,reason.trim());setConfirming(false);setPendingMove(null);setReason('')}
  const filterProfiles=profiles.filter(p=>p.ativo||items.some(i=>i.responsavel_id===p.id))
  return <PageShell title="Pipeline Comercial" description="Acompanhe oportunidades, valores e próximas ações em cada etapa." action={<Link to="/oportunidades" className="ds-button ds-button-primary"><Plus className="h-4 w-4"/>Nova oportunidade</Link>}>
    <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Kpi icon={UserRound} label="Oportunidades abertas" value={String(openItems.length)} hint={`${filtered.length} no filtro atual`}/><Kpi icon={CircleDollarSign} label="Valor em negociação" value={money(openValue)} hint="Soma das oportunidades abertas"/><Kpi icon={TrendingUp} label="Previsão do mês" value={money(monthForecast)} hint="Fechamentos previstos no mês"/><Kpi icon={CheckCircle2} label="Taxa de conversão" value={`${conversion}%`} hint={`${won} ganhas de ${won+lost} encerradas`}/></section>
    <Card className="overflow-hidden p-0"><Toolbar><div className="grid w-full gap-3 xl:grid-cols-[minmax(260px,1fr)_180px_170px_170px_auto]"><div className="relative"><Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-[var(--text-muted)]"/><Input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar oportunidades, clientes ou serviços..." className="pl-9"/></div><Select value={responsibleFilter} onChange={e=>setResponsibleFilter(e.target.value)}><option value="TODOS">Todos responsáveis</option>{filterProfiles.map(item=><option key={item.id} value={item.id}>{item.nome||'Usuário'}{!item.ativo?' (inativo)':''}</option>)}</Select><Select value={periodFilter} onChange={e=>setPeriodFilter(e.target.value)}><option value="TODOS">Todo período</option><option value="MES">Este mês</option><option value="ATRASADAS">Previsões atrasadas</option></Select><Select value={stageFilter} onChange={e=>setStageFilter(e.target.value)}><option value="TODAS">Todas as etapas</option>{stages.map(stage=><option key={stage}>{stage}</option>)}</Select><div className="flex gap-2"><Button variant="secondary" onClick={()=>setView('kanban')} className={view==='kanban'?'border-[var(--brand-300)] bg-[var(--brand-50)] text-[var(--brand-700)]':''}><Columns3 className="h-4 w-4"/>Kanban</Button><Button variant="secondary" onClick={()=>setView('table')} className={view==='table'?'border-[var(--brand-300)] bg-[var(--brand-50)] text-[var(--brand-700)]':''}><List className="h-4 w-4"/>Tabela</Button><Button variant="secondary" onClick={()=>void load()} title="Atualizar"><RefreshCw className="h-4 w-4"/></Button></div></div></Toolbar></Card>
    {error&&<InlineAlert>{error}</InlineAlert>}
    {loading?<Card className="p-12 text-center text-[var(--text-secondary)]">Carregando pipeline...</Card>:view==='kanban'?<div className="overflow-x-auto pb-3"><div className="flex min-w-max gap-3">{stages.map(stage=>{const col=filtered.filter(item=>currentStage(item)===stage);const total=col.reduce((sum,item)=>sum+Number(item.valor_estimado??0),0);return <section key={stage} onDragOver={e=>canWrite&&e.preventDefault()} onDrop={e=>onDrop(e,stage)} className={`w-[292px] shrink-0 rounded-[var(--radius-card)] border ${stageTone[stage]}`}><header className="border-b border-current/10 p-3.5"><div className="flex items-center justify-between gap-2"><h3 className="text-xs font-bold tracking-wide">{stage}</h3><span className="rounded-full bg-white/80 px-2 py-0.5 text-[11px] font-bold">{col.length}</span></div><div className="mt-1.5 flex items-center justify-between text-xs"><span>{col.length} oportunidade(s)</span><strong>{money(total)}</strong></div></header><div className="min-h-48 space-y-3 p-2.5">{col.length===0?<div className="rounded-[var(--radius-button)] border border-dashed border-current/20 bg-white/55 p-5 text-center text-xs opacity-70">Arraste uma oportunidade para cá</div>:col.map(item=><OpportunityCard key={item.id} item={item} responsible={profileInfo(item.responsavel_id)} task={nextTask(item.id)} canWrite={canWrite} moving={moving===item.id}/>)}</div></section>})}</div></div>:<PipelineTable items={filtered} profileInfo={profileInfo} nextTask={nextTask}/>} 
    <Card className="grid gap-4 px-5 py-4 sm:grid-cols-2 xl:grid-cols-5"><Summary label="Oportunidades" value={String(filtered.length)}/><Summary label="Valor total filtrado" value={money(filtered.reduce((sum,item)=>sum+Number(item.valor_estimado??0),0))}/><Summary label="Previsão do mês" value={money(monthForecast)}/><Summary label="Ticket médio" value={money(items.length?items.reduce((sum,item)=>sum+Number(item.valor_estimado??0),0)/items.length:0)}/><Summary label="Taxa de conversão" value={`${conversion}%`}/></Card>
    {!canWrite&&<div className="text-xs text-[var(--text-secondary)]"><Columns3 className="mr-1 inline h-4 w-4"/>Seu perfil pode visualizar o Pipeline, mas não mover oportunidades.</div>}
    <Modal open={Boolean(pendingMove)} onClose={()=>setPendingMove(null)} title={pendingMove?.stage==='GANHO'?'Confirmar oportunidade ganha':'Confirmar oportunidade perdida'}><form onSubmit={confirmTerminalMove} className="space-y-4"><div className={`rounded-[var(--radius-card)] p-4 text-sm ${pendingMove?.stage==='GANHO'?'bg-emerald-50 text-emerald-800':'bg-red-50 text-red-800'}`}>{pendingMove?.stage==='GANHO'?'Confirme o fechamento e informe o resultado comercial. Nenhum contrato ou OS será criado automaticamente.':'Informe o motivo da perda para preservar o histórico comercial.'}</div><label><FieldLabel className="mb-1.5 block">{pendingMove?.stage==='GANHO'?'Observação do fechamento':'Motivo da perda'} *</FieldLabel><textarea required value={reason} onChange={e=>setReason(e.target.value)} rows={4} className="ds-field" placeholder={pendingMove?.stage==='GANHO'?'Ex.: proposta aprovada pelo cliente':'Ex.: preço, prazo, concorrente ou desistência'}/></label><div className="flex justify-end gap-2"><Button type="button" variant="secondary" onClick={()=>setPendingMove(null)}>Cancelar</Button><Button disabled={confirming} variant={pendingMove?.stage==='GANHO'?'primary':'danger'}>{confirming?'Confirmando...':'Confirmar movimentação'}</Button></div></form></Modal>
  </PageShell>
}
function OpportunityCard({item,responsible,task,canWrite,moving}:{item:Opp;responsible:Profile;task:Task|undefined;canWrite:boolean;moving:boolean}){const name=responsible.nome||'Sem responsável';return <Card draggable={canWrite} onDragStart={e=>{e.dataTransfer.setData('text/plain',`opp:${item.id}`);e.dataTransfer.effectAllowed='move'}} className={`p-3.5 transition hover:-translate-y-0.5 hover:shadow-md ${canWrite?'cursor-grab active:cursor-grabbing':''} ${moving?'opacity-50':''}`}><Link to={`/oportunidades/${item.id}`} className="block"><div className="font-bold text-[var(--text-primary)]">{item.clientes?.nome_fantasia||item.clientes?.razao_social||'Cliente não identificado'}</div><div className="mt-1 line-clamp-2 text-xs text-[var(--text-secondary)]">{item.titulo}</div><div className="mt-3 text-base font-bold text-[var(--text-primary)]">{money(Number(item.valor_estimado??0))}</div><div className="mt-3 flex items-center gap-2 text-xs"><UserAvatar name={name} avatarUrl={responsible.avatar_url} size="sm"/><span className="truncate">{name}{responsible.id&&!responsible.ativo?' · inativo':''}</span></div><div className="mt-3 space-y-1.5 border-t border-[var(--border)] pt-3 text-[11px] text-[var(--text-secondary)]"><div className="flex items-center gap-2"><CalendarDays className="h-3.5 w-3.5"/>Previsão: {dateLabel(item.previsao_fechamento)}</div><div className="flex items-start gap-2"><Clock3 className="mt-0.5 h-3.5 w-3.5 shrink-0"/><span className="line-clamp-2">Próxima ação: {task?.titulo||'Não definida'}</span></div></div><div className="mt-3"><Badge>{daysSince(item.updated_at||item.created_at)} dias nesta etapa</Badge></div></Link></Card>}
function Kpi({icon:Icon,label,value,hint}:{icon:typeof UserRound;label:string;value:string;hint:string}){return <Card className="flex h-20 items-center gap-3 p-4"><span className="grid h-11 w-11 shrink-0 place-items-center rounded-full bg-[var(--brand-50)] text-[var(--brand-700)]"><Icon className="h-5 w-5"/></span><div className="min-w-0"><div className="text-xs text-[var(--text-secondary)]">{label}</div><strong className="mt-1 block truncate text-xl text-[var(--text-primary)]">{value}</strong><div className="truncate text-[10px] text-[var(--success)]">{hint}</div></div></Card>}
function Summary({label,value}:{label:string;value:string}){return <div><div className="text-xs text-[var(--text-muted)]">{label}</div><div className="mt-1 font-bold text-[var(--text-primary)]">{value}</div></div>}
function PipelineTable({items,profileInfo,nextTask}:{items:Opp[];profileInfo:(id:string|null)=>Profile;nextTask:(id:string)=>Task|undefined}){return <TableShell><div className="overflow-x-auto"><table className="min-w-full text-sm"><thead className="text-left"><tr><th className="px-5 py-3">Cliente / oportunidade</th><th className="px-5 py-3">Etapa</th><th className="px-5 py-3">Valor</th><th className="px-5 py-3">Responsável</th><th className="px-5 py-3">Previsão</th><th className="px-5 py-3">Próxima ação</th><th className="px-5 py-3">Ação</th></tr></thead><tbody>{items.length===0?<tr><td colSpan={7}><TableEmpty label="Nenhuma oportunidade encontrada."/></td></tr>:items.map(item=>{const p=profileInfo(item.responsavel_id);const name=p.nome||'Sem responsável';return <tr key={item.id}><td className="px-5 py-4"><div className="font-semibold text-[var(--text-primary)]">{item.clientes?.nome_fantasia||item.clientes?.razao_social||'Cliente não identificado'}</div><div className="mt-1 text-xs text-[var(--text-secondary)]">{item.titulo}</div></td><td className="px-5 py-4"><Badge>{item.estagio||'NOVO CONTATO'}</Badge></td><td className="px-5 py-4 font-semibold">{money(Number(item.valor_estimado??0))}</td><td className="px-5 py-4"><div className="flex items-center gap-2"><UserAvatar name={name} avatarUrl={p.avatar_url} size="sm"/><span>{name}{p.id&&!p.ativo?' (inativo)':''}</span></div></td><td className="px-5 py-4">{dateLabel(item.previsao_fechamento)}</td><td className="px-5 py-4">{nextTask(item.id)?.titulo||'Não definida'}</td><td className="px-5 py-4"><Link to={`/oportunidades/${item.id}`} className="font-semibold text-[var(--brand-700)]">Visualizar</Link></td></tr>})}</tbody></table></div></TableShell>}
