import { useMemo, useState } from 'react';
import { movimentosPorMes } from '../../lib/relatorioFinanceiro.js';
const moeda=v=>Number(v||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
export default function ComparativoMensal({movimentos=[]}){
 const [mes,setMes]=useState('');
 const meses=useMemo(()=>movimentosPorMes(movimentos),[movimentos]);
 const maximo=Math.max(1,...meses.flatMap(m=>[m.entradas,m.saidas]));
 const detalhe=meses.find(m=>m.mes===mes);
 return <section className="rounded-2xl border bg-white p-5"><h2 className="text-lg font-semibold text-blue-900">Comparação mensal do banco</h2><p className="mt-1 text-sm text-slate-600">Entradas e saídas do extrato no filtro selecionado, incluindo transferências. Movimento líquido não é lucro. Clique no mês para conferir os documentos.</p><p className="my-4 text-sm"><span className="text-emerald-700">■ Entradas</span> · <span className="text-rose-700">■ Saídas</span></p><div className="space-y-4">{!meses.length?<p>Sem movimentos no período.</p>:meses.map(m=><button key={m.mes} className="block w-full rounded-xl border p-3 text-left hover:bg-slate-50" onClick={()=>setMes(m.mes===mes?'':m.mes)} aria-expanded={mes===m.mes}><div className="mb-2 flex flex-wrap justify-between gap-2 text-sm"><b>{m.mes.split('-').reverse().join('/')}</b><span>Entradas {moeda(m.entradas)} · Saídas {moeda(m.saidas)} · Líquido {moeda(m.entradas-m.saidas)}</span></div><div className="h-2 rounded bg-emerald-600" style={{width:`${m.entradas/maximo*100}%`}}/><div className="mt-1 h-2 rounded bg-rose-500" style={{width:`${m.saidas/maximo*100}%`}}/></button>)}</div>{detalhe&&<div className="mt-5 max-h-96 overflow-auto"><table className="w-full text-left text-sm"><caption className="pb-3 font-semibold">Documentos de {detalhe.mes} · {detalhe.itens.length} movimentos</caption><thead><tr><th>Data</th><th>Descrição</th><th>Tipo</th><th>Valor</th></tr></thead><tbody>{detalhe.itens.map(m=><tr key={m.id} className="border-t"><td className="p-2 whitespace-nowrap">{m.data_movimento}</td><td className="p-2">{m.descricao}</td><td className="p-2">{m.tipo}</td><td className="p-2 whitespace-nowrap">{moeda(Math.abs(Number(m.valor||0)))}</td></tr>)}</tbody></table></div>}</section>
}
