import { useMemo } from 'react';
import { periodoAnual, resumoAnual } from '../../lib/financeiroAnual.js';
const nomes=['Jan','Fev','Mar','Abr','Mai','Jun','Jul','Ago','Set','Out','Nov','Dez'];
const moeda=v=>v.toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
export default function ReguaAnual({ano,setAno,movimentos,conta,de,ate,onPeriodo,loading}){
 const meses=useMemo(()=>resumoAnual(movimentos,ano,conta),[movimentos,ano,conta]);
 const totais=meses.reduce((s,m)=>({entradas:s.entradas+Math.round(m.entradas*100),saidas:s.saidas+Math.round(m.saidas*100)}),{entradas:0,saidas:0});
 function mudarAno(a){setAno(a);onPeriodo(periodoAnual(a))}
 const inteiro=periodoAnual(ano),anoSelecionado=de===inteiro.de&&ate===inteiro.ate;
 return <section className="rounded-2xl border bg-white p-5" aria-label="Régua anual"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-lg font-semibold text-blue-900">O ano em uma visão</h2><p className="text-sm text-slate-600">Selecione um mês para filtrar os relatórios abaixo.</p></div><div className="flex items-center gap-2"><button className="btn-outline" aria-label="Ano anterior" disabled={ano<=1900} onClick={()=>mudarAno(ano-1)}>‹</button><strong className="px-2 text-lg tabular-nums">{ano}</strong><button className="btn-outline" aria-label="Próximo ano" disabled={ano>=2200} onClick={()=>mudarAno(ano+1)}>›</button><button aria-pressed={anoSelecionado} className={anoSelecionado?'btn-primary':'btn-outline'} onClick={()=>onPeriodo(inteiro)}>Ano inteiro</button></div></div><p className="my-4 text-sm text-slate-600">{loading?'Carregando valores…':`Entradas ${moeda(totais.entradas/100)} · Saídas ${moeda(totais.saidas/100)} · Movimento líquido ${moeda((totais.entradas-totais.saidas)/100)}`}<span className="block mt-1 text-xs">Valores bancários da empresa e conta selecionadas. Incluem transferências; não representam lucro.</span></p><div className="grid grid-cols-2 gap-2 sm:grid-cols-3 xl:grid-cols-6">{meses.map(m=>{const p=periodoAnual(ano,m.mes),selecionado=de===p.de&&ate===p.ate;return <button key={m.mes} aria-pressed={selecionado} aria-label={`${nomes[m.mes-1]} de ${ano}`} onClick={()=>onPeriodo(p)} className={`rounded-xl border p-3 text-left transition ${selecionado?'border-blue-500 bg-blue-50 ring-1 ring-blue-500':'border-slate-200 hover:bg-slate-50'}`}><b className="text-blue-900">{nomes[m.mes-1]}</b>{loading?<span className="block text-xs text-slate-500">Carregando…</span>:!m.registros?<span className="mt-2 block text-xs text-slate-500">Sem movimentos</span>:<span className="mt-2 block space-y-1 text-xs tabular-nums"><span className="block text-emerald-700">Entrou {moeda(m.entradas)}</span><span className="block text-rose-700">Saiu {moeda(m.saidas)}</span><span className="block font-semibold text-slate-700">Líquido {moeda(m.liquido)}</span></span>}</button>})}</div></section>
}
