import {useEffect,useState} from "react";
import {Link2,SlidersHorizontal,RotateCcw,X} from "lucide-react";
import {finTituloCandidatos,finTituloConciliar,finOmieAjustar,finOmieRestaurar} from "../../services/financeiroAjustes.js";
const moeda=v=>Number(v||0).toLocaleString("pt-BR",{style:"currency",currency:"BRL"});
const dataBR=v=>{if(!v)return"—";const p=String(v).slice(0,10).split("-");return p.length===3?`${p[2]}/${p[1]}/${p[0]}`:String(v)};
const inputCls="w-full rounded-xl border border-slate-200 bg-white px-3 py-2 text-sm text-slate-800 outline-none transition focus:border-teal-500 focus:ring-2 focus:ring-teal-100";
const primaryCls="rounded-xl bg-teal-600 px-4 py-2 text-sm font-semibold text-white transition hover:bg-teal-700 disabled:cursor-not-allowed disabled:opacity-50";
const campos={RECEBIMENTO:[['cliente','Cliente','text'],['cnpj_cpf','CNPJ/CPF','text'],['descricao','Descrição','text'],['numero_nf','Nº NF','text'],['valor_previsto','Valor previsto','number'],['valor_recebido','Valor recebido','number'],['valor_pendente','Valor pendente','number'],['data_vencimento','Vencimento','date'],['data_pagamento','Pagamento','date'],['status','Status','text'],['observacao','Observação','text']],DESPESA:[['fornecedor','Fornecedor','text'],['cnpj_cpf','CNPJ/CPF','text'],['descricao','Descrição','text'],['valor_original','Valor original','number'],['valor_pago','Valor pago','number'],['valor_pendente','Valor pendente','number'],['data_lancamento','Lançamento','date'],['data_vencimento','Vencimento','date'],['data_pagamento','Pagamento','date'],['status','Status','text'],['observacao','Observação','text']]};
function Modal({titulo,onClose,children}){return <div className="fixed inset-0 z-[70] flex items-center justify-center bg-slate-950/45 p-4"><div className="max-h-[92vh] w-full max-w-3xl overflow-hidden rounded-2xl bg-white shadow-2xl"><div className="flex items-center justify-between border-b px-5 py-4"><b>{titulo}</b><button type="button" onClick={onClose} className="rounded-lg p-2 hover:bg-slate-100"><X size={18}/></button></div><div className="max-h-[calc(92vh-70px)] overflow-y-auto p-5">{children}</div></div></div>}
export default function TituloOmieAcoes({tipo,titulo,onAtualizado,onErro,onSucesso}){const ehOmie=String(titulo?.origem||'').toUpperCase()==='OMIE',nominal=Number(tipo==='RECEBIMENTO'?titulo?.valor_previsto:titulo?.valor_original)||0,conciliado=Number(titulo?.valor_conciliado||0),restante=Math.max(0,nominal-conciliado),cancelado=['CANCELADO','CANCELADA'].includes(String(titulo?.status||'').toUpperCase());const[modal,setModal]=useState(''),[lista,setLista]=useState([]),[carregando,setCarregando]=useState(false),[selecionado,setSelecionado]=useState(null),[valor,setValor]=useState(''),[form,setForm]=useState({}),[motivo,setMotivo]=useState('');
useEffect(()=>{if(modal==='ajuste'){const x={};for(const[c]of campos[tipo]||[])x[c]=titulo?.[c]??'';setForm(x);setMotivo('')}},[modal,tipo,titulo]);
async function abrirConciliar(){setSelecionado(null);setValor('');setModal('conciliar');setCarregando(true);try{setLista(await finTituloCandidatos(tipo,titulo.id))}catch(e){onErro?.(e.message);setModal('')}finally{setCarregando(false)}}
async function conciliar(){if(!selecionado)return;const max=Math.min(restante,Number(selecionado.disponivel||0)),v=Number(valor||max);if(!(v>0)||v>max+.004){onErro?.(`Informe um valor entre R$ 0,01 e ${moeda(max)}.`);return}setCarregando(true);try{await finTituloConciliar(tipo,titulo.id,selecionado.id,v);onSucesso?.('Conciliação registrada com sucesso.');setModal('');await onAtualizado?.()}catch(e){onErro?.(e.message)}finally{setCarregando(false)}}
async function ajustar(e){e.preventDefault();if(!motivo.trim()){onErro?.('Informe o motivo do ajuste manual Omie.');return}const dados={};for(const[c,,t]of campos[tipo]||[]){let v=form[c];if(t==='number')v=v===''?null:Number(v);dados[c]=v===''?null:v}setCarregando(true);try{await finOmieAjustar(tipo,titulo.id,dados,motivo.trim());onSucesso?.('Ajuste manual protegido salvo. A sincronização Omie não sobrescreverá estes campos.');setModal('');await onAtualizado?.()}catch(e2){onErro?.(e2.message)}finally{setCarregando(false)}}
async function restaurar(){if(!confirm('Restaurar os valores originais recebidos da Omie e remover o ajuste manual protegido?'))return;setCarregando(true);try{await finOmieRestaurar(tipo,titulo.id);onSucesso?.('Valores originais da Omie restaurados.');await onAtualizado?.()}catch(e){onErro?.(e.message)}finally{setCarregando(false)}}
return <><div className="flex items-center gap-1">{restante>.004&&!cancelado&&<button type="button" onClick={abrirConciliar} title="Conciliar com movimento bancário" className="rounded-lg p-2 text-sky-600 hover:bg-sky-50"><Link2 size={16}/></button>}{ehOmie&&<button type="button" onClick={()=>setModal('ajuste')} title="Ajuste manual protegido" className="rounded-lg p-2 text-violet-600 hover:bg-violet-50"><SlidersHorizontal size={16}/></button>}{ehOmie&&titulo?.omie_override_manual&&<button type="button" onClick={restaurar} disabled={carregando} title="Restaurar original Omie" className="rounded-lg p-2 text-amber-600 hover:bg-amber-50"><RotateCcw size={16}/></button>}</div>
{modal==='conciliar'&&<Modal titulo={`Conciliar ${tipo==='RECEBIMENTO'?'recebimento':'despesa'}`} onClose={()=>setModal('')}><div className="mb-4 rounded-xl bg-slate-50 p-3 text-sm">Valor ainda disponível no título: <b>{moeda(restante)}</b></div>{carregando?<p className="text-sm text-slate-500">Buscando movimentos...</p>:!lista.length?<p className="text-sm text-slate-500">Nenhum movimento bancário com saldo disponível foi encontrado para esta empresa.</p>:<div className="space-y-2">{lista.map(x=><button type="button" key={x.id} onClick={()=>{setSelecionado(x);setValor(String(Math.min(restante,Number(x.disponivel||0)).toFixed(2)))}} className={`w-full rounded-xl border p-3 text-left text-sm ${selecionado?.id===x.id?'border-teal-400 bg-teal-50':'border-slate-200 hover:bg-slate-50'}`}><div className="flex justify-between gap-3"><b>{dataBR(x.data)} · {x.favorecido||x.descricao||'Movimento bancário'}</b><b>{moeda(x.valor)}</b></div><div className="mt-1 text-xs text-slate-500">Documento: {x.documento||'—'} · Disponível: {moeda(x.disponivel)}</div></button>)}</div>}{selecionado&&<div className="mt-4 flex items-end gap-3"><label className="flex-1"><span className="mb-1 block text-xs font-semibold text-slate-500">VALOR A CONCILIAR</span><input className={inputCls} type="number" min="0.01" step="0.01" value={valor} onChange={e=>setValor(e.target.value)}/></label><button type="button" className={primaryCls} disabled={carregando} onClick={conciliar}>Confirmar conciliação</button></div>}</Modal>}
{modal==='ajuste'&&<Modal titulo="Ajuste manual protegido — Omie" onClose={()=>setModal('')}><div className="mb-4 rounded-xl border border-violet-200 bg-violet-50 p-3 text-sm text-violet-800">Use somente para uma exceção que precise aparecer diferente no Financeiro. O valor original da Omie será guardado e poderá ser restaurado.</div><form onSubmit={ajustar} className="space-y-4"><div className="grid gap-3 md:grid-cols-2">{(campos[tipo]||[]).map(([c,l,t])=><label key={c}><span className="mb-1 block text-xs font-semibold text-slate-500">{l.toUpperCase()}</span><input className={inputCls} type={t} step={t==='number'?'0.01':undefined} value={form[c]??''} onChange={e=>setForm(v=>({...v,[c]:e.target.value}))}/></label>)}</div><label className="block"><span className="mb-1 block text-xs font-semibold text-slate-500">MOTIVO DO AJUSTE *</span><textarea className={`${inputCls} min-h-20`} required value={motivo} onChange={e=>setMotivo(e.target.value)}/></label><div className="flex justify-end"><button type="submit" className={primaryCls} disabled={carregando}>{carregando?'Salvando...':'Salvar ajuste protegido'}</button></div></form></Modal>}</>}
