import { useEffect, useState } from 'react'
import { NavLink, useLocation } from 'react-router-dom'
import { BarChart3, BrainCircuit, CalendarDays, ChevronDown, ClipboardList, Columns3, FileText, FlaskConical, Gavel, Handshake, History, Import, LayoutDashboard, Layers3, LogOut, MapPinned, Menu, Repeat2, Settings, ShieldCheck, Smile, Users, X, ListTodo } from 'lucide-react'
import { useAuth } from '../hooks/useAuth'
import type { PermissionCode } from '../contexts/AuthContext'
import { UserAvatar } from '../components/users/UserAvatar'

type MenuItem = readonly [string, string, typeof LayoutDashboard, PermissionCode[]]
type MenuGroup = readonly [string, MenuItem[]]
const dashboard: MenuItem = ['Dashboard','/dashboard',LayoutDashboard,['crm.read','operational.read']]
const groups: MenuGroup[] = [
 ['Comercial',[[ 'Atendimentos','/atendimentos',ClipboardList,['crm.read']],[ 'Oportunidades','/oportunidades',Handshake,['crm.read']],[ 'Pipeline','/pipeline',Columns3,['crm.read']],[ 'Propostas','/propostas',FileText,['crm.read']],[ 'Clientes','/clientes',Users,['crm.read']]]],
 ['Operação',[[ 'Contratos','/contratos',FileText,['operational.read']],[ 'Ordens de Serviço','/ordens-servico',FlaskConical,['operational.read']],[ 'Coletas','/coletas',MapPinned,['crm.read']],[ 'Agenda','/agenda',CalendarDays,['crm.read']]]],
 ['Pós-venda',[[ 'Visão Geral','/pos-venda/visao-geral',BarChart3,['crm.read','operational.read']],[ 'Clientes Recorrentes','/pos-venda/clientes-recorrentes',Repeat2,['crm.read','operational.read']],[ 'Calendário','/pos-venda/calendario',CalendarDays,['crm.read']],[ 'Acompanhamentos','/pos-venda/acompanhamentos',ListTodo,['crm.read','operational.read']],[ 'Satisfação (NPS)','/pos-venda/nps',Smile,['crm.read']],[ 'Histórico','/pos-venda/historico',History,['crm.read','operational.read']]]],
 ['Gestão',[[ 'Licitações','/licitacoes',Gavel,['crm.read']],[ 'Tarefas','/tarefas',ListTodo,['crm.read']],[ 'Inteligência','/inteligencia',BrainCircuit,['crm.read']]]],
 ['Análises',[[ 'Amostras e Parâmetros','/amostras-parametros',FlaskConical,['operational.read']],[ 'Relatórios','/relatorios',BarChart3,['crm.read','operational.read']]]],
 ['Cadastros',[[ 'Catálogo','/catalogo',Layers3,['crm.read','operational.read']],[ 'Importações','/importacoes',Import,['imports.manage']]]],
 ['Administração',[[ 'Acessos e Configurações','/configuracoes',Settings,['admin.manage']],[ 'Auditoria','/auditoria',ShieldCheck,['audit.read']]]],
]

export function Sidebar({open,onClose}:{open:boolean;onClose:()=>void}){
 const {profile,hasPermission,signOut}=useAuth();const location=useLocation();const[signingOut,setSigningOut]=useState(false);const[openGroup,setOpenGroup]=useState<string|null>(null);const[profileOpen,setProfileOpen]=useState(false)
 const canSee=(item:MenuItem)=>item[3].some(code=>hasPermission(code));const visibleGroups=groups.map(([label,items])=>[label,items.filter(canSee)] as const).filter(([,items])=>items.length)
 useEffect(()=>{setOpenGroup(null);setProfileOpen(false)},[location.pathname])
 async function handleSignOut(){if(signingOut)return;setSigningOut(true);try{await signOut()}catch(error){console.error('Falha ao encerrar sessão:',error);setSigningOut(false)}}
 return <header className="sticky top-0 z-50 border-b border-slate-200 bg-white shadow-sm">
  <div className="flex h-16 items-center gap-4 px-4 lg:px-6">
   <NavLink to="/dashboard" className="shrink-0" onClick={()=>setOpenGroup(null)}><img src={`${import.meta.env.BASE_URL}minaslab-logo.svg`} alt="MinasLab - Laboratório de Controle de Qualidade" className="h-10 w-44 object-contain object-left"/></NavLink>
   <div className="hidden min-w-0 flex-1 lg:block"><p className="text-[11px] font-semibold uppercase tracking-[0.14em] text-[#078c86]">CRM MinasLab 2.0</p><p className="truncate text-xs text-slate-500">Gestão comercial e operacional</p></div>
   <div className="ml-auto flex items-center gap-2">
    <div className="relative hidden md:block"><button type="button" onClick={()=>setProfileOpen(v=>!v)} className="flex items-center gap-2 rounded-lg px-2 py-1 hover:bg-slate-50"><UserAvatar name={profile?.nome} avatarUrl={profile?.avatar_url}/><span className="max-w-44 truncate text-sm font-semibold text-slate-700">{profile?.nome||'Usuário'}</span><ChevronDown className={`h-4 w-4 text-slate-400 transition ${profileOpen?'rotate-180':''}`}/></button>{profileOpen&&<div className="absolute right-0 top-full mt-2 w-64 rounded-xl border border-slate-200 bg-white p-2 shadow-xl"><div className="flex items-center gap-3 border-b border-slate-200 p-3"><UserAvatar name={profile?.nome} avatarUrl={profile?.avatar_url} size="md"/><div className="min-w-0"><div className="truncate font-semibold text-slate-800">{profile?.nome||'Usuário'}</div><div className="text-xs text-slate-500">Perfil do CRM</div></div></div><NavLink to="/meu-perfil" onClick={()=>setProfileOpen(false)} className="mt-2 flex items-center gap-2 rounded-lg px-3 py-2 text-sm text-slate-700 hover:bg-slate-50"><Settings className="h-4 w-4"/>Meu perfil</NavLink>{hasPermission('admin.manage')&&<NavLink to="/configuracoes" onClick={()=>setProfileOpen(false)} className="flex items-center gap-2 rounded-lg px-3 py-2 text-sm text-slate-700 hover:bg-slate-50"><Users className="h-4 w-4"/>Acessos e usuários</NavLink>}<button type="button" onClick={()=>void handleSignOut()} disabled={signingOut} className="flex w-full items-center gap-2 rounded-lg px-3 py-2 text-sm text-red-600 hover:bg-red-50"><LogOut className="h-4 w-4"/>{signingOut?'Saindo...':'Sair'}</button></div>}</div>
    <button type="button" aria-label={open?'Fechar menu':'Abrir menu'} onClick={onClose} className="rounded-lg border border-slate-200 p-2 text-slate-700 lg:hidden">{open?<X className="h-5 w-5"/>:<Menu className="h-5 w-5"/>}</button></div>
  </div>
  <nav className="hidden h-11 items-stretch bg-[#2B444E] px-4 text-white lg:flex">{canSee(dashboard)&&<NavLink to={dashboard[1]} onClick={()=>setOpenGroup(null)} className={({isActive})=>`flex items-center gap-2 px-4 text-[13px] font-semibold transition hover:bg-white/10 ${isActive?'bg-white/10 text-[#30C8B3]':'text-white/90'}`}><LayoutDashboard className="h-4 w-4"/>Dashboard</NavLink>}{visibleGroups.map(([label,items])=>{const active=items.some(([,to])=>location.pathname===to||location.pathname.startsWith(to+'/'));const isOpen=openGroup===label;return <div key={label} className="relative"><button type="button" onClick={()=>setOpenGroup(current=>current===label?null:label)} className={`flex h-full items-center gap-1.5 px-4 text-[13px] font-semibold transition hover:bg-white/10 ${active?'bg-white/10 text-[#30C8B3]':'text-white/90'}`}>{label}<ChevronDown className={`h-3.5 w-3.5 transition ${isOpen?'rotate-180':''}`}/></button>{isOpen&&<div className="absolute left-0 top-full min-w-72 rounded-b-xl border border-slate-200 bg-white p-2 text-slate-800 shadow-xl">{items.map(([itemLabel,to,Icon])=><NavLink key={to} to={to} onClick={()=>setOpenGroup(null)} className={({isActive})=>`flex items-center gap-3 rounded-lg px-3 py-2.5 text-sm transition ${isActive?'bg-teal-50 font-semibold text-teal-800':'hover:bg-slate-50'}`}><span className="grid h-8 w-8 place-items-center rounded-lg bg-teal-50 text-teal-700"><Icon className="h-4 w-4"/></span>{itemLabel}</NavLink>)}</div>}</div>})}</nav>
  {open&&<div className="absolute inset-x-0 top-16 max-h-[calc(100vh-4rem)] overflow-y-auto border-t border-slate-200 bg-[#2B444E] p-4 text-white shadow-xl lg:hidden">{canSee(dashboard)&&<NavLink to={dashboard[1]} onClick={onClose} className="mb-2 flex items-center gap-3 rounded-lg bg-white/10 px-4 py-2.5 font-semibold"><LayoutDashboard className="h-5 w-5"/>Dashboard</NavLink>}{visibleGroups.map(([label,items])=><section key={label} className="border-t border-white/10 py-3"><h3 className="mb-2 px-2 text-xs font-bold uppercase tracking-wider text-teal-200">{label}</h3>{items.map(([itemLabel,to,Icon])=><NavLink key={to} to={to} onClick={onClose} className={({isActive})=>`flex items-center gap-3 rounded-lg px-4 py-2.5 text-sm ${isActive?'bg-[#00B29A] font-semibold':'text-white/85'}`}><Icon className="h-4 w-4"/>{itemLabel}</NavLink>)}</section>)}<button type="button" onClick={()=>void handleSignOut()} disabled={signingOut} className="mt-2 flex w-full items-center gap-3 rounded-lg border border-white/20 px-4 py-2.5 text-sm"><LogOut className="h-4 w-4"/>{signingOut?'Saindo...':'Sair'}</button></div>}
 </header>
}
