import { useEffect, useState } from 'react'
import { BriefcaseBusiness, CircleDollarSign, Plus, Search, Target, Trophy, XCircle } from 'lucide-react'
import { Link } from 'react-router-dom'
import { PageShell } from '../../components/ui/PageShell'
import { Modal } from '../../components/ui/Modal'
import { Badge, Button, Card, FieldLabel, Input, Select } from '../../components/ui/DesignSystem'
import { InlineAlert, TableEmpty, TableFooter, TableLoading, TableShell, Toolbar } from '../../components/ui/DataDisplay'
import { UserAvatar } from '../../components/users/UserAvatar'
import { supabase } from '../../services/supabase'
import { useAuth } from '../../hooks/useAuth'

type Opp={id:string;cliente_id:string|null;titulo:string;valor_estimado:number|null;estagio:string|null;status:string|null;responsavel_id:string|null;previsao_fechamento:string|null;created_at:string;cliente_nome:string;responsavel_nome:string|null;responsavel_avatar:string|null;lifecycle_status:string}
type Client={id:string;nome_fantasia:string|null;razao_social:string|null}
type Person={id:string;nome:string|null;avatar_url:string|null}
type Stats={open_count:number;won_count:number;lost_count:number;open_value:number;conversion:number}
type RpcPayload={rows:Opp[];total:number;stats:Stats}
const TABLE_PAGE_SIZE=25
const stages=['NOVO CONTATO','QUALIFICAÇÃO','PROPOSTA','NEGOCIAÇÃO','GANHO','PERDIDO']
const creationStages=['NOVO CONTATO','QUALIFICAÇÃO','PROPOSTA','NEGOCIAÇÃO']
const statuses=['ABERTA','GANHA','PERDIDA','CANCELADA']
const emptyForm={cliente_id:'',titulo:'',valor_estimado:'',estagio:'NOVO CONTATO',responsavel_id:'',previsao_fechamento:''}

export function Oportunidades(){
 const{profile,hasPermission}=useAuth();const canWrite=hasPermission('crm.write')
 const[rows,setRows]=useState<Opp[]>([]);const[clients,setClients]=useState<Client[]>([]);const[people,setPeople]=useState<Person[]>([]);const[q,setQ]=useState('');const[query,setQuery]=useState('');const[stage,setStage]=useState('TODAS');const[status,setStatus]=useState('TODOS');const[owner,setOwner]=useState('TODOS');const[error,setError]=useState('');const[loading,setLoading]=useState(true);const[page,setPage]=useState(1);const[total,setTotal]=useState(0);const[stats,setStats]=useState<Stats>({open_count:0,won_count:0,lost_count:0,open_value:0,conversion:0});const[open,setOpen]=useState(false);const[saving,setSaving]=useState(false);const[form,setForm]=useState({...emptyForm})

 useEffect(()=>{const timer=window.setTimeout(()=>setQuery(q.trim()),250);return()=>window.clearTimeout(timer)},[q])
 useEffect(()=>{setPage(1)},[query,stage,status,owner])
 useEffect(()=>{void loadMetadata()},[])
 useEffect(()=>{void loadRows()},[query,stage,status,owner,page])

 async function loadMetadata(){
  const[clientsResult,peopleResult]=await Promise.all([
   supabase.from('clientes').select('id,nome_fantasia,razao_social').is('deleted_at',null).order('razao_social'),
   supabase.from('profiles').select('id,nome,avatar_url').eq('ativo',true).order('nome')
  ])
  const e=clientsResult.error||peopleResult.error
  if(e)setError(e.message);else{setClients((clientsResult.data??[]) as Client[]);setPeople((peopleResult.data??[]) as Person[])}
 }
 async function loadRows(){
  setLoading(true);setError('')
  const{data,error:rpcError}=await supabase.rpc('crm_oportunidades_list',{p_query:query||null,p_stage:stage,p_status:status,p_responsible:owner==='TODOS'?null:owner,p_page:page,p_page_size:TABLE_PAGE_SIZE})
  if(rpcError)setError(rpcError.message);else{const payload=(data??{}) as RpcPayload;setRows(Array.isArray(payload.rows)?payload.rows:[]);setTotal(Number(payload.total||0));setStats(payload.stats??{open_count:0,won_count:0,lost_count:0,open_value:0,conversion:0})}
  setLoading(false)
 }
 const pages=Math.max(1,Math.ceil(total/TABLE_PAGE_SIZE))
 function newOpportunity(){setError('');setForm({...emptyForm,responsavel_id:profile?.id??''});setOpen(true)}
 async function save(e:React.FormEvent){e.preventDefault();if(!canWrite)return;if(!form.cliente_id){setError('Selecione o cliente da oportunidade.');return}if(!form.titulo.trim()){setError('Informe o título da oportunidade.');return}setSaving(true);setError('');const{error:saveError}=await supabase.from('oportunidades').insert({cliente_id:form.cliente_id,titulo:form.titulo.trim(),valor_estimado:form.valor_estimado===''?null:Number(form.valor_estimado),estagio:form.estagio,status:'ABERTA',responsavel_id:form.responsavel_id||null,previsao_fechamento:form.previsao_fechamento||null,ativo:true,created_by:profile?.id??null});if(saveError)setError(saveError.message);else{setOpen(false);setForm({...emptyForm});setPage(1);await loadRows()}setSaving(false)}
 return <PageShell title="Oportunidades" description="Acompanhe oportunidades comerciais, responsáveis, etapas e valores." action={canWrite?<Button onClick={newOpportunity}><Plus className="h-4 w-4"/>Nova oportunidade</Button>:undefined}>
  <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-5"><K icon={BriefcaseBusiness} label="Abertas" value={stats.open_count} active={status==='ABERTA'} onClick={()=>setStatus(status==='ABERTA'?'TODOS':'ABERTA')}/><K icon={Trophy} label="Ganhas" value={stats.won_count} active={status==='GANHA'} onClick={()=>setStatus(status==='GANHA'?'TODOS':'GANHA')}/><K icon={XCircle} label="Perdidas" value={stats.lost_count} active={status==='PERDIDA'} onClick={()=>setStatus(status==='PERDIDA'?'TODOS':'PERDIDA')}/><K icon={CircleDollarSign} label="Valor em aberto" value={money(Number(stats.open_value||0))} active={status==='ABERTA'} onClick={()=>setStatus(status==='ABERTA'?'TODOS':'ABERTA')}/><K icon={Target} label="Taxa de ganho" value={`${Number(stats.conversion||0).toFixed(1)}%`} active={status==='ENCERRADAS'} onClick={()=>setStatus(status==='ENCERRADAS'?'TODOS':'ENCERRADAS')}/></section>
  <Card className="overflow-hidden p-0"><Toolbar><div className="grid w-full gap-3 xl:grid-cols-[1.4fr_.7fr_.7fr_.8fr]"><div className="relative"><Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-[var(--text-muted)]"/><Input value={q} onChange={e=>setQ(e.target.value)} placeholder="Buscar oportunidade ou cliente..." className="pl-9"/></div><Select value={stage} onChange={e=>setStage(e.target.value)}><option value="TODAS">Todas as etapas</option>{stages.map(x=><option key={x}>{x}</option>)}</Select><Select value={status} onChange={e=>setStatus(e.target.value)}><option value="TODOS">Todos os status</option><option value="ENCERRADAS">Encerradas</option>{statuses.map(x=><option key={x}>{x}</option>)}</Select><Select value={owner} onChange={e=>setOwner(e.target.value)}><option value="TODOS">Todos os responsáveis</option>{people.map(x=><option key={x.id} value={x.id}>{x.nome||'Sem nome'}</option>)}</Select></div></Toolbar></Card>
  {error&&<InlineAlert>{error}</InlineAlert>}
  <TableShell><div className="overflow-x-auto"><table className="min-w-full text-sm"><thead className="text-left"><tr><th className="px-5 py-3">Oportunidade / Cliente</th><th className="px-5 py-3">Valor estimado</th><th className="px-5 py-3">Etapa</th><th className="px-5 py-3">Status</th><th className="px-5 py-3">Previsão</th><th className="px-5 py-3">Responsável</th><th className="px-5 py-3">Ação</th></tr></thead><tbody className="divide-y">{loading?<tr><td colSpan={7}><TableLoading/></td></tr>:rows.length?rows.map(r=><tr key={r.id}><td className="px-5 py-4"><div className="font-semibold text-[var(--text-primary)]">{r.titulo}</div><div className="text-xs text-[var(--text-secondary)]">{r.cliente_nome||'Cliente não informado'}</div></td><td className="px-5 py-4">{money(Number(r.valor_estimado||0))}</td><td className="px-5 py-4"><Badge>{r.estagio||'Sem etapa'}</Badge></td><td className="px-5 py-4"><StatusBadge value={r.lifecycle_status||'ABERTA'}/></td><td className="px-5 py-4">{date(r.previsao_fechamento)}</td><td className="px-5 py-4"><div className="flex items-center gap-2"><UserAvatar name={r.responsavel_nome||'Sem responsável'} avatarUrl={r.responsavel_avatar||null} size="sm"/><span>{r.responsavel_nome||'Sem responsável'}</span></div></td><td className="px-5 py-4"><Link to={`/oportunidades/${r.id}`} className="font-semibold text-[var(--brand-700)]">Visualizar</Link></td></tr>):<tr><td colSpan={7}><TableEmpty label="Nenhuma oportunidade neste filtro."/></td></tr>}</tbody></table></div>{!loading&&total>0&&<TableFooter><span>{total} oportunidade(s) · página {page} de {pages}</span><div className="flex gap-2"><Button variant="secondary" disabled={page<=1} onClick={()=>setPage(p=>Math.max(1,p-1))}>Anterior</Button><Button variant="secondary" disabled={page>=pages} onClick={()=>setPage(p=>Math.min(pages,p+1))}>Próxima</Button></div></TableFooter>}</TableShell>
  <Modal open={open} onClose={()=>setOpen(false)} title="Nova oportunidade"><form onSubmit={save} className="grid gap-4 sm:grid-cols-2"><label className="sm:col-span-2"><FieldLabel className="mb-1 block">Cliente *</FieldLabel><Select required value={form.cliente_id} onChange={e=>setForm({...form,cliente_id:e.target.value})}><option value="">Selecione</option>{clients.map(c=><option key={c.id} value={c.id}>{c.nome_fantasia||c.razao_social||'Cliente'}</option>)}</Select></label><label className="sm:col-span-2"><FieldLabel className="mb-1 block">Título *</FieldLabel><Input required value={form.titulo} onChange={e=>setForm({...form,titulo:e.target.value})} placeholder="Ex.: Análises de água - proposta setembro"/></label><label><FieldLabel className="mb-1 block">Valor estimado</FieldLabel><Input type="number" min="0" step="0.01" value={form.valor_estimado} onChange={e=>setForm({...form,valor_estimado:e.target.value})}/></label><label><FieldLabel className="mb-1 block">Responsável</FieldLabel><Select value={form.responsavel_id} onChange={e=>setForm({...form,responsavel_id:e.target.value})}><option value="">Sem responsável</option>{people.map(p=><option key={p.id} value={p.id}>{p.nome||'Usuário'}</option>)}</Select></label><label><FieldLabel className="mb-1 block">Etapa inicial</FieldLabel><Select value={form.estagio} onChange={e=>setForm({...form,estagio:e.target.value})}>{creationStages.map(x=><option key={x}>{x}</option>)}</Select></label><label><FieldLabel className="mb-1 block">Status</FieldLabel><Input value="ABERTA" disabled/></label><label className="sm:col-span-2"><FieldLabel className="mb-1 block">Previsão de fechamento</FieldLabel><Input type="date" value={form.previsao_fechamento} onChange={e=>setForm({...form,previsao_fechamento:e.target.value})}/></label><p className="sm:col-span-2 text-xs text-[var(--text-secondary)]">O encerramento como GANHO ou PERDIDO continua sendo feito pelo Pipeline, onde o sistema exige a observação/motivo e registra o histórico.</p><div className="sm:col-span-2 flex justify-end gap-2"><Button type="button" variant="secondary" onClick={()=>setOpen(false)}>Cancelar</Button><Button disabled={saving}>{saving?'Salvando...':'Salvar oportunidade'}</Button></div></form></Modal>
 </PageShell>
}
function K({icon:I,label,value,active=false,onClick}:{icon:any;label:string;value:string|number;active?:boolean;onClick:()=>void}){return <button type="button" onClick={onClick} aria-pressed={active} className={`flex h-20 w-full items-center gap-3 rounded-3xl border bg-white p-4 text-left shadow-sm transition hover:-translate-y-0.5 hover:shadow-md focus:outline-none focus:ring-2 focus:ring-[var(--brand-600)] ${active?'border-[var(--brand-600)] ring-2 ring-teal-100':'border-[var(--border)]'}`}><span className="grid h-11 w-11 shrink-0 place-items-center rounded-full bg-[var(--brand-50)] text-[var(--brand-700)]"><I className="h-5 w-5"/></span><div className="min-w-0"><span className="text-xs text-[var(--text-secondary)]">{label}</span><strong className="mt-1 block truncate text-xl text-[var(--text-primary)]">{value}</strong></div></button>}
function StatusBadge({value}:{value:string}){const variant=value==='GANHA'?'success':value==='PERDIDA'||value==='CANCELADA'?'danger':'brand';return <Badge variant={variant}>{value}</Badge>}
function money(v:number){return v.toLocaleString('pt-BR',{style:'currency',currency:'BRL'})}
function date(v:string|null){return v?new Date(`${v}T12:00:00`).toLocaleDateString('pt-BR'):'—'}
