import { createClient } from "https://esm.sh/@supabase/supabase-js@2.45.0";
import * as XLSX from "npm:xlsx@0.18.5";

const SUPABASE_URL=Deno.env.get("SUPABASE_URL")!;
const SERVICE_KEY=Deno.env.get("SB_SECRET_KEY")??Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;
const TOKEN=Deno.env.get("ML_TOKEN")??"";
const JWT_SECRET=Deno.env.get("ML_JWT_SECRET")??"";
const sb=createClient(SUPABASE_URL,SERVICE_KEY,{auth:{persistSession:false,autoRefreshToken:false}});
const enc=new TextEncoder(),dec=new TextDecoder();
const CORS={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type, x-token","Access-Control-Allow-Methods":"POST, OPTIONS"};
const resp=(d:any,s=200)=>new Response(JSON.stringify(d),{status:s,headers:{...CORS,"Content-Type":"application/json; charset=utf-8","Cache-Control":"no-store"}});
const txt=(v:any)=>String(v??"").trim();
const num=(v:any)=>{if(typeof v==="number")return Number.isFinite(v)?v:0;let s=txt(v).replace(/R\$/gi,"").replace(/\s/g,"");if(/,/.test(s))s=s.replace(/\./g,"").replace(",",".");const n=Number(s);return Number.isFinite(n)?n:0};
const iso=()=>new Date().toISOString();
const key=(s:any)=>txt(s).normalize("NFD").replace(/[\u0300-\u036f]/g,"").toUpperCase().replace(/[^A-Z0-9]/g,"");
const normDoc=(s:any)=>txt(s).replace(/\D/g,"");
function b64u(s:string){s=s.replace(/-/g,"+").replace(/_/g,"/");while(s.length%4)s+="=";const b=atob(s),o=new Uint8Array(b.length);for(let i=0;i<b.length;i++)o[i]=b.charCodeAt(i);return o}
async function jwt(t:string){if(!JWT_SECRET||!t)return null;const p=t.split(".");if(p.length!==3)return null;try{const k=await crypto.subtle.importKey("raw",enc.encode(JWT_SECRET),{name:"HMAC",hash:"SHA-256"},false,["verify"]);if(!await crypto.subtle.verify("HMAC",k,b64u(p[2]),enc.encode(`${p[0]}.${p[1]}`)))return null;const x=JSON.parse(dec.decode(b64u(p[1])));if(x.sis!=="minaslab"||(typeof x.exp==="number"&&x.exp<Math.floor(Date.now()/1000)))return null;return x}catch{return null}}
function excelDate(v:any){if(!v)return null;if(typeof v==="number"){const d=XLSX.SSF.parse_date_code(v);return d?`${d.y}-${String(d.m).padStart(2,"0")}-${String(d.d).padStart(2,"0")}`:null}const s=txt(v);let m=s.match(/^(\d{1,2})\/(\d{1,2})\/(\d{4})/);if(m)return `${m[3]}-${m[2].padStart(2,"0")}-${m[1].padStart(2,"0")}`;m=s.match(/^(\d{4})-(\d{2})-(\d{2})/);return m?s.slice(0,10):null}
function cellMap(r:any){const m:any={};for(const [k,v] of Object.entries(r||{}))m[key(k)]=v;return m}
async function audit(id:string,campo:string,a:any,n:any,u:string,origem="MANUAL"){if(String(a??"")===String(n??""))return;await sb.from("servicos_gerados_historico").insert({servico_id:id,campo,valor_anterior:a==null?null:String(a),valor_novo:n==null?null:String(n),origem,usuario:u})}
async function particularidade(s:any){const doc=normDoc(s.cnpj_cpf);if(doc){const r=await sb.from("servicos_gerados_particularidades").select("*").eq("ativo",true).eq("cnpj_cpf",doc).limit(1);if(!r.error&&r.data?.[0])return r.data[0]}const r=await sb.from("servicos_gerados_particularidades").select("*").eq("ativo",true).eq("cliente_chave",key(s.cliente)).limit(1);return r.data?.[0]??null}
async function listar(f:any={}){let q=sb.from("servicos_gerados").select("*,empresa:empresas(id,nome)").eq("apagado",false).order("data_os",{ascending:false,nullsFirst:false}).order("created_at",{ascending:false}).limit(3000);if(f.empresaId)q=q.eq("empresa_id",f.empresaId);if(f.statusFaturamento)q=q.eq("status_faturamento",f.statusFaturamento);if(f.statusPagamento)q=q.eq("status_pagamento",f.statusPagamento);const {data,error}=await q;if(error)throw error;let itens=data??[];const b=txt(f.busca).toLowerCase();if(b)itens=itens.filter((x:any)=>[x.os_numero,x.cliente,x.cnpj_cpf,x.numero_nf,x.contrato_proposta,x.referencia_pagamento].some(v=>txt(v).toLowerCase().includes(b)));for(const x of itens)x.particularidade=await particularidade(x);const resumo={total:itens.length,aguardandoFaturamento:itens.filter((x:any)=>["AGUARDANDO","PRONTO PARA FATURAR"].includes(x.status_faturamento)).length,faturados:itens.filter((x:any)=>x.status_faturamento==="FATURADO").length,aguardandoPagamento:itens.filter((x:any)=>["AGUARDANDO","A RECEBER","PARCIAL"].includes(x.status_pagamento)&&x.status_faturamento==="FATURADO").length,vencidos:itens.filter((x:any)=>x.status_pagamento==="VENCIDO").length,divergencias:itens.filter((x:any)=>x.status_pagamento==="DIVERGENCIA").length};return{itens,resumo}}
async function salvar(x:any,u:string){if(!x.id)throw new Error("Serviço não informado.");const {data:ant,error:e}=await sb.from("servicos_gerados").select("*").eq("id",x.id).maybeSingle();if(e)throw e;if(!ant)throw new Error("Serviço não encontrado.");const novoStatus=Object.prototype.hasOwnProperty.call(x,"status_faturamento")?x.status_faturamento:ant.status_faturamento;const novoVencimento=Object.prototype.hasOwnProperty.call(x,"data_vencimento")?x.data_vencimento:ant.data_vencimento;const novoValor=Object.prototype.hasOwnProperty.call(x,"valor_faturar")?num(x.valor_faturar):num(ant.valor_faturar);const novaForma=Object.prototype.hasOwnProperty.call(x,"forma_pagamento")?x.forma_pagamento:ant.forma_pagamento;if(novoStatus==="FATURADO"){if(!ant.empresa_id)throw new Error("Defina a empresa de emissão antes de faturar esta OS.");if(!novoVencimento)throw new Error("Informe o vencimento antes de faturar esta OS.");if(novoValor<=0)throw new Error("Informe um valor de faturamento maior que zero.");if(!txt(novaForma))throw new Error("Informe a forma de pagamento antes de faturar esta OS.");}const campos=["valor_faturar","data_emissao","data_vencimento","forma_pagamento","numero_nf","tipo_emissao","status_faturamento","status_pagamento","referencia_pagamento","observacao"];const p:any={updated_at:iso(),updated_by:u};for(const c of campos)if(Object.prototype.hasOwnProperty.call(x,c))p[c]=x[c]??null;if(Object.prototype.hasOwnProperty.call(x,"status_faturamento"))p.faturamento_manual=true;if(Object.prototype.hasOwnProperty.call(x,"status_pagamento")&&txt(x.status_pagamento)!==txt(ant.status_pagamento))p.pagamento_manual=true;const {data,error}=await sb.from("servicos_gerados").update(p).eq("id",x.id).select("*").maybeSingle();if(error)throw error;for(const c of campos)if(Object.prototype.hasOwnProperty.call(p,c))await audit(x.id,c,ant[c],p[c],u);return data}
async function salvarPart(x:any,u:string){const chave=key(x.cliente_chave||x.cliente_nome);if(!chave)throw new Error("Informe o cliente.");const p={empresa_id:x.empresa_id||null,cnpj_cpf:normDoc(x.cnpj_cpf)||null,cliente_chave:chave,cliente_nome:txt(x.cliente_nome)||null,tem_contrato:txt(x.tem_contrato)||null,coleta:txt(x.coleta)||null,faturamento:txt(x.faturamento)||null,email_financeiro:txt(x.email_financeiro)||null,observacao:txt(x.observacao)||null,ativo:x.ativo!==false,updated_at:iso(),updated_by:u};let r;if(x.id)r=await sb.from("servicos_gerados_particularidades").update(p).eq("id",x.id).select("*").maybeSingle();else{const ex=await sb.from("servicos_gerados_particularidades").select("id").eq("cliente_chave",chave).limit(1);if(ex.data?.[0])r=await sb.from("servicos_gerados_particularidades").update(p).eq("id",ex.data[0].id).select("*").maybeSingle();else r=await sb.from("servicos_gerados_particularidades").insert(p).select("*").maybeSingle()}if(r.error)throw r.error;return r.data}
async function empresas(){const r=await sb.from("empresas").select("id,nome,usa_omie").eq("ativa",true);if(r.error)throw r.error;const minas=r.data?.find((x:any)=>x.usa_omie===true),mlab=r.data?.find((x:any)=>x.usa_omie===false);if(!minas||!mlab)throw new Error("Empresas MinasLab/M Lab não encontradas.");return{minas,mlab}}
function statusFat(v:any){const s=key(v);if(s.includes("CANCEL"))return"CANCELADO";if(s.includes("EMITIDA")||s.includes("EMITIDO"))return"FATURADO";return"AGUARDANDO"}
function statusPag(v:any){const s=key(v);if(s.includes("CANCEL"))return"CANCELADO";if(s.includes("PARCIAL"))return"PARCIAL";if(s.includes("PAGO"))return"PAGO";return"A RECEBER"}
function emailsSeguros(v:any){const s=txt(v);if(!s)return null;if(/\b(SENHA|PASSWORD|LOGIN)\b/i.test(s)){const xs=s.match(/[\w.+-]+@[\w.-]+\.[A-Za-z]{2,}/g)||[];return xs.join("; ")||null}return s}
async function importarHistorico(wb:any,u:string){const {minas,mlab}=await empresas();const ws=wb.Sheets[wb.SheetNames.find((n:string)=>key(n)==="DADOS")!];const rows=XLSX.utils.sheet_to_json(ws,{defval:"",raw:true,range:1}) as any[];const lotes:any[]=[];let validos=0,ignorados=0;for(let i=0;i<rows.length;i++){const m=cellMap(rows[i]);const os=txt(m.ORDEMDESERVICO);if(!os){ignorados++;continue}const empresaNome=key(m.EMPRESADEEMISSAO);const empresa=empresaNome.includes("MLAB")&&!empresaNome.includes("MINASLAB")?mlab:minas;const ref=txt(m.OMIEC6BANK)||null;const nf=empresa.id===mlab.id?ref:null;const dataPag=excelDate(m.DATADOPAGAMENTO);lotes.push({empresa_id:empresa.id,os_numero:os,codigo_gerencialab:null,contrato_proposta:txt(m.CONTRATO)||null,cliente:txt(m.NOME)||"Cliente não informado",cnpj_cpf:normDoc(m.CNPJ)||null,servico:null,data_os:excelDate(m.DATADAORDEM),valor_original:num(m.VALOR),valor_faturar:num(m.VALOR),data_emissao:excelDate(m.DATADEEMISSAO),data_vencimento:null,forma_pagamento:txt(m.FORMADEPAGAMENTO)||null,numero_nf:nf,tipo_emissao:txt(m.TIPODEEMISSAO)||null,status_faturamento:statusFat(m.STATUSDENF),status_pagamento:statusPag(m.STATUSDEPAGAMENTO),faturamento_manual:false,pagamento_manual:false,pagamento_origem:"PLANILHA HISTÓRICA",pagamento_referencia:ref,pagamento_identificado_em:dataPag?`${dataPag}T12:00:00-03:00`:null,recebimento_id:null,nota_fiscal_id:null,observacao:null,dados_origem:{fonte:"PLANILHA_NOTAS_FISCAIS",linha:i+3,status_emissao_original:txt(m.STATUSDEEMISSAO),status_nf_original:txt(m.STATUSDENF),status_pagamento_original:txt(m.STATUSDEPAGAMENTO)},referencia_pagamento:ref,updated_at:iso(),updated_by:u,created_by:u,apagado:false});validos++}
let inseridos=0;for(let i=0;i<lotes.length;i+=150){const lote=lotes.slice(i,i+150);const r=await sb.from("servicos_gerados").upsert(lote,{onConflict:"empresa_id,os_numero"}).select("id");if(r.error)throw r.error;inseridos+=r.data?.length||0}
let particularidades=0;const pn=wb.SheetNames.find((n:string)=>key(n)==="PARTICULARIDADES");if(pn){const prs=XLSX.utils.sheet_to_json(wb.Sheets[pn],{defval:"",raw:true,range:1}) as any[];for(const rr of prs){const m=cellMap(rr),nome=txt(m.EMPRESA);if(!nome)continue;const p={empresa_id:null,cnpj_cpf:null,cliente_chave:key(nome),cliente_nome:nome,tem_contrato:txt(m.TEMCONTRATO)||null,coleta:txt(m.COLETA)||null,faturamento:txt(m.FATURAMENTO)||null,email_financeiro:emailsSeguros(m.EMAILFINANCEIRO),observacao:null,ativo:true,updated_at:iso(),updated_by:u};const ex=await sb.from("servicos_gerados_particularidades").select("id").eq("cliente_chave",p.cliente_chave).limit(1);const r=ex.data?.[0]?await sb.from("servicos_gerados_particularidades").update(p).eq("id",ex.data[0].id):await sb.from("servicos_gerados_particularidades").insert(p);if(r.error)throw r.error;particularidades++}}
return{ok:true,modo:"HISTORICO",aba:"DADOS",lidos:rows.length,inseridos,atualizados:0,ignorados,particularidades,validos}}
async function importarGerencia(wb:any,empresaId:string,u:string){if(!empresaId)throw new Error("Selecione a empresa antes de importar.");const nome=wb.SheetNames.find((n:string)=>key(n).includes("CONFERENCIAOS"))??wb.SheetNames[0];const rows=XLSX.utils.sheet_to_json(wb.Sheets[nome],{defval:"",raw:true}) as any[];let inseridos=0,atualizados=0,ignorados=0;for(const r0 of rows){const m=cellMap(r0);const os=txt(m.NOME||m.ORDEMDESERVICO||m.OS);if(!os){ignorados++;continue}const p:any={empresa_id:empresaId,os_numero:os,codigo_gerencialab:txt(m.CODIGO)||null,contrato_proposta:txt(m.PROPOSTA||m.CONTRATO)||null,cliente:txt(m.CLIENTE||m.NOMECLIENTE)||"Cliente não informado",cnpj_cpf:normDoc(m.CNPJDOCLIENTE||m.CNPJCPF||m.CNPJ)||null,servico:txt(m.SERVICO)||null,data_os:excelDate(m.DATA||m.DATAOS)||null,valor_original:num(m.TOTAL||m.VALOR),valor_faturar:num(m.TOTAL||m.VALOR),forma_pagamento:txt(m.FORMADEPAGAMENTO)||null,dados_origem:r0,updated_at:iso(),updated_by:u};const {data:ja}=await sb.from("servicos_gerados").select("id").eq("empresa_id",empresaId).eq("os_numero",os).maybeSingle();if(ja){const {error}=await sb.from("servicos_gerados").update({codigo_gerencialab:p.codigo_gerencialab,contrato_proposta:p.contrato_proposta,cliente:p.cliente,cnpj_cpf:p.cnpj_cpf,servico:p.servico,data_os:p.data_os,valor_original:p.valor_original,dados_origem:p.dados_origem,updated_at:iso(),updated_by:u}).eq("id",ja.id);if(error)throw error;atualizados++}else{const {error}=await sb.from("servicos_gerados").insert({...p,status_faturamento:"AGUARDANDO",status_pagamento:"AGUARDANDO",faturamento_manual:false,pagamento_manual:false,created_by:u});if(error)throw error;inseridos++}}return{ok:true,modo:"GERENCIALAB",aba:nome,lidos:rows.length,inseridos,atualizados,ignorados}}
async function importar(body:any,u:string){const b=atob(txt(body.base64));const arr=new Uint8Array(b.length);for(let i=0;i<b.length;i++)arr[i]=b.charCodeAt(i);const wb=XLSX.read(arr,{type:"array",cellDates:false});if(wb.SheetNames.some((n:string)=>key(n)==="DADOS"))return importarHistorico(wb,u);return importarGerencia(wb,txt(body.empresaId),u)}
async function sincronizar(u:string){const {data:serv,error}=await sb.from("servicos_gerados").select("*,empresa:empresas(nome)").eq("apagado",false).eq("status_faturamento","FATURADO");if(error)throw error;let atualizados=0;for(const s of serv??[]){if(s.pagamento_manual)continue;let rec:any=null,orig="";const emp=txt(s.empresa?.nome).toUpperCase();if(emp.includes("MINASLAB")){const ref=txt(s.referencia_pagamento||s.pagamento_referencia);if(ref){const r=await sb.from("recebimentos").select("id,status,valor_previsto,valor_recebido,data_pagamento,data_vencimento,numero_nf,dados_omie,cnpj_cpf").eq("empresa_id",s.empresa_id).eq("apagado",false).filter("dados_omie->>numero_pedido","eq",ref).limit(100);if(r.error)throw r.error;let candidatos=r.data??[];if(!candidatos.length&&s.numero_nf){const n=await sb.from("recebimentos").select("id,status,valor_previsto,valor_recebido,data_pagamento,data_vencimento,numero_nf,dados_omie,cnpj_cpf").eq("empresa_id",s.empresa_id).eq("apagado",false).eq("numero_nf",s.numero_nf).limit(100);if(n.error)throw n.error;candidatos=n.data??[]}const documento=(v:any)=>txt(v).replace(/\D/g,"");const sd=documento(s.cnpj_cpf);if(sd)candidatos=candidatos.filter((x:any)=>documento(x.cnpj_cpf)===sd);else candidatos=[];if(s.numero_nf)candidatos=candidatos.filter((x:any)=>!x.numero_nf||txt(x.numero_nf)===txt(s.numero_nf));const grupo=(serv??[]).filter((x:any)=>x.empresa_id===s.empresa_id&&documento(x.cnpj_cpf)===sd&&txt(x.referencia_pagamento||x.pagamento_referencia)===ref&&x.status_faturamento==="FATURADO"&&x.apagado===false);const totalGrupo=grupo.reduce((v:number,x:any)=>v+num(x.valor_faturar),0);const valores=candidatos.filter((x:any)=>Math.abs(num(x.valor_previsto)-num(s.valor_faturar))<=0.01||Math.abs(num(x.valor_previsto)-totalGrupo)<=0.01);if(valores.length)candidatos=valores;if(candidatos.length===1)rec=candidatos[0];orig="OMIE (pedido/NF)"}}else{const nf=txt(s.numero_nf||s.referencia_pagamento||s.pagamento_referencia);if(nf){const r=await sb.from("recebimentos").select("id,status,valor_previsto,valor_recebido,data_pagamento,data_vencimento,numero_nf,c6_status,c6_data_pagamento_boleto,c6_data_credito").eq("empresa_id",s.empresa_id).eq("apagado",false).eq("numero_nf",nf).limit(1);rec=r.data?.[0]??null;orig="C6 (NF)"}}
if(!rec)continue;let st="A RECEBER";const c6=txt(rec.c6_status).toUpperCase();if(!emp.includes("MINASLAB")&&c6.includes("PAGO"))st="PAGO";else if(rec.status==="PAGO")st="PAGO";else if(rec.status==="PARCIAL")st="PARCIAL";else if(rec.status==="VENCIDO")st="VENCIDO";const vf=num(s.valor_faturar),vr=num(rec.valor_previsto);const grupoValor=emp.includes("MINASLAB")?(serv??[]).filter((x:any)=>x.empresa_id===s.empresa_id&&txt(x.cnpj_cpf).replace(/\D/g,"")===txt(s.cnpj_cpf).replace(/\D/g,"")&&txt(x.referencia_pagamento||x.pagamento_referencia)===txt(s.referencia_pagamento||s.pagamento_referencia)&&x.apagado===false).reduce((v:number,x:any)=>v+num(x.valor_faturar),0):vf;if(st!=="PAGO"&&vf>0&&vr>0&&Math.abs(vf-vr)>0.01&&Math.abs(grupoValor-vr)>0.01)st="DIVERGENCIA";const p:any={status_pagamento:st,pagamento_origem:orig,pagamento_referencia:emp.includes("MINASLAB")?txt(s.referencia_pagamento||s.pagamento_referencia):txt(s.numero_nf||s.referencia_pagamento||s.pagamento_referencia),pagamento_identificado_em:iso(),recebimento_id:rec.id,updated_at:iso(),updated_by:u};if(!s.numero_nf&&rec.numero_nf)p.numero_nf=rec.numero_nf;if(!s.data_vencimento&&rec.data_vencimento)p.data_vencimento=rec.data_vencimento;const salvo=await sb.from("servicos_gerados").update(p).eq("id",s.id);if(salvo.error)throw salvo.error;await audit(s.id,"status_pagamento",s.status_pagamento,st,u,"AUTOMATICO");atualizados++}return{ok:true,atualizados}}

Deno.serve(async req=>{if(req.method==="OPTIONS")return new Response("ok",{headers:CORS});if(req.method!=="POST")return resp({erro:"Use POST."},405);let b:any;try{b=await req.json()}catch{return resp({erro:"JSON inválido."},400)}const m=txt(req.headers.get("authorization")).match(/^Bearer\s+(.+)$/i),cr=m?await jwt(m[1]):null,maq=!!TOKEN&&req.headers.get("x-token")===TOKEN;if(!cr&&!maq)return resp({erro:"Entre no sistema.",semSessao:true},401);if(!maq&&txt(cr?.papel)!=="direcao"){if(txt(b.action)!=="historico")return resp({erro:"Consulta permitida; alterações são exclusivas da direção.",semPermissao:true},403);const acesso=await sb.from("ml_contas").select("ativo,paginas_consulta").eq("usuario",txt(cr?.sub)).maybeSingle();if(acesso.error||!acesso.data?.ativo||!Array.isArray(acesso.data.paginas_consulta)||!acesso.data.paginas_consulta.includes("financas/servicos-gerados"))return resp({erro:"Sem permissão para Serviços Gerados.",semPermissao:true},403);}const u=maq?"maquina":txt(cr?.sub)||"direcao";try{switch(txt(b.action)){case"listar":return resp(await listar(b.filtros));case"salvar":return resp({item:await salvar(b.registro??{},u)});case"particularidadeSalvar":return resp({item:await salvarPart(b.registro??{},u)});case"importar":return resp(await importar(b,u));case"sincronizarPagamentos":return resp(await sincronizar(u));case"registrarTratamento":{const nota=txt(b.justificativa),ids=Array.isArray(b.servicoIds)?[...new Set(b.servicoIds.map(txt).filter(Boolean))]:[];if(nota.length<10||nota.length>1000)return resp({erro:"Descreva a análise em 10 a 1.000 caracteres."},400);if(!ids.length||ids.length>100)return resp({erro:"Selecione até 100 OS para registrar a análise."},400);const q=await sb.from("servicos_gerados").select("id,status_pagamento").in("id",ids).eq("apagado",false);if(q.error)throw q.error;if(q.data?.length!==ids.length||q.data.some((x:any)=>x.status_pagamento!=="DIVERGENCIA"))return resp({erro:"Atualize a tela: uma OS não está mais em divergência."},409);const linhas=ids.map((id:string)=>({servico_id:id,campo:"tratamento_divergencia",valor_anterior:null,valor_novo:nota,origem:"MANUAL",usuario:u}));const gravar=await sb.from("servicos_gerados_historico").insert(linhas);if(gravar.error)throw gravar.error;return resp({ok:true,quantidade:ids.length})}case"historico":{const {data,error}=await sb.from("servicos_gerados_historico").select("*").eq("servico_id",txt(b.id)).order("criado_em",{ascending:false});if(error)throw error;return resp({itens:data??[]})}default:return resp({erro:"Ação desconhecida."},400)}}catch(e){console.error(e);return resp({erro:e instanceof Error?e.message:"Falha interna."},500)}});
