import { useEffect, useMemo, useState } from "react";
import { ArrowLeft, Ban, Search, X } from "lucide-react";
import { useNavigate } from "react-router-dom";
import { PageTitle } from "../components/ui.jsx";
import { finNfseListar, finNfseCancelarProducao } from "../services/financeiro.js";
const moeda=v=>Number(v||0).toLocaleString("pt-BR",{style:"currency",currency:"BRL"});
const dataBR=v=>{const p=String(v||"").slice(0,10).split("-");return p.length===3?`${p[2]}/${p[1]}/${p[0]}`:"—"};
export default function CancelarNfse(){
 const nav=useNavigate(),[itens,setItens]=useState([]),[busca,setBusca]=useState(""),[sel,setSel]=useState(null),[codigo,setCodigo]=useState("1"),[motivo,setMotivo]=useState(""),[erro,setErro]=useState(""),[ok,setOk]=useState(""),[enviando,setEnviando]=useState(false);
 async function carregar(){try{setErro("");setItens(await finNfseListar())}catch(e){setErro(e.message)}} useEffect(()=>{carregar()},[]);
 const lista=useMemo(()=>{const t=busca.toLowerCase().trim();return itens.filter(x=>["AUTORIZADA","CANCELADA"].includes(String(x.status_fiscal||""))&&(!t||`${x.numero_nf||""} ${x.nome_destinatario||""} ${x.cnpj_destinatario||""} ${x.chave_acesso||""}`.toLowerCase().includes(t)))},[itens,busca]);
 function abrir(x){if(x.status_fiscal!=="AUTORIZADA")return;setSel(x);setCodigo("1");setMotivo("");setErro("");setOk("")}
 async function cancelar(e){e.preventDefault();if(!sel)return;setErro("");setOk("");if(motivo.trim().length<15){setErro("Informe um motivo com pelo menos 15 caracteres.");return}if(!confirm(`CONFIRMA O CANCELAMENTO FISCAL da NFS-e ${sel.numero_nf}?\n\nEsta ação será enviada à NFS-e Nacional e não poderá ser desfeita pelo sistema.`))return;setEnviando(true);try{const r=await finNfseCancelarProducao(sel.id,codigo,motivo.trim());setOk(`NFS-e ${r.numeroNf||sel.numero_nf} cancelada no Sistema Nacional.`);setSel(null);await carregar()}catch(e){setErro(e.message)}finally{setEnviando(false)}}
 return <div className="space-y-5"><div className="flex items-center gap-3"><button className="btn-ghost h-9 w-9 p-0" onClick={()=>nav('/financas')}><ArrowLeft size={18}/></button><PageTitle titulo="Cancelar NFS-e" descricao="Cancelamento fiscal real no Sistema Nacional, com preservação do histórico e proteção do Financeiro."/></div>
 <div className="rounded-xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-900"><b>Importante:</b> cancelar aqui envia um evento fiscal à NFS-e Nacional. A nota não é excluída. Se o Recebimento estiver aberto e sem baixa/conciliação, ele será cancelado automaticamente; se já houver movimentação financeira, ela será preservada para revisão.</div>
 {erro&&<div className="rounded-xl bg-red-50 p-3 text-sm text-red-700">{erro}</div>}{ok&&<div className="rounded-xl bg-emerald-50 p-3 text-sm text-emerald-700">{ok}</div>}
 <div className="rounded-2xl border bg-white p-4"><div className="relative"><Search size={16} className="absolute left-3 top-3 text-slate-400"/><input className="input pl-9" value={busca} onChange={e=>setBusca(e.target.value)} placeholder="Pesquisar por número, cliente, CNPJ ou chave"/></div></div>
 <div className="overflow-x-auto rounded-2xl border bg-white"><table className="min-w-full text-sm"><thead className="bg-slate-50 text-left text-xs uppercase text-slate-500"><tr><th className="px-4 py-3">NFS-e</th><th className="px-4 py-3">Emissão</th><th className="px-4 py-3">Cliente</th><th className="px-4 py-3 text-right">Valor</th><th className="px-4 py-3">Situação</th><th className="px-4 py-3"></th></tr></thead><tbody>{lista.length===0?<tr><td colSpan="6" className="p-8 text-center text-slate-500">Nenhuma NFS-e autorizada/cancelada encontrada.</td></tr>:lista.map(x=><tr key={x.id} className="border-t"><td className="px-4 py-3"><b>{x.numero_nf||"—"}</b><div className="max-w-64 truncate text-[10px] text-slate-500">{x.chave_acesso}</div></td><td className="px-4 py-3">{dataBR(x.data_emissao)}</td><td className="px-4 py-3">{x.nome_destinatario||x.cliente?.nome||"—"}</td><td className="px-4 py-3 text-right font-semibold">{moeda(x.valor_total)}</td><td className="px-4 py-3"><span className={x.status_fiscal==='CANCELADA'?'rounded-full bg-slate-100 px-2 py-1 text-xs font-bold text-slate-700':'rounded-full bg-emerald-50 px-2 py-1 text-xs font-bold text-emerald-700'}>{x.status_fiscal}</span>{x.nfse_cancelamento_motivo&&<div className="mt-1 max-w-64 text-xs text-slate-500">{x.nfse_cancelamento_motivo}</div>}</td><td className="px-4 py-3 text-right">{x.status_fiscal==='AUTORIZADA'?<button className="btn-outline border-red-200 text-red-700" onClick={()=>abrir(x)}><Ban size={15}/>Cancelar</button>:<span className="text-xs text-slate-400">Histórico preservado</span>}</td></tr>)}</tbody></table></div>
 {sel&&<div className="fixed inset-0 z-50 grid place-items-center bg-slate-950/50 p-4"><div className="w-full max-w-xl rounded-2xl bg-white shadow-2xl"><div className="flex items-center justify-between border-b px-5 py-4"><div><h2 className="font-bold">Cancelar NFS-e {sel.numero_nf}</h2><p className="text-xs text-slate-500">{sel.nome_destinatario} · {moeda(sel.valor_total)}</p></div><button className="btn-ghost h-9 w-9 p-0" onClick={()=>setSel(null)}><X size={18}/></button></div><form onSubmit={cancelar} className="space-y-4 p-5"><label><span className="label">Motivo fiscal</span><select className="input" value={codigo} onChange={e=>setCodigo(e.target.value)}><option value="1">1 — Erro na emissão</option><option value="2">2 — Serviço não prestado</option><option value="9">9 — Outros</option></select></label><label><span className="label">Descrição do motivo *</span><textarea className="input min-h-28" maxLength={255} value={motivo} onChange={e=>setMotivo(e.target.value)} placeholder="Descreva claramente o motivo do cancelamento (15 a 255 caracteres)."/><div className="mt-1 text-right text-xs text-slate-400">{motivo.length}/255</div></label><div className="rounded-xl bg-red-50 p-3 text-sm text-red-800"><b>Atenção:</b> após a confirmação, o pedido será transmitido ao Sistema Nacional. A nota continuará no histórico com situação CANCELADA.</div><div className="flex justify-end gap-2"><button type="button" className="btn-outline" onClick={()=>setSel(null)} disabled={enviando}>Voltar</button><button type="submit" className="btn-primary bg-red-600 hover:bg-red-700" disabled={enviando}>{enviando?'Cancelando...':'Confirmar cancelamento fiscal'}</button></div></form></div></div>}
 </div>;
}