import { useEffect, useMemo, useState } from 'react';
import { financeiroOpcoes, finRecebimentosListar, finDespesasListar, finNotasListar } from '../services/financeiro.js';
import { pendenciasFinanceiras } from '../lib/financeiroIntegridade.js';
import OmieAutoStatus from '../components/financeiro/OmieAutoStatus.jsx';
const moeda = v => Number(v||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
export default function ConferenciaFinanceiro(){
 const [dados,setDados]=useState(null),[erro,setErro]=useState(''),[empresa,setEmpresa]=useState(''),[motivo,setMotivo]=useState(''),[loading,setLoading]=useState(true);
 async function carregar(){setLoading(true);setErro('');try{const [o,r,d,n]=await Promise.all([financeiroOpcoes(),finRecebimentosListar(),finDespesasListar(),finNotasListar()]);setDados({o,r,d,n})}catch(e){setErro(e.message)}finally{setLoading(false)}}
 useEffect(()=>{carregar()},[]);
 const pendencias=useMemo(()=>dados?pendenciasFinanceiras(dados.r,dados.d,dados.n):[],[dados]);
 const visiveis=pendencias.filter(x=>(!empresa||x.registro.empresa_id===empresa)&&(!motivo||x.motivo===motivo));
 return <div className="space-y-5"><header><h1 className="text-2xl font-bold text-blue-900">Conferência financeira</h1><p className="mt-2 text-slate-600">Confira documentos, parcelas e datas antes de corrigir a origem. Nenhum registro é excluído ou descontado automaticamente.</p></header><OmieAutoStatus compacto/>
 <div className="flex flex-wrap items-end gap-3"><label><span className="label">Empresa</span><select className="input" value={empresa} onChange={e=>setEmpresa(e.target.value)}><option value="">Todas</option>{dados?.o.empresas.map(e=><option key={e.id} value={e.id}>{e.nome}</option>)}</select></label><label><span className="label">Conferência</span><select className="input" value={motivo} onChange={e=>setMotivo(e.target.value)}><option value="">Todas</option>{[...new Set(pendencias.map(x=>x.motivo))].map(m=><option key={m}>{m}</option>)}</select></label><button className="btn-outline" disabled={loading} onClick={carregar}>{loading?'Conferindo…':'Conferir novamente'}</button></div>
 {erro&&<p role="alert" className="rounded-xl bg-red-50 p-4 text-red-700">{erro}</p>}
 {!loading&&dados&&<><p className="text-sm text-slate-600">Base consultada: {dados.r.length} recebimentos · {dados.d.length} despesas · {dados.n.length} notas. {visiveis.length} apontamentos no filtro. Esta conferência automatizada não substitui a conciliação documental.</p><div className="space-y-3">{visiveis.length===0?<p className="rounded-xl border bg-white p-5">Nenhum apontamento nestas verificações e filtros.</p>:visiveis.map(x=>{const r=x.registro;return <details key={x.id} className="rounded-xl border bg-white p-4"><summary className="cursor-pointer"><span className="font-semibold text-blue-900">{x.motivo}</span><span className="mt-1 block text-sm text-slate-600">{r.empresa?.nome} · {r.cliente||r.fornecedor||r.nome_destinatario||r.descricao||'Documento'}{r.numero_nf?` · NF ${r.numero_nf}`:''}</span></summary><dl className="mt-4 grid gap-3 text-sm sm:grid-cols-2"><div><dt className="text-slate-500">Origem e situação</dt><dd>{r.origem} · {r.status||r.status_fiscal||'Não informada'}</dd></div><div><dt className="text-slate-500">Valor do título / documento</dt><dd>{moeda(r.valor_previsto??r.valor_original??r.valor_total)}</dd></div><div><dt className="text-slate-500">Vencimento / pagamento</dt><dd>{r.data_vencimento||'Sem vencimento'} / {r.data_pagamento||'Sem data de pagamento'}</dd></div><div><dt className="text-slate-500">Pendente</dt><dd>{moeda(r.valor_pendente)}</dd></div><div className="sm:col-span-2"><dt className="text-slate-500">Identificador para conferência na origem</dt><dd className="break-all">{r.id_omie?`Omie: ${r.id_omie} · `:''}{r.id}</dd></div></dl></details>})}</div></>}
 </div>
}
