import {useEffect,useMemo,useState} from "react";
import {useNavigate,useParams} from "react-router-dom";
import {ArrowLeft,Pencil,Plus,Save} from "lucide-react";
import {PageTitle} from "../components/ui.jsx";
import {finCategoriaSalvar,finCentroSalvar,finConfigListar,finContaSalvar,finFormaSalvar} from "../services/financeiro.js";

const contaVazia=(empresaId="")=>({id:"",empresa_id:empresaId,nome:"",banco:"",agencia:"",conta:"",saldo_inicial:"0",ativa:true});
const tituloSecao={categorias:"Categorias",contas:"Contas bancárias",centros:"Centros de custo",formas:"Formas de pagamento"};
const descricaoSecao={categorias:"Classificação das receitas e despesas do Financeiro.",contas:"Contas usadas no extrato, conciliação, recebimentos e despesas.",centros:"Centros de custo utilizados na análise das despesas.",formas:"Formas disponíveis nos lançamentos e baixas financeiras."};

export default function ConfigCadastrosFinanceiro(){
 const navigate=useNavigate();const{secao}=useParams();const[dados,setDados]=useState({empresas:[],categorias:[],contas:[],centros:[],formas:[]});const[erro,setErro]=useState("");const[ok,setOk]=useState("");
 const[categoria,setCategoria]=useState({id:"",empresa_id:"",nome:"",tipo:"AMBOS"});const[conta,setConta]=useState(contaVazia());const[centro,setCentro]=useState({id:"",empresa_id:"",nome:""});const[forma,setForma]=useState({id:"",empresa_id:"",nome:""});
 async function carregar(){setErro("");try{const d=await finConfigListar();setDados(d||{empresas:[],categorias:[],contas:[],centros:[],formas:[]});const padrao=d?.empresas?.find(x=>x.usa_omie)?.id||d?.empresas?.[0]?.id||"";setConta(v=>({...v,empresa_id:v.empresa_id||padrao}));setCentro(v=>({...v,empresa_id:v.empresa_id||padrao}));setForma(v=>({...v,empresa_id:v.empresa_id||padrao}))}catch(e){setErro(e.message)}}
 useEffect(()=>{carregar()},[]);
 const empresas=useMemo(()=>new Map((dados.empresas||[]).map(x=>[x.id,x.nome])),[dados.empresas]);
 async function salvar(fn,obj,limpar){try{setErro("");setOk("");await fn(obj);setOk(obj.id?"Cadastro atualizado com sucesso.":"Cadastro salvo com sucesso.");limpar();await carregar()}catch(e){setErro(e.message)}}
 if(!tituloSecao[secao])return <div className="space-y-5"><PageTitle titulo="Configuração não encontrada" descricao="Escolha uma opção válida em Configurações Financeiras."/><button className="btn-outline" onClick={()=>navigate("/financas/configuracoes")}>Voltar</button></div>;
 return <div className="space-y-5"><div className="flex items-center gap-3"><button className="btn-ghost h-9 w-9 p-0" onClick={()=>navigate("/financas/configuracoes")}><ArrowLeft size={18}/></button><PageTitle titulo={tituloSecao[secao]} descricao={descricaoSecao[secao]}/></div>{erro&&<div className="rounded-xl bg-red-50 p-3 text-sm text-red-700">{erro}</div>}{ok&&<div className="rounded-xl bg-emerald-50 p-3 text-sm text-emerald-700">{ok}</div>}
 {secao==="categorias"&&<><section className="rounded-2xl border bg-white p-5"><div className="flex items-center justify-between"><h2 className="font-bold">{categoria.id?"Editar categoria":"Nova categoria"}</h2>{categoria.id&&<button className="btn-outline" onClick={()=>setCategoria({id:"",empresa_id:"",nome:"",tipo:"AMBOS"})}><Plus size={15}/>Nova</button>}</div><div className="mt-3 grid gap-3 md:grid-cols-3"><select className="input" value={categoria.empresa_id} onChange={e=>setCategoria({...categoria,empresa_id:e.target.value})}><option value="">Global</option>{dados.empresas.map(x=><option key={x.id} value={x.id}>{x.nome}</option>)}</select><input className="input" placeholder="Nome" value={categoria.nome} onChange={e=>setCategoria({...categoria,nome:e.target.value})}/><select className="input" value={categoria.tipo} onChange={e=>setCategoria({...categoria,tipo:e.target.value})}><option>AMBOS</option><option>RECEITA</option><option>DESPESA</option></select></div><button className="btn-primary mt-3" onClick={()=>salvar(finCategoriaSalvar,categoria,()=>setCategoria({id:"",empresa_id:"",nome:"",tipo:"AMBOS"}))}><Save size={15}/>Salvar categoria</button></section><Lista titulo="Categorias cadastradas" itens={dados.categorias} colunas={[x=>x.nome,x=>x.tipo||"AMBOS",x=>x.empresa_id?empresas.get(x.empresa_id)||"—":"Global"]} cabecalhos={["Nome","Tipo","Empresa"]} onEditar={x=>setCategoria({id:x.id,empresa_id:x.empresa_id||"",nome:x.nome||"",tipo:x.tipo||"AMBOS"})}/></>}
 {secao==="contas"&&<><section className="rounded-2xl border bg-white p-5"><div className="flex items-center justify-between"><h2 className="font-bold">{conta.id?"Editar conta bancária":"Nova conta bancária"}</h2>{conta.id&&<button className="btn-outline" onClick={()=>setConta(contaVazia(conta.empresa_id))}><Plus size={15}/>Nova</button>}</div><div className="mt-3 grid gap-3 md:grid-cols-3"><select className="input" value={conta.empresa_id} onChange={e=>setConta({...conta,empresa_id:e.target.value})}><option value="">Selecione a empresa</option>{dados.empresas.map(x=><option key={x.id} value={x.id}>{x.nome}</option>)}</select><input className="input" placeholder="Nome da conta" value={conta.nome} onChange={e=>setConta({...conta,nome:e.target.value})}/><input className="input" placeholder="Banco" value={conta.banco} onChange={e=>setConta({...conta,banco:e.target.value})}/><input className="input" placeholder="Agência" value={conta.agencia} onChange={e=>setConta({...conta,agencia:e.target.value})}/><input className="input" placeholder="Conta" value={conta.conta} onChange={e=>setConta({...conta,conta:e.target.value})}/><input className="input" type="number" step="0.01" placeholder="Saldo inicial" value={conta.saldo_inicial} onChange={e=>setConta({...conta,saldo_inicial:e.target.value})}/></div><label className="mt-3 inline-flex items-center gap-2 text-sm"><input type="checkbox" checked={conta.ativa!==false} onChange={e=>setConta({...conta,ativa:e.target.checked})}/>Conta ativa</label><div><button className="btn-primary mt-3" onClick={()=>salvar(finContaSalvar,{...conta,saldo_inicial:Number(conta.saldo_inicial||0)},()=>setConta(contaVazia(conta.empresa_id)))}><Save size={15}/>Salvar conta</button></div></section><Lista titulo="Contas bancárias cadastradas" itens={dados.contas} colunas={[x=>x.nome,x=>x.banco||"—",x=>`${x.agencia||"—"} / ${x.conta||"—"}`,x=>empresas.get(x.empresa_id)||"—",x=>x.ativa===false?"INATIVA":"ATIVA"]} cabecalhos={["Conta","Banco","Agência / Conta","Empresa","Status"]} onEditar={x=>setConta({id:x.id,empresa_id:x.empresa_id||"",nome:x.nome||"",banco:x.banco||"",agencia:x.agencia||"",conta:x.conta||"",saldo_inicial:String(x.saldo_inicial??0),ativa:x.ativa!==false})}/></>}
 {secao==="centros"&&<><section className="rounded-2xl border bg-white p-5"><div className="flex items-center justify-between"><h2 className="font-bold">{centro.id?"Editar centro de custo":"Novo centro de custo"}</h2>{centro.id&&<button className="btn-outline" onClick={()=>setCentro({id:"",empresa_id:centro.empresa_id,nome:""})}><Plus size={15}/>Novo</button>}</div><div className="mt-3 grid gap-3 md:grid-cols-2"><select className="input" value={centro.empresa_id} onChange={e=>setCentro({...centro,empresa_id:e.target.value})}><option value="">Selecione a empresa</option>{dados.empresas.map(x=><option key={x.id} value={x.id}>{x.nome}</option>)}</select><input className="input" placeholder="Nome" value={centro.nome} onChange={e=>setCentro({...centro,nome:e.target.value})}/></div><button className="btn-primary mt-3" onClick={()=>salvar(finCentroSalvar,centro,()=>setCentro({id:"",empresa_id:centro.empresa_id,nome:""}))}><Save size={15}/>Salvar centro</button></section><Lista titulo="Centros de custo cadastrados" itens={dados.centros} colunas={[x=>x.nome,x=>empresas.get(x.empresa_id)||"—"]} cabecalhos={["Nome","Empresa"]} onEditar={x=>setCentro({id:x.id,empresa_id:x.empresa_id||"",nome:x.nome||""})}/></>}
 {secao==="formas"&&<><section className="rounded-2xl border bg-white p-5"><div className="flex items-center justify-between"><h2 className="font-bold">{forma.id?"Editar forma de pagamento":"Nova forma de pagamento"}</h2>{forma.id&&<button className="btn-outline" onClick={()=>setForma({id:"",empresa_id:forma.empresa_id,nome:""})}><Plus size={15}/>Nova</button>}</div><div className="mt-3 grid gap-3 md:grid-cols-2"><select className="input" value={forma.empresa_id} onChange={e=>setForma({...forma,empresa_id:e.target.value})}><option value="">Global</option>{dados.empresas.map(x=><option key={x.id} value={x.id}>{x.nome}</option>)}</select><input className="input" placeholder="Nome" value={forma.nome} onChange={e=>setForma({...forma,nome:e.target.value})}/></div><button className="btn-primary mt-3" onClick={()=>salvar(finFormaSalvar,forma,()=>setForma({id:"",empresa_id:forma.empresa_id,nome:""}))}><Save size={15}/>Salvar forma</button></section><Lista titulo="Formas de pagamento cadastradas" itens={dados.formas} colunas={[x=>x.nome,x=>x.empresa_id?empresas.get(x.empresa_id)||"—":"Global"]} cabecalhos={["Nome","Empresa"]} onEditar={x=>setForma({id:x.id,empresa_id:x.empresa_id||"",nome:x.nome||""})}/></>}
 </div>
}

function Lista({titulo,itens=[],cabecalhos,colunas,onEditar}){return <section className="rounded-2xl border bg-white p-5"><h2 className="font-bold">{titulo}</h2><div className="mt-3 overflow-x-auto"><table className="min-w-full text-sm"><thead><tr className="text-left text-xs uppercase text-slate-500">{cabecalhos.map(x=><th key={x} className="py-2 pr-4">{x}</th>)}<th/></tr></thead><tbody>{itens.length===0?<tr><td colSpan={cabecalhos.length+1} className="py-8 text-center text-slate-500">Nenhum cadastro encontrado.</td></tr>:itens.map(x=><tr key={x.id} className="border-t">{colunas.map((fn,i)=><td key={i} className="py-3 pr-4">{fn(x)}</td>)}<td className="py-2 text-right"><button className="btn-ghost h-8 px-2" onClick={()=>onEditar(x)}><Pencil size={14}/>Editar</button></td></tr>)}</tbody></table></div></section>}
