import { useEffect, useState } from "react";
import { ArrowLeft, RefreshCw, Save, CloudDownload, CheckCircle2, AlertTriangle } from "lucide-react";
import { useNavigate } from "react-router-dom";
import { PageTitle } from "../components/ui.jsx";
import { finConfigListar, finCategoriaSalvar, finContaSalvar, finCentroSalvar, finFormaSalvar, finOmieEstado, finOmieSincronizarPagina } from "../services/financeiro.js";

const hoje = () => new Date().toISOString().slice(0,10);
const inicioAno = () => `${new Date().getFullYear()}-01-01`;

export default function ConfigFinanceiro(){
 const navigate=useNavigate();const[dados,setDados]=useState({empresas:[],categorias:[],contas:[],centros:[],formas:[]});const[omie,setOmie]=useState({ligado:false});const[erro,setErro]=useState("");const[ok,setOk]=useState("");const[sincronizando,setSincronizando]=useState(false);const[progresso,setProgresso]=useState("");const[periodo,setPeriodo]=useState({de:inicioAno(),ate:hoje()});
 const[categoria,setCategoria]=useState({empresa_id:"",nome:"",tipo:"AMBOS"});const[conta,setConta]=useState({empresa_id:"",nome:"",banco:"",agencia:"",conta:"",saldo_inicial:"0"});const[centro,setCentro]=useState({empresa_id:"",nome:""});const[forma,setForma]=useState({empresa_id:"",nome:""});
 async function carregar(){setErro("");try{const[d,o]=await Promise.all([finConfigListar(),finOmieEstado()]);setDados(d);setOmie(o);const minas=d.empresas?.find(x=>x.usa_omie);if(minas){setCategoria(v=>({...v,empresa_id:v.empresa_id||minas.id}));setConta(v=>({...v,empresa_id:v.empresa_id||minas.id}));setCentro(v=>({...v,empresa_id:v.empresa_id||minas.id}));}}catch(e){setErro(e.message)}}
 useEffect(()=>{carregar()},[]);
 async function salvar(fn,obj,limpar){try{setErro("");await fn(obj);setOk("Cadastro salvo.");limpar();await carregar()}catch(e){setErro(e.message)}}
 async function sincronizar(){if(!omie.ligado){setErro("A integração Omie não está configurada nos Secrets do Supabase.");return}setSincronizando(true);setErro("");setOk("");try{for(const tipo of ["RECEBER","PAGAR"]){let p=1;for(;;){setProgresso(`${tipo === "RECEBER" ? "Contas a receber" : "Contas a pagar"} · página ${p}`);const r=await finOmieSincronizarPagina(tipo,periodo.de,periodo.ate,p);if(!r.proxima)break;p=r.proxima;if(p>5000)throw new Error("A sincronização excedeu o limite de segurança de páginas.");}}setOk("Sincronização Omie concluída. Recebimentos e despesas da MinasLab foram atualizados sem alterar lançamentos manuais.");setProgresso("");}catch(e){setErro(e.message)}finally{setSincronizando(false)}}
 return <div className="space-y-5"><div className="flex items-center gap-3"><button className="btn-ghost h-9 w-9 p-0" onClick={()=>navigate("/financas")}><ArrowLeft size={18}/></button><PageTitle titulo="Configurações Financeiras" descricao="Empresas, categorias, contas, centros de custo e integração Omie."/></div>
 {erro&&<div className="rounded-xl bg-red-50 p-3 text-sm text-red-700">{erro}</div>}{ok&&<div className="rounded-xl bg-emerald-50 p-3 text-sm text-emerald-700">{ok}</div>}
 <section className="rounded-2xl border bg-white p-5"><div className="flex flex-col gap-4 md:flex-row md:items-center md:justify-between"><div><div className="flex items-center gap-2"><h2 className="font-bold text-slate-900">Integração Omie — MinasLab</h2>{omie.ligado?<span className="inline-flex items-center gap-1 rounded-full bg-emerald-50 px-2 py-1 text-xs font-semibold text-emerald-700"><CheckCircle2 size={13}/>Configurada</span>:<span className="inline-flex items-center gap-1 rounded-full bg-amber-50 px-2 py-1 text-xs font-semibold text-amber-700"><AlertTriangle size={13}/>Não configurada</span>}</div><p className="mt-1 text-sm text-slate-500">Regra fixa: MinasLab = Omie + manual. M Lab = somente manual. A sincronização usa o ID do título Omie e nunca sobrescreve lançamento manual.</p></div><button className="btn-outline" onClick={carregar}><RefreshCw size={15}/>Verificar</button></div>
 <div className="mt-4 grid gap-3 md:grid-cols-4"><label><span className="label">De</span><input className="input" type="date" value={periodo.de} onChange={e=>setPeriodo({...periodo,de:e.target.value})}/></label><label><span className="label">Até</span><input className="input" type="date" value={periodo.ate} onChange={e=>setPeriodo({...periodo,ate:e.target.value})}/></label><div className="md:col-span-2 flex items-end"><button className="btn-primary w-full" disabled={sincronizando||!omie.ligado} onClick={sincronizar}><CloudDownload size={16}/>{sincronizando?(progresso||"Sincronizando..."):"Sincronizar Omie"}</button></div></div></section>

 <div className="grid gap-5 xl:grid-cols-2">
 <section className="rounded-2xl border bg-white p-5"><h2 className="font-bold">Categorias</h2><div className="mt-3 grid gap-3 md:grid-cols-3"><select className="input" value={categoria.empresa_id} onChange={e=>setCategoria({...categoria,empresa_id:e.target.value})}><option value="">Global</option>{dados.empresas.map(x=><option key={x.id} value={x.id}>{x.nome}</option>)}</select><input className="input" placeholder="Nome" value={categoria.nome} onChange={e=>setCategoria({...categoria,nome:e.target.value})}/><select className="input" value={categoria.tipo} onChange={e=>setCategoria({...categoria,tipo:e.target.value})}><option>AMBOS</option><option>RECEITA</option><option>DESPESA</option></select></div><button className="btn-primary mt-3" onClick={()=>salvar(finCategoriaSalvar,categoria,()=>setCategoria({...categoria,nome:""}))}><Save size={15}/>Salvar categoria</button><div className="mt-4 flex flex-wrap gap-2">{dados.categorias.map(x=><span key={x.id} className="rounded-full bg-slate-100 px-2.5 py-1 text-xs">{x.nome} · {x.tipo}</span>)}</div></section>
 <section className="rounded-2xl border bg-white p-5"><h2 className="font-bold">Contas bancárias</h2><div className="mt-3 grid gap-3 md:grid-cols-2"><select className="input" value={conta.empresa_id} onChange={e=>setConta({...conta,empresa_id:e.target.value})}>{dados.empresas.map(x=><option key={x.id} value={x.id}>{x.nome}</option>)}</select><input className="input" placeholder="Nome da conta" value={conta.nome} onChange={e=>setConta({...conta,nome:e.target.value})}/><input className="input" placeholder="Banco" value={conta.banco} onChange={e=>setConta({...conta,banco:e.target.value})}/><input className="input" placeholder="Agência" value={conta.agencia} onChange={e=>setConta({...conta,agencia:e.target.value})}/><input className="input" placeholder="Conta" value={conta.conta} onChange={e=>setConta({...conta,conta:e.target.value})}/><input className="input" type="number" step="0.01" placeholder="Saldo inicial" value={conta.saldo_inicial} onChange={e=>setConta({...conta,saldo_inicial:e.target.value})}/></div><button className="btn-primary mt-3" onClick={()=>salvar(finContaSalvar,conta,()=>setConta({...conta,nome:"",banco:"",agencia:"",conta:"",saldo_inicial:"0"}))}><Save size={15}/>Salvar conta</button><div className="mt-4 space-y-2">{dados.contas.map(x=><div key={x.id} className="rounded-xl bg-slate-50 p-2 text-sm"><b>{x.nome}</b> · {x.banco||"Banco não informado"}</div>)}</div></section>
 <section className="rounded-2xl border bg-white p-5"><h2 className="font-bold">Centros de custo</h2><div className="mt-3 flex gap-2"><select className="input" value={centro.empresa_id} onChange={e=>setCentro({...centro,empresa_id:e.target.value})}>{dados.empresas.map(x=><option key={x.id} value={x.id}>{x.nome}</option>)}</select><input className="input" placeholder="Centro de custo" value={centro.nome} onChange={e=>setCentro({...centro,nome:e.target.value})}/></div><button className="btn-primary mt-3" onClick={()=>salvar(finCentroSalvar,centro,()=>setCentro({...centro,nome:""}))}><Save size={15}/>Salvar centro</button><div className="mt-4 flex flex-wrap gap-2">{dados.centros.map(x=><span key={x.id} className="rounded-full bg-slate-100 px-2.5 py-1 text-xs">{x.nome}</span>)}</div></section>
 <section className="rounded-2xl border bg-white p-5"><h2 className="font-bold">Formas de pagamento</h2><div className="mt-3 flex gap-2"><select className="input" value={forma.empresa_id} onChange={e=>setForma({...forma,empresa_id:e.target.value})}><option value="">Global</option>{dados.empresas.map(x=><option key={x.id} value={x.id}>{x.nome}</option>)}</select><input className="input" placeholder="Forma" value={forma.nome} onChange={e=>setForma({...forma,nome:e.target.value})}/></div><button className="btn-primary mt-3" onClick={()=>salvar(finFormaSalvar,forma,()=>setForma({...forma,nome:""}))}><Save size={15}/>Salvar forma</button><div className="mt-4 flex flex-wrap gap-2">{dados.formas.map(x=><span key={x.id} className="rounded-full bg-slate-100 px-2.5 py-1 text-xs">{x.nome}</span>)}</div></section>
 </div></div>
}
