import { useEffect, useMemo, useState } from "react";
import { ArrowLeft, BriefcaseBusiness, CheckCircle2, FilePlus2, Save, Search, ShieldCheck, UserPlus, X, XCircle } from "lucide-react";
import { useNavigate } from "react-router-dom";
import { PageTitle } from "../components/ui.jsx";
import { finClientesListar, finNfseEmitir, finNfseEmitirProducao, finNfseEstado, finNfseListar, finNfsePreparar, finNfseRascunhoSalvar, finNfseVerificarCertificado } from "../services/financeiro.js";

const hoje=()=>new Date().toLocaleDateString("en-CA",{timeZone:"America/Sao_Paulo"});
const vazio=()=>({id:"",cliente_id:"",data_emissao:hoje(),data_vencimento:"",quantidade:"1",valor_unitario:"",desconto_percentual:"0",valor_total:"",codigo_servico:"170202",nbs:"118064000",servico_descricao:"",aliquota_iss:"",aliquota_simples_nacional:"2.01",iss_retido:false,regime_especial:"",forma_pagamento:"BOLETO",observacao:"",cliente:null});
const clienteNovo=()=>({nome:"",nome_fantasia:"",cnpj_cpf:"",inscricao_estadual:"",inscricao_municipal:"",email:"",telefone:"",cep:"",logradouro:"",numero:"",complemento:"",bairro:"",cidade:"",uf:"MG"});
const moeda=v=>Number(v||0).toLocaleString("pt-BR",{style:"currency",currency:"BRL"});
const dataBR=v=>{const p=String(v||"").slice(0,10).split("-");return p.length===3?`${p[2]}/${p[1]}/${p[0]}`:"—"};
const dataHoraBR=v=>v?new Date(v).toLocaleString("pt-BR"):"—";
const abas=[["servico","Serviço"],["financeiro","Financeiro"],["fiscal","Tributação"],["email","E-mail ao Cliente"],["observacoes","Observações"]];
const servicosPadrao=[{id:"mlab-170202",codigo:"170202",nbs:"118064000",nome:"Expediente, secretaria e apoio administrativo",detalhe:"Código nacional 17.02.02 · NBS 1.1806.40.00",perfil:"Perfil fiscal homologado da M Lab"}];

function calcularItem(f){
  const quantidade=Math.max(0,Number(f.quantidade||0));
  const valorUnitario=Math.max(0,Number(f.valor_unitario||0));
  const desconto=Math.min(100,Math.max(0,Number(f.desconto_percentual||0)));
  const subtotal=quantidade*valorUnitario;
  const valorDesconto=subtotal*desconto/100;
  const total=Math.max(0,subtotal-valorDesconto);
  return {quantidade,valorUnitario,desconto,subtotal,valorDesconto,total};
}

export default function EmitirNfse(){
  const navigate=useNavigate();
  const [estado,setEstado]=useState(null);
  const [clientes,setClientes]=useState([]);
  const [rascunhos,setRascunhos]=useState([]);
  const [form,setForm]=useState(vazio());
  const [novoCliente,setNovoCliente]=useState(false);
  const [cliente,setCliente]=useState(clienteNovo());
  const [busca,setBusca]=useState("");
  const [buscaServico,setBuscaServico]=useState("");
  const [clienteModal,setClienteModal]=useState(false);
  const [servicoModal,setServicoModal]=useState(false);
  const [erro,setErro]=useState("");
  const [ok,setOk]=useState("");
  const [carregando,setCarregando]=useState(true);
  const [salvando,setSalvando]=useState(false);
  const [emitindo,setEmitindo]=useState(false);
  const [verificando,setVerificando]=useState(false);
  const [verificacao,setVerificacao]=useState(null);
  const [preparacao,setPreparacao]=useState(null);
  const [aba,setAba]=useState("servico");

  async function carregar(){setCarregando(true);setErro("");try{const [e,c,r]=await Promise.all([finNfseEstado(),finClientesListar(""),finNfseListar()]);setEstado(e);setClientes(c);setRascunhos(r)}catch(ex){setErro(ex.message)}finally{setCarregando(false)}}
  useEffect(()=>{carregar()},[]);

  const item=useMemo(()=>calcularItem(form),[form.quantidade,form.valor_unitario,form.desconto_percentual]);
  const clientesFiltrados=useMemo(()=>{const q=busca.trim().toLowerCase();if(!q)return clientes.slice(0,120);return clientes.filter(x=>`${x.nome||""} ${x.nome_fantasia||""} ${x.cnpj_cpf||""} ${x.email||""}`.toLowerCase().includes(q)).slice(0,120)},[clientes,busca]);
  const servicosFiltrados=useMemo(()=>{const q=buscaServico.trim().toLowerCase();if(!q)return servicosPadrao;return servicosPadrao.filter(x=>`${x.codigo} ${x.nbs} ${x.nome}`.toLowerCase().includes(q))},[buscaServico]);
  const selecionado=clientes.find(x=>x.id===form.cliente_id)||null;
  const clienteEmUso=novoCliente?cliente:selecionado;
  const producao=estado?.ambiente==="PRODUCAO";
  const producaoLiberada=producao&&estado?.producaoLiberada&&estado?.transmissaoAtiva;

  function atualizarItem(campo,valor){setForm(v=>{const prox={...v,[campo]:valor};const c=calcularItem(prox);return {...prox,valor_total:c.total?c.total.toFixed(2):""}});setPreparacao(null)}
  function limpar(){setForm(vazio());setNovoCliente(false);setCliente(clienteNovo());setPreparacao(null);setAba("servico");setOk("");setErro("")}
  function registro(){const c=calcularItem(form);return {...form,cliente_id:novoCliente?"":form.cliente_id,cliente:novoCliente?cliente:null,quantidade:c.quantidade,valor_unitario:c.valorUnitario,desconto_percentual:c.desconto,valor_total:c.total,aliquota_simples_nacional:Number(form.aliquota_simples_nacional||2.01)}}
  function escolherCliente(x){setForm(v=>({...v,cliente_id:x.id}));setNovoCliente(false);setCliente(clienteNovo());setPreparacao(null);setClienteModal(false);setBusca("")}
  function abrirNovoCliente(){setNovoCliente(true);setForm(v=>({...v,cliente_id:""}));setClienteModal(false);setPreparacao(null)}
  function escolherServico(x){setForm(v=>({...v,codigo_servico:x.codigo,nbs:x.nbs,servico_descricao:v.servico_descricao||x.nome}));setPreparacao(null);setServicoModal(false);setBuscaServico("")}
  async function verificarA1(){setVerificando(true);setErro("");setOk("");try{const r=await finNfseVerificarCertificado();setVerificacao(r);setEstado(x=>({...x,...r}));setOk("Certificado A1 aberto com sucesso. Arquivo, senha e validade foram conferidos no servidor.")}catch(ex){setVerificacao(null);setErro(ex.message)}finally{setVerificando(false)}}
  async function preparar(){setErro("");setOk("");try{const r=await finNfsePreparar(registro());setPreparacao(r);setOk("Pré-validação concluída. Nenhuma nota foi emitida.")}catch(ex){setPreparacao(null);setErro(ex.message)}}
  async function salvar(){setSalvando(true);setErro("");setOk("");try{const r=await finNfseRascunhoSalvar(registro());setForm(v=>({...v,id:r.item.id,cliente_id:r.cliente.id,cliente:null,valor_total:String(r.item.valor_total??v.valor_total)}));setNovoCliente(false);setCliente(clienteNovo());setOk("Rascunho salvo. O cliente foi vinculado ao cadastro central da M Lab.");await carregar()}catch(ex){setErro(ex.message)}finally{setSalvando(false)}}
  async function emitir(){if(!form.id){setErro("Salve o rascunho antes de emitir.");return}if(producao&&!producaoLiberada){setErro("A produção continua bloqueada. As travas de liberação e transmissão ainda não estão ativas.");return}const texto=producao?`ATENÇÃO: esta ação emitirá uma NFS-e REAL em PRODUÇÃO no valor de ${moeda(item.total)} para ${clienteEmUso?.nome||"o cliente selecionado"}. Deseja continuar?`:`Transmitir esta NFS-e em HOMOLOGAÇÃO? Nenhum recebimento real será criado.`;if(!confirm(texto))return;setEmitindo(true);setErro("");setOk("");try{const r=producao?await finNfseEmitirProducao(form.id):await finNfseEmitir(form.id);setOk(r.mensagem||(producao?"NFS-e de produção processada.":"NFS-e transmitida em homologação."));await carregar()}catch(ex){setErro(ex.message)}finally{setEmitindo(false)}}
  function editar(x){const d=x.nfse_dados||{},s=d.servico||{};const qtd=String(s.quantidade??1),vu=String(s.valorUnitario??x.valor_total??""),desc=String(s.descontoPercentual??0);setForm({id:x.id,cliente_id:x.cliente_id||"",data_emissao:x.data_emissao||hoje(),data_vencimento:x.data_vencimento||"",quantidade:qtd,valor_unitario:vu,desconto_percentual:desc,valor_total:String(x.valor_total??""),codigo_servico:s.codigo||"170202",nbs:s.nbs||"118064000",servico_descricao:s.descricao||"",aliquota_iss:d.tributacao?.aliquotaIss??"",aliquota_simples_nacional:String(d.tributacao?.aliquotaSimplesNacional??"2.01"),iss_retido:!!d.tributacao?.issRetido,regime_especial:d.tributacao?.regimeEspecial||"",forma_pagamento:d.financeiro?.formaPagamento||"BOLETO",observacao:x.observacao||"",cliente:null});setNovoCliente(false);setCliente(clienteNovo());setPreparacao(null);setAba("servico");window.scrollTo({top:0,behavior:"smooth"})}

  return <div className="space-y-5">
    <div className="flex items-center gap-3"><button className="btn-ghost h-9 w-9 p-0" onClick={()=>navigate("/financas/notas-fiscais")}><ArrowLeft size={18}/></button><PageTitle titulo="Nota Fiscal de Serviço — M Lab" descricao="Emissão pelo padrão nacional com fluxo visual simplificado, inspirado na organização do Omie."/></div>

    <div className={`rounded-2xl border p-4 ${estado?.configurado?"border-emerald-200 bg-emerald-50":"border-amber-200 bg-amber-50"}`}><div className="flex flex-col gap-3 lg:flex-row lg:items-center lg:justify-between"><div><div className="flex items-center gap-2 font-semibold">{estado?.configurado?<CheckCircle2 size={18}/>:<XCircle size={18}/>}NFS-e Nacional · {estado?.ambiente||"HOMOLOGACAO"}</div><p className="mt-1 text-sm">Emitente: <b>{estado?.empresa?.nome||"M Lab"}</b> · CNPJ {estado?.empresa?.cnpj||"—"}</p></div><div className="flex items-center gap-2"><span className={`rounded-full px-3 py-1 text-xs font-semibold ${producaoLiberada?"bg-red-100 text-red-700":"bg-white text-slate-600"}`}>{producaoLiberada?"PRODUÇÃO LIBERADA":"Produção protegida"}</span><button type="button" className="btn-outline h-9 px-3 text-xs" disabled={verificando} onClick={verificarA1}>{verificando?"Verificando...":"Verificar A1"}</button></div></div>{verificacao?.certificado?.valido&&<div className="mt-3 rounded-xl border border-emerald-200 bg-white/80 p-3 text-xs text-slate-700"><b>A1 válido.</b> {verificacao.certificado.titular||""} · validade até {dataHoraBR(verificacao.certificado.validoAte)}</div>}</div>

    {erro&&<div className="rounded-xl bg-red-50 p-3 text-sm text-red-700">{erro}</div>}
    {ok&&<div className="rounded-xl bg-emerald-50 p-3 text-sm text-emerald-700">{ok}</div>}

    <section className="overflow-hidden rounded-2xl border bg-white shadow-sm">
      <div className="flex items-center justify-between border-b px-5 py-4"><div><h2 className="text-lg font-bold text-slate-800">{form.id?"Editar Nota Fiscal de Serviço":"Nova Nota Fiscal de Serviço"}</h2><p className="text-xs text-slate-500">Cliente, financeiro e serviço organizados no mesmo fluxo visual da OS do Omie.</p></div>{form.id&&<button className="btn-outline" onClick={limpar}><FilePlus2 size={15}/>Nova</button>}</div>

      <div className="grid xl:grid-cols-[1fr_220px]">
        <div className="min-w-0 border-r">
          <div className="grid gap-3 bg-slate-50 p-4 lg:grid-cols-[1.5fr_.72fr_.72fr_.72fr_1fr]">
            <div><div className="mb-1 flex items-center justify-between"><span className="text-xs font-semibold text-slate-600">Cliente</span><button type="button" className="text-xs font-semibold text-teal-700" onClick={abrirNovoCliente}>+ Novo cliente</button></div>{!novoCliente?<button type="button" onClick={()=>setClienteModal(true)} className="flex h-[42px] w-full items-center gap-2 rounded-lg border border-slate-300 bg-white px-3 text-left text-sm hover:border-teal-400"><Search size={15} className="shrink-0 text-slate-400"/><span className={`min-w-0 flex-1 truncate ${selecionado?"font-medium text-slate-800":"text-slate-400"}`}>{selecionado?selecionado.nome:"Pesquisar e selecionar cliente"}</span><span className="text-lg font-light text-teal-700">+</span></button>:<div className="flex h-[42px] items-center justify-between rounded-lg border border-teal-200 bg-teal-50 px-3 text-xs text-teal-800"><span><UserPlus size={14} className="mr-1 inline"/>Novo cliente</span><button type="button" className="font-semibold" onClick={()=>setNovoCliente(false)}>Usar cadastrado</button></div>}</div>
            <label><span className="text-xs font-semibold text-slate-600">Emissão</span><input className="input mt-1" type="date" value={form.data_emissao} onChange={e=>setForm({...form,data_emissao:e.target.value})}/></label>
            <label><span className="text-xs font-semibold text-slate-600">Vencimento</span><input className="input mt-1" type="date" value={form.data_vencimento} onChange={e=>setForm({...form,data_vencimento:e.target.value})}/></label>
            <label><span className="text-xs font-semibold text-slate-600">Pagamento</span><select className="input mt-1" value={form.forma_pagamento} onChange={e=>setForm({...form,forma_pagamento:e.target.value})}><option>BOLETO</option><option>PIX</option><option>TRANSFERENCIA</option><option>OUTRO</option></select></label>
            <div className="rounded-xl border bg-white p-3 text-xs"><div className="flex justify-between text-slate-500"><span>Serviços</span><span>{moeda(item.subtotal)}</span></div><div className="mt-1 flex justify-between text-slate-500"><span>Descontos</span><span>- {moeda(item.valorDesconto)}</span></div><div className="mt-1 flex justify-between text-slate-400"><span>Reembolsáveis</span><span>{moeda(0)}</span></div><div className="mt-2 flex justify-between border-t pt-2 font-bold text-slate-800"><span>Valor Total</span><span>{moeda(item.total)}</span></div></div>
          </div>

          {selecionado&&!novoCliente&&<div className="border-t bg-white px-4 py-2 text-xs text-slate-500"><b className="text-slate-700">{selecionado.nome}</b> · {selecionado.cnpj_cpf||"—"}{selecionado.email&&<> · {selecionado.email}</>}</div>}
          {novoCliente&&<div className="border-t bg-white p-4"><div className="mb-3 text-sm font-bold">Dados do novo cliente</div><div className="grid gap-3 md:grid-cols-3"><input className="input" placeholder="Razão social / Nome *" value={cliente.nome} onChange={e=>setCliente({...cliente,nome:e.target.value})}/><input className="input" placeholder="Nome fantasia" value={cliente.nome_fantasia} onChange={e=>setCliente({...cliente,nome_fantasia:e.target.value})}/><input className="input" placeholder="CPF/CNPJ *" value={cliente.cnpj_cpf} onChange={e=>setCliente({...cliente,cnpj_cpf:e.target.value})}/><input className="input" type="email" placeholder="E-mail fiscal" value={cliente.email} onChange={e=>setCliente({...cliente,email:e.target.value})}/><input className="input" placeholder="Telefone" value={cliente.telefone} onChange={e=>setCliente({...cliente,telefone:e.target.value})}/><input className="input" placeholder="CEP" value={cliente.cep} onChange={e=>setCliente({...cliente,cep:e.target.value})}/><input className="input md:col-span-2" placeholder="Logradouro" value={cliente.logradouro} onChange={e=>setCliente({...cliente,logradouro:e.target.value})}/><input className="input" placeholder="Número" value={cliente.numero} onChange={e=>setCliente({...cliente,numero:e.target.value})}/><input className="input" placeholder="Bairro" value={cliente.bairro} onChange={e=>setCliente({...cliente,bairro:e.target.value})}/><input className="input" placeholder="Cidade" value={cliente.cidade} onChange={e=>setCliente({...cliente,cidade:e.target.value})}/><input className="input" maxLength={2} placeholder="UF" value={cliente.uf} onChange={e=>setCliente({...cliente,uf:e.target.value.toUpperCase()})}/></div></div>}

          <div className="flex gap-1 overflow-x-auto border-y bg-white px-4 pt-2">{abas.map(([id,nome])=><button key={id} type="button" onClick={()=>setAba(id)} className={`whitespace-nowrap rounded-t-lg border-b-2 px-4 py-2 text-xs font-semibold ${aba===id?"border-teal-600 bg-teal-50 text-teal-700":"border-transparent text-slate-500 hover:text-slate-800"}`}>{nome}</button>)}</div>

          <div className="min-h-[330px] p-5">
            {aba==="servico"&&<div><div className="mb-4 flex flex-wrap items-center justify-between gap-2"><div><h3 className="font-bold">Serviço</h3><p className="text-xs text-slate-500">Linha de serviço com cálculo automático do item.</p></div><button type="button" className="btn-outline h-9 px-3 text-xs" onClick={()=>setServicoModal(true)}><BriefcaseBusiness size={14}/>Selecionar serviço já cadastrado</button></div><div className="grid gap-4 md:grid-cols-2 lg:grid-cols-6"><label><span className="label">Tipo de Tributação</span><input className="input" value="Operação Tributável" readOnly/></label><label><span className="label">Código do Serviço</span><div className="flex gap-2"><input className="input" value={form.codigo_servico} onChange={e=>setForm({...form,codigo_servico:e.target.value})}/><button type="button" className="btn-outline px-3" onClick={()=>setServicoModal(true)}><Search size={15}/></button></div></label><label><span className="label">NBS</span><input className="input" value={form.nbs} onChange={e=>setForm({...form,nbs:e.target.value})}/></label><label><span className="label">Quantidade</span><input className="input" type="number" min="0.01" step="0.01" value={form.quantidade} onChange={e=>atualizarItem("quantidade",e.target.value)}/></label><label><span className="label">Valor Unitário</span><input className="input" type="number" min="0" step="0.01" value={form.valor_unitario} onChange={e=>atualizarItem("valor_unitario",e.target.value)}/></label><label><span className="label">% Desconto</span><input className="input" type="number" min="0" max="100" step="0.01" value={form.desconto_percentual} onChange={e=>atualizarItem("desconto_percentual",e.target.value)}/></label><label><span className="label">Valor do Desconto</span><input className="input" value={moeda(item.valorDesconto)} readOnly/></label><label><span className="label">Valor Total do Item</span><input className="input font-semibold" value={moeda(item.total)} readOnly/></label><label><span className="label">Alíquota ISS (%)</span><input className="input" type="number" min="0" step="0.01" value={form.aliquota_iss} onChange={e=>setForm({...form,aliquota_iss:e.target.value})}/></label><label className="flex items-end gap-2 pb-3"><input type="checkbox" checked={form.iss_retido} onChange={e=>setForm({...form,iss_retido:e.target.checked})}/> ISS retido</label><label className="md:col-span-2"><span className="label">Município da prestação</span><input className="input" value="Montes Claros/MG" readOnly/></label><label className="md:col-span-2 lg:col-span-6"><span className="label">Descrição Detalhada do Serviço</span><textarea className="input min-h-28" value={form.servico_descricao} onChange={e=>setForm({...form,servico_descricao:e.target.value})} placeholder="Ex.: SERVIÇOS PRESTADOS PELA M LAB: Contrato: ... | OS: ..."/></label></div></div>}
            {aba==="financeiro"&&<div className="grid gap-4 md:grid-cols-3"><label><span className="label">Data de emissão</span><input className="input" type="date" value={form.data_emissao} onChange={e=>setForm({...form,data_emissao:e.target.value})}/></label><label><span className="label">Vencimento do recebimento</span><input className="input" type="date" value={form.data_vencimento} onChange={e=>setForm({...form,data_vencimento:e.target.value})}/></label><label><span className="label">Forma de pagamento</span><select className="input" value={form.forma_pagamento} onChange={e=>setForm({...form,forma_pagamento:e.target.value})}><option>BOLETO</option><option>PIX</option><option>TRANSFERENCIA</option><option>OUTRO</option></select></label><div className="md:col-span-3 grid gap-3 sm:grid-cols-3"><div className="rounded-xl border bg-slate-50 p-4"><div className="text-xs text-slate-500">Subtotal</div><b>{moeda(item.subtotal)}</b></div><div className="rounded-xl border bg-slate-50 p-4"><div className="text-xs text-slate-500">Desconto</div><b>{moeda(item.valorDesconto)}</b></div><div className="rounded-xl border bg-teal-50 p-4"><div className="text-xs text-teal-700">A receber após emissão</div><b className="text-teal-800">{moeda(item.total)}</b></div></div><div className="md:col-span-3 rounded-xl border bg-slate-50 p-4 text-sm text-slate-600">O Recebimento será criado automaticamente somente depois de uma NFS-e autorizada em produção.</div></div>}
            {aba==="fiscal"&&<div className="grid gap-4 md:grid-cols-2 lg:grid-cols-4"><label><span className="label">PIS/COFINS</span><input className="input" value="00 - Nenhum" readOnly/></label><label><span className="label">Retenção PIS/COFINS/CSLL</span><input className="input" value="0 - Não retidos" readOnly/></label><label><span className="label">CST IBS/CBS</span><input className="input" value="000 - Tributação integral" readOnly/></label><label><span className="label">Classificação IBS/CBS</span><input className="input" value="000001" readOnly/></label><label><span className="label">Indicador da operação</span><input className="input" value="100301" readOnly/></label><label><span className="label">Alíquota Simples Nacional</span><input className="input" value={`${form.aliquota_simples_nacional}%`} readOnly/></label><div className="md:col-span-2 rounded-xl border border-teal-100 bg-teal-50 p-3 text-xs text-teal-800">Perfil fiscal homologado da M Lab para o serviço 170202 / NBS 118064000.</div></div>}
            {aba==="email"&&<div><h3 className="font-bold">E-mail ao Cliente</h3><p className="mt-2 text-sm text-slate-600">Destinatário fiscal: <b>{clienteEmUso?.email||"não informado"}</b></p><div className="mt-4 rounded-xl border bg-slate-50 p-4 text-sm text-slate-600">O envio será feito somente depois da autorização e do salvamento do XML/PDF. O rascunho não envia e-mail.</div></div>}
            {aba==="observacoes"&&<label className="block"><span className="label">Observações da NFS-e</span><textarea className="input min-h-44" value={form.observacao} onChange={e=>setForm({...form,observacao:e.target.value})} placeholder="Informações complementares da nota"/></label>}
            {preparacao&&<div className="mt-5 rounded-xl border border-sky-200 bg-sky-50 p-3 text-sm text-sky-800"><b>Pré-validação OK.</b> Cliente: {preparacao.cliente?.nome}. Valor: {moeda(item.total)}. Ambiente: {preparacao.ambiente}.</div>}
          </div>
        </div>

        <aside className="flex flex-col bg-slate-50 p-4"><div className="space-y-2"><button className="btn-outline w-full justify-start" disabled={salvando} onClick={salvar}><Save size={16}/>{salvando?"Salvando...":"Salvar rascunho"}</button><button className="btn-outline w-full justify-start" onClick={preparar}><ShieldCheck size={16}/>Pré-validar</button></div><div className="mt-4 rounded-xl border bg-white p-3 text-xs text-slate-600"><div className="font-semibold text-slate-800">Valor da nota</div><div className="mt-1 text-lg font-bold text-slate-800">{moeda(item.total)}</div><div className="mt-3 font-semibold text-slate-800">Ambiente atual</div><div className="mt-1">{estado?.ambiente||"—"}</div><div className="mt-3 font-semibold text-slate-800">Status de produção</div><div className="mt-1">{producaoLiberada?"Liberada pelas duas travas":"Bloqueada"}</div></div><div className="mt-auto pt-6"><button className={`w-full rounded-xl px-4 py-3 text-sm font-bold text-white ${producao?"bg-red-600 hover:bg-red-700":"bg-teal-600 hover:bg-teal-700"} disabled:cursor-not-allowed disabled:opacity-40`} disabled={emitindo||!form.id||(producao&&!producaoLiberada)} onClick={emitir}><FilePlus2 size={16} className="mr-2 inline"/>{emitindo?"Transmitindo...":producao?"Emitir NFS-e REAL":"Emitir em homologação"}</button><p className="mt-2 text-center text-[11px] text-slate-500">{producao?"A emissão real exige as duas travas de produção ativas.":"Homologação não cria recebimento real."}</p></div></aside>
      </div>
    </section>

    <section className="rounded-2xl border bg-white p-5"><h2 className="font-bold">Rascunhos e NFS-e da M Lab</h2><div className="mt-4 overflow-x-auto"><table className="min-w-full text-sm"><thead><tr className="text-left text-xs uppercase text-slate-500"><th className="py-2">Cliente</th><th>Emissão</th><th>Vencimento</th><th className="text-right">Valor</th><th>Status fiscal</th><th>Ambiente</th><th></th></tr></thead><tbody>{carregando?<tr><td colSpan="7" className="py-8 text-center text-slate-500">Carregando...</td></tr>:rascunhos.length===0?<tr><td colSpan="7" className="py-8 text-center text-slate-500">Nenhum rascunho NFS-e cadastrado.</td></tr>:rascunhos.map(x=><tr key={x.id} className="border-t"><td className="py-3"><b>{x.cliente?.nome||x.nome_destinatario||"—"}</b><div className="text-xs text-slate-500">{x.cliente?.cnpj_cpf||x.cnpj_destinatario||""}</div></td><td>{dataBR(x.data_emissao)}</td><td>{dataBR(x.data_vencimento)}</td><td className="text-right font-semibold">{moeda(x.valor_total)}</td><td><span className="rounded-full bg-slate-100 px-2 py-1 text-xs font-semibold">{x.status_fiscal||"—"}</span></td><td>{x.nfse_ambiente||"—"}</td><td className="text-right"><button className="btn-ghost" onClick={()=>editar(x)}>Abrir</button></td></tr>)}</tbody></table></div></section>

    {clienteModal&&<div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-900/40 p-4" onMouseDown={e=>{if(e.target===e.currentTarget)setClienteModal(false)}}><div className="w-full max-w-3xl overflow-hidden rounded-2xl bg-white shadow-2xl"><div className="flex items-center justify-between border-b px-5 py-4"><div><h3 className="font-bold text-slate-800">Selecionar cliente</h3><p className="text-xs text-slate-500">Pesquise por razão social, fantasia, CPF/CNPJ ou e-mail.</p></div><button className="btn-ghost h-9 w-9 p-0" onClick={()=>setClienteModal(false)}><X size={18}/></button></div><div className="border-b p-4"><div className="relative"><Search size={16} className="absolute left-3 top-3 text-slate-400"/><input autoFocus className="input pl-10" value={busca} onChange={e=>setBusca(e.target.value)} placeholder="Digite para pesquisar..."/></div></div><div className="max-h-[430px] overflow-y-auto p-2">{clientesFiltrados.length===0?<div className="p-8 text-center text-sm text-slate-500">Nenhum cliente encontrado.</div>:clientesFiltrados.map(x=><button type="button" key={x.id} onClick={()=>escolherCliente(x)} className="flex w-full items-center justify-between rounded-xl px-4 py-3 text-left hover:bg-teal-50"><div className="min-w-0"><div className="truncate font-semibold text-slate-800">{x.nome}</div><div className="mt-1 text-xs text-slate-500">{x.nome_fantasia?`${x.nome_fantasia} · `:""}{x.cnpj_cpf||"sem documento"}{x.email?` · ${x.email}`:""}</div></div>{form.cliente_id===x.id&&<CheckCircle2 size={18} className="shrink-0 text-teal-600"/>}</button>)}</div><div className="flex justify-between border-t bg-slate-50 p-4"><span className="text-xs text-slate-500">{clientesFiltrados.length} cliente(s) exibido(s)</span><button type="button" className="btn-outline" onClick={abrirNovoCliente}><UserPlus size={15}/>Cadastrar novo cliente</button></div></div></div>}

    {servicoModal&&<div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-900/40 p-4" onMouseDown={e=>{if(e.target===e.currentTarget)setServicoModal(false)}}><div className="w-full max-w-2xl overflow-hidden rounded-2xl bg-white shadow-2xl"><div className="flex items-center justify-between border-b px-5 py-4"><div><h3 className="font-bold text-slate-800">Selecionar serviço</h3><p className="text-xs text-slate-500">Serviços pré-configurados e fiscalmente validados para a M Lab.</p></div><button className="btn-ghost h-9 w-9 p-0" onClick={()=>setServicoModal(false)}><X size={18}/></button></div><div className="border-b p-4"><div className="relative"><Search size={16} className="absolute left-3 top-3 text-slate-400"/><input autoFocus className="input pl-10" value={buscaServico} onChange={e=>setBuscaServico(e.target.value)} placeholder="Pesquisar por código, NBS ou descrição..."/></div></div><div className="max-h-[360px] overflow-y-auto p-3">{servicosFiltrados.map(x=><button type="button" key={x.id} onClick={()=>escolherServico(x)} className="w-full rounded-xl border p-4 text-left hover:border-teal-300 hover:bg-teal-50"><div className="flex items-start gap-3"><div className="rounded-lg bg-teal-100 p-2 text-teal-700"><BriefcaseBusiness size={18}/></div><div><div className="font-semibold text-slate-800">{x.nome}</div><div className="mt-1 text-xs text-slate-500">{x.detalhe}</div><div className="mt-2 text-[11px] font-semibold text-teal-700">{x.perfil}</div></div></div></button>)}</div><div className="border-t bg-amber-50 px-4 py-3 text-xs text-amber-800">A lista mostra somente serviços que já possuem perfil fiscal validado. Novos códigos não são inventados automaticamente.</div></div></div>}
  </div>
}
