import { useEffect, useMemo, useRef, useState } from "react";
import { ArrowLeft, Upload, RefreshCw, Search, Link2 } from "lucide-react";
import { useNavigate } from "react-router-dom";
import { PageTitle } from "../components/ui.jsx";
import { financeiroOpcoes, finMovimentosListar, finMovimentosImportar, finRecebimentosListar, finDespesasListar, finConciliar } from "../services/financeiro.js";

const moeda = (v) => Number(v || 0).toLocaleString("pt-BR", { style:"currency", currency:"BRL" });
const dataBR = (v) => { if(!v)return "—"; const p=String(v).slice(0,10).split("-"); return p.length===3?`${p[2]}/${p[1]}/${p[0]}`:v; };
function tag(bloco,nome){const m=bloco.match(new RegExp(`<${nome}>([^<\r\n]+)`,`i`));return m?m[1].trim():""}
function dataOfx(v){const s=String(v||"");const m=s.match(/^(\d{4})(\d{2})(\d{2})/);return m?`${m[1]}-${m[2]}-${m[3]}`:""}
function parseOFX(texto){const blocos=String(texto||"").split(/<STMTTRN>/i).slice(1);return blocos.map(b=>{const valor=Number(tag(b,"TRNAMT").replace(",","."))||0;return{data_movimento:dataOfx(tag(b,"DTPOSTED")),descricao:tag(b,"MEMO")||tag(b,"NAME"),tipo:valor>=0?"CREDITO":"DEBITO",valor,fitid:tag(b,"FITID"),documento:tag(b,"CHECKNUM"),origem:"OFX"}}).filter(x=>x.data_movimento&&x.valor!==0)}

export default function Extrato(){
 const navigate=useNavigate(), fileRef=useRef(null); const[op,setOp]=useState({empresas:[],contas:[]});const[empresa,setEmpresa]=useState("");const[conta,setConta]=useState("");const[itens,setItens]=useState([]);const[receber,setReceber]=useState([]);const[pagar,setPagar]=useState([]);const[busca,setBusca]=useState("");const[erro,setErro]=useState("");const[loading,setLoading]=useState(true);const[conciliando,setConciliando]=useState(null);
 async function carregar(){setLoading(true);setErro("");try{const[o,m,r,d]=await Promise.all([financeiroOpcoes(),finMovimentosListar(empresa),finRecebimentosListar(empresa),finDespesasListar(empresa)]);setOp(o);setItens(m);setReceber(r);setPagar(d);}catch(e){setErro(e.message)}finally{setLoading(false)}}
 useEffect(()=>{carregar()},[empresa]);
 const filtrados=useMemo(()=>{const t=busca.toLowerCase().trim();return itens.filter(x=>(!conta||x.conta_bancaria_id===conta)&&(!t||`${x.descricao||""} ${x.documento||""}`.toLowerCase().includes(t)))},[itens,busca,conta]);
 const candidatos=(mov)=>{const fonte=mov.tipo==="CREDITO"?receber:pagar;return fonte.filter(x=>x.status!=="CANCELADO"&&Number(x.valor_pendente||0)>0&&Math.abs(Number(x.valor_pendente||0)-Number(mov.valor||0))<0.01).filter(x=>{const a=new Date(`${x.data_vencimento||"1900-01-01"}T00:00:00`),b=new Date(`${mov.data_movimento}T00:00:00`);return Math.abs(a-b)<=3*86400000}).slice(0,8)};
 async function importar(e){const f=e.target.files?.[0];if(!f)return;if(!empresa){setErro("Selecione a empresa antes de importar.");return}try{const txt=await f.text();const dados=parseOFX(txt);if(!dados.length)throw new Error("Nenhuma movimentação OFX válida encontrada.");await finMovimentosImportar(empresa,conta||null,dados);await carregar();}catch(ex){setErro(ex.message)}finally{e.target.value=""}}
 async function conciliar(mov,dest){try{await finConciliar(mov.id,{recebimentoId:mov.tipo==="CREDITO"?dest.id:null,despesaId:mov.tipo==="DEBITO"?dest.id:null,valor:Math.min(Number(mov.valor||0),Number(dest.valor_pendente||0))});setConciliando(null);await carregar()}catch(ex){setErro(ex.message)}}
 return <div className="space-y-5"><div className="flex items-center gap-3"><button className="btn-ghost h-9 w-9 p-0" onClick={()=>navigate("/financas")}><ArrowLeft size={18}/></button><PageTitle titulo="Extrato / OFX" descricao="Importação bancária com empresa preservada e conciliação por data/valor."/></div>
 <div className="grid gap-3 rounded-2xl border bg-white p-4 md:grid-cols-4"><label><span className="label">Empresa</span><select className="input" value={empresa} onChange={e=>{setEmpresa(e.target.value);setConta("")}}><option value="">Todas</option>{op.empresas.map(x=><option key={x.id} value={x.id}>{x.nome}</option>)}</select></label><label><span className="label">Conta bancária</span><select className="input" value={conta} onChange={e=>setConta(e.target.value)}><option value="">Todas / não informada</option>{op.contas.filter(c=>!empresa||c.empresa_id===empresa).map(c=><option key={c.id} value={c.id}>{c.nome}</option>)}</select></label><label><span className="label">Pesquisar</span><div className="relative"><Search size={15} className="absolute left-3 top-3 text-slate-400"/><input className="input pl-9" value={busca} onChange={e=>setBusca(e.target.value)} placeholder="Descrição ou documento"/></div></label><div className="flex items-end gap-2"><button className="btn-outline" onClick={carregar}><RefreshCw size={15}/></button><button className="btn-primary flex-1" onClick={()=>fileRef.current?.click()} disabled={!empresa}><Upload size={16}/>Importar OFX</button><input ref={fileRef} type="file" accept=".ofx" className="hidden" onChange={importar}/></div></div>
 {erro&&<div className="rounded-xl bg-red-50 p-3 text-sm text-red-700">{erro}</div>}
 <div className="overflow-x-auto rounded-2xl border bg-white"><table className="min-w-full text-sm"><thead className="bg-slate-50 text-left text-xs uppercase text-slate-500"><tr><th className="px-4 py-3">Data</th><th className="px-4 py-3">Descrição</th><th className="px-4 py-3">Conta</th><th className="px-4 py-3">Tipo</th><th className="px-4 py-3 text-right">Valor</th><th className="px-4 py-3">Situação</th><th className="px-4 py-3"></th></tr></thead><tbody>{loading?<tr><td colSpan="7" className="p-8 text-center text-slate-500">Carregando...</td></tr>:filtrados.length===0?<tr><td colSpan="7" className="p-8 text-center text-slate-500">Nenhuma movimentação.</td></tr>:filtrados.map(m=><tr key={m.id} className="border-t"><td className="px-4 py-3">{dataBR(m.data_movimento)}</td><td className="px-4 py-3"><div className="font-medium">{m.descricao||"—"}</div><div className="text-xs text-slate-500">FITID {m.fitid||"—"}</div></td><td className="px-4 py-3">{m.conta?.nome||"—"}</td><td className={`px-4 py-3 font-semibold ${m.tipo==="CREDITO"?"text-emerald-700":"text-rose-700"}`}>{m.tipo}</td><td className="px-4 py-3 text-right font-semibold">{moeda(m.valor)}</td><td className="px-4 py-3"><span className={`rounded-full px-2 py-1 text-xs font-semibold ${m.conciliado?"bg-emerald-50 text-emerald-700":"bg-amber-50 text-amber-700"}`}>{m.conciliado?"CONCILIADO":"PENDENTE"}</span></td><td className="px-4 py-3 text-right">{!m.conciliado&&<button className="btn-outline py-1.5" onClick={()=>setConciliando(m)}><Link2 size={14}/>Conciliar</button>}</td></tr>)}</tbody></table></div>
 {conciliando&&<div className="fixed inset-0 z-50 grid place-items-center bg-slate-950/45 p-4"><div className="max-h-[90vh] w-full max-w-2xl overflow-y-auto rounded-2xl bg-white p-5 shadow-2xl"><div className="mb-4 flex items-start justify-between"><div><h2 className="font-bold">Conciliar {moeda(conciliando.valor)}</h2><p className="text-sm text-slate-500">Regra sugerida: mesmo valor e vencimento até ±3 dias. Se houver mais de um candidato, escolha manualmente.</p></div><button className="btn-ghost" onClick={()=>setConciliando(null)}>Fechar</button></div><div className="space-y-2">{candidatos(conciliando).length===0?<p className="rounded-xl bg-slate-50 p-4 text-sm text-slate-500">Nenhum candidato automático. Cadastre/ajuste o título e tente novamente.</p>:candidatos(conciliando).map(x=><button key={x.id} onClick={()=>conciliar(conciliando,x)} className="w-full rounded-xl border p-3 text-left hover:bg-slate-50"><div className="flex justify-between gap-3"><span className="font-medium">{x.cliente||x.fornecedor}</span><span className="font-semibold">{moeda(x.valor_pendente)}</span></div><div className="mt-1 text-xs text-slate-500">Vencimento {dataBR(x.data_vencimento)} · {x.origem}</div></button>)}</div></div></div>}
 </div>
}
