import { useEffect, useMemo, useState } from "react";
import { Wallet, TrendingUp, AlertTriangle, Landmark, RefreshCw, ReceiptText, Plus, ArrowDownCircle, ArrowUpCircle, ChevronRight, CheckCircle2, Clock3 } from "lucide-react";
import { useNavigate } from "react-router-dom";
import { financeiroOpcoes, finRecebimentosListar, finDespesasListar, finNotasListar, finMovimentosListar } from "../services/financeiro.js";

const moeda=(v)=>Number(v||0).toLocaleString("pt-BR",{style:"currency",currency:"BRL"});
const hoje=()=>new Date().toISOString().slice(0,10);
const nomeEmpresa=(x)=>String(x?.nome||"").trim();
const ehMLab=(x)=>/^m\s*lab$/i.test(nomeEmpresa(x));
const ehMinas=(x)=>/minas\s*lab/i.test(nomeEmpresa(x));
const pendente=(x)=>String(x?.status||"").toUpperCase()!=="CANCELADO"&&Number(x?.valor_pendente||0)>0;

function Kpi({titulo,valor,sub,Icone,tom="slate",onClick}){
 const tons={slate:"bg-slate-50 text-slate-700",sky:"bg-sky-50 text-sky-700",rose:"bg-rose-50 text-rose-700",amber:"bg-amber-50 text-amber-700",emerald:"bg-emerald-50 text-emerald-700"};
 return <button type="button" onClick={onClick} className="rounded-2xl border border-slate-200 bg-white p-4 text-left shadow-sm transition hover:-translate-y-0.5 hover:shadow-md"><div className="flex items-start gap-3"><span className={`rounded-xl p-2.5 ${tons[tom]}`}><Icone size={20}/></span><div><p className="text-sm font-semibold text-slate-700">{titulo}</p><p className="mt-1 text-2xl font-bold text-slate-950">{valor}</p><p className="mt-1 text-xs text-slate-500">{sub}</p></div></div></button>;
}

export default function FinanceiroDashboard(){
 const navigate=useNavigate();
 const [op,setOp]=useState({empresas:[],contas:[]});
 const [empresaId,setEmpresaId]=useState("");
 const [rec,setRec]=useState([]); const [des,setDes]=useState([]); const [notas,setNotas]=useState([]); const [mov,setMov]=useState([]);
 const [loading,setLoading]=useState(true); const [erro,setErro]=useState("");
 async function carregar(){setLoading(true);setErro("");try{const [o,r,d,n,m]=await Promise.all([financeiroOpcoes(),finRecebimentosListar(empresaId),finDespesasListar(empresaId),finNotasListar(empresaId),finMovimentosListar(empresaId)]);setOp(o||{empresas:[],contas:[]});setRec(r||[]);setDes(d||[]);setNotas(n||[]);setMov(m||[])}catch(e){setErro(e.message||"Falha ao carregar o Financeiro.")}finally{setLoading(false)}}
 useEffect(()=>{carregar()},[empresaId]);
 const selecionada=(op.empresas||[]).find(x=>x.id===empresaId);
 const modo=empresaId?(ehMLab(selecionada)?"MLAB":"MINAS"):"CONSOLIDADO";
 const dados=useMemo(()=>{
  const rA=rec.filter(pendente),dA=des.filter(pendente),h=hoje();
  const rV=rA.filter(x=>x.data_vencimento&&String(x.data_vencimento).slice(0,10)<h),dV=dA.filter(x=>x.data_vencimento&&String(x.data_vencimento).slice(0,10)<h);
  const contas=(op.contas||[]).filter(c=>c.ativa!==false&&(!empresaId||c.empresa_id===empresaId));
  const saldoOk=contas.length>0&&contas.every(c=>c.saldo_atual!==null&&c.saldo_atual!==undefined);
  const saldo=saldoOk?contas.reduce((s,c)=>s+Number(c.saldo_atual||0),0):null;
  const aReceber=rA.reduce((s,x)=>s+Number(x.valor_pendente||0),0),aPagar=dA.reduce((s,x)=>s+Number(x.valor_pendente||0),0);
  const vencidos=rV.reduce((s,x)=>s+Number(x.valor_pendente||0),0)+dV.reduce((s,x)=>s+Number(x.valor_pendente||0),0);
  const pendMov=mov.filter(x=>!x.conciliado&&!x.classificacao_bancaria).length;
  const resultado=mov.filter(x=>String(x.data_movimento||"").slice(0,7)===h.slice(0,7)&&!x.classificacao_bancaria).reduce((s,x)=>s+(String(x.tipo).toUpperCase()==="CREDITO"?Math.abs(Number(x.valor||0)):-Math.abs(Number(x.valor||0))),0);
  return{contas,saldo,saldoOk,aReceber,aPagar,vencidos,rV,dV,pendMov,resultado};
 },[rec,des,mov,op.contas,empresaId]);
 const porEmpresa=useMemo(()=>{return(op.empresas||[]).filter(e=>e.ativa!==false).map(e=>{const rs=rec.filter(x=>x.empresa_id===e.id&&pendente(x)).reduce((s,x)=>s+Number(x.valor_pendente||0),0);const ds=des.filter(x=>x.empresa_id===e.id&&pendente(x)).reduce((s,x)=>s+Number(x.valor_pendente||0),0);const cs=(op.contas||[]).filter(c=>c.empresa_id===e.id&&c.ativa!==false);const saldo=cs.length&&cs.every(c=>c.saldo_atual!=null)?cs.reduce((s,c)=>s+Number(c.saldo_atual||0),0):null;return{...e,receber:rs,pagar:ds,saldo}})},[op,rec,des]);
 const recentes=[...mov].sort((a,b)=>String(b.data_movimento||"").localeCompare(String(a.data_movimento||""))).slice(0,6);
 const notasRecentes=[...notas].sort((a,b)=>String(b.data_emissao||"").localeCompare(String(a.data_emissao||""))).slice(0,5);
 return <div className="space-y-5">
  <div className="flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between"><div><h1 className="text-3xl font-bold tracking-tight text-slate-950">Financeiro</h1><p className="mt-1 text-sm text-slate-500">Visão estratégica das empresas e operação financeira em um só lugar.</p></div><button className="btn-outline self-start" onClick={carregar} disabled={loading}><RefreshCw size={15} className={loading?"animate-spin":""}/>{loading?"Atualizando...":"Atualizar dados"}</button></div>
  <div className="flex flex-wrap gap-2">{[{id:"",nome:"Consolidado"},...(op.empresas||[]).filter(e=>e.ativa!==false)].map(e=><button key={e.id||"all"} onClick={()=>setEmpresaId(e.id)} className={`rounded-xl border px-5 py-2.5 text-sm font-semibold transition ${empresaId===e.id?"border-blue-600 bg-blue-600 text-white shadow-sm":"border-slate-200 bg-white text-slate-700 hover:bg-slate-50"}`}>{e.nome}</button>)}</div>
  {erro&&<div className="rounded-xl bg-red-50 p-3 text-sm text-red-700">{erro}</div>}
  <div className={`rounded-2xl border p-4 ${modo==="MLAB"?"border-blue-100 bg-blue-50/60":modo==="MINAS"?"border-emerald-100 bg-emerald-50/60":"border-slate-200 bg-white"}`}><div className="flex flex-col gap-3 md:flex-row md:items-center md:justify-between"><div><p className="font-bold text-slate-900">{modo==="CONSOLIDADO"?"Gestão estratégica consolidada":modo==="MINAS"?"MinasLab · operação alimentada pela Omie":"M Lab · operação realizada neste sistema"}</p><p className="mt-1 text-sm text-slate-600">{modo==="CONSOLIDADO"?"Use esta visão para acompanhar caixa, compromissos e desempenho das duas empresas.":modo==="MINAS"?"Acompanhe aqui os dados financeiros sincronizados. A operação continua sendo feita na Omie.":"Receba, pague, emita NFS-e, envie ao cliente, atualize o C6 e faça a conciliação por aqui."}</p></div>{modo==="MLAB"&&<div className="flex flex-wrap gap-2"><button className="btn-primary" onClick={()=>navigate("/financas/notas-fiscais/emitir")}><ReceiptText size={15}/>Emitir NFS-e</button><button className="btn-outline" onClick={()=>navigate("/financas/movimentacao-conta")}><Landmark size={15}/>Atualizar C6</button></div>}</div></div>
  <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-5"><Kpi titulo="Saldo disponível" valor={dados.saldoOk?moeda(dados.saldo):"A informar"} sub={`${dados.contas.length} conta(s) ativa(s)`} Icone={Wallet} tom="emerald" onClick={()=>navigate("/financas/movimentacao-conta")}/><Kpi titulo="A receber" valor={moeda(dados.aReceber)} sub={`${rec.filter(pendente).length} título(s) em aberto`} Icone={ArrowDownCircle} tom="sky" onClick={()=>navigate("/financas/contas-a-receber")}/><Kpi titulo="A pagar" valor={moeda(dados.aPagar)} sub={`${des.filter(pendente).length} título(s) em aberto`} Icone={ArrowUpCircle} tom="rose" onClick={()=>navigate("/financas/contas-a-pagar")}/><Kpi titulo="Vencidos" valor={moeda(dados.vencidos)} sub={`${dados.rV.length} a receber · ${dados.dV.length} a pagar`} Icone={AlertTriangle} tom="amber" onClick={()=>navigate("/financas/contas-a-receber")}/><Kpi titulo="Resultado do mês" valor={moeda(dados.resultado)} sub="Movimentação bancária do mês" Icone={TrendingUp} tom={dados.resultado>=0?"emerald":"rose"}/></div>
  <div className="grid gap-5 xl:grid-cols-3"><section className="rounded-2xl border bg-white p-5 shadow-sm"><div className="mb-4 flex items-center justify-between"><h2 className="font-bold text-slate-900">Saldos por conta</h2><button className="text-sm font-medium text-blue-700" onClick={()=>navigate("/financas/movimentacao-conta")}>Ver todas</button></div><div className="space-y-2">{dados.contas.length?dados.contas.map(c=><div key={c.id} className="flex items-center justify-between rounded-xl bg-slate-50 px-3 py-3"><div><p className="text-sm font-semibold">{c.nome||c.banco}</p><p className="text-xs text-slate-500">{c.banco||"Conta bancária"}</p></div><strong className="text-sm">{c.saldo_atual==null?"A informar":moeda(c.saldo_atual)}</strong></div>):<p className="py-8 text-center text-sm text-slate-500">Nenhuma conta encontrada.</p>}</div></section>
  <section className="rounded-2xl border bg-white p-5 shadow-sm"><div className="mb-4 flex items-center justify-between"><h2 className="font-bold text-slate-900">O que precisa da sua atenção</h2><AlertTriangle size={18} className="text-amber-500"/></div><div className="divide-y"><button className="flex w-full items-center justify-between py-3 text-left" onClick={()=>navigate("/financas/contas-a-receber")}><span className="text-sm">Contas a receber vencidas</span><strong className="text-sm text-red-600">{dados.rV.length}</strong></button><button className="flex w-full items-center justify-between py-3 text-left" onClick={()=>navigate("/financas/contas-a-pagar")}><span className="text-sm">Contas a pagar vencidas</span><strong className="text-sm text-red-600">{dados.dV.length}</strong></button><button className="flex w-full items-center justify-between py-3 text-left" onClick={()=>navigate("/financas/conciliacao")}><span className="text-sm">Movimentos para conciliar</span><strong className="text-sm text-amber-600">{dados.pendMov}</strong></button><button className="flex w-full items-center justify-between py-3 text-left" onClick={()=>navigate("/financas/notas-fiscais")}><span className="text-sm">Notas fiscais no cadastro</span><strong className="text-sm text-blue-700">{notas.length}</strong></button></div></section>
  <section className="rounded-2xl border bg-white p-5 shadow-sm"><h2 className="mb-4 font-bold text-slate-900">Atalhos rápidos</h2><div className="grid gap-2 sm:grid-cols-2 xl:grid-cols-1 2xl:grid-cols-2">{modo!=="MINAS"&&<><button className="btn-outline justify-start" onClick={()=>navigate("/financas/contas-a-receber")}><Plus size={15}/>Nova conta a receber</button><button className="btn-outline justify-start" onClick={()=>navigate("/financas/contas-a-pagar")}><Plus size={15}/>Nova conta a pagar</button></>}{modo==="MLAB"&&<button className="btn-outline justify-start" onClick={()=>navigate("/financas/notas-fiscais/emitir")}><ReceiptText size={15}/>Emitir NFS-e</button>}<button className="btn-outline justify-start" onClick={()=>navigate("/financas/movimentacao-conta")}><Landmark size={15}/>{modo==="MLAB"?"Atualizar C6":"Movimentação"}</button><button className="btn-outline justify-start" onClick={()=>navigate("/financas/fluxo-caixa")}><TrendingUp size={15}/>Fluxo de caixa</button><button className="btn-outline justify-start" onClick={()=>navigate("/financas/conciliacao")}><CheckCircle2 size={15}/>Conciliação</button></div></section></div>
  {modo==="CONSOLIDADO"&&<section className="rounded-2xl border bg-white p-5 shadow-sm"><h2 className="mb-4 font-bold text-slate-900">MinasLab × M Lab</h2><div className="grid gap-3 md:grid-cols-2">{porEmpresa.map(e=><button key={e.id} onClick={()=>setEmpresaId(e.id)} className="rounded-xl border border-slate-200 p-4 text-left hover:bg-slate-50"><div className="mb-3 flex items-center justify-between"><strong>{e.nome}</strong><ChevronRight size={16} className="text-slate-400"/></div><div className="grid grid-cols-3 gap-2 text-sm"><div><span className="block text-xs text-slate-500">Saldo</span><b>{e.saldo==null?"A informar":moeda(e.saldo)}</b></div><div><span className="block text-xs text-slate-500">A receber</span><b>{moeda(e.receber)}</b></div><div><span className="block text-xs text-slate-500">A pagar</span><b>{moeda(e.pagar)}</b></div></div></button>)}</div></section>}
  <div className="grid gap-5 xl:grid-cols-2"><section className="overflow-hidden rounded-2xl border bg-white shadow-sm"><div className="flex items-center justify-between p-5"><h2 className="font-bold">Últimas movimentações</h2><button className="text-sm font-medium text-blue-700" onClick={()=>navigate("/financas/movimentacao-conta")}>Ver todas</button></div><div className="overflow-x-auto"><table className="min-w-full text-sm"><thead className="bg-slate-50 text-left text-xs text-slate-500"><tr><th className="px-4 py-3">Data</th><th className="px-4 py-3">Descrição</th><th className="px-4 py-3 text-right">Valor</th><th className="px-4 py-3">Situação</th></tr></thead><tbody>{recentes.map(m=><tr key={m.id} className="border-t"><td className="px-4 py-3">{String(m.data_movimento||"").slice(0,10).split("-").reverse().join("/")}</td><td className="px-4 py-3 font-medium">{m.descricao||m.documento||"Movimento"}</td><td className="px-4 py-3 text-right font-semibold">{moeda(Math.abs(Number(m.valor||0)))}</td><td className="px-4 py-3">{m.classificacao_bancaria?<span className="rounded-full bg-blue-50 px-2 py-1 text-xs text-blue-700">{m.classificacao_bancaria}</span>:m.conciliado?<span className="rounded-full bg-emerald-50 px-2 py-1 text-xs text-emerald-700">Conciliado</span>:<span className="rounded-full bg-amber-50 px-2 py-1 text-xs text-amber-700">A conferir</span>}</td></tr>)}</tbody></table></div></section>
  <section className="overflow-hidden rounded-2xl border bg-white shadow-sm"><div className="flex items-center justify-between p-5"><h2 className="font-bold">Notas Fiscais</h2><button className="text-sm font-medium text-blue-700" onClick={()=>navigate("/financas/notas-fiscais")}>Ver todas</button></div><div className="divide-y">{notasRecentes.length?notasRecentes.map(n=><div key={n.id} className="flex items-center justify-between gap-3 px-5 py-3"><div><p className="text-sm font-semibold">{n.cliente||n.fornecedor||n.numero_nf||"Nota fiscal"}</p><p className="text-xs text-slate-500">{n.numero_nf?`Nº ${n.numero_nf} · `:""}{String(n.data_emissao||"").slice(0,10).split("-").reverse().join("/")}</p></div><div className="text-right"><p className="text-sm font-bold">{moeda(n.valor_total)}</p><p className="text-xs text-slate-500">{n.status||"Registrada"}</p></div></div>):<p className="p-8 text-center text-sm text-slate-500">Nenhuma nota encontrada.</p>}</div></section></div>
 </div>;
}