import { useEffect, useMemo, useState } from "react";
import { ArrowLeft, RefreshCw } from "lucide-react";
import { useNavigate } from "react-router-dom";
import { PageTitle } from "../components/ui.jsx";
import { financeiroDashboard, financeiroOpcoes } from "../services/financeiro.js";

const moeda=v=>Number(v||0).toLocaleString("pt-BR",{style:"currency",currency:"BRL"});
const dataBR=v=>{const p=String(v||"").slice(0,10).split("-");return p.length===3?`${p[2]}/${p[1]}/${p[0]}`:"—"};
const mesBR=v=>{const [a,m]=String(v||"").split("-");return a&&m?new Date(Number(a),Number(m)-1,1).toLocaleDateString("pt-BR",{month:"long",year:"numeric"}):"—"};
const hoje=()=>new Date().toISOString().slice(0,10);
const fimAno=()=>`${new Date().getFullYear()}-12-31`;

export default function FluxoCaixa(){
 const navigate=useNavigate();const[op,setOp]=useState({empresas:[]});const[empresa,setEmpresa]=useState("");const[de,setDe]=useState(hoje());const[ate,setAte]=useState(fimAno());const[dados,setDados]=useState(null);const[erro,setErro]=useState("");
 async function carregar(){setErro("");try{const[o,d]=await Promise.all([financeiroOpcoes(),financeiroDashboard({empresaId:empresa,de,ate})]);setOp(o);setDados(d)}catch(e){setErro(e.message)}}
 useEffect(()=>{carregar()},[empresa,de,ate]);
 const empresaSelecionada=useMemo(()=>op.empresas.find(x=>x.id===empresa)||null,[op.empresas,empresa]);
 const mensal=!!empresaSelecionada&&!empresaSelecionada.usa_omie;
 const linhas=useMemo(()=>{const m=new Map();const chave=d=>mensal?String(d).slice(0,7):d;for(const r of dados?.recebimentos||[]){if(r.status==="CANCELADO")continue;const d=r.data_vencimento;if(!d)continue;const k=chave(d),x=m.get(k)||{data:k,entradas:0,saidas:0};x.entradas+=Number(r.valor_pendente||0);m.set(k,x)}for(const p of dados?.despesas||[]){if(p.status==="CANCELADO")continue;const d=p.data_vencimento;if(!d)continue;const k=chave(d),x=m.get(k)||{data:k,entradas:0,saidas:0};x.saidas+=Number(p.valor_pendente||0);m.set(k,x)}let saldo=Number(dados?.saldoAtual||0);return[...m.values()].sort((a,b)=>a.data.localeCompare(b.data)).map(x=>{saldo+=x.entradas-x.saidas;return{...x,saldo}})},[dados,mensal]);
 return <div className="space-y-5"><div className="flex items-center gap-3"><button className="btn-ghost h-9 w-9 p-0" onClick={()=>navigate("/financas")}><ArrowLeft size={18}/></button><PageTitle titulo="Fluxo de Caixa" descricao={mensal?"M Lab: entradas e saídas previstas com projeção mensal.":"MinasLab: entradas e saídas previstas com saldo projetado por dia."}/></div><div className="grid gap-3 rounded-2xl border bg-white p-4 md:grid-cols-4"><label><span className="label">Empresa</span><select className="input" value={empresa} onChange={e=>setEmpresa(e.target.value)}><option value="">Consolidado</option>{op.empresas.map(x=><option key={x.id} value={x.id}>{x.nome}</option>)}</select></label><label><span className="label">De</span><input className="input" type="date" value={de} onChange={e=>setDe(e.target.value)}/></label><label><span className="label">Até</span><input className="input" type="date" value={ate} onChange={e=>setAte(e.target.value)}/></label><div className="flex items-end"><button className="btn-outline w-full" onClick={carregar}><RefreshCw size={15}/>Atualizar</button></div></div>{erro&&<div className="rounded-xl bg-red-50 p-3 text-sm text-red-700">{erro}</div>}<div className="grid gap-3 sm:grid-cols-3"><div className="rounded-2xl border bg-white p-4"><p className="text-xs uppercase text-slate-500">Saldo atual</p><p className="mt-1 text-xl font-bold">{moeda(dados?.saldoAtual)}</p></div><div className="rounded-2xl border bg-white p-4"><p className="text-xs uppercase text-slate-500">Entradas previstas</p><p className="mt-1 text-xl font-bold text-emerald-700">{moeda(dados?.totalReceber)}</p></div><div className="rounded-2xl border bg-white p-4"><p className="text-xs uppercase text-slate-500">Saldo projetado</p><p className="mt-1 text-xl font-bold">{moeda(dados?.saldoProjetado)}</p></div></div><div className="overflow-x-auto rounded-2xl border bg-white"><table className="min-w-full text-sm"><thead className="bg-slate-50 text-left text-xs uppercase text-slate-500"><tr><th className="px-4 py-3">{mensal?"Mês":"Data"}</th><th className="px-4 py-3 text-right">Entradas</th><th className="px-4 py-3 text-right">Saídas</th><th className="px-4 py-3 text-right">Resultado</th><th className="px-4 py-3 text-right">Saldo projetado</th></tr></thead><tbody>{linhas.length===0?<tr><td colSpan="5" className="p-8 text-center text-slate-500">Sem previsões no período.</td></tr>:linhas.map(x=><tr key={x.data} className="border-t"><td className="px-4 py-3">{mensal?mesBR(x.data):dataBR(x.data)}</td><td className="px-4 py-3 text-right text-emerald-700">{moeda(x.entradas)}</td><td className="px-4 py-3 text-right text-rose-700">{moeda(x.saidas)}</td><td className="px-4 py-3 text-right">{moeda(x.entradas-x.saidas)}</td><td className={`px-4 py-3 text-right font-semibold ${x.saldo<0?"text-red-700":"text-slate-900"}`}>{moeda(x.saldo)}</td></tr>)}</tbody></table></div></div>
}
