import { useEffect, useMemo, useState } from "react";
import {
  AlertTriangle, BarChart3, Boxes, ClipboardList, FileText, PackagePlus, PackageMinus,
  Plus, Search, Settings, Tags, Truck,
} from "lucide-react";
import { PageTitle, Card, Modal, Aviso, CarregandoModulo, ErroModulo } from "../components/ui.jsx";
import { carregarColecoes, salvar, estoquePedidoExcluir, estoqueEntrada, estoqueRetirada } from "../services/dados.js";
import { podeEditar, podeVerSecao } from "../lib/sessao.js";

const SECOES = [
  ["dashboard", "Dashboard", BarChart3],
  ["cadastro-insumo", "Cadastro de Insumos", Boxes],
  ["entrada-lote", "Entrada de Estoque", PackagePlus],
  ["retirada-baixa", "Saída / Baixa", PackageMinus],
  ["fornecedores", "Fornecedores", Truck],
  ["etiquetas", "Etiquetas", Tags],
  ["relatorios", "Relatórios", FileText],
  ["configuracoes", "Configurações", Settings],
  ["pedido-compra", "Pedido de Compra", ClipboardList],
];
const COLECOES = ["estoque_produtos_base","estoque_lotes","estoque_movimentos","estoque_fornecedores","estoque_pedidos","estoque_inspecoes","estoque_avaliacoes_fornecedor","estoque_fapes","estoque_tipos_documentos_fornecedor","estoque_regras_documentos_fornecedor","estoque_documentos_fornecedor","estoque_config"];

function n(v){ const x=Number(v); return Number.isFinite(x)?x:0; }
function statusLote(l){
  const atual=n(l.totalAtual ?? l.total_atual);
  const minimo=n(l.qtdMinima ?? l.qtd_minima);
  if(atual<=0) return "ZERADO";
  if(minimo>0 && atual<=minimo) return "CRÍTICO";
  return "OK";
}
function Campo({rotulo,...props}){return <label className="block"><span className="label">{rotulo}</span><input className="input" {...props}/></label>}

function Dashboard({produtos,lotes,fornecedores,pedidos}){
  const vm=useMemo(()=>{
    const ativos=lotes.filter(l=>n(l.totalAtual ?? l.total_atual)>0);
    return {
      produtos:produtos.length,
      lotes:ativos.length,
      criticos:ativos.filter(l=>statusLote(l)==="CRÍTICO").length,
      fornecedores:fornecedores.filter(f=>String(f.status||"ATIVO").toUpperCase()!=="INATIVO").length,
      pedidos:pedidos.filter(p=>!["RECEBIDO","CANCELADO","INTEGRADO"].includes(String(p.status||"").toUpperCase())).length,
    };
  },[produtos,lotes,fornecedores,pedidos]);
  const cards=[
    ["Produtos cadastrados",vm.produtos,Boxes],
    ["Lotes com saldo",vm.lotes,PackagePlus],
    ["Estoque crítico",vm.criticos,AlertTriangle],
    ["Fornecedores ativos",vm.fornecedores,Truck],
    ["Pedidos em aberto",vm.pedidos,ClipboardList],
  ];
  return <div className="space-y-5">
    <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-5">{cards.map(([r,v,I])=><Card key={r}><div className="flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-xl bg-brand-50 text-brand-700"><I size={18}/></span><span><span className="block text-xs text-slate-500">{r}</span><strong className="font-display text-2xl text-slate-900">{v}</strong></span></div></Card>)}</div>
    <Card><h2 className="font-display text-base font-bold text-slate-900">Visão geral do estoque</h2><p className="mt-1 text-sm text-slate-600">Os indicadores usam as coleções exclusivas da nova Gestão de Estoque. Nenhum dado da página Compras é misturado aqui.</p></Card>
  </div>;
}

function EntradaEstoque({produtos,lotes,fornecedores,aoRecarregar}){
  const vazio={dataChegada:new Date().toISOString().slice(0,10),notaFiscal:"",valorNF:"",fornecedor:"",cnpj:"",grupo:"",produto:"",referencia:"",lote:"",unidade:"UN",validade:"",conteudoKit:"1",qtdKit:"1",qtdMinima:"",observacao:""};
  const [form,setForm]=useState(vazio); const [salvando,setSalvando]=useState(false); const [aviso,setAviso]=useState(null);
  const total=n(form.conteudoKit)*n(form.qtdKit);
  const escolherProduto=(nome)=>{const p=produtos.find(x=>x.produto===nome)||{};setForm({...form,produto:nome,grupo:p.grupo||form.grupo,unidade:p.unidade||form.unidade,qtdMinima:p.qtdMinima??form.qtdMinima,referencia:p.especificacao||form.referencia});};
  const salvarEntrada=async()=>{if(!form.produto.trim()||!form.lote.trim()||total<=0){setAviso({tipo:"erro",texto:"Informe produto, lote e quantidades válidas."});return;}setSalvando(true);try{const ids=lotes.map(l=>String(l.codigoID||l.codigoAuto||l.id||"")).filter(x=>/^ML-\d+$/.test(x)).map(x=>Number(x.split("-")[1]));const codigo="ML-"+String((Math.max(0,...ids)+1)).padStart(2,"0");const id="lote-"+codigo.toLowerCase();const reg={id,codigoID:codigo,codigoAuto:codigo,...form,produto:form.produto.toUpperCase(),lote:form.lote.toUpperCase(),notaFiscal:form.notaFiscal.toUpperCase(),fornecedor:form.fornecedor.toUpperCase(),qtdTotal:total,qtdRetirada:0,totalAtual:total,qtdAtual:total,dataAbertura:"",ultimaRetirada:"",statusValidade:"OK",statusCompra:"OK",origem:"GESTAO_ESTOQUE"};await estoqueEntrada({...reg,totalRecebido:total},{codigoID:codigo,produto:reg.produto,lote:reg.lote,quantidade:total,unidade:reg.unidade,data:new Date().toISOString()});setForm(vazio);setAviso({tipo:"ok",texto:`Entrada ${codigo} cadastrada com sucesso.`});await aoRecarregar();}catch(e){setAviso({tipo:"erro",texto:e.message});}finally{setSalvando(false);}};
  return <div className="space-y-4"><Aviso aviso={aviso} aoFechar={()=>setAviso(null)}/><Card><div className="grid gap-4 md:grid-cols-3"><Campo rotulo="Data de chegada" type="date" value={form.dataChegada} onChange={e=>setForm({...form,dataChegada:e.target.value})}/><Campo rotulo="Nota fiscal" value={form.notaFiscal} onChange={e=>setForm({...form,notaFiscal:e.target.value})}/><Campo rotulo="Valor da NF" type="number" step="0.01" value={form.valorNF} onChange={e=>setForm({...form,valorNF:e.target.value})}/><label className="block"><span className="label">Fornecedor</span><select className="input" value={form.fornecedor} onChange={e=>{const x=fornecedores.find(f=>f.nome===e.target.value);setForm({...form,fornecedor:e.target.value,cnpj:x?.cnpj||""});}}><option value="">Selecione</option>{fornecedores.map(f=><option key={f.id||f.cnpj||f.nome} value={f.nome}>{f.nome}</option>)}</select></label><Campo rotulo="CNPJ" value={form.cnpj} onChange={e=>setForm({...form,cnpj:e.target.value})}/><Campo rotulo="Grupo" value={form.grupo} onChange={e=>setForm({...form,grupo:e.target.value})}/><label className="block"><span className="label">Produto</span><select className="input" value={form.produto} onChange={e=>escolherProduto(e.target.value)}><option value="">Selecione</option>{produtos.map(p=><option key={p.id} value={p.produto}>{p.produto}</option>)}</select></label><Campo rotulo="Referência / especificação" value={form.referencia} onChange={e=>setForm({...form,referencia:e.target.value})}/><Campo rotulo="Lote" value={form.lote} onChange={e=>setForm({...form,lote:e.target.value})}/><Campo rotulo="Unidade" value={form.unidade} onChange={e=>setForm({...form,unidade:e.target.value})}/><Campo rotulo="Validade" type="date" value={form.validade} onChange={e=>setForm({...form,validade:e.target.value})}/><Campo rotulo="Conteúdo do kit" type="number" value={form.conteudoKit} onChange={e=>setForm({...form,conteudoKit:e.target.value})}/><Campo rotulo="Qtd. kits" type="number" value={form.qtdKit} onChange={e=>setForm({...form,qtdKit:e.target.value})}/><Campo rotulo="Qtd. mínima" type="number" value={form.qtdMinima} onChange={e=>setForm({...form,qtdMinima:e.target.value})}/><div><span className="label">Quantidade total</span><div className="input bg-slate-50 font-semibold">{total}</div></div><label className="block md:col-span-3"><span className="label">Observação</span><input className="input" value={form.observacao} onChange={e=>setForm({...form,observacao:e.target.value})}/></label></div><div className="mt-5 flex justify-end"><button className="btn-primary" disabled={salvando||!podeEditar()} onClick={salvarEntrada}>{salvando?"Salvando...":"Registrar entrada"}</button></div></Card></div>;
}

function SaidaEstoque({lotes,aoRecarregar}){
 const disponiveis=useMemo(()=>lotes.filter(l=>n(l.totalAtual??l.qtdAtual)>0&&(!l.validade||l.validade>=new Date().toISOString().slice(0,10))).sort((a,b)=>(a.validade||"9999").localeCompare(b.validade||"9999")),[lotes]);
 const [id,setId]=useState("");const [qtd,setQtd]=useState("");const [dataAbertura,setDataAbertura]=useState("");const [salvando,setSalvando]=useState(false);const [aviso,setAviso]=useState(null);const lote=disponiveis.find(l=>l.id===id);
 const baixar=async()=>{const q=n(qtd),saldo=n(lote?.totalAtual??lote?.qtdAtual);if(!lote||q<=0||q>saldo){setAviso({tipo:"erro",texto:q>saldo?`Quantidade superior ao saldo disponível (${saldo} ${lote?.unidade||""}).`:"Selecione um lote e informe quantidade maior que zero."});return;}setSalvando(true);try{await estoqueRetirada(lote.id,q,dataAbertura||"","");setId("");setQtd("");setDataAbertura("");setAviso({tipo:"ok",texto:`Saída de ${q} ${lote.unidade||""} processada.`});await aoRecarregar();}catch(e){setAviso({tipo:"erro",texto:e.message});}finally{setSalvando(false);}};
 return <div className="space-y-4"><Aviso aviso={aviso} aoFechar={()=>setAviso(null)}/><Card><div className="grid gap-4 md:grid-cols-3"><label className="block md:col-span-2"><span className="label">Produto / lote disponível</span><select className="input" value={id} onChange={e=>setId(e.target.value)}><option value="">Selecione</option>{disponiveis.map(l=><option key={l.id} value={l.id}>{l.produto} — lote {l.lote} — saldo {n(l.totalAtual??l.qtdAtual)} {l.unidade||""}{l.validade?` — val. ${l.validade}`:""}</option>)}</select></label><Campo rotulo="Quantidade da saída" type="number" min="0" step="any" value={qtd} onChange={e=>setQtd(e.target.value)}/><Campo rotulo="Data de abertura (opcional)" type="date" value={dataAbertura} onChange={e=>setDataAbertura(e.target.value)}/>{lote&&<div className="md:col-span-2 rounded-xl bg-slate-50 p-3 text-sm"><b>{lote.codigoID||lote.codigoAuto}</b> · {lote.produto} · lote {lote.lote}<br/><span className="text-slate-600">Saldo atual: {n(lote.totalAtual??lote.qtdAtual)} {lote.unidade||""}</span></div>}</div><div className="mt-5 flex justify-end"><button className="btn-primary" disabled={salvando||!podeEditar()} onClick={baixar}>{salvando?"Processando...":"Confirmar saída / baixa"}</button></div></Card></div>;
}


function Fornecedores({fornecedores,avaliacoes,documentos,tiposDocumentos=[],regrasDocumentos=[],aoRecarregar}){
 const [busca,setBusca]=useState(""); const [form,setForm]=useState(null); const [avaliar,setAvaliar]=useState(null); const [aviso,setAviso]=useState(null); const [salvando,setSalvando]=useState(false);
 const lista=fornecedores.filter(f=>[f.id,f.nome,f.cnpj,f.tipoServico,f.tipoFornecedor].join(" ").toLowerCase().includes(busca.toLowerCase())); const resumoDoc=(x)=>{const regras=regrasDocumentos.filter(r=>String(r.tipoFornecedor||"").toUpperCase()===String(x.tipoFornecedor||"").toUpperCase()&&String(r.ativo||"SIM").toUpperCase()!=="NÃO");if(!regras.length)return "NÃO CONFIGURADO";const sts=regras.map(r=>{const tipo=tiposDocumentos.find(t=>t.id===r.tipoDocumentoId||t.idTipoDocumento===r.tipoDocumentoId)||{};const hist=documentos.filter(d=>d.fornecedorId===x.id&&(d.tipoDocumentoId===r.tipoDocumentoId||d.idTipoDocumento===r.tipoDocumentoId)&&String(d.ativo||"SIM").toUpperCase()!=="NÃO").sort((a,b)=>n(b.versao)-n(a.versao));return {regra:String(r.regra||"").toUpperCase(),status:statusDocFornecedor(r.regra,tipo,hist[0])}});if(sts.some(s=>s.regra==="OBRIGATÓRIO"&&s.status==="VENCIDO"))return "VENCIDO";if(sts.some(s=>s.regra==="OBRIGATÓRIO"&&s.status==="PENDENTE"))return "PENDENTE";if(sts.some(s=>s.regra==="OBRIGATÓRIO"&&s.status==="VENCENDO"))return "VENCENDO";return "REGULAR"};
 const novo=()=>setForm({nome:"",cnpj:"",endereco:"",telefone:"",email:"",website:"",tipoServico:"COMPRAS",status:"ATIVO",relacaoMinaslab:"FORNECEDOR",tipoFornecedor:"COMPRAS",requerQualificacao:"SIM",periodicidade:"SEMESTRAL"});
 const gravar=async()=>{setSalvando(true);try{await salvar("estoque_fornecedores",{...form,id:form.id||undefined,origem:"GESTAO_ESTOQUE"});setForm(null);setAviso({tipo:"ok",texto:"Fornecedor salvo."});await aoRecarregar();}catch(e){setAviso({tipo:"erro",texto:e.message});}finally{setSalvando(false)}};
 const gravarAvaliacao=async()=>{const notas=[1,2,3,4].map(i=>Number(avaliar["criterio"+i]));if(notas.some(x=>![0,1,2].includes(x))){setAviso({tipo:"erro",texto:"As notas dos quatro critérios devem ser 0, 1 ou 2."});return;}const nota=notas.reduce((a,b)=>a+b,0);const classificacao=nota<=2?"RUIM":nota<=5?"BOM":"ÓTIMO";const tipo=avaliar.tipoAvaliacao||"INICIAL";const resultado=(avaliar.resultadoFinal||"").toUpperCase();if(!String(avaliar.avaliador||"").trim()){setAviso({tipo:"erro",texto:"Avaliador é obrigatório."});return;}if(String(avaliar.requerQualificacao||"SIM").toUpperCase()!=="SIM"){setAviso({tipo:"erro",texto:"QUALIFICAÇÃO NÃO SE APLICA para este fornecedor."});return;}if(!["QUALIFICADO","QUALIFICADO PORÉM REINCIDÊNCIA O DESQUALIFICA","DESQUALIFICADO"].includes(resultado)){setAviso({tipo:"erro",texto:"Selecione o resultado final da avaliação."});return;}if(tipo==="INICIAL"&&avaliar.problemaGrave==="SIM"&&!String(avaliar.relatoProblemaGrave||"").trim()){setAviso({tipo:"erro",texto:"Informe o relato do problema grave."});return;}if(tipo==="REAVALIACAO_SEMESTRAL"&&avaliar.evidenciaSimNao==="SIM"&&!String(avaliar.evidenciaReavaliacao||"").trim()){setAviso({tipo:"erro",texto:"Informe a evidência da reavaliação."});return;}setSalvando(true);try{const agora=new Date();const proxima=new Date(agora);if(String(avaliar.periodicidade||"").toUpperCase()==="SEMESTRAL")proxima.setMonth(proxima.getMonth()+6);await salvar("estoque_avaliacoes_fornecedor",{fornecedorId:avaliar.id,cnpj:avaliar.cnpj,tipoAvaliacao:tipo,dataAvaliacao:agora.toISOString(),avaliador:avaliar.avaliador||"",criterio1Nota:notas[0],criterio1Relato:avaliar.criterio1Relato||"",criterio2Nota:notas[1],criterio2Relato:avaliar.criterio2Relato||"",criterio3Nota:notas[2],criterio3Relato:avaliar.criterio3Relato||"",criterio4Nota:notas[3],criterio4Relato:avaliar.criterio4Relato||"",notaFinal:nota,classificacaoNota:classificacao,problemaGrave:tipo==="INICIAL"?(avaliar.problemaGrave||"NÃO"):"",relatoProblemaGrave:tipo==="INICIAL"?(avaliar.relatoProblemaGrave||""):"",evidenciaReavaliacao:tipo==="REAVALIACAO_SEMESTRAL"?`${avaliar.evidenciaSimNao||"NÃO"}| ${avaliar.evidenciaReavaliacao||""}`:"",resultadoFinal:resultado,observacao:avaliar.observacao||""});await salvar("estoque_fornecedores",{...avaliar,resultadoQualificacao:resultado,dataUltimaAvaliacao:agora.toISOString(),dataProximaAvaliacao:String(avaliar.periodicidade||"").toUpperCase()==="SEMESTRAL"?proxima.toISOString():"",statusReavaliacao:String(avaliar.periodicidade||"").toUpperCase()==="SEMESTRAL"?"EM DIA":"NÃO SE APLICA"});setAvaliar(null);setAviso({tipo:"ok",texto:`Avaliação registrada: ${resultado}. Nota ${nota}/8 — ${classificacao}.`});await aoRecarregar();}catch(e){setAviso({tipo:"erro",texto:e.message});}finally{setSalvando(false)}};
 return <div className="space-y-4"><Aviso aviso={aviso} aoFechar={()=>setAviso(null)}/><div className="flex gap-2"><div className="relative flex-1"><Search size={16} className="absolute left-3 top-2.5 text-slate-400"/><input className="input pl-9" value={busca} onChange={e=>setBusca(e.target.value)} placeholder="Buscar fornecedor, CNPJ ou tipo..."/></div>{podeEditar()&&<button className="btn-primary" onClick={novo}><Plus size={15}/>Novo fornecedor</button>}</div><Card className="overflow-hidden p-0"><div className="overflow-x-auto"><table className="w-full text-sm"><thead className="bg-slate-50 text-left text-xs uppercase text-slate-500"><tr>{["ID","Fornecedor","CNPJ","Tipo","Status","Qualificação","Documentos","Ações"].map(h=><th key={h} className="px-4 py-3">{h}</th>)}</tr></thead><tbody className="divide-y">{lista.map(x=><tr key={x.id}><td className="px-4 py-3">{x.id}</td><td className="px-4 py-3 font-medium">{x.nome}</td><td className="px-4 py-3">{x.cnpj||"—"}</td><td className="px-4 py-3">{x.tipoFornecedor||x.tipoServico||"—"}</td><td className="px-4 py-3">{x.status||"ATIVO"}</td><td className="px-4 py-3">{x.resultadoQualificacao||x.statusReavaliacao||"PENDENTE"}</td><td className="px-4 py-3"><b>{resumoDoc(x)}</b><small className="block text-slate-500">{documentos.filter(d=>d.fornecedorId===x.id).length} arquivo(s)</small></td><td className="px-4 py-3"><button className="btn-outline text-xs" onClick={()=>setAvaliar({...x,tipoAvaliacao:avaliacoes.some(a=>a.fornecedorId===x.id)?"REAVALIACAO_SEMESTRAL":"INICIAL",criterio1:0,criterio2:0,criterio3:0,criterio4:0,criterio1Relato:"",criterio2Relato:"",criterio3Relato:"",criterio4Relato:"",problemaGrave:"NÃO",relatoProblemaGrave:"",evidenciaSimNao:"NÃO",evidenciaReavaliacao:"",resultadoFinal:"QUALIFICADO",avaliador:""})}>Avaliar</button></td></tr>)}</tbody></table></div></Card>
 {form&&<Modal titulo="Fornecedor" aberto aoFechar={()=>setForm(null)} largura="max-w-4xl"><div className="grid gap-4 md:grid-cols-2"><Campo rotulo="Nome do fornecedor" value={form.nome} onChange={e=>setForm({...form,nome:e.target.value})}/><Campo rotulo="CNPJ" value={form.cnpj} onChange={e=>setForm({...form,cnpj:e.target.value})}/><Campo rotulo="Endereço completo" value={form.endereco} onChange={e=>setForm({...form,endereco:e.target.value})}/><Campo rotulo="Telefone / contato" value={form.telefone} onChange={e=>setForm({...form,telefone:e.target.value})}/><Campo rotulo="E-mail" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/><Campo rotulo="Website" value={form.website} onChange={e=>setForm({...form,website:e.target.value})}/><Campo rotulo="Tipo de serviço/suprimento" value={form.tipoServico} onChange={e=>setForm({...form,tipoServico:e.target.value})}/><Campo rotulo="Tipo de fornecedor" value={form.tipoFornecedor} onChange={e=>setForm({...form,tipoFornecedor:e.target.value})}/></div><div className="mt-5 flex justify-end gap-2"><button className="btn-outline" onClick={()=>setForm(null)}>Cancelar</button><button className="btn-primary" disabled={salvando||!form.nome} onClick={gravar}>Salvar</button></div></Modal>}
 {avaliar&&<Modal titulo={`Avaliação — ${avaliar.nome}`} aberto aoFechar={()=>setAvaliar(null)} largura="max-w-4xl"><div className="mb-4 rounded-lg bg-slate-50 p-3 text-sm text-slate-600">Tipo: <b>{avaliar.tipoAvaliacao==="INICIAL"?"Avaliação inicial":"Reavaliação semestral"}</b>. Notas de 0 a 2 por critério; classificação: 0–2 RUIM, 3–5 BOM e 6–8 ÓTIMO.</div><Campo rotulo="Avaliador" value={avaliar.avaliador||""} onChange={e=>setAvaliar({...avaliar,avaliador:e.target.value})}/><div className="mt-4 grid gap-4 sm:grid-cols-2">{[1,2,3,4].map(i=><div key={i} className="rounded-lg border p-3"><Campo rotulo={`Critério ${i} — nota`} type="number" min="0" max="2" step="1" value={avaliar["criterio"+i]} onChange={e=>setAvaliar({...avaliar,["criterio"+i]:e.target.value})}/><Campo rotulo="Relato / resposta" value={avaliar["criterio"+i+"Relato"]||""} onChange={e=>setAvaliar({...avaliar,["criterio"+i+"Relato"]:e.target.value})}/></div>)}</div>{avaliar.tipoAvaliacao==="INICIAL"?<><label className="mt-4 block"><span className="label">Problema grave</span><select className="input" value={avaliar.problemaGrave} onChange={e=>setAvaliar({...avaliar,problemaGrave:e.target.value})}><option>NÃO</option><option>SIM</option></select></label>{avaliar.problemaGrave==="SIM"&&<Campo rotulo="Relato do problema grave" value={avaliar.relatoProblemaGrave||""} onChange={e=>setAvaliar({...avaliar,relatoProblemaGrave:e.target.value})}/>}</>:<><label className="mt-4 block"><span className="label">Neste período houve evidência que desqualifique o provedor externo?</span><select className="input" value={avaliar.evidenciaSimNao} onChange={e=>setAvaliar({...avaliar,evidenciaSimNao:e.target.value})}><option>NÃO</option><option>SIM</option></select></label>{avaliar.evidenciaSimNao==="SIM"&&<Campo rotulo="Evidência / descrição" value={avaliar.evidenciaReavaliacao||""} onChange={e=>setAvaliar({...avaliar,evidenciaReavaliacao:e.target.value})}/>}</>}<label className="mt-4 block"><span className="label">Resultado final</span><select className="input" value={avaliar.resultadoFinal} onChange={e=>setAvaliar({...avaliar,resultadoFinal:e.target.value})}><option>QUALIFICADO</option><option>QUALIFICADO PORÉM REINCIDÊNCIA O DESQUALIFICA</option><option>DESQUALIFICADO</option></select></label><Campo rotulo="Observação" value={avaliar.observacao||""} onChange={e=>setAvaliar({...avaliar,observacao:e.target.value})}/><div className="mt-5 flex justify-end"><button className="btn-primary" disabled={salvando} onClick={gravarAvaliacao}>Concluir avaliação</button></div></Modal>}</div>;
}

function Pedidos({pedidos,produtos,fornecedores,inspecoes,aoRecarregar}){
 const [form,setForm]=useState(null);const [inspecao,setInspecao]=useState(null);const [aviso,setAviso]=useState(null);const [salvando,setSalvando]=useState(false);
 const codigoDe=p=>p.pedidoCodigo||p.idPedido||p.codigoPedido||String(p.id||"").replace(/-item-\\d+$/,"");
 const grupos=useMemo(()=>{const m=new Map();for(const p of pedidos){const k=codigoDe(p);if(!m.has(k))m.set(k,[]);m.get(k).push(p)}return [...m.entries()].sort((a,b)=>String(b[0]).localeCompare(String(a[0]),"pt-BR",{numeric:true}))},[pedidos]);
 const proximoCodigo=()=>{let mx=0;for(const p of pedidos){const s=codigoDe(p);const m=String(s).match(/(\\d+)/g);if(m)mx=Math.max(mx,Number(m[m.length-1])||0)}return "PC-"+String(mx+1).padStart(4,"0")};
 const itemVazio=()=>({produto:"",produtoId:"",grupo:"",especificacao:"",unidade:"UN",conteudoKit:"1",quantidadeKits:"1",valor:""});
 const novo=()=>setForm({pedidoCodigo:proximoCodigo(),dataPedido:new Date().toISOString().slice(0,10),fornecedor:"",cnpj:"",responsavel:"",observacao:"",status:"PENDENTE",prazoEntrega:"",formaPagamento:"",valorFrete:"0",valorImposto:"0",itens:[itemVazio()]});
 const mudarItem=(i,k,v)=>setForm(x=>({...x,itens:x.itens.map((it,j)=>j===i?{...it,[k]:v}:it)}));
 const escolherProduto=(i,nome)=>{const p=produtos.find(x=>x.produto===nome)||{};setForm(x=>({...x,itens:x.itens.map((it,j)=>j===i?{...it,produto:nome,produtoId:p.id||"",grupo:p.grupo||"",especificacao:p.especificacao||"",unidade:p.unidade||"UN",conteudoKit:p.conteudoKit||1}:it)}))};
 const gravar=async()=>{if(!form.fornecedor)return setAviso({tipo:"erro",texto:"Selecione o fornecedor."});if(!form.itens.length||form.itens.some(i=>!i.produto||n(i.quantidadeKits)<=0))return setAviso({tipo:"erro",texto:"Informe produto e quantidade válida em todos os itens."});setSalvando(true);try{for(let i=0;i<form.itens.length;i++){const it=form.itens[i];await salvar("estoque_pedidos",{...form,itens:undefined,...it,id:`${form.pedidoCodigo}-item-${String(i+1).padStart(2,"0")}`,pedidoCodigo:form.pedidoCodigo,itemNumero:i+1,valor:n(it.valor),conteudoKit:n(it.conteudoKit),quantidadeKits:n(it.quantidadeKits),valorFrete:i===0?n(form.valorFrete):0,valorImposto:i===0?n(form.valorImposto):0,origem:"GESTAO_ESTOQUE"})}setForm(null);setAviso({tipo:"ok",texto:"Pedido com "+form.itens.length+" item(ns) salvo."});await aoRecarregar()}catch(e){setAviso({tipo:"erro",texto:e.message})}finally{setSalvando(false)}};
 const excluirPedido=async(codigo,itens)=>{if(itens.some(x=>String(x.status||"PENDENTE").toUpperCase()!=="PENDENTE"))return setAviso({tipo:"erro",texto:"Somente pedidos PENDENTES podem ser excluídos."});if(!window.confirm(`Excluir o pedido ${codigo} e seus ${itens.length} item(ns)?`))return;setSalvando(true);try{await estoquePedidoExcluir(itens.map(x=>x.id));setAviso({tipo:"ok",texto:"Pedido excluído."});await aoRecarregar()}catch(e){setAviso({tipo:"erro",texto:e.message})}finally{setSalvando(false)}};
 const abrirIR=(codigo,itens)=>setInspecao({idPedido:codigo,itens,dataRecebimento:new Date().toISOString().slice(0,10),fabricante:"",lote:"",validade:"",notaFinal:"",statusQualidade:"ÓTIMO",observacoes:""});
 const salvarIR=async()=>{if(!inspecao.dataRecebimento||!inspecao.lote)return setAviso({tipo:"erro",texto:"Data de recebimento e lote são obrigatórios."});setSalvando(true);try{await salvar("estoque_inspecoes",{idPedido:inspecao.idPedido,dataRecebimento:inspecao.dataRecebimento,fabricante:inspecao.fabricante,lote:inspecao.lote,validade:inspecao.validade,notaFinal:n(inspecao.notaFinal),statusQualidade:inspecao.statusQualidade,observacoes:inspecao.observacoes||""});for(const p of inspecao.itens)await salvar("estoque_pedidos",{...p,status:"RECEBIDO"});setInspecao(null);setAviso({tipo:"ok",texto:"Inspeção de recebimento registrada."});await aoRecarregar()}catch(e){setAviso({tipo:"erro",texto:e.message})}finally{setSalvando(false)}};
 return <div className="space-y-4"><Aviso aviso={aviso} aoFechar={()=>setAviso(null)}/><div className="flex justify-end">{podeEditar()&&<button className="btn-primary" onClick={novo}><Plus size={15}/>Novo pedido</button>}</div><Card className="overflow-hidden p-0"><div className="overflow-x-auto"><table className="w-full text-sm"><thead className="bg-slate-50 text-left text-xs uppercase text-slate-500"><tr>{["Pedido","Data","Fornecedor","Itens","Valor itens","Status","IR","Ações"].map(h=><th className="px-4 py-3" key={h}>{h}</th>)}</tr></thead><tbody className="divide-y">{grupos.map(([codigo,itens])=>{const p=itens[0];const status=[...new Set(itens.map(x=>x.status||"PENDENTE"))].join(" / ");const total=itens.reduce((s,x)=>s+n(x.valor),0);const ir=inspecoes.some(i=>i.idPedido===codigo||i.idPedido===p.id);return <tr key={codigo}><td className="px-4 py-3 font-medium">{codigo}</td><td className="px-4 py-3">{p.dataPedido||"—"}</td><td className="px-4 py-3">{p.fornecedor||"—"}</td><td className="px-4 py-3">{itens.length}<small className="block text-slate-500">{itens.map(x=>x.produto).filter(Boolean).join(", ")}</small></td><td className="px-4 py-3">{total.toLocaleString("pt-BR",{style:"currency",currency:"BRL"})}</td><td className="px-4 py-3">{status}</td><td className="px-4 py-3">{ir?"Concluída":<button className="btn-outline text-xs" onClick={()=>abrirIR(codigo,itens)}>Inspecionar</button>}</td><td className="px-4 py-3">{podeEditar()&&itens.every(x=>String(x.status||"PENDENTE").toUpperCase()==="PENDENTE")&&<button className="btn-outline text-xs" disabled={salvando} onClick={()=>excluirPedido(codigo,itens)}>Excluir</button>}</td></tr>})}</tbody></table></div></Card>
 {form&&<Modal titulo={`Pedido de Compra — ${form.pedidoCodigo}`} aberto aoFechar={()=>setForm(null)} largura="max-w-5xl"><div className="grid gap-4 md:grid-cols-3"><Campo rotulo="Data do pedido" type="date" value={form.dataPedido} onChange={e=>setForm({...form,dataPedido:e.target.value})}/><label><span className="label">Fornecedor</span><select className="input" value={form.fornecedor} onChange={e=>{const x=fornecedores.find(f=>f.nome===e.target.value);setForm({...form,fornecedor:e.target.value,cnpj:x?.cnpj||""})}}><option value="">Selecione</option>{fornecedores.map(f=><option key={f.id} value={f.nome}>{f.nome}</option>)}</select></label><Campo rotulo="CNPJ" value={form.cnpj} onChange={e=>setForm({...form,cnpj:e.target.value})}/><Campo rotulo="Prazo de entrega" value={form.prazoEntrega} onChange={e=>setForm({...form,prazoEntrega:e.target.value})}/><Campo rotulo="Forma de pagamento" value={form.formaPagamento} onChange={e=>setForm({...form,formaPagamento:e.target.value})}/><Campo rotulo="Responsável" value={form.responsavel} onChange={e=>setForm({...form,responsavel:e.target.value})}/><Campo rotulo="Frete total" type="number" step="0.01" value={form.valorFrete} onChange={e=>setForm({...form,valorFrete:e.target.value})}/><Campo rotulo="Imposto total" type="number" step="0.01" value={form.valorImposto} onChange={e=>setForm({...form,valorImposto:e.target.value})}/><Campo rotulo="Observação" value={form.observacao} onChange={e=>setForm({...form,observacao:e.target.value})}/></div><div className="mt-5 space-y-3"><div className="flex items-center justify-between"><h3 className="font-semibold">Itens do pedido</h3><button className="btn-outline text-xs" onClick={()=>setForm({...form,itens:[...form.itens,itemVazio()]})}><Plus size={14}/>Adicionar item</button></div>{form.itens.map((it,i)=><div key={i} className="grid gap-3 rounded-xl border p-3 md:grid-cols-5"><label className="md:col-span-2"><span className="label">Produto</span><select className="input" value={it.produto} onChange={e=>escolherProduto(i,e.target.value)}><option value="">Selecione</option>{produtos.map(p=><option key={p.id} value={p.produto}>{p.produto}</option>)}</select></label><Campo rotulo="Qtd. kits" type="number" min="1" value={it.quantidadeKits} onChange={e=>mudarItem(i,"quantidadeKits",e.target.value)}/><Campo rotulo="Valor do item" type="number" step="0.01" value={it.valor} onChange={e=>mudarItem(i,"valor",e.target.value)}/><div className="flex items-end"><button className="btn-outline w-full" disabled={form.itens.length===1} onClick={()=>setForm({...form,itens:form.itens.filter((_,j)=>j!==i)})}>Remover</button></div><div className="md:col-span-5 text-xs text-slate-500">{it.grupo||"—"} · {it.especificacao||"—"} · {it.unidade||"—"} · conteúdo kit {it.conteudoKit||1}</div></div>)}</div><div className="mt-5 flex justify-end"><button className="btn-primary" disabled={salvando} onClick={gravar}>Salvar pedido</button></div></Modal>}
 {inspecao&&<Modal titulo={`Inspeção de Recebimento — ${inspecao.idPedido}`} aberto aoFechar={()=>setInspecao(null)}><div className="grid gap-4 sm:grid-cols-2"><Campo rotulo="Data de recebimento" type="date" value={inspecao.dataRecebimento} onChange={e=>setInspecao({...inspecao,dataRecebimento:e.target.value})}/><Campo rotulo="Fabricante" value={inspecao.fabricante} onChange={e=>setInspecao({...inspecao,fabricante:e.target.value})}/><Campo rotulo="Lote" value={inspecao.lote} onChange={e=>setInspecao({...inspecao,lote:e.target.value})}/><Campo rotulo="Validade" type="date" value={inspecao.validade} onChange={e=>setInspecao({...inspecao,validade:e.target.value})}/><Campo rotulo="Nota final" type="number" value={inspecao.notaFinal} onChange={e=>setInspecao({...inspecao,notaFinal:e.target.value})}/><Campo rotulo="Status da qualidade" value={inspecao.statusQualidade} onChange={e=>setInspecao({...inspecao,statusQualidade:e.target.value})}/><div className="sm:col-span-2"><Campo rotulo="Observações" value={inspecao.observacoes} onChange={e=>setInspecao({...inspecao,observacoes:e.target.value})}/></div></div><div className="mt-3 text-xs text-slate-500">{inspecao.itens.length} item(ns) vinculados a este pedido.</div><div className="mt-5 flex justify-end"><button className="btn-primary" disabled={salvando} onClick={salvarIR}>Concluir inspeção</button></div></Modal>}</div>;
}

function Relatorios({lotes,movimentos}){
 const vencidos=lotes.filter(l=>l.validade&&l.validade<new Date().toISOString().slice(0,10)&&n(l.totalAtual??l.qtdAtual)>0);
 const criticos=lotes.filter(l=>statusLote(l)==="CRÍTICO");
 return <div className="grid gap-4 lg:grid-cols-2"><Card><h2 className="font-display font-bold">Estoque crítico</h2><p className="mt-1 text-sm text-slate-500">{criticos.length} lote(s) abaixo ou no mínimo definido.</p>{criticos.slice(0,20).map(l=><p key={l.id} className="mt-2 text-sm">{l.produto} · {l.lote} · <b>{n(l.totalAtual??l.qtdAtual)} {l.unidade}</b></p>)}</Card><Card><h2 className="font-display font-bold">Vencidos com saldo</h2><p className="mt-1 text-sm text-slate-500">{vencidos.length} lote(s).</p>{vencidos.slice(0,20).map(l=><p key={l.id} className="mt-2 text-sm">{l.produto} · {l.lote} · {l.validade}</p>)}</Card><Card className="lg:col-span-2"><h2 className="font-display font-bold">Movimentações</h2><p className="mt-1 text-sm text-slate-500">{movimentos.length} movimentação(ões) registradas na nova Gestão de Estoque.</p></Card></div>;
}

function statusDocFornecedor(regra,tipo,doc){const r=String(regra||"").toUpperCase();if(r==="NÃO SE APLICA")return "NÃO SE APLICA";if(!doc)return r==="OBRIGATÓRIO"?"PENDENTE":"OPCIONAL";if(String(tipo?.possuiValidade||"NÃO").toUpperCase()!=="SIM"||!doc.dataValidade)return "REGULAR";const h=new Date();h.setHours(0,0,0,0);const v=new Date(String(doc.dataValidade).slice(0,10)+"T12:00:00");if(Number.isNaN(v.getTime()))return "REGULAR";if(v<h)return "VENCIDO";const d=Number(tipo?.prazoAlertaDias);if(Number.isFinite(d)){const lim=new Date(h);lim.setDate(lim.getDate()+d);if(v<=lim)return "VENCENDO";}return "REGULAR"}

function Configuracoes({config,tiposDocumentos=[],regrasDocumentos=[],aoRecarregar}){
 const [form,setForm]=useState(()=>config[0]||{grupos:"Reagentes\nMateriais\nMRC",unidades:"UN\nmL\ng\nL",usuarios:""});const [aviso,setAviso]=useState(null); const [doc,setDoc]=useState({nomeDocumento:"",descricao:"",possuiValidade:"NÃO",prazoAlertaDias:""}); const [regra,setRegra]=useState({tipoFornecedor:"COMPRAS",tipoDocumentoId:"",regra:"OBRIGATÓRIO"});
 const gravar=async()=>{try{await salvar("estoque_config",{...form,id:form.id||"config-principal"});setAviso({tipo:"ok",texto:"Configurações salvas."});await aoRecarregar();}catch(e){setAviso({tipo:"erro",texto:e.message})}}; const salvarTipo=async()=>{if(!doc.nomeDocumento.trim())return setAviso({tipo:"erro",texto:"Nome do documento é obrigatório."});if(doc.possuiValidade==="SIM"&&doc.prazoAlertaDias!==""&&(!/^\\d+$/.test(doc.prazoAlertaDias)||n(doc.prazoAlertaDias)<0))return setAviso({tipo:"erro",texto:"Prazo de alerta inválido."});try{await salvar("estoque_tipos_documentos_fornecedor",{...doc,nomeDocumento:doc.nomeDocumento.trim().toUpperCase(),prazoAlertaDias:doc.prazoAlertaDias===""?"":n(doc.prazoAlertaDias),ativo:"SIM"});setDoc({nomeDocumento:"",descricao:"",possuiValidade:"NÃO",prazoAlertaDias:""});await aoRecarregar();setAviso({tipo:"ok",texto:"Tipo documental cadastrado."})}catch(e){setAviso({tipo:"erro",texto:e.message})}}; const salvarRegra=async()=>{const tipo=tiposDocumentos.find(t=>(t.id||t.idTipoDocumento)===regra.tipoDocumentoId);if(!tipo)return setAviso({tipo:"erro",texto:"Selecione o documento."});if(regrasDocumentos.some(r=>String(r.tipoFornecedor).toUpperCase()===regra.tipoFornecedor&&r.tipoDocumentoId===regra.tipoDocumentoId&&String(r.ativo||"SIM").toUpperCase()!=="NÃO"))return setAviso({tipo:"erro",texto:"Já existe regra para este tipo de fornecedor e documento."});try{await salvar("estoque_regras_documentos_fornecedor",{...regra,tipoDocumento:tipo.nomeDocumento,ativo:"SIM"});setRegra({...regra,tipoDocumentoId:""});await aoRecarregar();setAviso({tipo:"ok",texto:"Regra documental cadastrada."})}catch(e){setAviso({tipo:"erro",texto:e.message})}};
 return <div><Aviso aviso={aviso} aoFechar={()=>setAviso(null)}/><Card><div className="grid gap-4 md:grid-cols-3">{[["grupos","Grupos"],["unidades","Unidades"],["usuarios","Usuários"]].map(([k,r])=><label key={k}><span className="label">{r} — um por linha</span><textarea className="input min-h-48" value={form[k]||""} onChange={e=>setForm({...form,[k]:e.target.value})}/></label>)}</div><div className="mt-5 flex justify-end"><button className="btn-primary" onClick={gravar}>Salvar configurações</button></div></Card><div className="mt-4 grid gap-4 lg:grid-cols-2"><Card><h3 className="font-semibold">Tipos de documentos de fornecedores</h3><div className="mt-3 grid gap-3"><Campo rotulo="Nome do documento" value={doc.nomeDocumento} onChange={e=>setDoc({...doc,nomeDocumento:e.target.value})}/><Campo rotulo="Descrição" value={doc.descricao} onChange={e=>setDoc({...doc,descricao:e.target.value})}/><label><span className="label">Possui validade?</span><select className="input" value={doc.possuiValidade} onChange={e=>setDoc({...doc,possuiValidade:e.target.value})}><option>NÃO</option><option>SIM</option></select></label>{doc.possuiValidade==="SIM"&&<Campo rotulo="Alerta antes do vencimento (dias)" type="number" min="0" value={doc.prazoAlertaDias} onChange={e=>setDoc({...doc,prazoAlertaDias:e.target.value})}/>}<button className="btn-primary" onClick={salvarTipo}>Cadastrar tipo</button></div><div className="mt-4 text-sm">{tiposDocumentos.map(t=><div key={t.id||t.idTipoDocumento} className="border-t py-2"><b>{t.nomeDocumento}</b> · {t.possuiValidade==="SIM"?`validade / alerta ${t.prazoAlertaDias||0} dias`:"sem validade"}</div>)}</div></Card><Card><h3 className="font-semibold">Matriz documental por tipo de fornecedor</h3><div className="mt-3 grid gap-3"><Campo rotulo="Tipo de fornecedor" value={regra.tipoFornecedor} onChange={e=>setRegra({...regra,tipoFornecedor:e.target.value.toUpperCase()})}/><label><span className="label">Documento</span><select className="input" value={regra.tipoDocumentoId} onChange={e=>setRegra({...regra,tipoDocumentoId:e.target.value})}><option value="">Selecione...</option>{tiposDocumentos.filter(t=>String(t.ativo||"SIM").toUpperCase()!=="NÃO").map(t=><option key={t.id||t.idTipoDocumento} value={t.id||t.idTipoDocumento}>{t.nomeDocumento}</option>)}</select></label><label><span className="label">Regra</span><select className="input" value={regra.regra} onChange={e=>setRegra({...regra,regra:e.target.value})}><option>OBRIGATÓRIO</option><option>OPCIONAL</option><option>NÃO SE APLICA</option></select></label><button className="btn-primary" onClick={salvarRegra}>Cadastrar regra</button></div><div className="mt-4 text-sm">{regrasDocumentos.map(r=><div key={r.id} className="border-t py-2"><b>{r.tipoFornecedor}</b> · {r.tipoDocumento} · {r.regra}</div>)}</div></Card></div></div>;
}

function Etiquetas({lotes}){return <Card><h2 className="font-display text-lg font-bold">Emissão de etiquetas</h2><p className="mt-1 text-sm text-slate-600">Selecione os lotes para conferência e impressão.</p><div className="mt-4 grid gap-2 md:grid-cols-2">{lotes.filter(l=>n(l.totalAtual??l.qtdAtual)>0).slice(0,100).map(l=><label key={l.id} className="flex items-center gap-3 rounded-xl border border-slate-200 p-3 text-sm"><input type="checkbox"/><span><b>{l.codigoID||l.codigoAuto}</b> · {l.produto}<small className="block text-slate-500">Lote {l.lote} · Validade {l.validade||"—"} · Saldo {n(l.totalAtual??l.qtdAtual)} {l.unidade||""}</small></span></label>)}</div></Card>}

function CadastroInsumos({produtos,aoRecarregar}){
  const [busca,setBusca]=useState("");
  const [form,setForm]=useState(null);
  const [gravando,setGravando]=useState(false);
  const [aviso,setAviso]=useState(null);
  const lista=useMemo(()=>produtos.filter(p=>[p.id,p.produto,p.especificacao,p.grupo,p.fornecedorAtual].join(" ").toLowerCase().includes(busca.toLowerCase())),[produtos,busca]);
  const novo=()=>setForm({id:"",fornecedorAtual:"",grupo:"",produto:"",especificacao:"",requerCertificado:"NAO",unidade:"UN",conteudoKit:"",qtdMinima:"",setor:"",statusQuantidade:"ATIVO",statusCompra:""});
  const gravar=async()=>{
    setGravando(true);
    try{await salvar("estoque_produtos_base",{...form,id:form.id||undefined,qtdMinima:n(form.qtdMinima),conteudoKit:n(form.conteudoKit),origem:"GESTAO_ESTOQUE"});setForm(null);setAviso({tipo:"ok",texto:"Insumo salvo."});await aoRecarregar();}
    catch(e){setAviso({tipo:"erro",texto:e.message});}finally{setGravando(false);}
  };
  return <div>
    <Aviso aviso={aviso} aoFechar={()=>setAviso(null)}/>
    <div className="mb-4 flex flex-wrap items-center gap-2"><div className="relative min-w-56 flex-1"><Search className="absolute left-3 top-2.5 text-slate-400" size={16}/><input className="input pl-9" placeholder="Buscar ID, produto, grupo, fornecedor..." value={busca} onChange={e=>setBusca(e.target.value)}/></div>{podeEditar()&&<button className="btn-primary" onClick={novo}><Plus size={15}/> Novo insumo</button>}</div>
    <Card className="overflow-hidden p-0"><div className="overflow-x-auto"><table className="w-full text-sm"><thead className="bg-slate-50 text-left text-xs uppercase text-slate-500"><tr>{["ID","Grupo","Produto","Especificação","Fornecedor atual","Unidade","Qtd. mínima","Setor","Status"].map(h=><th key={h} className="px-4 py-3">{h}</th>)}</tr></thead><tbody className="divide-y divide-slate-100">{lista.map(p=><tr key={p.id} className="hover:bg-slate-50"><td className="px-4 py-3 font-medium">{p.id}</td><td className="px-4 py-3">{p.grupo||"—"}</td><td className="px-4 py-3 font-medium text-slate-900">{p.produto||"—"}</td><td className="px-4 py-3">{p.especificacao||"—"}</td><td className="px-4 py-3">{p.fornecedorAtual||"—"}</td><td className="px-4 py-3">{p.unidade||"—"}</td><td className="px-4 py-3">{p.qtdMinima??"—"}</td><td className="px-4 py-3">{p.setor||"—"}</td><td className="px-4 py-3">{p.statusQuantidade||"—"}</td></tr>)}</tbody></table>{!lista.length&&<p className="p-6 text-center text-sm text-slate-500">Nenhum insumo encontrado.</p>}</div></Card>
    {form&&<Modal titulo="Novo insumo" aberto aoFechar={()=>setForm(null)} largura="max-w-3xl"><div className="grid gap-4 sm:grid-cols-2"><Campo rotulo="ID" value={form.id} onChange={e=>setForm({...form,id:e.target.value})} placeholder="Gerado automaticamente se vazio"/><Campo rotulo="Fornecedor atual" value={form.fornecedorAtual} onChange={e=>setForm({...form,fornecedorAtual:e.target.value})}/><Campo rotulo="Grupo" value={form.grupo} onChange={e=>setForm({...form,grupo:e.target.value})}/><Campo rotulo="Produto" value={form.produto} onChange={e=>setForm({...form,produto:e.target.value})}/><label className="block sm:col-span-2"><span className="label">Especificação</span><input className="input" value={form.especificacao} onChange={e=>setForm({...form,especificacao:e.target.value})}/></label><Campo rotulo="Unidade" value={form.unidade} onChange={e=>setForm({...form,unidade:e.target.value})}/><Campo rotulo="Conteúdo do kit" type="number" value={form.conteudoKit} onChange={e=>setForm({...form,conteudoKit:e.target.value})}/><Campo rotulo="Quantidade mínima" type="number" value={form.qtdMinima} onChange={e=>setForm({...form,qtdMinima:e.target.value})}/><Campo rotulo="Setor" value={form.setor} onChange={e=>setForm({...form,setor:e.target.value})}/></div><div className="mt-5 flex justify-end gap-2"><button className="btn-outline" onClick={()=>setForm(null)}>Cancelar</button><button className="btn-primary" disabled={gravando||!form.produto.trim()} onClick={gravar}>{gravando?"Salvando...":"Salvar insumo"}</button></div></Modal>}
  </div>;
}

export default function GestaoEstoque(){
  const [secao,setSecao]=useState("dashboard");
  const [dados,setDados]=useState(null);
  const [erro,setErro]=useState("");
  const carregar=async()=>{try{const r=await carregarColecoes(COLECOES);setDados(r);setErro("");}catch(e){setErro(e.message);}};
  useEffect(()=>{carregar();},[]);
  if(erro&&!dados)return <ErroModulo mensagem={erro} aoTentar={carregar}/>;
  if(!dados)return <CarregandoModulo/>;
  const secoesVisiveis=SECOES.filter(([id])=>podeVerSecao("gestao-estoque",id));
  const secaoEfetiva=secoesVisiveis.some(([id])=>id===secao)?secao:(secoesVisiveis[0]?.[0]||"dashboard");
  const atual=SECOES.find(([id])=>id===secaoEfetiva)||SECOES[0];
  return <div><PageTitle titulo="Gestão de Estoque" descricao="Controle de insumos, lotes, entradas, saídas, fornecedores, compras, inspeções, etiquetas e relatórios."/><div className="mb-5 flex gap-2 overflow-x-auto pb-1">{secoesVisiveis.map(([id,nome,Icone])=><button key={id} type="button" onClick={()=>setSecao(id)} className={secaoEfetiva===id?"btn-primary shrink-0":"btn-outline shrink-0"}><Icone size={15}/>{nome}</button>)}</div>{secaoEfetiva==="dashboard"?<Dashboard produtos={dados.estoque_produtos_base} lotes={dados.estoque_lotes} fornecedores={dados.estoque_fornecedores} pedidos={dados.estoque_pedidos}/>:secaoEfetiva==="cadastro-insumo"?<CadastroInsumos produtos={dados.estoque_produtos_base} aoRecarregar={carregar}/>:secaoEfetiva==="entrada-lote"?<EntradaEstoque produtos={dados.estoque_produtos_base} lotes={dados.estoque_lotes} fornecedores={dados.estoque_fornecedores} aoRecarregar={carregar}/>:secaoEfetiva==="retirada-baixa"?<SaidaEstoque lotes={dados.estoque_lotes} aoRecarregar={carregar}/>:secaoEfetiva==="fornecedores"?<Fornecedores fornecedores={dados.estoque_fornecedores} avaliacoes={dados.estoque_avaliacoes_fornecedor} documentos={dados.estoque_documentos_fornecedor} tiposDocumentos={dados.estoque_tipos_documentos_fornecedor} regrasDocumentos={dados.estoque_regras_documentos_fornecedor} aoRecarregar={carregar}/>:secaoEfetiva==="pedido-compra"?<Pedidos pedidos={dados.estoque_pedidos} produtos={dados.estoque_produtos_base} fornecedores={dados.estoque_fornecedores} inspecoes={dados.estoque_inspecoes} aoRecarregar={carregar}/>:secaoEfetiva==="relatorios"?<Relatorios lotes={dados.estoque_lotes} movimentos={dados.estoque_movimentos}/>:secaoEfetiva==="configuracoes"?<Configuracoes config={dados.estoque_config} tiposDocumentos={dados.estoque_tipos_documentos_fornecedor} regrasDocumentos={dados.estoque_regras_documentos_fornecedor} aoRecarregar={carregar}/>:secaoEfetiva==="etiquetas"?<Etiquetas lotes={dados.estoque_lotes}/>:<Card><h2 className="font-display text-lg font-bold text-slate-900">{atual[1]}</h2><p className="mt-1 text-sm text-slate-600">Estrutura criada. Esta etapa será conectada às regras do sistema legado na sequência da migração.</p></Card>}</div>;
}
