import { useRef, useState } from "react";
import { ArrowLeft, Upload, CheckCircle2, AlertTriangle } from "lucide-react";
import { useNavigate } from "react-router-dom";
import { PageTitle } from "../components/ui.jsx";
import { finNfseHistoricoPreview, finNfseHistoricoImportar } from "../services/financeiro.js";

const moeda=v=>Number(v||0).toLocaleString("pt-BR",{style:"currency",currency:"BRL"});
const dataBR=v=>{const p=String(v||"").slice(0,10).split("-");return p.length===3?`${p[2]}/${p[1]}/${p[0]}`:"—"};

export default function ImportarNfseHistorico(){
 const nav=useNavigate(),ref=useRef(null);const[arquivos,setArquivos]=useState([]),[previa,setPrevia]=useState(null),[erro,setErro]=useState(""),[ok,setOk]=useState(""),[carregando,setCarregando]=useState(false);
 async function selecionar(e){const fs=[...(e.target.files||[])];e.target.value="";setErro("");setOk("");setPrevia(null);if(!fs.length)return;if(fs.length>200){setErro("Selecione no máximo 200 XMLs por lote.");return}try{const out=[];for(const f of fs){if(!/\.xml$/i.test(f.name))continue;if(f.size>8*1024*1024)throw new Error(`${f.name}: arquivo maior que 8 MB.`);out.push({nome:f.name,xml:await f.text()})}if(!out.length)throw new Error("Nenhum XML válido selecionado.");setArquivos(out)}catch(ex){setErro(ex.message)}}
 async function visualizar(){if(!arquivos.length)return;setCarregando(true);setErro("");setOk("");try{setPrevia(await finNfseHistoricoPreview(arquivos))}catch(ex){setErro(ex.message)}finally{setCarregando(false)}}
 async function importar(){if(!previa||!arquivos.length)return;if(!confirm(`Importar o histórico da M Lab?\n\nNovas: ${previa.novas||0}\nJá existentes: ${previa.repetidas||0}\nCancelamentos: ${previa.cancelamentos||0}\n\nRecebimentos NÃO serão criados automaticamente.`))return;setCarregando(true);setErro("");setOk("");try{const r=await finNfseHistoricoImportar(arquivos);setOk(`Importação concluída: ${r.inseridas||0} novas, ${r.atualizadas||0} existentes atualizadas e ${r.canceladas||0} canceladas.`);setArquivos([]);setPrevia(null)}catch(ex){setErro(ex.message)}finally{setCarregando(false)}}
 return <div className="space-y-5"><div className="flex items-center gap-3"><button className="btn-ghost h-9 w-9 p-0" onClick={()=>nav('/financas')}><ArrowLeft size={18}/></button><PageTitle titulo="Importar histórico NFS-e" descricao="Importa XMLs emitidos pela M Lab no Portal Nacional, sem duplicar notas e sem criar recebimentos automaticamente."/></div>
 <div className="rounded-xl border border-sky-200 bg-sky-50 p-4 text-sm text-sky-900"><b>Como usar:</b> no Portal Nacional da NFS-e, baixe/exporte os XMLs das notas emitidas pela M Lab. Você pode selecionar vários XMLs de uma vez. O sistema confere o CNPJ da M Lab e a chave de acesso antes de gravar.</div>
 {erro&&<div className="rounded-xl bg-red-50 p-3 text-sm text-red-700"><AlertTriangle size={16} className="mr-2 inline"/>{erro}</div>}{ok&&<div className="rounded-xl bg-emerald-50 p-3 text-sm text-emerald-700"><CheckCircle2 size={16} className="mr-2 inline"/>{ok}</div>}
 <div className="rounded-2xl border bg-white p-5"><div className="flex flex-col gap-3 md:flex-row md:items-center"><button className="btn-outline" onClick={()=>ref.current?.click()} disabled={carregando}><Upload size={16}/>Selecionar XMLs</button><input ref={ref} type="file" multiple accept=".xml,text/xml,application/xml" className="hidden" onChange={selecionar}/><div className="text-sm text-slate-600">{arquivos.length?`${arquivos.length} arquivo(s) selecionado(s)`:"Nenhum arquivo selecionado"}</div><div className="md:ml-auto"><button className="btn-primary" onClick={visualizar} disabled={!arquivos.length||carregando}>{carregando?"Processando...":"Conferir antes de importar"}</button></div></div></div>
 {previa&&<><div className="grid gap-3 md:grid-cols-5"><div className="rounded-xl border bg-white p-4"><div className="text-xs text-slate-500">Arquivos</div><div className="text-2xl font-bold">{previa.totalArquivos||0}</div></div><div className="rounded-xl border bg-white p-4"><div className="text-xs text-slate-500">Novas</div><div className="text-2xl font-bold text-emerald-700">{previa.novas||0}</div></div><div className="rounded-xl border bg-white p-4"><div className="text-xs text-slate-500">Já existem</div><div className="text-2xl font-bold">{previa.repetidas||0}</div></div><div className="rounded-xl border bg-white p-4"><div className="text-xs text-slate-500">Cancelamentos</div><div className="text-2xl font-bold text-amber-700">{previa.cancelamentos||0}</div></div><div className="rounded-xl border bg-white p-4"><div className="text-xs text-slate-500">Com erro</div><div className="text-2xl font-bold text-red-700">{previa.erros?.length||0}</div></div></div>
 <div className="overflow-x-auto rounded-2xl border bg-white"><table className="min-w-full text-sm"><thead className="bg-slate-50 text-left text-xs uppercase text-slate-500"><tr><th className="px-4 py-3">NF</th><th className="px-4 py-3">Emissão</th><th className="px-4 py-3">Cliente</th><th className="px-4 py-3 text-right">Valor</th><th className="px-4 py-3">Ação</th></tr></thead><tbody>{(previa.amostra||[]).map((x,i)=><tr key={i} className="border-t"><td className="px-4 py-3 font-medium">{x.numero||"—"}</td><td className="px-4 py-3">{dataBR(x.data)}</td><td className="px-4 py-3">{x.cliente||"—"}</td><td className="px-4 py-3 text-right font-semibold">{moeda(x.valor)}</td><td className="px-4 py-3"><span className={x.acao==='IMPORTAR'?"font-semibold text-emerald-700":"text-slate-500"}>{x.acao}</span></td></tr>)}</tbody></table></div>
 {(previa.erros||[]).length>0&&<div className="rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-800"><b>Arquivos não importáveis:</b><div className="mt-2 space-y-1">{previa.erros.slice(0,20).map((x,i)=><div key={i}>{x.arquivo}: {x.erro}</div>)}</div></div>}
 <div className="flex justify-end"><button className="btn-primary" onClick={importar} disabled={carregando||((previa.novas||0)===0&&(previa.cancelamentos||0)===0)}>{carregando?"Importando...":"Importar histórico"}</button></div></>}
 </div>;
}
