import { useEffect, useMemo, useRef, useState } from "react";
import { AlertCircle, ArrowDown, ArrowLeftRight, ArrowUp, BarChart3, CalendarDays, CheckCircle2, ChevronLeft, ChevronRight, CircleDollarSign, Download, Link2, MoreVertical, RefreshCw, RotateCcw, Search, Undo2, Upload, Wallet, X } from "lucide-react";
import { useNavigate } from "react-router-dom";
import { PageTitle } from "../components/ui.jsx";
import { financeiroOpcoes, finMovimentosImportar, finMovimentosPagina } from "../services/financeiro.js";
import { finDesfazerConciliacaoMovimento } from "../services/conciliacaoDesfazer.js";
import { API } from "../lib/api.js";
import { comCracha } from "../lib/sessao.js";
import { nomeMovimento } from "../lib/movimentoNome.js";

const FILTROS_STORAGE_KEY="financeiro.movimentacao.filtros";
const moeda=v=>Number(v||0).toLocaleString("pt-BR",{style:"currency",currency:"BRL"});
const dataBR=v=>{if(!v)return"—";const p=String(v).slice(0,10).split("-");return p.length===3?`${p[2]}/${p[1]}/${p[0]}`:v};
const soDigitos=v=>String(v||"").replace(/\D/g,"");
function lerFiltrosSalvos(iniMes,fimMes){try{const s=JSON.parse(sessionStorage.getItem(FILTROS_STORAGE_KEY)||"{}");return{empresa:s.empresa||"",conta:s.conta||"",busca:s.busca||"",status:s.status||"",tipoMovimento:s.tipoMovimento||"",de:s.de||iniMes,ate:s.ate||fimMes}}catch{return{empresa:"",conta:"",busca:"",status:"",tipoMovimento:"",de:iniMes,ate:fimMes}}}
function tag(b,n){const m=b.match(new RegExp(`<${n}>([^<\\r\\n]+)`,"i"));return m?m[1].trim():""}
function dataOfx(v){const m=String(v||"").match(/^(\d{4})(\d{2})(\d{2})/);return m?`${m[1]}-${m[2]}-${m[3]}`:""}
function lerContaOFX(t){return{banco:tag(t,"BANKID"),agencia:tag(t,"BRANCHID"),conta:tag(t,"ACCTID")}}
function parseOFX(t){return String(t||"").split(/<STMTTRN>/i).slice(1).map(b=>{const valor=Number(tag(b,"TRNAMT").replace(",","."))||0,memo=tag(b,"MEMO"),name=tag(b,"NAME");return{data_movimento:dataOfx(tag(b,"DTPOSTED")),descricao:[name,memo].filter(Boolean).filter((x,i,a)=>a.indexOf(x)===i).join(" · ")||memo||name,tipo:valor>=0?"CREDITO":"DEBITO",valor,fitid:tag(b,"FITID"),documento:tag(b,"CHECKNUM"),origem:"OFX"}}).filter(x=>x.data_movimento&&x.valor!==0)}
function detectarContaOFX(meta,contas,empresaId){const cs=(contas||[]).filter(c=>c.empresa_id===empresaId);if(cs.length===1)return cs[0];const co=soDigitos(meta?.conta),ba=soDigitos(meta?.banco),ag=soDigitos(meta?.agencia);const pc=cs.filter(c=>co&&soDigitos(c.conta)===co);if(pc.length===1)return pc[0];const p=cs.filter(c=>(!ba||soDigitos(c.banco)===ba)&&(!co||soDigitos(c.conta)===co)&&(!ag||soDigitos(c.agencia)===ag));return p.length===1?p[0]:null}
function classificacaoAmigavel(v){const x=String(v||"").toUpperCase();if(x==="ESTORNO")return"Estorno";if(x==="TRANSFERENCIA")return"Transferência";if(x==="MOVIMENTO_INTERNO")return"Movimento bancário";return""}
function situacaoAmigavel(m){if(!m.conciliado)return"Não conciliado";return classificacaoAmigavel(m.classificacao_bancaria)||"Conciliado"}
function situacaoClasses(m){const s=situacaoAmigavel(m);if(s==="Conciliado")return"bg-emerald-50 text-emerald-700 border-emerald-100";if(s==="Não conciliado")return"bg-amber-50 text-amber-700 border-amber-100";if(s==="Estorno")return"bg-blue-50 text-blue-700 border-blue-100";return"bg-slate-100 text-slate-700 border-slate-200"}
async function chamarInterno(corpo){const r=await comCracha(`${API}/ml-financeiro-movimentos-internos`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(corpo)});const b=await r.json().catch(()=>({}));if(!r.ok)throw new Error(b?.erro||"Não foi possível resolver o movimento.");return b}
async function carregarExtrato(f){const r=await comCracha(`${API}/ml-financeiro-movimentacao-extrato`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(f)});const b=await r.json().catch(()=>({}));if(!r.ok)throw new Error(b?.erro||"Não foi possível carregar a movimentação.");return b}

export default function MovimentacaoContaNova(){
 const navigate=useNavigate(),ofxRef=useRef(null);
 const hoje=new Date(),iniMes=`${hoje.getFullYear()}-${String(hoje.getMonth()+1).padStart(2,"0")}-01`,fimMes=new Date(hoje.getFullYear(),hoje.getMonth()+1,0).toISOString().slice(0,10);
 const filtrosIniciais=lerFiltrosSalvos(iniMes,fimMes);
 const [op,setOp]=useState({empresas:[],contas:[]}),[empresa,setEmpresa]=useState(filtrosIniciais.empresa),[conta,setConta]=useState(filtrosIniciais.conta),[itens,setItens]=useState([]);
 const [busca,setBusca]=useState(filtrosIniciais.busca),[status,setStatus]=useState(filtrosIniciais.status),[tipoMovimento,setTipoMovimento]=useState(filtrosIniciais.tipoMovimento),[de,setDe]=useState(filtrosIniciais.de),[ate,setAte]=useState(filtrosIniciais.ate),[deRasc,setDeRasc]=useState(filtrosIniciais.de),[ateRasc,setAteRasc]=useState(filtrosIniciais.ate),[periodoAberto,setPeriodoAberto]=useState(false);
 const [pagina,setPagina]=useState(1),[meta,setMeta]=useState({total:0,paginas:1}),[resumo,setResumo]=useState({entradas:0,saidas:0}),[saldoAtual,setSaldoAtual]=useState(null),[loading,setLoading]=useState(true),[erro,setErro]=useState(""),[aviso,setAviso]=useState(""),[importando,setImportando]=useState(false);
 const [detalhe,setDetalhe]=useState(null),[menu,setMenu]=useState(null),[resolver,setResolver]=useState(null),[classe,setClasse]=useState(""),[relacionadoId,setRelacionadoId]=useState(""),[contrapartidas,setContrapartidas]=useState([]),[salvando,setSalvando]=useState(false);
 const limite=8;
 async function carregar(p=1){setLoading(true);setErro("");try{const[o,m]=await Promise.all([financeiroOpcoes(),carregarExtrato({empresaId:empresa,contaId:conta,busca,status,tipoMovimento,de,ate,pagina:p,limite})]);setOp(o||{empresas:[],contas:[]});setItens(m.itens||[]);setMeta({total:m.total||0,paginas:m.paginas||1});setResumo(m.resumo||{entradas:0,saidas:0});setSaldoAtual(m.saldoAtual??null);setPagina(m.pagina||p)}catch(e){setErro(e.message)}finally{setLoading(false)}}
 useEffect(()=>{const t=setTimeout(()=>carregar(1),180);return()=>clearTimeout(t)},[empresa,conta,busca,status,tipoMovimento,de,ate]);
 useEffect(()=>{try{sessionStorage.setItem(FILTROS_STORAGE_KEY,JSON.stringify({empresa,conta,busca,status,tipoMovimento,de,ate}))}catch{}},[empresa,conta,busca,status,tipoMovimento,de,ate]);
 useEffect(()=>{if(!empresa||conta||!op.contas?.length)return;const cs=op.contas.filter(c=>c.empresa_id===empresa);if(cs.length===1)setConta(cs[0].id)},[empresa,conta,op.contas]);
 const empresaSelecionada=useMemo(()=>op.empresas.find(x=>x.id===empresa),[op.empresas,empresa]);
 const contasEmpresa=useMemo(()=>op.contas.filter(c=>!empresa||c.empresa_id===empresa),[op.contas,empresa]);
 const contaSelecionada=useMemo(()=>op.contas.find(c=>c.id===conta),[op.contas,conta]);
 const resultado=Number(resumo.entradas||0)-Number(resumo.saidas||0),ehMLab=/m\s*lab/i.test(empresaSelecionada?.nome||"")&&!/minas/i.test(empresaSelecionada?.nome||"");
 const periodoTexto=`${dataBR(de)}  →  ${dataBR(ate)}`;
 async function importarOFX(e){const f=e.target.files?.[0];if(!f)return;if(!empresa){setErro("Selecione a empresa antes de atualizar o extrato.");e.target.value="";return}setImportando(true);setErro("");try{const texto=await f.text(),dados=parseOFX(texto),metaConta=lerContaOFX(texto);if(!dados.length)throw new Error("Nenhuma movimentação válida foi encontrada.");const detectada=conta?op.contas.find(c=>c.id===conta):detectarContaOFX(metaConta,op.contas,empresa);if(!detectada)throw new Error("Não foi possível identificar a conta.");setConta(detectada.id);const r=await finMovimentosImportar(empresa,detectada.id,dados);setAviso(`Extrato atualizado: ${r?.inseridos||0} novos e ${r?.ignorados||0} já existentes.`);await carregar(1)}catch(e2){setErro(e2.message)}finally{setImportando(false);e.target.value=""}}
 function aplicarPeriodo(){if(!deRasc||!ateRasc||deRasc>ateRasc){setErro("Informe um período válido.");return}setDe(deRasc);setAte(ateRasc);setPeriodoAberto(false)}
 function abrirMenu(e,m){e.stopPropagation();const r=e.currentTarget.getBoundingClientRect(),w=300;setMenu({item:m,top:Math.max(12,Math.min(window.innerHeight-330,r.bottom+8)),left:Math.max(12,Math.min(window.innerWidth-w-12,r.right-w))})}
 function abrirConciliacao(m){setMenu(null);const tipo=m.tipo==="CREDITO"?"RECEBIMENTO":"DESPESA";navigate(`/financas/conciliacao?tipo=${tipo}&empresaId=${encodeURIComponent(m.empresa_id||"")}&movimentoId=${encodeURIComponent(m.id||"")}`)}
 async function escolherResolucao(tipo,alvoBase=null){const alvo=alvoBase||detalhe||menu?.item;if(!alvo)return;if(tipo==="TITULO")return abrirConciliacao(alvo);setClasse(tipo);setRelacionadoId("");setResolver(alvo);setDetalhe(null);setMenu(null);setErro("");try{if(tipo!=="MOVIMENTO_INTERNO"){const r=await finMovimentosPagina({empresaId:alvo.empresa_id,status:"PENDENTE",tipoMovimento:alvo.tipo==="CREDITO"?"DEBITO":"CREDITO",pagina:1,limite:100});setContrapartidas((r.itens||[]).filter(x=>x.id!==alvo.id&&Math.abs(Number(x.valor||0)-Number(alvo.valor||0))<.01))}else setContrapartidas([])}catch(e){setErro(e.message);setResolver(null)}}
 async function salvarResolucao(){if(!resolver)return;if(classe!=="MOVIMENTO_INTERNO"&&!relacionadoId){setErro("Selecione o movimento correspondente.");return}setSalvando(true);try{await chamarInterno({action:"classificar",movimentoId:resolver.id,classificacao:classe,relacionadoId:classe==="MOVIMENTO_INTERNO"?null:relacionadoId});setResolver(null);setAviso("Movimento resolvido.");await carregar(pagina)}catch(e){setErro(e.message)}finally{setSalvando(false)}}
 async function desfazerClassificacao(m){try{await chamarInterno({action:"desfazer",movimentoId:m.id});setDetalhe(null);await carregar(pagina)}catch(e){setErro(e.message)}}
 async function desfazerConciliacao(m){if(!window.confirm("Deseja realmente desfazer esta conciliação? Se o movimento estiver vinculado a vários títulos, todos os vínculos deste movimento serão removidos."))return;setSalvando(true);setErro("");try{const r=await finDesfazerConciliacaoMovimento(m.id);setDetalhe(null);setAviso(`${r?.removidas||1} conciliação(ões) desfeita(s).`);await carregar(pagina)}catch(e){setErro(e.message)}finally{setSalvando(false)}}
 function exportar(){const linhas=[["Data","Descrição","Documento","Categoria","Tipo","Valor","Saldo","Situação"],...itens.map(m=>[dataBR(m.data_movimento),m.descricao||nomeMovimento(m),m.documento||"",m.categoria_nome||"—",m.tipo==="CREDITO"?"Entrada":"Saída",Number(m.valor||0).toFixed(2).replace(".",","),m.saldo_movimento==null?"":Number(m.saldo_movimento).toFixed(2).replace(".",","),situacaoAmigavel(m)])];const csv=linhas.map(l=>l.map(v=>`"${String(v??"").replaceAll('"','""')}"`).join(";")).join("\n"),url=URL.createObjectURL(new Blob(["\ufeff"+csv],{type:"text/csv;charset=utf-8"})),a=document.createElement("a");a.href=url;a.download=`movimentacao-${de}-${ate}.csv`;a.click();URL.revokeObjectURL(url)}
 const paginas=useMemo(()=>{const t=Math.max(1,meta.paginas),a=Math.max(1,Math.min(pagina-2,t-4)),f=Math.min(t,a+4);return Array.from({length:f-a+1},(_,i)=>a+i)},[meta.paginas,pagina]);
 return <div className="space-y-4 pb-4">
  <div className="flex flex-col gap-4 lg:flex-row lg:items-start lg:justify-between"><PageTitle titulo="Movimentação da Conta" descricao="Extrato bancário com movimentações e situação de conciliação"/><div className="flex flex-wrap items-center gap-2 relative"><button className="flex min-w-[245px] items-center gap-3 rounded-xl border bg-white px-4 py-2.5 shadow-sm text-left" onClick={()=>{setDeRasc(de);setAteRasc(ate);setPeriodoAberto(v=>!v)}}><span className="grid h-10 w-10 place-items-center rounded-full bg-slate-100"><CalendarDays size={19}/></span><div><p className="text-xs text-slate-500">Período</p><p className="text-sm font-semibold">{periodoTexto}</p></div></button>{periodoAberto&&<div className="absolute right-0 top-14 z-40 w-[330px] rounded-2xl border bg-white p-4 shadow-2xl"><div className="grid grid-cols-2 gap-3"><label><span className="label">De</span><input className="input" type="date" value={deRasc} onChange={e=>setDeRasc(e.target.value)}/></label><label><span className="label">Até</span><input className="input" type="date" value={ateRasc} onChange={e=>setAteRasc(e.target.value)}/></label></div><div className="mt-4 flex justify-end gap-2"><button className="btn-outline" onClick={()=>setPeriodoAberto(false)}>Cancelar</button><button className="btn-primary" onClick={aplicarPeriodo}>Aplicar período</button></div></div>}<button className="btn-primary h-11" onClick={()=>carregar(pagina)}><RefreshCw size={16}/>Atualizar</button><button className="btn-outline h-11" onClick={()=>empresa?ofxRef.current?.click():setErro("Selecione a empresa antes de atualizar o extrato.")} disabled={importando}><Upload size={16}/>{importando?"Importando...":ehMLab?"Atualizar C6":"Importar extrato"}</button><input ref={ofxRef} type="file" accept=".ofx" className="hidden" onChange={importarOFX}/></div></div>
  <div className="grid gap-3 md:grid-cols-2 xl:grid-cols-4"><Card icon={<ArrowUp/>} titulo="Entradas do período" valor={moeda(resumo.entradas)} classe="emerald"/><Card icon={<ArrowDown/>} titulo="Saídas do período" valor={moeda(resumo.saidas)} classe="rose"/><Card icon={<BarChart3/>} titulo="Resultado do período" valor={moeda(resultado)} classe="blue"/><Card icon={<Wallet/>} titulo="Saldo atual da conta" valor={saldoAtual==null?"—":moeda(saldoAtual)} subtitulo={contaSelecionada?.nome||empresaSelecionada?.nome||"Selecione empresa/conta"} classe="slate"/></div>
  <div className="rounded-2xl border bg-white p-3 shadow-sm"><div className="grid gap-3 lg:grid-cols-[190px_170px_170px_1fr_auto]"><label><span className="label">Conta bancária</span><select className="input" value={conta} onChange={e=>setConta(e.target.value)}><option value="">Todas as contas</option>{contasEmpresa.map(c=><option key={c.id} value={c.id}>{c.nome}</option>)}</select></label><label><span className="label">Tipo</span><select className="input" value={tipoMovimento} onChange={e=>setTipoMovimento(e.target.value)}><option value="">Todos</option><option value="CREDITO">Entradas</option><option value="DEBITO">Saídas</option></select></label><label><span className="label">Situação</span><select className="input" value={status} onChange={e=>setStatus(e.target.value)}><option value="">Todas</option><option value="PENDENTE">Não conciliados</option><option value="CONCILIADO">Resolvidos</option></select></label><label><span className="label">Pesquisar</span><div className="relative"><Search size={16} className="absolute left-3 top-3 text-slate-400"/><input className="input pl-9" value={busca} onChange={e=>setBusca(e.target.value)} placeholder="Descrição, valor, documento..."/></div></label><button className="btn-outline mt-auto h-10" onClick={exportar}><Download size={16}/>Exportar</button></div><div className="mt-3 border-t pt-3"><label className="block max-w-[260px]"><span className="label">Empresa</span><select className="input" value={empresa} onChange={e=>{setEmpresa(e.target.value);setConta("")}}><option value="">Todas</option>{op.empresas.map(x=><option key={x.id} value={x.id}>{x.nome}</option>)}</select></label></div></div>
  {erro&&<div className="flex gap-2 rounded-xl bg-red-50 p-3 text-sm text-red-700"><AlertCircle size={17}/>{erro}</div>}{aviso&&<div className="flex gap-2 rounded-xl bg-emerald-50 p-3 text-sm text-emerald-700"><CheckCircle2 size={17}/>{aviso}</div>}
  <div className="rounded-2xl border bg-white shadow-sm overflow-hidden"><table className="w-full table-fixed text-sm"><thead className="bg-slate-50 text-left text-xs font-semibold uppercase text-slate-500"><tr><th className="w-[9%] px-3 py-3">Data</th><th className="w-[26%] px-3 py-3">Descrição</th><th className="w-[13%] px-3 py-3 hidden 2xl:table-cell">Documento</th><th className="w-[15%] px-3 py-3">Categoria</th><th className="w-[8%] px-3 py-3">Tipo</th><th className="w-[11%] px-3 py-3 text-right">Valor</th><th className="w-[11%] px-3 py-3 text-right hidden xl:table-cell">Saldo</th><th className="w-[12%] px-3 py-3">Situação</th><th className="w-[6%] px-3 py-3 text-right">Ações</th></tr></thead><tbody>{loading?<tr><td colSpan="9" className="p-10 text-center text-slate-500">Carregando...</td></tr>:itens.length===0?<tr><td colSpan="9" className="p-10 text-center text-slate-500">Nenhuma movimentação encontrada.</td></tr>:itens.map(m=><tr key={m.id} className="border-t hover:bg-slate-50"><td className="px-3 py-3 whitespace-nowrap">{dataBR(m.data_movimento)}</td><td className="px-3 py-3 min-w-0"><button className="w-full text-left" onClick={()=>setDetalhe(m)}><span className="block truncate font-semibold">{nomeMovimento(m)}</span><span className="block truncate text-xs text-slate-500">{m.descricao||""}</span></button></td><td className="px-3 py-3 truncate hidden 2xl:table-cell">{m.documento||"—"}</td><td className="px-3 py-3 truncate" title={m.categoria_nome||"—"}>{m.categoria_nome||"—"}</td><td className="px-3 py-3"><span className={`rounded-full px-2 py-1 text-xs font-semibold ${m.tipo==="CREDITO"?"bg-emerald-50 text-emerald-700":"bg-rose-50 text-rose-700"}`}>{m.tipo==="CREDITO"?"Entrada":"Saída"}</span></td><td className={`px-3 py-3 text-right font-bold whitespace-nowrap ${m.tipo==="CREDITO"?"text-emerald-700":"text-rose-700"}`}>{m.tipo==="DEBITO"?"- ":""}{moeda(Math.abs(m.valor))}</td><td className="px-3 py-3 text-right font-medium whitespace-nowrap hidden xl:table-cell">{m.saldo_movimento==null?"—":moeda(m.saldo_movimento)}</td><td className="px-3 py-3"><span className={`inline-flex items-center gap-1 rounded-full border px-2 py-1 text-xs font-semibold whitespace-nowrap ${situacaoClasses(m)}`}>{situacaoAmigavel(m)}</span></td><td className="px-3 py-3 text-right"><button className="btn-ghost h-8 w-8 p-0" onClick={e=>abrirMenu(e,m)}><MoreVertical size={18}/></button></td></tr>)}</tbody></table></div>
  <div className="flex items-center justify-between"><span className="text-sm text-slate-500">Mostrando {itens.length?(pagina-1)*limite+1:0} a {Math.min(pagina*limite,meta.total)} de {meta.total}</span><div className="flex gap-1"><button className="btn-outline h-9 w-9 p-0" disabled={pagina<=1} onClick={()=>carregar(pagina-1)}><ChevronLeft size={16}/></button>{paginas.map(p=><button key={p} className={p===pagina?"btn-primary h-9 min-w-9":"btn-outline h-9 min-w-9"} onClick={()=>carregar(p)}>{p}</button>)}<button className="btn-outline h-9 w-9 p-0" disabled={pagina>=meta.paginas} onClick={()=>carregar(pagina+1)}><ChevronRight size={16}/></button></div></div>
  {menu&&<><button className="fixed inset-0 z-40" onClick={()=>setMenu(null)}/><div className="fixed z-50 w-[300px] rounded-2xl border bg-white p-2 shadow-2xl" style={{top:menu.top,left:menu.left}}><p className="px-3 py-2 font-bold">O que é este movimento?</p>{!menu.item.conciliado?<><Acao icone={<Link2 size={16}/>} titulo="Conciliar" sub="Vincular a conta a receber ou pagar" onClick={()=>abrirConciliacao(menu.item)}/><Acao icone={<ArrowLeftRight size={16}/>} titulo="Transferência entre contas" sub="Movimento entre contas próprias" onClick={()=>escolherResolucao("TRANSFERENCIA",menu.item)}/><Acao icone={<Undo2 size={16}/>} titulo="Estorno" sub="Valor saiu e voltou" onClick={()=>escolherResolucao("ESTORNO",menu.item)}/><Acao icone={<CircleDollarSign size={16}/>} titulo="Outro movimento" sub="Tarifa, rendimento, ajuste etc." onClick={()=>escolherResolucao("MOVIMENTO_INTERNO",menu.item)}/></>:<Acao icone={<RotateCcw size={16}/>} titulo="Ver detalhes / desfazer" onClick={()=>{setMenu(null);setDetalhe(menu.item)}}/>}</div></>}
  {detalhe&&<div className="fixed inset-0 z-50 bg-slate-950/30" onClick={()=>setDetalhe(null)}><aside className="ml-auto h-full w-full max-w-xl overflow-y-auto bg-white shadow-2xl" onClick={e=>e.stopPropagation()}><div className="flex justify-between border-b p-5"><div><p className="text-xs uppercase text-slate-500">Movimentação</p><h2 className="text-xl font-bold">{nomeMovimento(detalhe)}</h2></div><button className="btn-ghost h-9 w-9 p-0" onClick={()=>setDetalhe(null)}><X size={18}/></button></div><div className="space-y-4 p-5"><Info k="Data" v={dataBR(detalhe.data_movimento)}/><Info k="Valor" v={moeda(Math.abs(detalhe.valor))}/><Info k="Saldo após movimento" v={detalhe.saldo_movimento==null?"—":moeda(detalhe.saldo_movimento)}/><Info k="Categoria" v={detalhe.categoria_nome||"—"}/><Info k="Documento" v={detalhe.documento||detalhe.fitid||"—"}/><Info k="Descrição" v={detalhe.descricao||"—"}/>{detalhe.conciliado&&detalhe.classificacao_bancaria&&<button className="btn-outline" onClick={()=>desfazerClassificacao(detalhe)}>Desfazer resolução</button>}{detalhe.conciliado&&!detalhe.classificacao_bancaria&&<button className="btn-outline border-rose-200 text-rose-700 hover:bg-rose-50" onClick={()=>desfazerConciliacao(detalhe)} disabled={salvando}><RotateCcw size={16}/>{salvando?"Desfazendo...":"Desfazer conciliação"}</button>}</div></aside></div>}
  {resolver&&<div className="fixed inset-0 z-[60] grid place-items-center bg-slate-950/45 p-4"><div className="w-full max-w-xl rounded-2xl bg-white p-5 shadow-2xl"><div className="flex justify-between"><div><h2 className="font-bold">{classificacaoAmigavel(classe)}</h2><p className="text-sm text-slate-500">{nomeMovimento(resolver)}</p></div><button className="btn-ghost" onClick={()=>setResolver(null)}><X size={18}/></button></div>{classe!=="MOVIMENTO_INTERNO"&&<label className="mt-4 block"><span className="label">Movimento correspondente</span><select className="input" value={relacionadoId} onChange={e=>setRelacionadoId(e.target.value)}><option value="">Selecione...</option>{contrapartidas.map(x=><option key={x.id} value={x.id}>{dataBR(x.data_movimento)} · {moeda(Math.abs(x.valor))} · {nomeMovimento(x)}</option>)}</select></label>}<div className="mt-5 flex justify-end gap-2"><button className="btn-outline" onClick={()=>setResolver(null)}>Cancelar</button><button className="btn-primary" onClick={salvarResolucao} disabled={salvando}>{salvando?"Salvando...":"Confirmar"}</button></div></div></div>}
 </div>
}
function Card({icon,titulo,valor,subtitulo,classe}){const m={emerald:"bg-emerald-50 text-emerald-700",rose:"bg-rose-50 text-rose-700",blue:"bg-blue-50 text-blue-700",slate:"bg-slate-100 text-slate-700"}[classe];return <div className="rounded-2xl border bg-white p-5 shadow-sm"><div className="flex items-center gap-4"><span className={`grid h-12 w-12 place-items-center rounded-full ${m}`}>{icon}</span><div className="min-w-0"><p className="text-sm text-slate-600">{titulo}</p><p className="mt-1 truncate text-2xl font-bold">{valor}</p>{subtitulo&&<p className="truncate text-xs text-slate-500">{subtitulo}</p>}</div></div></div>}
function Acao({icone,titulo,sub,onClick}){return <button className="flex w-full items-start gap-3 rounded-xl px-3 py-2.5 text-left hover:bg-slate-50" onClick={onClick}><span className="mt-0.5">{icone}</span><span><b className="block text-sm">{titulo}</b>{sub&&<small className="text-slate-500">{sub}</small>}</span></button>}
function Info({k,v}){return <div className="rounded-xl border bg-slate-50 p-3"><span className="text-xs text-slate-500">{k}</span><p className="font-semibold break-words">{v}</p></div>}
