import { useEffect, useMemo, useRef, useState } from "react";
import { ArrowLeft, Plus, Upload, Search, Trash2, X } from "lucide-react";
import { useNavigate } from "react-router-dom";
import { PageTitle } from "../components/ui.jsx";
import { financeiroOpcoes, finNotasListar, finNotaSalvar, finNotaExcluir } from "../services/financeiro.js";

const moeda=v=>Number(v||0).toLocaleString("pt-BR",{style:"currency",currency:"BRL"});
const dataBR=v=>{const p=String(v||"").slice(0,10).split("-");return p.length===3?`${p[2]}/${p[1]}/${p[0]}`:"—"};
const vazio={empresa_id:"",tipo:"SAIDA",numero_nf:"",chave_acesso:"",cnpj_emitente:"",cnpj_destinatario:"",nome_emitente:"",nome_destinatario:"",data_emissao:"",valor_total:"",email_destino:"",xml_url:"",pdf_url:"",observacao:"",origem:"MANUAL"};
function xmlTag(doc,nome){const el=doc.getElementsByTagName(nome)?.[0];return el?.textContent?.trim()||""}
function lerXML(text){const doc=new DOMParser().parseFromString(text,"application/xml");if(doc.querySelector("parsererror"))throw new Error("XML inválido.");const emis=xmlTag(doc,"dhEmi")||xmlTag(doc,"dEmi");const emit=doc.getElementsByTagName("emit")?.[0];const dest=doc.getElementsByTagName("dest")?.[0];const tg=(root,n)=>root?.getElementsByTagName(n)?.[0]?.textContent?.trim()||"";return{numero_nf:xmlTag(doc,"nNF"),chave_acesso:xmlTag(doc,"chNFe"),cnpj_emitente:tg(emit,"CNPJ")||tg(emit,"CPF"),cnpj_destinatario:tg(dest,"CNPJ")||tg(dest,"CPF"),nome_emitente:tg(emit,"xNome"),nome_destinatario:tg(dest,"xNome"),data_emissao:emis?emis.slice(0,10):"",valor_total:Number(xmlTag(doc,"vNF")||0),origem:"XML"}}
function Modal({titulo,onClose,children}){return <div className="fixed inset-0 z-50 grid place-items-center bg-slate-950/45 p-4"><div className="max-h-[92vh] w-full max-w-3xl overflow-hidden rounded-2xl bg-white shadow-2xl"><div className="flex items-center justify-between border-b px-5 py-4"><h2 className="font-bold">{titulo}</h2><button className="btn-ghost h-9 w-9 p-0" onClick={onClose}><X size={18}/></button></div><div className="max-h-[calc(92vh-68px)] overflow-y-auto p-5">{children}</div></div></div>}

export default function NotasFiscais(){
 const navigate=useNavigate(),fileRef=useRef(null);const[op,setOp]=useState({empresas:[]});const[itens,setItens]=useState([]);const[empresa,setEmpresa]=useState("");const[busca,setBusca]=useState("");const[form,setForm]=useState(vazio);const[modal,setModal]=useState(false);const[erro,setErro]=useState("");
 async function carregar(){try{const[o,d]=await Promise.all([financeiroOpcoes(),finNotasListar(empresa)]);setOp(o);setItens(d)}catch(e){setErro(e.message)}}useEffect(()=>{carregar()},[empresa]);
 const filtrados=useMemo(()=>{const t=busca.toLowerCase().trim();return itens.filter(x=>!t||`${x.numero_nf||""} ${x.nome_emitente||""} ${x.nome_destinatario||""} ${x.cnpj_emitente||""} ${x.cnpj_destinatario||""}`.toLowerCase().includes(t))},[itens,busca]);
 function novo(){setForm({...vazio,empresa_id:empresa||op.empresas?.[0]?.id||""});setModal(true)}
 async function salvar(e){e.preventDefault();try{await finNotaSalvar({...form,valor_total:Number(form.valor_total||0)});setModal(false);await carregar()}catch(ex){setErro(ex.message)}}
 async function importar(e){const f=e.target.files?.[0];if(!f)return;try{const x=lerXML(await f.text());setForm({...vazio,...x,empresa_id:empresa||op.empresas?.[0]?.id||""});setModal(true)}catch(ex){setErro(ex.message)}finally{e.target.value=""}}
 async function excluir(x){if(!confirm(`Excluir a nota ${x.numero_nf||"sem número"}?`))return;try{await finNotaExcluir(x.id);await carregar()}catch(ex){setErro(ex.message)}}
 return <div className="space-y-5"><div className="flex items-center gap-3"><button className="btn-ghost h-9 w-9 p-0" onClick={()=>navigate("/financas")}><ArrowLeft size={18}/></button><PageTitle titulo="Notas Fiscais" descricao="Cadastro manual e leitura de XML, com vínculo ao Financeiro e estrutura preparada para Storage."/></div><div className="flex flex-col gap-3 rounded-2xl border bg-white p-4 md:flex-row md:items-end"><label className="md:w-56"><span className="label">Empresa</span><select className="input" value={empresa} onChange={e=>setEmpresa(e.target.value)}><option value="">Todas</option>{op.empresas.map(x=><option key={x.id} value={x.id}>{x.nome}</option>)}</select></label><label className="flex-1"><span className="label">Pesquisar</span><div className="relative"><Search size={15} className="absolute left-3 top-3 text-slate-400"/><input className="input pl-9" value={busca} onChange={e=>setBusca(e.target.value)} placeholder="NF, razão social ou CNPJ"/></div></label><button className="btn-outline" onClick={()=>fileRef.current?.click()}><Upload size={16}/>Importar XML</button><input ref={fileRef} type="file" accept=".xml" className="hidden" onChange={importar}/><button className="btn-primary" onClick={novo}><Plus size={16}/>Nova nota</button></div>{erro&&<div className="rounded-xl bg-red-50 p-3 text-sm text-red-700">{erro}</div>}<div className="overflow-x-auto rounded-2xl border bg-white"><table className="min-w-full text-sm"><thead className="bg-slate-50 text-left text-xs uppercase text-slate-500"><tr><th className="px-4 py-3">Empresa</th><th className="px-4 py-3">NF</th><th className="px-4 py-3">Emissão</th><th className="px-4 py-3">Emitente / Destinatário</th><th className="px-4 py-3 text-right">Valor</th><th className="px-4 py-3">Origem</th><th className="px-4 py-3">Arquivos</th><th className="px-4 py-3"></th></tr></thead><tbody>{filtrados.length===0?<tr><td colSpan="8" className="p-8 text-center text-slate-500">Nenhuma nota cadastrada.</td></tr>:filtrados.map(x=><tr key={x.id} className="border-t"><td className="px-4 py-3">{x.empresa?.nome||"—"}</td><td className="px-4 py-3 font-medium">{x.numero_nf||"—"}</td><td className="px-4 py-3">{dataBR(x.data_emissao)}</td><td className="px-4 py-3"><div>{x.nome_emitente||"—"}</div><div className="text-xs text-slate-500">→ {x.nome_destinatario||"—"}</div></td><td className="px-4 py-3 text-right font-semibold">{moeda(x.valor_total)}</td><td className="px-4 py-3">{x.origem}</td><td className="px-4 py-3 text-xs">{x.pdf_url?"PDF ":""}{x.xml_url?"XML":""}{!x.pdf_url&&!x.xml_url?"—":""}</td><td className="px-4 py-3 text-right"><button className="btn-ghost h-8 w-8 p-0 text-red-600" onClick={()=>excluir(x)}><Trash2 size={15}/></button></td></tr>)}</tbody></table></div>
 {modal&&<Modal titulo={form.origem==="XML"?"Importar nota do XML":"Nova nota fiscal"} onClose={()=>setModal(false)}><form onSubmit={salvar} className="grid gap-4 md:grid-cols-2"><label><span className="label">Empresa</span><select className="input" required value={form.empresa_id} onChange={e=>setForm({...form,empresa_id:e.target.value})}>{op.empresas.map(x=><option key={x.id} value={x.id}>{x.nome}</option>)}</select></label><label><span className="label">Tipo</span><select className="input" value={form.tipo} onChange={e=>setForm({...form,tipo:e.target.value})}><option>SAIDA</option><option>ENTRADA</option></select></label><label><span className="label">Número NF</span><input className="input" value={form.numero_nf} onChange={e=>setForm({...form,numero_nf:e.target.value})}/></label><label><span className="label">Data emissão</span><input className="input" type="date" value={form.data_emissao} onChange={e=>setForm({...form,data_emissao:e.target.value})}/></label><label><span className="label">Emitente</span><input className="input" value={form.nome_emitente} onChange={e=>setForm({...form,nome_emitente:e.target.value})}/></label><label><span className="label">CNPJ emitente</span><input className="input" value={form.cnpj_emitente} onChange={e=>setForm({...form,cnpj_emitente:e.target.value})}/></label><label><span className="label">Destinatário</span><input className="input" value={form.nome_destinatario} onChange={e=>setForm({...form,nome_destinatario:e.target.value})}/></label><label><span className="label">CNPJ destinatário</span><input className="input" value={form.cnpj_destinatario} onChange={e=>setForm({...form,cnpj_destinatario:e.target.value})}/></label><label><span className="label">Valor total</span><input className="input" type="number" step="0.01" value={form.valor_total} onChange={e=>setForm({...form,valor_total:e.target.value})}/></label><label><span className="label">E-mail destino</span><input className="input" type="email" value={form.email_destino} onChange={e=>setForm({...form,email_destino:e.target.value})}/></label><label className="md:col-span-2"><span className="label">Chave de acesso</span><input className="input" value={form.chave_acesso} onChange={e=>setForm({...form,chave_acesso:e.target.value})}/></label><label className="md:col-span-2"><span className="label">Observação</span><textarea className="input min-h-20" value={form.observacao} onChange={e=>setForm({...form,observacao:e.target.value})}/></label><div className="md:col-span-2 flex justify-end gap-2"><button type="button" className="btn-outline" onClick={()=>setModal(false)}>Cancelar</button><button className="btn-primary">Salvar nota</button></div></form><p className="mt-4 rounded-xl bg-amber-50 p-3 text-xs text-amber-800">O cadastro já elimina a busca frágil por nome de arquivo do Google Drive. O upload físico de PDF/XML e o envio por e-mail serão ligados ao bucket privado ml-arquivos na etapa de anexos, sem recriar o erro do legado.</p></Modal>}
 </div>
}
