import { useEffect, useMemo, useState } from 'react';
import { Link } from 'react-router-dom';
import { FileText, RefreshCw } from 'lucide-react';
import { financeiroOpcoes, finMovimentosListar, finRecebimentosListar, finDespesasListar } from '../services/financeiro.js';
import { montarPatrimonial } from '../lib/financeiroPatrimonial.js';
import { moedaRelatorio as moeda, dataRelatorio as data, periodoValido } from '../lib/relatorioFinanceiro.js';
import '../components/financeiro/relatoriosFinanceiro.css';
const hoje = () => new Date().toLocaleDateString('en-CA');
export default function PatrimonialFinanceiro({tipo}) {
 const [empresa,setEmpresa]=useState(''),[conta,setConta]=useState(''),[pessoa,setPessoa]=useState('');
 const [de,setDe]=useState(`${new Date().getFullYear()}-01-01`),[ate,setAte]=useState(hoje());
 const [dados,setDados]=useState(null),[op,setOp]=useState({empresas:[],contas:[]}),[erro,setErro]=useState(''),[versao,setVersao]=useState(0),[gerando,setGerando]=useState(false);
 useEffect(()=>{let ativo=true;setDados(null);setErro('');Promise.all([financeiroOpcoes(),finMovimentosListar(empresa),finRecebimentosListar(empresa),finDespesasListar(empresa)]).then(([o,m,r,d])=>{if(ativo){setOp(o);setDados({empresa,movimentos:m,recebimentos:r,despesas:d,consultadoEm:new Date()});}}).catch(e=>{if(ativo)setErro(e.message);});return()=>{ativo=false;};},[empresa,versao]);
 const r=useMemo(()=>dados?.empresa===empresa&&periodoValido(de,ate)?montarPatrimonial({...dados,tipo,empresa,conta,pessoa,de,ate}):null,[dados,tipo,empresa,conta,pessoa,de,ate]);
 const aplicacoes=tipo==='aplicacoes',titulo=aplicacoes?'Aplicações financeiras':'Retiradas e movimentações dos sócios';
 const empresaNome=op.empresas.find(e=>e.id===empresa)?.nome||'Todas as empresas',contaNome=op.contas.find(c=>c.id===conta)?.nome||'Todas as contas';
 async function pdf(){if(!r||gerando)return;setGerando(true);try{const {gerarPdfPatrimonial}=await import('../lib/pdfPatrimonial.js');gerarPdfPatrimonial(r,{titulo,empresa:empresaNome,conta:contaNome,pessoa:r.pessoas.find(p=>p.id===pessoa)?.nome,consultadoEm:dados.consultadoEm}).save(`minaslab-${tipo}-${de}-${ate}.pdf`);}catch(e){setErro(e.message);}finally{setGerando(false);}}
 return <div className="fin-relatorios space-y-5">
  <div className="fin-relatorios-titulo"><div><h1 className="text-2xl font-bold text-blue-900">{titulo}</h1><p className="mt-2 text-sm text-slate-600">{aplicacoes?'Aportes, resgates e rendimentos identificados na base financeira.':'Saídas e entradas por favorecido, mantendo a natureza registrada na origem.'}</p></div><button className="btn-primary" disabled={!r||gerando} onClick={pdf}><FileText size={16}/>{gerando?'Preparando…':'Baixar PDF'}</button></div>
  <div className="flex flex-wrap gap-3"><Link className="btn-outline" to="/financas/aplicacoes">Aplicações</Link><Link className="btn-outline" to="/financas/socios">Sócios</Link><Link className="btn-outline" to="/financas/relatorios">Relatórios gerais</Link></div>
  <section className="fin-relatorios-bloco grid gap-3 md:grid-cols-4">
   <label><span className="label">Empresa</span><select className="input" value={empresa} onChange={e=>{setEmpresa(e.target.value);setConta('');setPessoa('');}}><option value="">Todas as empresas</option>{op.empresas.map(e=><option key={e.id} value={e.id}>{e.nome}</option>)}</select></label>
   <label><span className="label">Conta</span><select className="input" value={conta} onChange={e=>{setConta(e.target.value);setPessoa('');}}><option value="">Todas as contas</option>{op.contas.filter(c=>!empresa||c.empresa_id===empresa).map(c=><option key={c.id} value={c.id}>{c.nome}</option>)}</select></label>
   <label><span className="label">De</span><input className="input" type="date" value={de} onChange={e=>{setDe(e.target.value);setPessoa('');}}/></label><label><span className="label">Até</span><input className="input" type="date" value={ate} onChange={e=>{setAte(e.target.value);setPessoa('');}}/></label>
   <div className="flex flex-wrap gap-2 md:col-span-4"><button className="btn-outline" onClick={()=>{setDe(`${new Date().getFullYear()}-01-01`);setAte(hoje());setPessoa('');}}>Ano até hoje</button><button className="btn-outline" onClick={()=>{setDe(`${hoje().slice(0,7)}-01`);setAte(hoje());setPessoa('');}}>Este mês</button><button className="btn-outline" onClick={()=>setVersao(v=>v+1)}><RefreshCw size={14}/>Atualizar</button></div>
   {!aplicacoes&&r&&<label className="md:col-span-4"><span className="label">Sócio / favorecido identificado na origem</span><select className="input" value={pessoa} onChange={e=>setPessoa(e.target.value)}><option value="">Todos os favorecidos</option>{r.pessoas.map(p=><option key={p.id} value={p.id}>{p.nome}{p.empresa?` · ${p.empresa}`:''}</option>)}</select></label>}
  </section>
  {erro&&<p role="alert" className="rounded-xl bg-red-50 p-4 text-red-800">{erro}</p>}
  {!periodoValido(de,ate)&&<p role="alert">Confira as datas do período.</p>}
  {!dados&&!erro&&<p role="status">Consultando a base completa…</p>}
  {r&&<>
   {aplicacoes?<section className="fin-relatorios-bloco"><h2>Quanto está aplicado hoje?</h2><strong className="fin-relatorios-total">Saldo não informado pela integração</strong><p className="fin-relatorios-nota">A base contém movimentações, mas não uma posição identificada da carteira nem disponibilidade para resgate. Aportes menos resgates não comprovam o saldo aplicado. Nenhum valor foi estimado.</p></section>:<p className="rounded-xl bg-blue-50 p-4 text-sm text-blue-900">Mútuos, pró-labore, adiantamentos e distribuição de lucros são naturezas diferentes. Aqui cada lançamento mantém sua categoria de origem; o favorecido não é classificado como sócio apenas pelo nome.</p>}
   <section className="fin-relatorios-bloco"><h2>Movimentações identificadas no período</h2><div className="fin-relatorios-kpis"><article className="fin-relatorios-kpi fin-relatorios-saidas"><h3>{aplicacoes?'Saídas relacionadas a aplicações':'Saídas para sócios'}</h3><strong>{moeda(r.saidas)}</strong></article><article className="fin-relatorios-kpi fin-relatorios-entradas"><h3>{aplicacoes?'Entradas relacionadas a aplicações':'Entradas dos sócios'}</h3><strong>{moeda(r.entradas)}</strong></article><article className="fin-relatorios-kpi"><h3>Registros bancários</h3><strong>{r.itens.length}</strong><small>Consultados em {dados.consultadoEm.toLocaleString('pt-BR')}</small></article></div><p className="fin-relatorios-nota">Totais exclusivamente do banco, pela data do movimento e categoria explícita. Títulos a pagar/receber não são somados novamente. Sem registros não significa saldo zero.</p></section>
   <section className="fin-relatorios-bloco fin-relatorios-detalhes"><h2>Por natureza</h2><div className="overflow-auto"><table><thead><tr><th>Classificação</th><th>Entradas</th><th>Saídas</th></tr></thead><tbody>{r.naturezas.map(n=><tr key={n.nome}><td>{n.nome}</td><td>{moeda(n.entradas)}</td><td>{moeda(n.saidas)}</td></tr>)}</tbody></table></div>{!r.itens.length&&<p className="mt-3">Nenhuma movimentação com categoria específica neste recorte.</p>}</section>
   <section className="fin-relatorios-bloco fin-relatorios-detalhes"><h2>Comparação mês a mês</h2><div className="overflow-auto"><table><thead><tr><th>Mês</th><th>Entradas</th><th>Saídas</th><th>Registros</th></tr></thead><tbody>{r.meses.map(m=><tr key={m.nome}><td>{m.nome.split('-').reverse().join('/')}</td><td>{moeda(m.entradas)}</td><td>{moeda(m.saidas)}</td><td>{m.registros}</td></tr>)}</tbody></table></div></section>
   {!aplicacoes&&<section className="fin-relatorios-bloco fin-relatorios-detalhes"><h2>Por sócio / favorecido</h2><div className="overflow-auto"><table><thead><tr><th>Favorecido / empresa</th><th>Entradas</th><th>Saídas</th></tr></thead><tbody>{r.porPessoa.map(p=><tr key={p.id}><td>{p.nome}<small className="block">{p.empresa}</small></td><td>{moeda(p.entradas)}</td><td>{moeda(p.saidas)}</td></tr>)}</tbody></table></div></section>}
   <section className="fin-relatorios-bloco"><h2>Lançamentos e origem dos valores</h2><p className="fin-relatorios-nota">{r.itens.length} registros. Abra cada lançamento para conferir conta, categoria e identificação.</p><div className="mt-4 space-y-2">{r.itens.map(m=><details key={m.id} className="rounded-xl border p-3"><summary className="cursor-pointer text-sm"><b>{data(m.data_movimento)} · {m.natureza}</b> · {m.pessoa} · {m.tipo==='CREDITO'?'+':'−'} {moeda(m.valor)}</summary><div className="mt-3 space-y-2 break-words text-sm text-slate-600"><p>{m.empresa?.nome} · {m.conta?.nome || op.contas.find(c=>c.id===m.conta_bancaria_id)?.nome || 'Conta não informada'}</p><p>Categoria: {m.categoria}</p><p>{m.descricao}</p><p>Origem: {m.origem || 'Não informada'} · {m.conciliado?'Conciliado':'Conciliação pendente'}</p><p className="break-all">Identificador: {m.id_omie || m.fitid || m.id}</p></div></details>)}</div></section>
   {!pessoa&&<details className="fin-relatorios-bloco fin-relatorios-detalhes"><summary>Conferir fora dos totais · {r.candidatos.length} movimentos e {r.pendentes.length} títulos pendentes</summary><p className="fin-relatorios-nota">Descrições livres não comprovam a categoria. Títulos abaixo estão pendentes e ainda não representam pagamentos ou recebimentos bancários.</p>{r.candidatos.map(m=><p className="mt-3 text-sm" key={m.id}>{data(m.data_movimento)} · {m.descricao} · {moeda(m.valor)} — {m.motivo}</p>)}{r.pendentes.map(t=><p className="mt-3 text-sm" key={t.id}>{data(t.data_vencimento)} · {t.fornecedor || t.cliente} · Pendente {moeda(t.valor_pendente)}</p>)}<Link className="fin-relatorios-link" to="/financas/conferencia">Abrir conferência financeira</Link></details>}
  </>}
 </div>;
}
