import { useEffect, useMemo, useState } from "react";
import { Layers3, Pencil, Plus, Search, Save, Trash2, X } from "lucide-react";
import ServicosGerados from "./ServicosGerados.jsx";
import { servicosGeradosListar } from "../services/servicosGerados.js";
import { financeiroOpcoes } from "../services/financeiro.js";
import { API } from "../lib/api.js";
import { comCracha, mensagemDoStatus } from "../lib/sessao.js";

const moeda=v=>Number(v||0).toLocaleString("pt-BR",{style:"currency",currency:"BRL"});
const data=v=>v?String(v).slice(0,10):"";
const dataBr=v=>v?new Date(`${String(v).slice(0,10)}T12:00:00`).toLocaleDateString("pt-BR"):"—";
const dig=v=>String(v||"").replace(/\D/g,"");
const chaveCliente=x=>dig(x.cnpj_cpf)||String(x.cliente||"").trim().toUpperCase();
const badge={FATURADO:"bg-emerald-100 text-emerald-700",PAGO:"bg-emerald-100 text-emerald-700","A RECEBER":"bg-amber-100 text-amber-700",AGUARDANDO:"bg-blue-100 text-blue-700","PRONTO PARA FATURAR":"bg-blue-100 text-blue-700",PARCIAL:"bg-amber-100 text-amber-700",VENCIDO:"bg-red-100 text-red-700",DIVERGENCIA:"bg-violet-100 text-violet-700","NAO FATURAR":"bg-slate-100 text-slate-600",CANCELADO:"bg-slate-100 text-slate-600"};
const label=s=>({"PRONTO PARA FATURAR":"Pronto para faturar","NAO FATURAR":"Não faturar",DIVERGENCIA:"Divergência"}[s]||String(s||"").toLowerCase().replace(/(^|\s)\S/g,m=>m.toUpperCase()));
const Pill=({v})=>v?<span className={`inline-flex rounded-full px-2 py-0.5 text-[10px] font-semibold ${badge[String(v).toUpperCase()]||"bg-slate-100 text-slate-600"}`}>{label(v)}</span>:null;
const normal=v=>String(v??"").trim();
function comum(itens,campo,{date=false}={}){const vals=(itens||[]).map(x=>date?data(x?.[campo]):normal(x?.[campo]));const unicos=[...new Set(vals)];return {valor:unicos.length===1?unicos[0]:"",divergente:unicos.length>1};}
function valorForma(f){return normal(f?.nome||f?.descricao||f?.valor||f?.label||f);}
async function post(url,corpo){const resp=await comCracha(url,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(corpo)});const body=await resp.json().catch(()=>null);if(!resp.ok)throw new Error(body?.erro||body?.message||mensagemDoStatus(resp.status));return body||{}}
const grupoApi=corpo=>post(`${API}/ml-financeiro-servicos-grupar`,corpo);
const pagamentoApi=corpo=>post(`${API}/ml-financeiro-servicos-grupo-pagamento`,corpo);

export default function ServicosGeradosAgrupado(){
 const [grupos,setGrupos]=useState([]),[empresas,setEmpresas]=useState([]),[formas,setFormas]=useState([]),[grupo,setGrupo]=useState(null),[edit,setEdit]=useState(null),[itemEdit,setItemEdit]=useState(null),[divergencias,setDivergencias]=useState({}),[editando,setEditando]=useState(false),[modoAdd,setModoAdd]=useState(false),[dados,setDados]=useState([]),[busca,setBusca]=useState(""),[selecionados,setSelecionados]=useState([]),[erro,setErro]=useState(""),[ok,setOk]=useState(""),[salvando,setSalvando]=useState(false);
 async function carregarGrupos(){const r=await grupoApi({action:"listarGrupos"});setGrupos(r.grupos||[]);if(r.empresas?.length)setEmpresas(r.empresas);return r.grupos||[]}
 useEffect(()=>{carregarGrupos().catch(()=>{});financeiroOpcoes().then(r=>{if(r.empresas?.length)setEmpresas(r.empresas);setFormas(r.formas||r.formasPagamento||r.formas_pagamento||[])}).catch(()=>{})},[]);
 useEffect(()=>{const instalar=()=>{const modais=[...document.querySelectorAll("h2")].filter(h=>h.textContent?.trim()==="Faturamento agrupado");for(const h of modais){const caixa=h.closest(".flex.max-h-\\[88vh\\]");if(!caixa||caixa.querySelector("[data-gerenciar-grupo]"))continue;const rodape=[...caixa.querySelectorAll("div")].find(d=>d.className?.includes("justify-end")&&[...d.querySelectorAll("button")].some(b=>b.textContent?.trim()==="Fechar"));if(!rodape)continue;const b=document.createElement("button");b.type="button";b.dataset.gerenciarGrupo="1";b.className="btn-primary mr-2";b.innerHTML='<span style="display:inline-flex;align-items:center;gap:6px">⚙ Gerenciar este grupo</span>';rodape.insertBefore(b,rodape.firstChild)}};instalar();const obs=new MutationObserver(instalar);obs.observe(document.body,{childList:true,subtree:true});return()=>obs.disconnect()},[]);
 function montarEdicao(x){const itens=x.itens||[],campos={data_vencimento:comum(itens,"data_vencimento",{date:true}),data_emissao:comum(itens,"data_emissao",{date:true}),numero_nf:comum(itens,"numero_nf"),forma_pagamento:comum(itens,"forma_pagamento"),status_faturamento:comum(itens,"status_faturamento"),referencia_pagamento:comum(itens,"referencia_pagamento"),empresa_id:comum(itens,"empresa_id")};const d=Object.fromEntries(Object.entries(campos).map(([k,v])=>[k,v.divergente]));setDivergencias(d);return {...x,empresa_id:x.empresa_id||campos.empresa_id.valor||"",data_vencimento:data(x.data_vencimento)||campos.data_vencimento.valor,data_emissao:data(x.data_emissao)||campos.data_emissao.valor,numero_nf:normal(x.numero_nf)||campos.numero_nf.valor,forma_pagamento:normal(x.forma_pagamento)||campos.forma_pagamento.valor,status_faturamento:normal(x.status_faturamento)||campos.status_faturamento.valor,referencia_pagamento:normal(x.referencia_pagamento)||campos.referencia_pagamento.valor,status_pagamento:normal(x.status_pagamento)||""}}
 async function abrirGrupo(g){setErro("");setOk("");try{const r=await grupoApi({action:"obterGrupo",grupoId:g.id}),x=r.grupo;setGrupo(x);setEdit(montarEdicao(x));setEditando(false);setModoAdd(false);setSelecionados([])}catch(e){setErro(e.message)}}
 function fechar(){setGrupo(null);setEdit(null);setItemEdit(null);setEditando(false);setModoAdd(false);setSelecionados([]);setErro("")}
 function limparFiltrosGerais(botao){setTimeout(()=>{const raiz=botao.closest("section");if(!raiz)return;const buscaGeral=raiz.querySelector('input[placeholder="Buscar por OS, cliente, NF, CNPJ..."]');if(buscaGeral){const setter=Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,"value")?.set;setter?.call(buscaGeral,"");buscaGeral.dispatchEvent(new Event("input",{bubbles:true}))}const empresa=raiz.querySelector('select[aria-label="Filtrar por empresa"]');if(empresa){const setter=Object.getOwnPropertyDescriptor(HTMLSelectElement.prototype,"value")?.set;setter?.call(empresa,"TODAS");empresa.dispatchEvent(new Event("change",{bubbles:true}))}const todos=[...raiz.querySelectorAll("button")].find(b=>b.textContent?.trim()==="Todos");todos?.click()},0)}
 async function localizarGrupoPorModal(botao,lista){const modal=botao.closest(".fixed"),texto=modal?.innerText||"";let candidatos=lista.filter(g=>(g.cliente_nome&&texto.includes(g.cliente_nome))||(g.cnpj_cpf&&texto.includes(g.cnpj_cpf)));if(candidatos.length>1)candidatos=candidatos.filter(g=>!g.empresa?.nome||texto.includes(g.empresa.nome));if(candidatos.length>1)candidatos=candidatos.filter(g=>!g.referencia_pagamento||texto.includes(g.referencia_pagamento));return candidatos[0]}
 async function interceptarClique(ev){const alvo=ev.target.closest?.("button");if(alvo?.textContent?.includes("Limpar filtros")){limparFiltrosGerais(alvo);return}const gerenciar=ev.target.closest?.("[data-gerenciar-grupo]");if(gerenciar){ev.preventDefault();ev.stopPropagation();try{const lista=grupos.length?grupos:await carregarGrupos(),escolhido=await localizarGrupoPorModal(gerenciar,lista);if(!escolhido)throw new Error("Não foi possível localizar este agrupamento. Atualize a página e tente novamente.");await abrirGrupo(escolhido)}catch(e){setErro(e.message)}return}const botao=ev.target.closest?.('button[title="Visualizar grupo e suas OS"]');if(!botao)return;try{const lista=grupos.length?grupos:await carregarGrupos(),texto=botao.closest("tr")?.innerText||"";let candidatos=lista.filter(g=>(g.cliente_nome&&texto.includes(g.cliente_nome))||(g.cnpj_cpf&&texto.includes(g.cnpj_cpf)));if(candidatos.length>1)candidatos=candidatos.filter(g=>!g.empresa?.nome||texto.includes(g.empresa.nome));if(candidatos.length>1)candidatos=candidatos.filter(g=>!g.referencia_pagamento||texto.includes(g.referencia_pagamento));const escolhido=candidatos[0];if(!escolhido)return;ev.preventDefault();ev.stopPropagation();await abrirGrupo(escolhido)}catch(e){setErro(e.message)}}
 async function abrirAdicionar(){setErro("");setBusca("");setSelecionados([]);setModoAdd(true);try{const r=await servicosGeradosListar({busca:""});setDados(r.itens||[])}catch(e){setErro(e.message)}}
 const idsAgrupados=useMemo(()=>new Set(grupos.flatMap(g=>(g.itens||[]).map(x=>x.id))),[grupos]);
 const elegiveis=useMemo(()=>dados.filter(x=>!x.grupo_faturamento&&!idsAgrupados.has(x.id)&&x.status_faturamento==="PRONTO PARA FATURAR"&&x.empresa_id===grupo?.empresa_id&&chaveCliente(x)===String(grupo?.cliente_chave||"").toUpperCase()),[dados,idsAgrupados,grupo]);
 const filtrados=useMemo(()=>{const q=busca.trim().toLowerCase();return elegiveis.filter(x=>!q||`${x.os_numero} ${x.cliente} ${x.cnpj_cpf||""} ${x.contrato_proposta||""}`.toLowerCase().includes(q))},[elegiveis,busca]);
 const formasDisponiveis=useMemo(()=>{const vals=[...formas.map(valorForma),normal(edit?.forma_pagamento)].filter(Boolean);return [...new Set(vals)]},[formas,edit?.forma_pagamento]);
 function setCampo(campo,valor){setEdit(v=>({...v,[campo]:valor}));setDivergencias(v=>({...v,[campo]:false}))}
 const dica=campo=>divergencias[campo]?<span className="mt-1 block text-[10px] font-normal text-amber-700">Valores diferentes nas OS</span>:null;
 async function salvarGrupo(){if(!grupo||salvando)return;const qtd=grupo.itens?.length||0;if(!window.confirm(`Esta alteração será aplicada às ${qtd} OS deste grupo.\n\nDeseja continuar?`))return;setSalvando(true);setErro("");setOk("");try{const r=await grupoApi({action:"editarGrupo",grupoId:grupo.id,campos:{empresa_id:edit.empresa_id,data_vencimento:edit.data_vencimento,data_emissao:edit.data_emissao,numero_nf:edit.numero_nf,referencia_pagamento:edit.referencia_pagamento,forma_pagamento:edit.forma_pagamento,status_faturamento:edit.status_faturamento}});if(normal(edit.status_pagamento)!==normal(grupo.status_pagamento))await pagamentoApi({grupoId:grupo.id,status_pagamento:edit.status_pagamento});const atualizado={...r.grupo,status_pagamento:edit.status_pagamento};setGrupo(atualizado);setEdit(montarEdicao(atualizado));setEditando(false);await carregarGrupos();setOk(`Alteração aplicada às ${r.quantidade||qtd} OS do grupo.`)}catch(e){setErro(e.message)}finally{setSalvando(false)}}
 async function salvarItem(){if(!itemEdit||salvando)return;setSalvando(true);setErro("");try{const r=await grupoApi({action:"editarItem",grupoId:grupo.id,servicoId:itemEdit.id,campos:{empresa_id:itemEdit.empresa_id,data_vencimento:itemEdit.data_vencimento,data_emissao:itemEdit.data_emissao,numero_nf:itemEdit.numero_nf,referencia_pagamento:itemEdit.referencia_pagamento,forma_pagamento:itemEdit.forma_pagamento,status_faturamento:itemEdit.status_faturamento}});setGrupo(r.grupo);setEdit(montarEdicao(r.grupo));setItemEdit(null);await carregarGrupos();setOk("OS atualizada individualmente.")}catch(e){setErro(e.message)}finally{setSalvando(false)}}
 async function desagruparTudo(){if(!grupo||salvando)return;if(!window.confirm(`Desagrupar todas as ${grupo.itens?.length||0} OS deste grupo?\n\nAs OS voltarão a ficar individuais.`))return;setSalvando(true);setErro("");try{await grupoApi({action:"desagrupar",grupoId:grupo.id});await carregarGrupos();fechar();setOk("Agrupamento desfeito. As OS voltaram a ficar individuais.")}catch(e){setErro(e.message)}finally{setSalvando(false)}}
 async function adicionar(){if(!selecionados.length||salvando)return;if(!window.confirm(`Adicionar ${selecionados.length} OS a este grupo?\n\nOs dados compartilhados do grupo serão aplicados às novas OS.`))return;setSalvando(true);setErro("");try{await grupoApi({grupoId:grupo.id,servicoIds:selecionados});await carregarGrupos();const r=await grupoApi({action:"obterGrupo",grupoId:grupo.id});setGrupo(r.grupo);setEdit(montarEdicao(r.grupo));setModoAdd(false);setSelecionados([]);setOk(`${selecionados.length} OS adicionada(s) ao grupo. Total recalculado automaticamente.`)}catch(e){setErro(e.message)}finally{setSalvando(false)}}
 async function remover(item){if(salvando)return;const qtd=grupo.itens?.length||0,aviso=qtd<=2?"Como o grupo ficará com menos de duas OS, o agrupamento será encerrado.":"O valor total do grupo será recalculado.";if(!window.confirm(`Remover a OS ${item.os_numero} deste grupo?\n\n${aviso}`))return;setSalvando(true);setErro("");try{const r=await grupoApi({action:"desagruparItem",servicoId:item.id});await carregarGrupos();if(r.grupoEncerrado){fechar();setOk("Agrupamento encerrado e as OS voltaram a ficar individuais.")}else{const novo=await grupoApi({action:"obterGrupo",grupoId:grupo.id});setGrupo(novo.grupo);setEdit(montarEdicao(novo.grupo));setOk(`OS ${item.os_numero} removida. Total do grupo recalculado.`)}}catch(e){setErro(e.message)}finally{setSalvando(false)}}
 return <div onClickCapture={interceptarClique}>
  {ok&&<div className="mb-3 rounded-xl border border-emerald-200 bg-emerald-50 p-3 text-sm text-emerald-700">{ok}</div>}{erro&&!grupo&&<div className="mb-3 rounded-xl border border-red-200 bg-red-50 p-3 text-sm text-red-700">{erro}</div>}<ServicosGerados/>
  {grupo&&<div className="fixed inset-0 z-[90] flex items-center justify-center bg-slate-950/45 p-4" onClick={e=>e.stopPropagation()}><div className="flex max-h-[92vh] w-full max-w-6xl flex-col overflow-hidden rounded-2xl bg-white shadow-2xl"><div className="flex items-start justify-between border-b p-5"><div><div className="flex flex-wrap items-center gap-2"><Layers3 size={20} className="text-blue-600"/><h2 className="text-lg font-bold text-blue-900">Gerenciar faturamento agrupado</h2><Pill v={grupo.status_faturamento}/><Pill v={grupo.status_pagamento}/></div><p className="mt-1 text-sm text-slate-500">{grupo.cliente_nome} · {grupo.itens?.length||0} OS · Total {moeda(grupo.valor_total)}</p></div><button className="p-2" onClick={fechar}><X size={20}/></button></div>{erro&&<div className="mx-4 mt-4 rounded-xl border border-red-200 bg-red-50 p-3 text-sm text-red-700">{erro}</div>}{ok&&<div className="mx-4 mt-4 rounded-xl border border-emerald-200 bg-emerald-50 p-3 text-sm text-emerald-700">{ok}</div>}
  {!modoAdd&&<><div className="grid gap-3 border-b bg-slate-50/70 p-4 text-sm md:grid-cols-4"><div><span className="text-xs text-slate-500">Referência para pagamento</span><p className="font-semibold">{grupo.referencia_pagamento||"—"}</p></div><div><span className="text-xs text-slate-500">NF</span><p className="font-semibold">{grupo.numero_nf||grupo.itens?.find(x=>x.numero_nf)?.numero_nf||"—"}</p></div><div><span className="text-xs text-slate-500">Empresa</span><p className="font-semibold">{grupo.empresa?.nome||"—"}</p></div><div><span className="text-xs text-slate-500">Documento</span><p className="font-semibold">{grupo.cnpj_cpf||"—"}</p></div></div>
  {editando&&<div className="border-b bg-blue-50/40 p-4"><div className="mb-3 rounded-xl border border-blue-200 bg-blue-50 p-3 text-xs text-blue-800">Ao salvar, a alteração será aplicada a todas as <b>{grupo.itens?.length||0} OS</b> deste grupo. Campos com valores diferentes permanecem sem seleção até você escolher o valor que deve ser aplicado.</div><div className="grid gap-3 md:grid-cols-2 lg:grid-cols-4">
   <label className="text-xs font-semibold">Empresa<select className="input mt-1 w-full" value={edit?.empresa_id||""} onChange={e=>setCampo("empresa_id",e.target.value)}>{empresas.map(e=><option key={e.id} value={e.id}>{e.nome}</option>)}</select>{dica("empresa_id")}</label>
   <label className="text-xs font-semibold">Vencimento<input type="date" className="input mt-1 w-full" value={edit?.data_vencimento||""} onChange={e=>setCampo("data_vencimento",e.target.value)}/>{dica("data_vencimento")}</label>
   <label className="text-xs font-semibold">Emissão<input type="date" className="input mt-1 w-full" value={edit?.data_emissao||""} onChange={e=>setCampo("data_emissao",e.target.value)}/>{dica("data_emissao")}</label>
   <label className="text-xs font-semibold">NF<input className="input mt-1 w-full" value={edit?.numero_nf||""} placeholder={divergencias.numero_nf?"Valores diferentes":""} onChange={e=>setCampo("numero_nf",e.target.value)}/>{dica("numero_nf")}</label>
   <label className="text-xs font-semibold">Referência para pagamento<input className="input mt-1 w-full" value={edit?.referencia_pagamento||""} placeholder={divergencias.referencia_pagamento?"Valores diferentes":""} onChange={e=>setCampo("referencia_pagamento",e.target.value)}/>{dica("referencia_pagamento")}</label>
   <label className="text-xs font-semibold">Forma de pagamento<select className="input mt-1 w-full" value={edit?.forma_pagamento||""} onChange={e=>setCampo("forma_pagamento",e.target.value)}><option value="">{divergencias.forma_pagamento?"Valores diferentes":"—"}</option>{formasDisponiveis.map(f=><option key={f} value={f}>{f}</option>)}</select>{dica("forma_pagamento")}</label>
   <label className="text-xs font-semibold">Status de faturamento<select className="input mt-1 w-full" value={edit?.status_faturamento||""} onChange={e=>setCampo("status_faturamento",e.target.value)}><option value="">{divergencias.status_faturamento?"Valores diferentes":"—"}</option>{["AGUARDANDO","PRONTO PARA FATURAR","FATURADO","NAO FATURAR","CANCELADO"].map(s=><option key={s} value={s}>{label(s)}</option>)}</select>{dica("status_faturamento")}</label>
   <label className="text-xs font-semibold">Pagamento<select className="input mt-1 w-full" value={edit?.status_pagamento||""} onChange={e=>setCampo("status_pagamento",e.target.value)}><option value="">—</option>{["AGUARDANDO","A RECEBER","PAGO","PARCIAL","VENCIDO","DIVERGENCIA","CANCELADO"].map(s=><option key={s} value={s}>{label(s)}</option>)}</select></label>
  </div></div>}
  <div className="flex flex-wrap items-center justify-between gap-2 border-b px-4 py-3"><h3 className="font-bold text-blue-900">OS que compõem este grupo</h3><div className="flex gap-2">{editando?<><button className="btn-secondary text-xs" onClick={()=>setEditando(false)}>Cancelar edição</button><button className="btn-primary text-xs" onClick={salvarGrupo} disabled={salvando}><Save size={14}/>Salvar para {grupo.itens?.length||0} OS</button></>:<><button className="btn-secondary text-xs" onClick={()=>setEditando(true)}><Pencil size={14}/>Editar dados do grupo</button><button className="btn-primary text-xs" onClick={abrirAdicionar}><Plus size={14}/>Adicionar OS ao grupo</button><button className="btn-secondary text-xs" onClick={desagruparTudo} disabled={salvando}><Trash2 size={14}/>Desagrupar grupo</button></>}</div></div>
  <div className="overflow-auto p-4"><div className="overflow-x-auto rounded-xl border"><table className="w-full min-w-[900px] text-xs"><thead className="bg-slate-50 text-left text-slate-500"><tr><th className="p-3">OS</th><th>Contrato</th><th>NF</th><th>Faturamento</th><th>Pagamento</th><th>Vencimento</th><th className="text-right">Valor</th><th></th></tr></thead><tbody>{(grupo.itens||[]).map(s=><tr key={s.id} className="border-t"><td className="p-3 font-semibold">{s.os_numero}</td><td>{s.contrato_proposta||"—"}</td><td>{s.numero_nf||"—"}</td><td><Pill v={s.status_faturamento}/></td><td><Pill v={s.status_pagamento}/></td><td>{dataBr(s.data_vencimento)}</td><td className="text-right font-semibold">{moeda(s.valor_faturar??s.valor_original)}</td><td className="p-3 text-right"><div className="flex justify-end gap-2"><button className="inline-flex items-center gap-1 text-blue-700" onClick={()=>setItemEdit({...s})} disabled={salvando}><Pencil size={13}/>Editar</button><button className="inline-flex items-center gap-1 text-red-600" onClick={()=>remover(s)} disabled={salvando}><Trash2 size={13}/>Remover</button></div></td></tr>)}</tbody></table></div></div></>}
  {itemEdit&&<div className="fixed inset-0 z-[110] flex items-center justify-center bg-slate-950/50 p-4"><div className="w-full max-w-3xl rounded-2xl bg-white p-5 shadow-2xl"><div className="mb-4 flex justify-between"><div><h3 className="font-bold text-blue-900">Editar OS {itemEdit.os_numero}</h3><p className="text-xs text-slate-500">A alteração será aplicada somente nesta OS.</p></div><button onClick={()=>setItemEdit(null)}><X size={18}/></button></div><div className="grid gap-3 md:grid-cols-2"><label className="text-xs font-semibold">Vencimento<input type="date" className="input mt-1 w-full" value={data(itemEdit.data_vencimento)} onChange={e=>setItemEdit(v=>({...v,data_vencimento:e.target.value}))}/></label><label className="text-xs font-semibold">Emissão<input type="date" className="input mt-1 w-full" value={data(itemEdit.data_emissao)} onChange={e=>setItemEdit(v=>({...v,data_emissao:e.target.value}))}/></label><label className="text-xs font-semibold">NF<input className="input mt-1 w-full" value={itemEdit.numero_nf||""} onChange={e=>setItemEdit(v=>({...v,numero_nf:e.target.value}))}/></label><label className="text-xs font-semibold">Referência<input className="input mt-1 w-full" value={itemEdit.referencia_pagamento||""} onChange={e=>setItemEdit(v=>({...v,referencia_pagamento:e.target.value}))}/></label><label className="text-xs font-semibold">Forma de pagamento<input className="input mt-1 w-full" value={itemEdit.forma_pagamento||""} onChange={e=>setItemEdit(v=>({...v,forma_pagamento:e.target.value}))}/></label><label className="text-xs font-semibold">Status<select className="input mt-1 w-full" value={itemEdit.status_faturamento||""} onChange={e=>setItemEdit(v=>({...v,status_faturamento:e.target.value}))}>{["AGUARDANDO","PRONTO PARA FATURAR","FATURADO","NAO FATURAR","CANCELADO"].map(x=><option key={x} value={x}>{label(x)}</option>)}</select></label></div><div className="mt-5 flex justify-end gap-2"><button className="btn-secondary" onClick={()=>setItemEdit(null)}>Cancelar</button><button className="btn-primary" onClick={salvarItem} disabled={salvando}><Save size={14}/>Salvar somente esta OS</button></div></div></div>}
  {modoAdd&&<div className="flex min-h-0 flex-1 flex-col"><div className="flex items-center justify-between border-b p-4"><div><h3 className="font-bold text-blue-900">Adicionar OS ao grupo</h3><p className="text-xs text-slate-500">Mesmo cliente/CNPJ, mesma empresa e pronta para faturar.</p></div><button className="btn-secondary text-xs" onClick={()=>setModoAdd(false)}>Voltar</button></div><div className="space-y-3 overflow-auto p-4"><div className="relative"><Search size={15} className="absolute left-3 top-3 text-slate-400"/><input className="input w-full pl-9" placeholder="Buscar OS, cliente ou contrato..." value={busca} onChange={e=>setBusca(e.target.value)}/></div><div className="rounded-xl border"><table className="w-full text-xs"><tbody>{filtrados.map(x=><tr key={x.id} className="border-t"><td className="p-3"><input type="checkbox" checked={selecionados.includes(x.id)} onChange={()=>setSelecionados(v=>v.includes(x.id)?v.filter(id=>id!==x.id):[...v,x.id])}/></td><td className="font-semibold">{x.os_numero}</td><td>{x.contrato_proposta||"—"}</td><td className="text-right">{moeda(x.valor_faturar??x.valor_original)}</td></tr>)}</tbody></table>{!filtrados.length&&<div className="p-8 text-center text-sm text-slate-500">Nenhuma OS elegível encontrada.</div>}</div></div><div className="flex justify-end border-t p-4"><button className="btn-primary" disabled={salvando||!selecionados.length} onClick={adicionar}>Adicionar {selecionados.length||""} OS ao grupo</button></div></div>}
  {!modoAdd&&<div className="flex justify-end border-t p-4"><button className="btn-secondary" onClick={fechar}>Fechar</button></div>}</div></div>}
 </div>
}
