import { useEffect, useMemo, useState } from "react";
import { Layers3, Pencil, Plus, Search, Save, Trash2, X } from "lucide-react";
import ServicosGerados from "./ServicosGerados.jsx";
import { servicosGeradosListar } from "../services/servicosGerados.js";
import { financeiroOpcoes } from "../services/financeiro.js";
import { API } from "../lib/api.js";
import { comCracha, mensagemDoStatus } from "../lib/sessao.js";

const moeda=v=>Number(v||0).toLocaleString("pt-BR",{style:"currency",currency:"BRL"});
const data=v=>v?String(v).slice(0,10):"";
const dataBr=v=>v?new Date(`${String(v).slice(0,10)}T12:00:00`).toLocaleDateString("pt-BR"):"—";
const dig=v=>String(v||"").replace(/\D/g,"");
const chaveCliente=x=>dig(x.cnpj_cpf)||String(x.cliente||"").trim().toUpperCase();
const badge={FATURADO:"bg-emerald-100 text-emerald-700",PAGO:"bg-emerald-100 text-emerald-700","A RECEBER":"bg-amber-100 text-amber-700",AGUARDANDO:"bg-blue-100 text-blue-700","PRONTO PARA FATURAR":"bg-blue-100 text-blue-700",PARCIAL:"bg-amber-100 text-amber-700",VENCIDO:"bg-red-100 text-red-700",DIVERGENCIA:"bg-violet-100 text-violet-700","NAO FATURAR":"bg-slate-100 text-slate-600",CANCELADO:"bg-slate-100 text-slate-600"};
const label=s=>({"PRONTO PARA FATURAR":"Pronto para faturar","NAO FATURAR":"Não faturar",DIVERGENCIA:"Divergência"}[s]||String(s||"").toLowerCase().replace(/(^|\s)\S/g,m=>m.toUpperCase()));
const Pill=({v})=>v?<span className={`inline-flex rounded-full px-2 py-0.5 text-[10px] font-semibold ${badge[v]||"bg-slate-100 text-slate-600"}`}>{label(v)}</span>:null;

async function grupoApi(corpo){
  const resp=await comCracha(`${API}/ml-financeiro-servicos-grupar`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(corpo)});
  const body=await resp.json().catch(()=>null);
  if(!resp.ok)throw new Error(body?.erro||body?.message||mensagemDoStatus(resp.status));
  return body||{};
}

export default function ServicosGeradosAgrupado(){
  const [grupos,setGrupos]=useState([]),[empresas,setEmpresas]=useState([]),[grupo,setGrupo]=useState(null),[edit,setEdit]=useState(null),[editando,setEditando]=useState(false),[modoAdd,setModoAdd]=useState(false),[dados,setDados]=useState([]),[busca,setBusca]=useState(""),[selecionados,setSelecionados]=useState([]),[erro,setErro]=useState(""),[ok,setOk]=useState(""),[salvando,setSalvando]=useState(false);

  async function carregarGrupos(){const r=await grupoApi({action:"listarGrupos"});setGrupos(r.grupos||[]);if(r.empresas?.length)setEmpresas(r.empresas);return r.grupos||[]}
  useEffect(()=>{carregarGrupos().catch(()=>{});financeiroOpcoes().then(r=>{if(r.empresas?.length)setEmpresas(r.empresas)}).catch(()=>{})},[]);
  async function abrirGrupo(g){setErro("");setOk("");try{const r=await grupoApi({action:"obterGrupo",grupoId:g.id});const x=r.grupo;setGrupo(x);setEdit({...x,empresa_id:x.empresa_id||"",data_vencimento:data(x.data_vencimento),data_emissao:data(x.data_emissao),numero_nf:x.numero_nf||"",forma_pagamento:x.forma_pagamento||"",status_faturamento:x.status_faturamento||"",referencia_pagamento:x.referencia_pagamento||""});setEditando(false);setModoAdd(false);setSelecionados([])}catch(e){setErro(e.message)}}
  function fechar(){setGrupo(null);setEdit(null);setEditando(false);setModoAdd(false);setSelecionados([]);setErro("")}

  async function interceptarGrupo(ev){
    const botao=ev.target.closest?.('button[title="Visualizar grupo e suas OS"]');
    if(!botao)return;
    ev.preventDefault();ev.stopPropagation();
    try{
      const lista=grupos.length?grupos:await carregarGrupos(),tr=botao.closest("tr"),texto=tr?.innerText||"";
      const candidatos=lista.filter(g=>texto.includes(g.cliente_nome||"")&&texto.includes(String(g.itens?.length||0)+" OS"));
      const escolhido=candidatos.length===1?candidatos[0]:candidatos.find(g=>texto.includes((g.empresa?.nome||"")))||candidatos[0];
      if(!escolhido)throw new Error("Não foi possível localizar este agrupamento. Atualize a página e tente novamente.");
      await abrirGrupo(escolhido);
    }catch(e){setErro(e.message)}
  }

  async function abrirAdicionar(){setErro("");setBusca("");setSelecionados([]);setModoAdd(true);try{const r=await servicosGeradosListar({busca:""});setDados(r.itens||[])}catch(e){setErro(e.message)}}
  const idsAgrupados=useMemo(()=>new Set(grupos.flatMap(g=>(g.itens||[]).map(x=>x.id))),[grupos]);
  const elegiveis=useMemo(()=>dados.filter(x=>!x.grupo_faturamento&&!idsAgrupados.has(x.id)&&x.status_faturamento==="PRONTO PARA FATURAR"&&x.empresa_id===grupo?.empresa_id&&chaveCliente(x)===String(grupo?.cliente_chave||"").toUpperCase()),[dados,idsAgrupados,grupo]);
  const filtrados=useMemo(()=>{const q=busca.trim().toLowerCase();return elegiveis.filter(x=>!q||`${x.os_numero} ${x.cliente} ${x.cnpj_cpf||""} ${x.contrato_proposta||""}`.toLowerCase().includes(q))},[elegiveis,busca]);

  async function salvarGrupo(){if(!grupo||salvando)return;const qtd=grupo.itens?.length||0;if(!window.confirm(`Esta alteração será aplicada às ${qtd} OS deste grupo.\n\nDeseja continuar?`))return;setSalvando(true);setErro("");setOk("");try{const r=await grupoApi({action:"editarGrupo",grupoId:grupo.id,campos:{empresa_id:edit.empresa_id,data_vencimento:edit.data_vencimento,data_emissao:edit.data_emissao,numero_nf:edit.numero_nf,referencia_pagamento:edit.referencia_pagamento,forma_pagamento:edit.forma_pagamento,status_faturamento:edit.status_faturamento}});setGrupo(r.grupo);setEdit({...r.grupo,data_vencimento:data(r.grupo.data_vencimento),data_emissao:data(r.grupo.data_emissao),numero_nf:r.grupo.numero_nf||"",forma_pagamento:r.grupo.forma_pagamento||"",status_faturamento:r.grupo.status_faturamento||"",referencia_pagamento:r.grupo.referencia_pagamento||""});setEditando(false);await carregarGrupos();setOk(`Alteração aplicada às ${r.quantidade||qtd} OS do grupo.`)}catch(e){setErro(e.message)}finally{setSalvando(false)}}
  async function adicionar(){if(!selecionados.length||salvando)return;if(!window.confirm(`Adicionar ${selecionados.length} OS a este grupo?\n\nOs dados compartilhados do grupo serão aplicados às novas OS.`))return;setSalvando(true);setErro("");try{await grupoApi({grupoId:grupo.id,servicoIds:selecionados});await carregarGrupos();const r=await grupoApi({action:"obterGrupo",grupoId:grupo.id});setGrupo(r.grupo);setModoAdd(false);setSelecionados([]);setOk(`${selecionados.length} OS adicionada(s) ao grupo. Total recalculado automaticamente.`)}catch(e){setErro(e.message)}finally{setSalvando(false)}}
  async function remover(item){if(salvando)return;const qtd=grupo.itens?.length||0, aviso=qtd<=2?"Como o grupo ficará com menos de duas OS, o agrupamento será encerrado.":"O valor total do grupo será recalculado.";if(!window.confirm(`Remover a OS ${item.os_numero} deste grupo?\n\n${aviso}`))return;setSalvando(true);setErro("");try{const r=await grupoApi({action:"desagruparItem",servicoId:item.id});await carregarGrupos();if(r.grupoEncerrado){fechar();setOk("Agrupamento encerrado e as OS voltaram a ficar individuais.")}else{const novo=await grupoApi({action:"obterGrupo",grupoId:grupo.id});setGrupo(novo.grupo);setEdit(v=>({...v,...novo.grupo,data_vencimento:data(novo.grupo.data_vencimento),data_emissao:data(novo.grupo.data_emissao)}));setOk(`OS ${item.os_numero} removida. Total do grupo recalculado.`)}}catch(e){setErro(e.message)}finally{setSalvando(false)}}

  return <div onClickCapture={interceptarGrupo}>
    {ok&&<div className="mb-3 rounded-xl border border-emerald-200 bg-emerald-50 p-3 text-sm text-emerald-700">{ok}</div>}
    {erro&&!grupo&&<div className="mb-3 rounded-xl border border-red-200 bg-red-50 p-3 text-sm text-red-700">{erro}</div>}
    <ServicosGerados/>

    {grupo&&<div className="fixed inset-0 z-[90] flex items-center justify-center bg-slate-950/45 p-4" onClick={e=>e.stopPropagation()}><div className="flex max-h-[92vh] w-full max-w-6xl flex-col overflow-hidden rounded-2xl bg-white shadow-2xl">
      <div className="flex items-start justify-between border-b p-5"><div><div className="flex flex-wrap items-center gap-2"><Layers3 size={20} className="text-blue-600"/><h2 className="text-lg font-bold text-blue-900">Faturamento agrupado</h2><Pill v={grupo.status_faturamento}/>{grupo.itens?.some(x=>x.status_pagamento==="DIVERGENCIA")&&<Pill v="DIVERGENCIA"/>}</div><p className="mt-1 text-sm text-slate-500">{grupo.cliente_nome} · {grupo.itens?.length||0} OS · Total {moeda(grupo.valor_total)}</p></div><button className="p-2" onClick={fechar}><X size={20}/></button></div>
      {erro&&<div className="mx-4 mt-4 rounded-xl border border-red-200 bg-red-50 p-3 text-sm text-red-700">{erro}</div>}{ok&&<div className="mx-4 mt-4 rounded-xl border border-emerald-200 bg-emerald-50 p-3 text-sm text-emerald-700">{ok}</div>}

      {!modoAdd&&<>
        {!editando?<div className="grid gap-3 border-b bg-slate-50/70 p-4 text-sm md:grid-cols-4"><div><span className="text-xs text-slate-500">Referência para pagamento</span><p className="font-semibold">{grupo.referencia_pagamento||"—"}</p></div><div><span className="text-xs text-slate-500">NF</span><p className="font-semibold">{grupo.numero_nf||grupo.itens?.find(x=>x.numero_nf)?.numero_nf||"—"}</p></div><div><span className="text-xs text-slate-500">Empresa</span><p className="font-semibold">{grupo.empresa?.nome||"—"}</p></div><div><span className="text-xs text-slate-500">Documento</span><p className="font-semibold">{grupo.cnpj_cpf||"—"}</p></div></div>:
        <div className="border-b bg-blue-50/40 p-4"><div className="mb-3 rounded-xl border border-blue-200 bg-blue-50 p-3 text-xs text-blue-800">Os campos abaixo são compartilhados. Ao salvar, a alteração será aplicada a todas as <b>{grupo.itens?.length||0} OS</b> deste grupo.</div><div className="grid gap-3 md:grid-cols-2 lg:grid-cols-4"><label className="text-xs font-semibold text-slate-600">Empresa<select className="input mt-1 w-full" value={edit?.empresa_id||""} onChange={e=>setEdit(v=>({...v,empresa_id:e.target.value}))}>{empresas.map(e=><option key={e.id} value={e.id}>{e.nome}</option>)}</select></label><label className="text-xs font-semibold text-slate-600">Data de vencimento<input type="date" className="input mt-1 w-full" value={edit?.data_vencimento||""} onChange={e=>setEdit(v=>({...v,data_vencimento:e.target.value}))}/></label><label className="text-xs font-semibold text-slate-600">Data de emissão<input type="date" className="input mt-1 w-full" value={edit?.data_emissao||""} onChange={e=>setEdit(v=>({...v,data_emissao:e.target.value}))}/></label><label className="text-xs font-semibold text-slate-600">Informação / Nº da NF<input className="input mt-1 w-full" value={edit?.numero_nf||""} onChange={e=>setEdit(v=>({...v,numero_nf:e.target.value}))}/></label><label className="text-xs font-semibold text-slate-600">Referência para pagamento<input className="input mt-1 w-full" value={edit?.referencia_pagamento||""} onChange={e=>setEdit(v=>({...v,referencia_pagamento:e.target.value}))}/></label><label className="text-xs font-semibold text-slate-600">Forma de pagamento<input className="input mt-1 w-full" value={edit?.forma_pagamento||""} onChange={e=>setEdit(v=>({...v,forma_pagamento:e.target.value}))}/></label><label className="text-xs font-semibold text-slate-600">Status<select className="input mt-1 w-full" value={edit?.status_faturamento||""} onChange={e=>setEdit(v=>({...v,status_faturamento:e.target.value}))}><option value="">—</option>{["AGUARDANDO","PRONTO PARA FATURAR","FATURADO","NAO FATURAR","CANCELADO"].map(s=><option key={s} value={s}>{label(s)}</option>)}</select></label></div></div>}
        <div className="flex flex-wrap items-center justify-between gap-2 border-b px-4 py-3"><h3 className="font-bold text-blue-900">OS que compõem este grupo</h3><div className="flex flex-wrap gap-2">{editando?<><button className="btn-secondary text-xs" onClick={()=>setEditando(false)} disabled={salvando}>Cancelar edição</button><button className="btn-primary text-xs" onClick={salvarGrupo} disabled={salvando}><Save size={14}/>{salvando?"Aplicando...":`Salvar para ${grupo.itens?.length||0} OS`}</button></>:<><button className="btn-secondary text-xs" onClick={()=>setEditando(true)}><Pencil size={14}/>Editar dados do grupo</button><button className="btn-primary text-xs" onClick={abrirAdicionar}><Plus size={14}/>Adicionar OS ao grupo</button></>}</div></div>
        <div className="overflow-auto p-4"><div className="overflow-x-auto rounded-xl border"><table className="w-full min-w-[1080px] text-[11px]"><thead className="bg-slate-50 text-left text-[10px] uppercase text-slate-500"><tr><th className="px-3 py-2">OS</th><th className="px-3 py-2">Contrato</th><th className="px-3 py-2">NF</th><th className="px-3 py-2">Faturamento</th><th className="px-3 py-2">Pagamento</th><th className="px-3 py-2">Data da Recepção</th><th className="px-3 py-2">Emissão</th><th className="px-3 py-2">Vencimento</th><th className="px-3 py-2 text-right">Valor</th><th className="px-3 py-2 text-right">Ação</th></tr></thead><tbody>{(grupo.itens||[]).map(s=><tr key={s.id} className="border-t hover:bg-slate-50"><td className="px-3 py-2 font-semibold">{s.os_numero}</td><td className="px-3 py-2">{s.contrato_proposta||"—"}</td><td className="px-3 py-2">{s.numero_nf||"—"}</td><td className="px-3 py-2"><Pill v={s.status_faturamento}/></td><td className="px-3 py-2"><Pill v={s.status_pagamento}/></td><td className="px-3 py-2">{dataBr(s.data_os)}</td><td className="px-3 py-2">{dataBr(s.data_emissao)}</td><td className="px-3 py-2">{dataBr(s.data_vencimento)}</td><td className="px-3 py-2 text-right font-semibold">{moeda(s.valor_faturar||s.valor_original)}</td><td className="px-3 py-2 text-right"><button className="inline-flex items-center gap-1 rounded-lg px-2 py-1 text-red-600 hover:bg-red-50" disabled={salvando} onClick={()=>remover(s)} title="Remover esta OS do grupo"><Trash2 size={13}/>Remover</button></td></tr>)}</tbody><tfoot><tr className="border-t bg-slate-50"><td colSpan="8" className="px-3 py-2 font-bold">Total do grupo</td><td className="px-3 py-2 text-right font-bold">{moeda(grupo.valor_total)}</td><td/></tr></tfoot></table></div></div>
      </>}

      {modoAdd&&<div className="flex min-h-0 flex-1 flex-col"><div className="flex flex-wrap items-center justify-between gap-2 border-b p-4"><div><h3 className="font-bold text-blue-900">Adicionar OS ao grupo</h3><p className="text-xs text-slate-500">Somente OS prontas para faturar, do mesmo cliente/CNPJ e da mesma empresa.</p></div><button className="btn-secondary text-xs" onClick={()=>setModoAdd(false)}>Voltar ao grupo</button></div><div className="space-y-3 overflow-auto p-4"><div className="relative"><Search size={15} className="absolute left-3 top-3 text-slate-400"/><input className="input w-full pl-9" placeholder="Buscar OS, cliente ou contrato..." value={busca} onChange={e=>setBusca(e.target.value)}/></div><div className="max-h-[48vh] overflow-auto rounded-xl border"><table className="w-full text-xs"><thead className="sticky top-0 bg-slate-50 text-left text-slate-500"><tr><th className="p-3"></th><th>OS</th><th>Contrato</th><th>Serviço</th><th className="text-right">Valor</th></tr></thead><tbody>{filtrados.map(x=><tr key={x.id} className={`border-t ${selecionados.includes(x.id)?"bg-blue-50":""}`}><td className="p-3"><input type="checkbox" checked={selecionados.includes(x.id)} onChange={()=>setSelecionados(v=>v.includes(x.id)?v.filter(id=>id!==x.id):[...v,x.id])}/></td><td className="font-semibold">{x.os_numero}</td><td>{x.contrato_proposta||"—"}</td><td>{x.servico||"—"}</td><td className="p-3 text-right font-semibold">{moeda(x.valor_faturar||x.valor_original)}</td></tr>)}</tbody></table>{!filtrados.length&&<div className="p-8 text-center text-sm text-slate-500">Nenhuma OS elegível encontrada para este grupo.</div>}</div></div><div className="flex items-center justify-between border-t p-4"><span className="text-xs text-slate-500">{selecionados.length} OS selecionada(s)</span><button className="btn-primary" disabled={salvando||!selecionados.length} onClick={adicionar}>{salvando?"Adicionando...":`Adicionar ${selecionados.length||""} OS ao grupo`}</button></div></div>}

      {!modoAdd&&<div className="flex justify-end border-t p-4"><button className="btn-secondary" onClick={fechar}>Fechar</button></div>}
    </div></div>}
  </div>
}
