import { createClient } from "https://esm.sh/@supabase/supabase-js@2.45.0";
const U=Deno.env.get("SUPABASE_URL")!,K=Deno.env.get("SB_SECRET_KEY")??Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!,J=Deno.env.get("ML_JWT_SECRET")??"";
const sb=createClient(U,K,{auth:{persistSession:false,autoRefreshToken:false}}),enc=new TextEncoder(),dec=new TextDecoder();
const C={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type","Access-Control-Allow-Methods":"POST, OPTIONS"};
const out=(d:any,s=200)=>new Response(JSON.stringify(d),{status:s,headers:{...C,"Content-Type":"application/json; charset=utf-8","Cache-Control":"no-store"}}),txt=(v:any)=>String(v??"").trim();
function b64u(s:string){s=s.replace(/-/g,"+").replace(/_/g,"/");while(s.length%4)s+="=";const b=atob(s),o=new Uint8Array(b.length);for(let i=0;i<b.length;i++)o[i]=b.charCodeAt(i);return o}
async function jwt(t:string){if(!J||!t)return null;const p=t.split(".");if(p.length!==3)return null;try{const k=await crypto.subtle.importKey("raw",enc.encode(J),{name:"HMAC",hash:"SHA-256"},false,["verify"]);if(!await crypto.subtle.verify("HMAC",k,b64u(p[2]),enc.encode(`${p[0]}.${p[1]}`)))return null;const x=JSON.parse(dec.decode(b64u(p[1])));if(x.sis!=="minaslab"||(typeof x.exp==="number"&&x.exp<Math.floor(Date.now()/1000)))return null;return x}catch{return null}}
const dig=(v:any)=>txt(v).replace(/\D/g,"");
const refProvisoria=(v:any)=>["EM ANDAMENTO","SOLICITAR PO","AGUARDANDO","PENDENTE","A DEFINIR","SEM PO"].includes(txt(v).toUpperCase());
async function limparGrupo(id:string){try{await sb.from("servicos_gerados_grupos_itens").delete().eq("grupo_id",id)}catch{}try{await sb.from("servicos_gerados_grupos_faturamento").delete().eq("id",id)}catch{}}
Deno.serve(async req=>{if(req.method==="OPTIONS")return new Response("ok",{headers:C});if(req.method!=="POST")return out({erro:"Use POST."},405);const m=txt(req.headers.get("authorization")).match(/^Bearer\s+(.+)$/i),cr=m?await jwt(m[1]):null;if(!cr)return out({erro:"Entre no sistema."},401);if(txt(cr?.papel)!=="direcao")return out({erro:"O financeiro é somente da direção."},403);let b:any={};try{b=await req.json()}catch{return out({erro:"JSON inválido."},400)};
if(b.action==="listarGrupos"){const q=await sb.from("servicos_gerados_grupos_faturamento").select("id,empresa_id,cliente_chave,cliente_nome,cnpj_cpf,tipo,status,referencia_pagamento,valor_total,created_at").eq("status","ABERTO").order("created_at",{ascending:false}).limit(200);if(q.error)return out({erro:q.error.message},409);return out({ok:true,grupos:q.data||[]})}
if(b.action==="desagrupar"){const grupoId=txt(b.grupoId);if(!grupoId)return out({erro:"Agrupamento não informado."},400);try{const r=await sb.rpc("servicos_gerados_desagrupar",{p_grupo_id:grupoId});if(r.error)throw r.error;return out(r.data||{ok:true})}catch(e:any){return out({erro:e?.message||"Não foi possível desagrupar."},409)}}
if(b.action==="desagruparItem"){const servicoId=txt(b.servicoId);if(!servicoId)return out({erro:"OS não informada."},400);try{const r=await sb.rpc("servicos_gerados_desagrupar_item",{p_servico_id:servicoId});if(r.error)throw r.error;return out(r.data||{ok:true})}catch(e:any){return out({erro:e?.message||"Não foi possível desagrupar a OS."},409)}}
const ids=[...new Set((Array.isArray(b.servicoIds)?b.servicoIds:[]).map(txt).filter(Boolean))];const grupoExistenteId=txt(b.grupoId);if(grupoExistenteId&&ids.length<1)return out({erro:"Selecione ao menos uma OS para adicionar ao grupo."},400);if(!grupoExistenteId&&ids.length<2)return out({erro:"Selecione pelo menos duas OS para agrupar."},400);
try{const q=await sb.from("servicos_gerados").select("id,empresa_id,cliente,cnpj_cpf,os_numero,contrato_proposta,valor_faturar,valor_original,data_vencimento,forma_pagamento,status_faturamento,referencia_pagamento,empresa:empresas(nome,usa_omie)").in("id",ids).eq("apagado",false);if(q.error)throw q.error;const itens=q.data||[];if(itens.length!==ids.length)throw new Error("Uma ou mais OS não foram encontradas.");if(itens.some((x:any)=>x.status_faturamento!=="PRONTO PARA FATURAR"))throw new Error("Somente OS com status Pronto para faturar podem ser agrupadas.");const emp=itens[0].empresa_id,doc=dig(itens[0].cnpj_cpf),cli=txt(itens[0].cliente).toUpperCase();if(!emp||itens.some((x:any)=>x.empresa_id!==emp))throw new Error("As OS precisam pertencer à mesma empresa de emissão.");if(itens.some((x:any)=>(doc&&dig(x.cnpj_cpf)!==doc)||(!doc&&txt(x.cliente).toUpperCase()!==cli)))throw new Error("As OS precisam pertencer ao mesmo cliente/CNPJ.");const empresa=Array.isArray(itens[0].empresa)?itens[0].empresa[0]:itens[0].empresa;const usaOmie=!!empresa?.usa_omie,tipo=usaOmie?"OMIE":"FATURAMENTO",refInformada=txt(b.referenciaPagamento),refsExistentes=[...new Set(itens.map((x:any)=>txt(x.referencia_pagamento)).filter((v:string)=>v&&!refProvisoria(v)))];
if(grupoExistenteId){const gq=await sb.from("servicos_gerados_grupos_faturamento").select("*").eq("id",grupoExistenteId).single();if(gq.error||!gq.data)throw new Error("Agrupamento não encontrado.");const g:any=gq.data;if(g.status!=="ABERTO")throw new Error("Somente agrupamentos abertos podem receber novas OS.");if(g.empresa_id!==emp)throw new Error("A OS e o agrupamento precisam pertencer à mesma empresa.");const chave=doc||cli;if(txt(g.cliente_chave).toUpperCase()!==txt(chave).toUpperCase())throw new Error("A OS precisa pertencer ao mesmo cliente/CNPJ do agrupamento.");if(g.tipo!==tipo)throw new Error("O tipo de faturamento da OS não corresponde ao agrupamento.");const dup=await sb.from("servicos_gerados_grupos_itens").select("servico_id").in("servico_id",ids);if(dup.error)throw dup.error;if((dup.data||[]).length)throw new Error("Uma ou mais OS já pertencem a um agrupamento.");const gi=await sb.from("servicos_gerados_grupos_itens").insert(itens.map((x:any)=>({grupo_id:grupoExistenteId,servico_id:x.id,valor:Number(x.valor_faturar||x.valor_original||0)})));if(gi.error)throw gi.error;const adicional=itens.reduce((s:number,x:any)=>s+Number(x.valor_faturar||x.valor_original||0),0),novoTotal=Number(g.valor_total||0)+adicional;const ug=await sb.from("servicos_gerados_grupos_faturamento").update({valor_total:novoTotal}).eq("id",grupoExistenteId);if(ug.error)throw ug.error;if(usaOmie&&g.referencia_pagamento){const u=await sb.from("servicos_gerados").update({referencia_pagamento:g.referencia_pagamento,pagamento_referencia:g.referencia_pagamento,updated_at:new Date().toISOString(),updated_by:txt(cr.sub)||"direcao"}).in("id",ids);if(u.error)throw u.error}return out({ok:true,grupo:{...g,valor_total:novoTotal,usaOmie,adicionados:itens.map((x:any)=>x.os_numero)}})}
if(usaOmie&&refsExistentes.length>1)throw new Error("As OS possuem Pedidos/Referências Omie diferentes e não podem ser agrupadas juntas.");if(usaOmie&&refsExistentes.length===1&&refInformada&&refInformada.toUpperCase()!==refsExistentes[0].toUpperCase())throw new Error(`A referência informada não confere com o Pedido Omie já vinculado (${refsExistentes[0]}).`);const ref=usaOmie?(refsExistentes[0]||refInformada):refInformada;if(usaOmie&&(!ref||refProvisoria(ref)))throw new Error("Informe um Pedido/Referência Omie definitivo para o grupo.");const total=itens.reduce((s:number,x:any)=>s+Number(x.valor_faturar||x.valor_original||0),0);const g=await sb.from("servicos_gerados_grupos_faturamento").insert({empresa_id:emp,cliente_chave:doc||cli,cliente_nome:itens[0].cliente,cnpj_cpf:itens[0].cnpj_cpf||null,tipo,status:"ABERTO",referencia_pagamento:ref||null,valor_total:total}).select("*").single();if(g.error)throw g.error;const grupoId=g.data.id;const gi=await sb.from("servicos_gerados_grupos_itens").insert(itens.map((x:any)=>({grupo_id:grupoId,servico_id:x.id,valor:Number(x.valor_faturar||x.valor_original||0)})));if(gi.error){await limparGrupo(grupoId);if(String(gi.error.message||"").toLowerCase().includes("duplicate")||String(gi.error.code||"")==="23505")throw new Error("Uma ou mais OS já pertencem a outro agrupamento.");throw gi.error}if(usaOmie){const u=await sb.from("servicos_gerados").update({referencia_pagamento:ref,pagamento_referencia:ref,updated_at:new Date().toISOString(),updated_by:txt(cr.sub)||"direcao"}).in("id",ids);if(u.error){await limparGrupo(grupoId);throw u.error}}return out({ok:true,grupo:{...g.data,usaOmie,empresaNome:empresa?.nome,os:itens.map((x:any)=>x.os_numero),servicos:itens}})}catch(e:any){console.error(e);return out({erro:e?.message||"Falha ao agrupar OS."},409)}});