import { useEffect, useMemo, useState } from 'react'
import { CalendarCheck2, ChevronLeft, ChevronRight, RefreshCw, Search, XCircle } from 'lucide-react'
import { Coletas } from './Coletas'
import { UserAvatar } from '../../components/users/UserAvatar'
import { supabase } from '../../services/supabase'

type Agenda={id:string;inicio:string;fim:string|null;titulo:string|null;status:string|null;responsavel_id:string|null;cliente_id:string|null;ordem_servico_id:string|null;descricao:string|null;endereco_evento:string|null;external_calendar_id:string|null}
type GoogleEvent={id:string;summary:string|null;description:string|null;location:string|null;start:string|null;end:string|null;status:string|null;htmlLink:string|null;updated:string|null}
type Person={id:string;nome:string|null;avatar_url:string|null}
type Client={id:string;nome_fantasia:string|null;razao_social:string|null}
type OS={id:string;numero_os:string|null}
type QueryResult<T>={data:T[]|null;error:{message:string}|null}
type HistoryRow={id:string;date:string;event:string;detail:string;client:string;os:string;person:string;avatar:string|null;status:string;origin:'GOOGLE AGENDA'|'AGENDA CRM'}
const PAGE_SIZE=1000
const HISTORY_PAGE=20
const months=['Todos os meses','Janeiro','Fevereiro','Março','Abril','Maio','Junho','Julho','Agosto','Setembro','Outubro','Novembro','Dezembro']
async function fetchAll<T>(makeQuery:(from:number,to:number)=>PromiseLike<QueryResult<T>>){const rows:T[]=[];for(let from=0;;from+=PAGE_SIZE){const r=await makeQuery(from,from+PAGE_SIZE-1);if(r.error)return{data:rows,error:r.error};const batch=(r.data??[]) as T[];rows.push(...batch);if(batch.length<PAGE_SIZE)return{data:rows,error:null}}}

export function ColetasPainel(){return <><Coletas/><HistoricoAgenda/></>}

function HistoricoAgenda(){
 const[events,setEvents]=useState<Agenda[]>([]);const[googleEvents,setGoogleEvents]=useState<GoogleEvent[]>([]);const[people,setPeople]=useState<Person[]>([]);const[clients,setClients]=useState<Client[]>([]);const[orders,setOrders]=useState<OS[]>([]);const[q,setQ]=useState('');const[month,setMonth]=useState('0');const[page,setPage]=useState(1);const[error,setError]=useState('');const[loading,setLoading]=useState(true)
 async function load(){setLoading(true);setError('');const[a,b,c,d,g]=await Promise.all([
  fetchAll<Agenda>((from,to)=>supabase.from('agendamentos').select('id,inicio,fim,titulo,status,responsavel_id,cliente_id,ordem_servico_id,descricao,endereco_evento,external_calendar_id').is('deleted_at',null).order('inicio',{ascending:false}).range(from,to)),
  fetchAll<Person>((from,to)=>supabase.from('profiles').select('id,nome,avatar_url').order('nome').range(from,to)),
  fetchAll<Client>((from,to)=>supabase.from('clientes').select('id,nome_fantasia,razao_social').is('deleted_at',null).order('id').range(from,to)),
  fetchAll<OS>((from,to)=>supabase.from('ordens_servico').select('id,numero_os').is('deleted_at',null).order('id').range(from,to)),
  supabase.functions.invoke('google-calendar-events',{body:{time_max:new Date().toISOString()}})
 ]);const e=a.error||b.error||c.error||d.error||g.error;if(e)setError(e.message);setEvents(a.data);setPeople(b.data);setClients(c.data);setOrders(d.data);if(!g.error&&Array.isArray(g.data?.events))setGoogleEvents(g.data.events as GoogleEvent[]);setLoading(false)}
 useEffect(()=>{void load()},[])
 useEffect(()=>setPage(1),[q,month])
 const history=useMemo<HistoryRow[]>(()=>{
  const localByGoogle=new Set(events.map(e=>e.external_calendar_id).filter(Boolean) as string[])
  const local=events.filter(e=>new Date(e.inicio).getTime()<=Date.now()).map(e=>{const p=people.find(x=>x.id===e.responsavel_id);const c=clients.find(x=>x.id===e.cliente_id);const os=orders.find(x=>x.id===e.ordem_servico_id);return{id:`crm-${e.id}`,date:e.inicio,event:e.titulo||'Compromisso da agenda',detail:e.descricao||e.endereco_evento||'—',client:c?.nome_fantasia||c?.razao_social||'Cliente não vinculado',os:os?.numero_os||'Sem OS vinculada',person:p?.nome||'Sem coletor',avatar:p?.avatar_url||null,status:e.status||'—',origin:e.external_calendar_id?'GOOGLE AGENDA' as const:'AGENDA CRM' as const}})
  const direct=googleEvents.filter(e=>e.start&&!localByGoogle.has(e.id)&&new Date(e.start).getTime()<=Date.now()).map(e=>{const personName=parseDescription(e.description,'COLETOR')||'Sem coletor';const p=people.find(x=>normalize(x.nome||'')===normalize(personName));return{id:`google-${e.id}`,date:e.start!,event:e.summary||'Coleta no Google Agenda',detail:e.description||e.location||'—',client:clientFromSummary(e.summary),os:osFromSummary(e.summary),person:personName,avatar:p?.avatar_url||null,status:e.status||'confirmed',origin:'GOOGLE AGENDA' as const}})
  return [...local,...direct].sort((x,y)=>new Date(y.date).getTime()-new Date(x.date).getTime())
 },[events,googleEvents,people,clients,orders])
 const filtered=useMemo(()=>history.filter(e=>{const text=`${e.event} ${e.detail} ${e.client} ${e.os} ${e.person}`.toLocaleLowerCase('pt-BR');const d=new Date(e.date);return(!q.trim()||text.includes(q.trim().toLocaleLowerCase('pt-BR')))&&(month==='0'||d.getMonth()+1===Number(month))}),[history,q,month])
 const pages=Math.max(1,Math.ceil(filtered.length/HISTORY_PAGE));const safePage=Math.min(page,pages);const rows=filtered.slice((safePage-1)*HISTORY_PAGE,safePage*HISTORY_PAGE)
 const cancelled=filtered.filter(e=>['CANCELADO','CANCELADA','CANCELLED'].includes(normalize(e.status))).length
 return <section className="mx-auto mb-8 mt-6 max-w-[1600px] px-4 lg:px-8"><div className="rounded-3xl border bg-white shadow-sm">
  <div className="border-b p-5"><div className="flex items-center gap-2"><CalendarCheck2 className="h-5 w-5 text-teal-700"/><h2 className="font-bold text-slate-900">Histórico de coletas — Google Agenda</h2></div><p className="mt-1 text-sm text-slate-500">Consulta o histórico do Google Agenda e combina com os agendamentos do CRM. Um mesmo ID da Agenda pode conter várias OS.</p></div>
  <div className="flex flex-col gap-3 border-b bg-slate-50/70 p-5 lg:flex-row lg:items-end lg:justify-between"><div className="w-full max-w-xs"><label className="mb-1.5 block text-xs font-bold uppercase tracking-wide text-slate-600">Filtrar por mês</label><select value={month} onChange={e=>setMonth(e.target.value)} className="w-full rounded-xl border bg-white px-3 py-2.5 text-sm font-medium shadow-sm">{months.map((x,i)=><option key={i} value={String(i)}>{x}</option>)}</select></div><div className="flex flex-wrap gap-2"><div className="relative"><Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-slate-400"/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Buscar no histórico..." className="rounded-xl border bg-white py-2.5 pl-9 pr-3 text-sm"/></div><button onClick={()=>void load()} className="rounded-xl border bg-white p-2.5" title="Atualizar Google Agenda"><RefreshCw className={`h-4 w-4 ${loading?'animate-spin':''}`}/></button></div></div>
  <div className="grid gap-3 border-b p-5 sm:grid-cols-3"><div className="rounded-2xl border bg-slate-50 p-4"><div className="text-xs font-semibold uppercase text-slate-500">Registros no filtro</div><div className="mt-1 text-2xl font-bold text-slate-900">{filtered.length}</div></div><div className="rounded-2xl border border-red-100 bg-red-50 p-4"><div className="flex items-center gap-2 text-xs font-semibold uppercase text-red-600"><XCircle className="h-4 w-4"/>Cancelados</div><div className="mt-1 text-2xl font-bold text-red-700">{cancelled}</div></div><div className="rounded-2xl border bg-slate-50 p-4"><div className="text-xs font-semibold uppercase text-slate-500">Páginas</div><div className="mt-1 text-2xl font-bold text-slate-900">{pages}</div></div></div>
  {error&&<div className="m-4 rounded-xl bg-red-50 p-3 text-sm text-red-700">{error}</div>}<div className="overflow-x-auto"><table className="min-w-full text-sm"><thead className="bg-slate-50 text-left text-xs uppercase text-slate-500"><tr><th className="px-5 py-3">Data / hora</th><th className="px-5 py-3">Evento</th><th className="px-5 py-3">Cliente / OS</th><th className="px-5 py-3">Responsável</th><th className="px-5 py-3">Status</th><th className="px-5 py-3">Origem</th></tr></thead><tbody className="divide-y">{loading?<tr><td colSpan={6} className="p-8 text-center text-slate-500">Carregando Google Agenda...</td></tr>:rows.length?rows.map(e=><tr key={e.id}><td className="px-5 py-4 font-semibold">{new Date(e.date).toLocaleString('pt-BR')}</td><td className="px-5 py-4"><div className="font-medium">{e.event}</div><div className="max-w-md truncate text-xs text-slate-500" title={e.detail}>{e.detail}</div></td><td className="px-5 py-4"><div>{e.client}</div><div className="text-xs text-slate-500">{e.os}</div></td><td className="px-5 py-4"><div className="flex items-center gap-2"><UserAvatar name={e.person} avatarUrl={e.avatar} size="sm"/><span>{e.person}</span></div></td><td className="px-5 py-4">{e.status}</td><td className="px-5 py-4"><span className={`rounded-full px-2.5 py-1 text-xs font-bold ${e.origin==='GOOGLE AGENDA'?'bg-blue-50 text-blue-700':'bg-slate-100 text-slate-600'}`}>{e.origin}</span></td></tr>):<tr><td colSpan={6} className="p-8 text-center text-slate-500">Nenhuma coleta passada neste filtro.</td></tr>}</tbody></table></div>
  <div className="flex flex-col gap-3 border-t px-5 py-4 text-sm text-slate-500 sm:flex-row sm:items-center sm:justify-between"><span>Exibindo {filtered.length?((safePage-1)*HISTORY_PAGE)+1:0}–{Math.min(safePage*HISTORY_PAGE,filtered.length)} de {filtered.length} registros.</span><div className="flex items-center gap-2"><button disabled={safePage<=1} onClick={()=>setPage(p=>Math.max(1,p-1))} className="rounded-lg border p-2 disabled:opacity-40"><ChevronLeft className="h-4 w-4"/></button><span className="min-w-24 text-center">Página {safePage} de {pages}</span><button disabled={safePage>=pages} onClick={()=>setPage(p=>Math.min(pages,p+1))} className="rounded-lg border p-2 disabled:opacity-40"><ChevronRight className="h-4 w-4"/></button></div></div>
 </div></section>
}
function parseDescription(value:string|null,label:string){if(!value)return'';const line=value.split(/\r?\n/).find(x=>normalize(x).includes(normalize(label)+':'));return line?line.split(':').slice(1).join(':').trim():''}
function osFromSummary(value:string|null){const m=String(value||'').match(/\(OS:\s*([^\)]+)\)/i);return m?`OS ${m[1].trim()}`:'Sem OS identificada'}
function clientFromSummary(value:string|null){return String(value||'').replace(/^\[[^\]]+\]\s*-\s*/,'').replace(/\s*\(OS:[^\)]+\)\s*$/i,'').trim()||'Cliente não identificado'}
function normalize(v:string){return v.normalize('NFD').replace(/[̀-ͯ]/g,'').trim().toUpperCase()}
