import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import {createClient} from "https://esm.sh/@supabase/supabase-js@2";
import {PDFDocument,StandardFonts,rgb} from "npm:pdf-lib@1.17.1";
import fontkit from "npm:@pdf-lib/fontkit@1.1.1";
import QRCode from "npm:qrcode@1.5.4";
import {XMLParser} from "npm:fast-xml-parser@4.5.0";
const U=Deno.env.get("SUPABASE_URL")!,K=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!,B="ml-arquivos";
const G=String(Deno.env.get("NFSE_GATEWAY_URL")||"").replace(/\/$/,""),TK=String(Deno.env.get("NFSE_GATEWAY_TOKEN")||"");
const C={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization, content-type"};
const S=(v:any)=>String(v??"").trim(), N=(v:any)=>Number(S(v).replace(",","."))||0;
const money=(v:any)=>N(v).toLocaleString("pt-BR",{style:"currency",currency:"BRL"}), pct=(v:any)=>S(v)?N(v).toLocaleString("pt-BR",{minimumFractionDigits:2,maximumFractionDigits:2})+" %":"-";
const date=(v:any)=>{const m=S(v).match(/(\d{4})-(\d\d)-(\d\d)(?:T(\d\d):(\d\d):(\d\d))?/);return m?`${m[3]}/${m[2]}/${m[1]}${m[4]?` ${m[4]}:${m[5]}:${m[6]}`:""}`:"-"};
const doc=(v:any)=>{const d=S(v).replace(/\D/g,"");return d.length===14?`${d.slice(0,2)}.${d.slice(2,5)}.${d.slice(5,8)}/${d.slice(8,12)}-${d.slice(12)}`:d.length===11?`${d.slice(0,3)}.${d.slice(3,6)}.${d.slice(6,9)}-${d.slice(9)}`:S(v)||"-"};
const cep=(v:any)=>{const d=S(v).replace(/\D/g,"");return d.length===8?`${d.slice(0,2)}.${d.slice(2,5)}-${d.slice(5)}`:S(v)||"-"};
const ibge=(v:any)=>{const d=S(v);return d.length===7?`${d.slice(0,2)}.${d.slice(2)}`:d||"-"};
const trib=(v:any)=>{const d=S(v);return d.length===6?`${d.slice(0,2)}.${d.slice(2,4)}.${d.slice(4)} / -`:d||"-"};
const nbs=(v:any)=>{const d=S(v);return d.length===9?`${d[0]}.${d.slice(1,5)}.${d.slice(5,7)}.${d.slice(7)}`:d||"-"};
const phone=(v:any)=>{const d=S(v).replace(/\D/g,"");return d.length===11?`(${d.slice(0,2)}) ${d.slice(2,6)}-${d.slice(6)}`:d.length===10?`(${d.slice(0,2)}) ${d.slice(2,6)}-${d.slice(6)}`:"-"};
const addr=(e:any)=>[e?.xLgr,e?.nro,e?.xCpl,e?.xBairro].filter(Boolean).join(", ")||"-";
const get=(o:any,...p:string[])=>p.reduce((a,k)=>a?.[k],o);
async function logo(sb:any){const {data}=await sb.storage.from(B).download("financeiro/assets/nfse/Logo NFS-e.jpeg");return data?new Uint8Array(await data.arrayBuffer()):null}
async function build(xml:string,n:any,sb:any){
 const X=new XMLParser({ignoreAttributes:false,removeNSPrefix:true,parseTagValue:false,trimValues:true}).parse(xml),nf=X.NFSe||X,inf=nf.infNFSe||{},dps=inf.DPS?.infDPS||{},emit=inf.emit||{},prest=dps.prest||{},toma=dps.toma||{},serv=dps.serv||{},dv=dps.valores||{},ibs=inf.IBSCBS||{},dibs=dps.IBSCBS||{};
 const iv=ibs.valores||{},tot=ibs.totCIBS||{},gibs=tot.gIBS||{},gcbs=tot.gCBS||{},tm=get(dv,"trib","tribMun")||{},tf=get(dv,"trib","tribFed")||{},ch=S(n.chave_acesso)||S(inf['@_Id']).replace(/^NFS/,""),num=S(n.numero_nf)||S(inf.nNFSe),val=get(dv,"vServPrest","vServ")||tot.vTotNF||n.valor_total;
 const pdf=await PDFDocument.create();pdf.registerFontkit(fontkit);const p=pdf.addPage([595,842]),H=842,black=rgb(0,0,0),gray=rgb(.92,.92,.92);
 let f:any,b:any;
 try{
  const {data:fr}=await sb.storage.from(B).download("financeiro/assets/nfse/LiberationSans-Regular.ttf");
  const {data:fb}=await sb.storage.from(B).download("financeiro/assets/nfse/LiberationSans-Bold.ttf");
  if(!fr||!fb)throw new Error("fontes não encontradas");
  f=await pdf.embedFont(new Uint8Array(await fr.arrayBuffer()),{subset:true});b=await pdf.embedFont(new Uint8Array(await fb.arrayBuffer()),{subset:true});
 }catch{f=await pdf.embedFont(StandardFonts.Helvetica);b=await pdf.embedFont(StandardFonts.HelveticaBold);}
 const text=(s:any,x:number,t:number,z=7,bold=false,w=580)=>p.drawText(S(s)||"-",{x,y:H-t-z,size:z,font:bold?b:f,color:black,maxWidth:w});
 const line=(t:number,x1=8,x2=587)=>p.drawLine({start:{x:x1,y:H-t},end:{x:x2,y:H-t},thickness:.45,color:black});
 const field=(l:string,v:any,x:number,t:number,w:number,z=7)=>{text(l,x,t,6,true,w);text(v,x,t+6.8,7,false,w)};
 p.drawRectangle({x:7,y:7,width:581,height:828,borderColor:black,borderWidth:.7});
 const lg=await logo(sb);if(lg)try{p.drawImage(await pdf.embedJpg(lg),{x:12,y:H-35,width:91,height:23})}catch{}
 text("DANFSe v2.0",270,10,7.5,true);text("Documento Auxiliar da NFS-e",235,22,7,true);text(`Município: ${inf.xLocEmi||"Montes Claros"} - MG`,447,9,5.2,false,135);text(`Ambiente Gerador: ${inf.ambGer||"-"}`,447,16,4.8);text(`Tipo de Ambiente: ${dps.tpAmb||"-"}`,447,22,4.8);line(39);
 field("CHAVE DE ACESSO DA NFS-e",ch,12,44,430,5.3);
 try{const q=await QRCode.toBuffer(`https://www.nfse.gov.br/consultapublica?chave=${ch}`,{type:"png",width:500,margin:2,errorCorrectionLevel:"M"});p.drawImage(await pdf.embedPng(q),{x:495,y:H-101,width:41,height:41})}catch{}
 text("A autenticidade desta NFS-e pode ser verificada",447,103,4.15,false,135);text("pela leitura deste código QR ou pela consulta da",447,108,4.15,false,135);text("chave de acesso no portal nacional da NFS-e",447,113,4.15,false,135);
 field("NÚMERO DA NFS-e",num,12,61,130);field("COMPETÊNCIA DA NFS-e",date(dps.dCompet),155,61,130);field("DATA E HORA DA EMISSÃO DA NFS-e",date(inf.dhProc),300,61,140);field("NÚMERO DA DPS",dps.nDPS,12,78,130);field("SÉRIE DA DPS",dps.serie,155,78,130);field("DATA E HORA DA EMISSÃO DA DPS",date(dps.dhEmi),300,78,140);field("EMITENTE DA NFS-e","Prestador",12,95,130);field("SITUAÇÃO DA NFS-e","NFS-e Gerada",155,95,130);field("FINALIDADE","NFS-e regular",300,95,140);line(119);
 text("PRESTADOR / FORNECEDOR",12,123,5.8,true);field("CNPJ / CPF / NIF",doc(emit.CNPJ||prest.CNPJ),150,123,120);field("Indicador Municipal (Inscrição)",emit.IM||prest.IM||"-",292,123,130);field("Telefone","-",447,123,130);field("Nome / Nome Empresarial",emit.xNome||n.nome_emitente,12,139,260);field("Município / Sigla UF",`${inf.xLocEmi||"Montes Claros"} / ${emit.enderNac?.UF||"MG"}`,292,139,130);field("Código IBGE / CEP",`${ibge(emit.enderNac?.cMun)} / ${cep(emit.enderNac?.CEP)}`,447,139,130);field("Endereço",addr(emit.enderNac),12,155,260);field("E-mail","-",292,155,130);field("Simples Nacional na Data de Competência","Optante - Microempresa ou Empresa de ...",12,171,255,5.2);field("Regime de Apuração Tributária pelo SN","Regime de apuração dos tributos federais e municipal pelo Simples Nacional",292,171,285,4.9);line(190);
 text("TOMADOR / ADQUIRENTE",12,194,5.8,true);field("CNPJ / CPF / NIF",doc(toma.CNPJ||toma.CPF),150,194,120);field("Indicador Municipal (Inscrição)",toma.IM||"-",292,194,130);field("Telefone",phone(toma.fone),447,194,130);field("Nome / Nome Empresarial",toma.xNome,12,210,260);field("Município / Sigla UF",`${inf.xLocPrestacao||"Montes Claros"} / MG`,292,210,130);field("Código IBGE / CEP",`${ibge(toma.end?.endNac?.cMun)} / ${cep(toma.end?.endNac?.CEP)}`,447,210,130);field("Endereço",addr({...toma.end,...toma.end?.endNac}),12,226,420,5.2);field("E-mail",toma.email||"-",447,226,130);line(245);
 text("DESTINATÁRIO DA OPERAÇÃO NÃO IDENTIFICADO NA NFS-e",190,248,5.1,true);line(255);text("INTERMEDIÁRIO DA OPERAÇÃO NÃO IDENTIFICADO NA NFS-e",190,257,5.1,true);line(264);
 text("SERVIÇO PRESTADO",12,268,5.8,true);field("Código de Tributação Nacional/Municipal",trib(serv.cServ?.cTribNac),150,268,175);field("Código da NBS",nbs(serv.cServ?.cNBS),340,268,110);field("Local da Prestação / Sigla UF / País",`${inf.xLocPrestacao||"Montes Claros"} / MG / -`,455,268,125,5.1);text(inf.xTribNac||"-",12,285,5.2,false,565);field("Descrição do Serviço",serv.cServ?.xDescServ||"-",12,294,565,5.2);line(311);
 text("TRIBUTAÇÃO MUNICIPAL (ISSQN)",12,315,5.8,true);field("Tipo de Tributação do ISSQN",get(dv,"trib","tribMun","tribISSQN")==="1"?"Operação Tributável":"-",150,315,165);field("Município / Sigla UF / País de Incidência do ISSQN",`${inf.xLocIncid||"Montes Claros"} / MG / -`,325,315,245,5.1);field("BC ISSQN",S(tm.vBC)?money(tm.vBC):"-",12,332,120);field("Alíquota Aplicada",S(tm.pAliq)?pct(tm.pAliq):"-",150,332,120);field("Retenção do ISSQN",tm.tpRetISSQN==="2"?"Retido":"Não Retido",325,332,120);field("ISSQN Apurado",S(tm.vISSQN)?money(tm.vISSQN):"-",455,332,120);line(351);
 text("TRIBUTAÇÃO FEDERAL (EXCETO CBS)",12,355,5.8,true);field("IRRF",S(tf.vIRRF)?money(tf.vIRRF):"-",150,355,110);field("Contribuição Previdenciária - Retida",S(tf.vRetCP)?money(tf.vRetCP):"-",270,355,165);field("Contribuições Sociais - Retidas",S(tf.vRetCSLL)?money(tf.vRetCSLL):"-",455,355,120,5);field("PIS - Débito Apuração Própria","-",12,372,150);field("COFINS - Débito Apuração Própria","-",180,372,150);field("Descrição Contrib. Sociais - Retidas",get(dv,"trib","tribFed","piscofins","tpRetPisCofins")==="0"?"0 - PIS/COFINS/CSLL Não Retidos":"-",350,372,225,5.1);line(392);
 text("TRIBUTAÇÃO IBS/CBS",12,396,5.8,true);field("CST / cClassTrib",`${get(dibs,"valores","trib","gIBSCBS","CST")||"-"} / ${get(dibs,"valores","trib","gIBSCBS","cClassTrib")||"-"}`,150,396,150);field("Indicador de Operação / Código IBGE Incidência / Município Incidência / Sigla UF",`${dibs.cIndOp||"-"} / ${ibs.cLocalidadeIncid||"-"} / ${ibs.xLocalidadeIncid||"-"} / MG`,310,396,270,5);field("Exclusões e Reduções da Base de Cálculo",money(iv.vCalcReeRepRes||0),12,413,165);field("Base de Cálculo Após Exclusões e Reduções",money(iv.vBC||val),185,413,180);field("Red. Alíquota IBS / Red. Alíquota CBS","- / - / -",380,413,195);field("Alíquota - IBS UF / IBS Mun",`${pct(iv.uf?.pIBSUF)} / ${pct(iv.mun?.pIBSMun)}`,12,430,165);field("Alíq. Efetiva Municipal - IBS",pct(iv.mun?.pAliqEfetMun),185,430,180);field("Valor Apurado Municipal - IBS",money(gibs.gIBSMunTot?.vIBSMun||0),380,430,195);field("Alíq. Efetiva Estadual - IBS",pct(iv.uf?.pAliqEfetUF),12,447,165);field("Valor Apurado Estadual - IBS",money(gibs.gIBSUFTot?.vIBSUF||0),185,447,180);field("Valor Total Apurado - IBS",money(gibs.vIBSTot||0),380,447,195);field("Alíquota - CBS",pct(iv.fed?.pCBS),12,464,165);field("Alíquota Efetiva - CBS",pct(iv.fed?.pAliqEfetCBS),185,464,180);field("Valor Total Apurado - CBS",money(gcbs.vCBS||0),380,464,195);line(484);
 text("VALOR TOTAL DA NFS-e",12,488,5.8,true);field("VALOR DA OPERAÇÃO / SERVIÇO",money(val),150,488,130);field("Desconto Incondicionado",S(get(dv,"vDescIncond"))?money(get(dv,"vDescIncond")):"-",292,488,130);field("Desconto Condicionado",S(get(dv,"vDescCond"))?money(get(dv,"vDescCond")):"-",447,488,130);field("Total das Retenções (ISSQN / Federais)",S(inf.valores?.vTotalRet)?money(inf.valores.vTotalRet):"-",12,505,130);field("VALOR LÍQUIDO DA NFS-e",money(inf.valores?.vLiq||val),150,505,130);field("Total do IBS/CBS",money(N(gibs.vIBSTot)+N(gcbs.vCBS)),292,505,130);field("VALOR LÍQUIDO DA NFS-e + IBS/CBS",money(inf.valores?.vLiq||val),447,505,130,5.2);line(525);
 text("INFORMAÇÕES COMPLEMENTARES",12,529,5.8,true);text(`Totais aproximados dos Tributos cfe. Lei n° 12.741/2012: Federais: -; Estaduais: -; Municipais: -;`,12,548,5.2,false,565);
 line(807);p.drawLine({start:{x:145,y:7},end:{x:145,y:35},thickness:.45,color:black});p.drawLine({start:{x:292,y:7},end:{x:292,y:35},thickness:.45,color:black});field("DATA CIENTIFICAÇÃO:","",12,812,125,4.7);field("IDENTIFICAÇÃO E ASSINATURA","",150,812,130,4.7);field("N° NFS-e / CHAVE NFS-e",`${num} / ${ch}`,297,812,285,4.7);
 return new Uint8Array(await pdf.save());}
function b64(s:string){const z=atob(s),a=new Uint8Array(z.length);for(let i=0;i<z.length;i++)a[i]=z.charCodeAt(i);return a}

/* PORTA (auditoria de 28/09/2026). Antes a função atendia qualquer um: bastava um id para
   regenerar e sobrescrever o PDF de qualquer nota. Agora: crachá da direção (a tela, "Gerar PDF")
   vale para qualquer nota autorizada; sem crachá, só o caso exato em que o gatilho do banco chama
   (disparar_danfse_nfse_autorizada: NFS-e Nacional AUTORIZADA, com XML e ainda sem PDF). O
   cabeçalho x-internal-token do gatilho não serve de segredo: o valor está numa migração pública. */
const J=String(Deno.env.get("ML_JWT_SECRET")||""),enc=new TextEncoder(),dec=new TextDecoder();
function b64u(s:string){s=s.replace(/-/g,"+").replace(/_/g,"/");while(s.length%4)s+="=";const b=atob(s),o=new Uint8Array(b.length);for(let i=0;i<b.length;i++)o[i]=b.charCodeAt(i);return o}
async function crachaDirecao(req:Request){const t=String(req.headers.get("authorization")||"").replace(/^Bearer\s+/i,"");if(!t||!J)return false;const p=t.split(".");if(p.length!==3)return false;try{const k=await crypto.subtle.importKey("raw",enc.encode(J),{name:"HMAC",hash:"SHA-256"},false,["verify"]);if(!await crypto.subtle.verify("HMAC",k,b64u(p[2]),enc.encode(`${p[0]}.${p[1]}`)))return false;const x=JSON.parse(dec.decode(b64u(p[1])));return x.sis==="minaslab"&&!(typeof x.exp==="number"&&x.exp<Math.floor(Date.now()/1000))&&String(x.papel||"")==="direcao"}catch{return false}}
Deno.serve(async r=>{if(r.method==="OPTIONS")return new Response("ok",{headers:C});try{const direcao=await crachaDirecao(r);const {id}=await r.json(),sb=createClient(U,K,{auth:{persistSession:false}}),{data:n}=await sb.from("notas_fiscais").select("*").eq("id",id).eq("apagado",false).maybeSingle();const casoDoGatilho=!!n&&n.origem==="NFSE_NACIONAL"&&n.status_fiscal==="AUTORIZADA"&&!!n.xml_url&&!n.pdf_url;if(!direcao&&!casoDoGatilho)return new Response(JSON.stringify({ok:false,erro:"Entre no sistema.",semSessao:true}),{status:401,headers:{...C,"content-type":"application/json"}});if(!n)return new Response(JSON.stringify({ok:false,erro:"Nota não encontrada."}),{status:404,headers:{...C,"content-type":"application/json"}});let bytes:any=null,src="";if(G&&TK&&n.chave_acesso)try{const q=await fetch(`${G}/v1/danfse/${encodeURIComponent(n.chave_acesso)}`,{headers:{Authorization:`Bearer ${TK}`}}),j=await q.json();if(q.ok&&j.pdfBase64){bytes=b64(j.pdfBase64);src="oficial"}}catch{}if(!bytes){const {data:x}=await sb.storage.from(B).download(n.xml_url);bytes=await build(await x!.text(),n,sb);src="xml_template_oficial"}const path=`financeiro/${n.empresa_id}/nfse/${String(n.data_emissao).slice(0,4)}/${n.chave_acesso}.pdf`;const {error}=await sb.storage.from(B).upload(path,bytes,{contentType:"application/pdf",cacheControl:"0",upsert:true});if(error)throw error;await sb.from("notas_fiscais").update({pdf_url:path,updated_at:new Date().toISOString()}).eq("id",id);return new Response(JSON.stringify({ok:true,pdfPath:path,origemPdf:src,bytes:bytes.length}),{headers:{...C,"content-type":"application/json","cache-control":"no-store"}})}catch(e){return new Response(JSON.stringify({ok:false,erro:String(e)}),{status:500,headers:{...C,"content-type":"application/json"}})}});