import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2";
import { PDFDocument, StandardFonts, rgb } from "npm:pdf-lib@1.17.1";

const U=Deno.env.get("SUPABASE_URL")!;
const K=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;
const BUCKET="ml-arquivos";
const LOGO_NFSE_PATH=Deno.env.get("DANFSE_LOGO_NFSE_PATH")||"financeiro/assets/nfse/Logo NFS-e.jpeg";
const LOGO_PREFEITURA_PATH=Deno.env.get("DANFSE_LOGO_PREFEITURA_PATH")||"financeiro/assets/nfse/Logo prefeitura.jpeg";
const cors={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization, content-type","Access-Control-Allow-Methods":"POST, OPTIONS"};
const json=(b:any,s=200)=>new Response(JSON.stringify(b),{status:s,headers:{...cors,"Content-Type":"application/json","Cache-Control":"no-store"}});
const strip=(s:string)=>String(s||"").replace(/<[^>]+>/g,"").trim();
const tag=(x:string,n:string)=>{const m=x.match(new RegExp(`<(?:\\w+:)?${n}[^>]*>([\\s\\S]*?)<\\/(?:\\w+:)?${n}>`,`i`));return m?strip(m[1]):""};
const sec=(x:string,n:string)=>{const m=x.match(new RegExp(`<(?:\\w+:)?${n}[^>]*>([\\s\\S]*?)<\\/(?:\\w+:)?${n}>`,`i`));return m?m[1]:""};
const br=(v:string)=>{const p=String(v||"").slice(0,10).split("-");return p.length===3?`${p[2]}/${p[1]}/${p[0]}`:"-"};
const money=(v:any)=>Number(String(v||0).replace(",",".")).toLocaleString("pt-BR",{style:"currency",currency:"BRL"});
const doc=(v:string)=>{const d=String(v||"").replace(/\D/g,"");return d.length===14?`${d.slice(0,2)}.${d.slice(2,5)}.${d.slice(5,8)}/${d.slice(8,12)}-${d.slice(12)}`:v||"-"};
async function asset(sb:any,path:string){const {data,error}=await sb.storage.from(BUCKET).download(path);if(error||!data)return null;return new Uint8Array(await data.arrayBuffer())}

async function gerarPdfLocal(xml:string,n:any,sb:any){
 const pdf=await PDFDocument.create(),p=pdf.addPage([595.28,841.89]),font=await pdf.embedFont(StandardFonts.Helvetica),bold=await pdf.embedFont(StandardFonts.HelveticaBold),H=p.getHeight(),ink=rgb(.04,.04,.04),line=rgb(.18,.18,.18);
 const tx=(s:any,x:number,t:number,z=4.5,b=false,w=570)=>p.drawText(String(s??"-"),{x,y:H-t-z,size:z,font:b?bold:font,color:ink,maxWidth:w});
 const hl=(t:number)=>p.drawLine({start:{x:8,y:H-t},end:{x:587,y:H-t},thickness:.55,color:line});
 const fld=(l:string,v:any,x:number,t:number,w:number,z=4.55)=>{tx(l.toUpperCase(),x,t,4.05,true,w);tx(v||"-",x,t+6,z,false,w)};
 p.drawRectangle({x:7,y:8,width:581,height:827,borderColor:line,borderWidth:.7});
 const inf=sec(xml,"infNFSe")||xml,dps=sec(xml,"infDPS")||xml,e=sec(xml,"emit")||sec(xml,"prest"),to=sec(xml,"toma"),sv=sec(dps,"serv")||dps,ib=sec(dps,"IBSCBS")||dps;
 const ch=String(n.chave_acesso||tag(inf,"chNFSe")),num=String(n.numero_nf||tag(inf,"nNFSe")||"-"),dh=tag(inf,"dhProc")||tag(dps,"dhEmi")||n.data_emissao||"",dt=(v:string)=>br(v)+(v.includes("T")?" "+v.slice(11,19):"");
 const [logoNfse,logoPref]=await Promise.all([asset(sb,LOGO_NFSE_PATH),asset(sb,LOGO_PREFEITURA_PATH)]);
 if(logoNfse)try{p.drawImage(await pdf.embedJpg(logoNfse),{x:13,y:H-39,width:105,height:25})}catch{}
 if(logoPref)try{p.drawImage(await pdf.embedJpg(logoPref),{x:495,y:H-40,width:28,height:28})}catch{}
 tx("DANFSe v2.0",271,12,7,true);tx("Documento Auxiliar da NFS-e",229,25,7,true);tx("Município: Montes Claros - MG",430,10,4.3,false,145);tx("Ambiente Gerador: 2",430,17,4);tx("Tipo de Ambiente: 1",430,24,4);hl(45);
 fld("Chave de Acesso da NFS-e",ch,13,50,385,5);fld("Número da NFS-e",num,13,72,120);fld("Competência da NFS-e",br(tag(dps,"dCompet")||n.data_emissao),150,72,120);fld("Data e Hora da Emissão da NFS-e",dt(dh),292,72,185);fld("Número da DPS",tag(dps,"nDPS")||num,13,94,120);fld("Série da DPS",tag(dps,"serie")||"70000",150,94,120);fld("Data e Hora da Emissão da DPS",dt(tag(dps,"dhEmi")||dh),292,94,185);
 try{const q=(await import("npm:qrcode-generator@1.4.4")).default(0,"M");q.addData("https://www.nfse.gov.br/consultapublica?chave="+ch);q.make();const m=q.getModuleCount(),s=47/m;for(let r=0;r<m;r++)for(let c=0;c<m;c++)if(q.isDark(r,c))p.drawRectangle({x:532+c*s,y:H-50-(r+1)*s,width:s+.04,height:s+.04,color:ink})}catch{}
 tx("A autenticidade desta NFS-e pode ser verificada",447,103,3.7,false,132);tx("pela leitura deste código QR ou pela consulta da",447,108,3.7,false,132);tx("chave de acesso no portal nacional da NFS-e",447,113,3.7,false,132);hl(132);
 fld("Emitente da NFS-e","Prestador",13,136,125);fld("Situação da NFS-e",String(n.status_fiscal).toUpperCase()==="CANCELADA"?"NFS-e Cancelada":"NFS-e Gerada",150,136,125);fld("Finalidade","NFS-e regular",292,136,125);hl(158);
 tx("PRESTADOR / FORNECEDOR",13,162,5,true);fld("CNPJ / CPF / NIF",doc(tag(e,"CNPJ")||n.cnpj_emitente),150,162,125);fld("Indicador Municipal (Inscrição)",tag(e,"IM")||"130602",292,162,145);fld("Telefone",tag(e,"fone")||"(38) 9812-9311",444,162,135);fld("Nome / Nome Empresarial",tag(e,"xNome")||n.nome_emitente||"M LAB SERVICOS LTDA",13,184,260);fld("Município / Sigla UF",`${tag(e,"xMun")||"Montes Claros"} / ${tag(e,"UF")||"MG"}`,292,184,145);fld("Código IBGE / CEP",`${tag(e,"cMun")||"31.43302"} / ${tag(e,"CEP")||"39.400-241"}`,444,184,135);fld("Endereço",[tag(e,"xLgr"),tag(e,"nro"),tag(e,"xBairro")].filter(Boolean).join(", ")||"R RAIMUNDO FERNANDES DIAS, 96, RENASCENCA",13,206,260);fld("E-mail",tag(e,"email")||"financeiro@minaslab.net",292,206,287);fld("Simples Nacional na Data de Competência","Optante - Microempresa ou Empresa de Pequeno Porte",13,228,260,4.25);fld("Regime de Apuração Tributária pelo SN","Regime de apuração dos tributos federais e municipal pelo Simples Nacional",292,228,287,4.1);hl(252);
 tx("TOMADOR / ADQUIRENTE",13,256,5,true);fld("CNPJ / CPF / NIF",doc(tag(to,"CNPJ")||n.cnpj_destinatario),150,256,125);fld("Indicador Municipal (Inscrição)",tag(to,"IM")||"-",292,256,145);fld("Telefone",tag(to,"fone")||"-",444,256,135);fld("Nome / Nome Empresarial",tag(to,"xNome")||n.nome_destinatario||"-",13,278,260);fld("Município / Sigla UF",`${tag(to,"xMun")||"-"} / ${tag(to,"UF")||"-"}`,292,278,145);fld("Código IBGE / CEP",`${tag(to,"cMun")||"-"} / ${tag(to,"CEP")||"-"}`,444,278,135);fld("Endereço",[tag(to,"xLgr"),tag(to,"nro"),tag(to,"xBairro")].filter(Boolean).join(", ")||"-",13,300,260);fld("E-mail",tag(to,"email")||"-",292,300,287);hl(324);
 tx("DESTINATÁRIO DA OPERAÇÃO NÃO IDENTIFICADO NA NFS-e",185,327,4.6,true);hl(337);tx("INTERMEDIÁRIO DA OPERAÇÃO NÃO IDENTIFICADO NA NFS-e",178,340,4.6,true);hl(350);
 tx("SERVIÇO PRESTADO",13,354,5,true);fld("Código de Tributação Nacional/Municipal",`${tag(sv,"cTribNac")||tag(dps,"cTribNac")||"-"} / ${tag(sv,"cTribMun")||"-"}`,150,354,180);fld("Código da NBS",tag(sv,"cNBS")||tag(dps,"cNBS")||"-",340,354,110);fld("Local da Prestação / Sigla UF / País",`${tag(sv,"xMun")||"Montes Claros"} / ${tag(sv,"UF")||"MG"} / -`,456,354,123,4.15);tx(tag(sv,"xTribNac")||"Expediente, secretaria em geral, apoio e infra-estrutura administrativa e congêneres.",13,377,4.35,false,565);fld("Descrição do Serviço",tag(sv,"xDescServ")||tag(dps,"xDescServ")||"Serviço conforme NFS-e autorizada.",13,391,565,4.35);hl(416);
 tx("TRIBUTAÇÃO MUNICIPAL (ISSQN)",13,420,5,true);fld("Tipo de Tributação do ISSQN","Operação Tributável",150,420,130);fld("Município / Sigla UF / País de Incidência do ISSQN",`${tag(sv,"xMun")||"Montes Claros"} / MG / -`,292,420,287,4.1);fld("BC ISSQN",tag(dps,"vBC")?money(tag(dps,"vBC")):"-",13,442,120);fld("Alíquota Aplicada",tag(dps,"pAliq")?tag(dps,"pAliq").replace(".",",")+" %":"-",150,442,120);fld("Retenção do ISSQN",tag(dps,"tpRetISSQN")==="2"?"Retido":"Não Retido",292,442,130);fld("ISSQN Apurado",tag(dps,"vISSQN")?money(tag(dps,"vISSQN")):"-",444,442,135);hl(466);
 tx("TRIBUTAÇÃO FEDERAL (EXCETO CBS)",13,470,5,true);fld("IRRF",tag(dps,"vIR")?money(tag(dps,"vIR")):"-",150,470,100);fld("Contribuição Previdenciária - Retida",tag(dps,"vINSS")?money(tag(dps,"vINSS")):"-",260,470,160);fld("Contribuições Sociais - Retidas",tag(dps,"vCSLL")?money(tag(dps,"vCSLL")):"-",430,470,149);fld("PIS - Débito Apuração Própria",tag(dps,"vPIS")?money(tag(dps,"vPIS")):"-",13,492,150);fld("COFINS - Débito Apuração Própria",tag(dps,"vCOFINS")?money(tag(dps,"vCOFINS")):"-",180,492,165);fld("Descrição Contrib. Sociais - Retidas",tag(dps,"xDescRet")||"-",360,492,219,4.1);hl(516);
 tx("TRIBUTAÇÃO IBS/CBS",13,520,5,true);fld("CST / cClassTrib",`${tag(ib,"CST")||"-"} / ${tag(ib,"cClassTrib")||"-"}`,150,520,130);fld("Indicador de Operação / Código IBGE Incidência / Município Incidência / Sigla UF",`${tag(ib,"cIndOp")||"-"} / ${tag(ib,"cMunIncid")||"-"} / Montes Claros / MG`,292,520,287,3.95);fld("Exclusões e Reduções da Base de Cálculo",money(tag(ib,"vExcRed")||0),13,544,170,4.1);fld("Base de Cálculo Após Exclusões e Reduções",money(tag(ib,"vBC")||tag(inf,"vTotNF")||n.valor_total),196,544,180,4.1);fld("Red. Alíquota IBS / Red. Alíquota CBS","- / - / -",388,544,191,4.1);fld("Alíquota - IBS UF / IBS Mun",`${tag(ib,"pIBSUF")||"-"} % / ${tag(ib,"pIBSMun")||"-"} %`,13,568,150,4.1);fld("Alíq. Efetiva Municipal - IBS",`${tag(ib,"pAliqEfetIBSMun")||"-"} %`,180,568,150,4.1);fld("Valor Apurado Municipal - IBS",tag(ib,"vIBSMun")?money(tag(ib,"vIBSMun")):"-",346,568,150,4.1);fld("Alíq. Efetiva Estadual - IBS",`${tag(ib,"pAliqEfetIBSUF")||"-"} %`,13,592,150,4.1);fld("Valor Apurado Estadual - IBS",tag(ib,"vIBSUF")?money(tag(ib,"vIBSUF")):"-",180,592,150,4.1);fld("Valor Total Apurado - IBS",tag(ib,"vIBS")?money(tag(ib,"vIBS")):"-",346,592,150,4.1);fld("Alíquota - CBS",`${tag(ib,"pCBS")||"-"} %`,13,616,150);fld("Alíquota Efetiva - CBS",`${tag(ib,"pAliqEfetCBS")||"-"} %`,180,616,150);fld("Valor Total Apurado - CBS",tag(ib,"vCBS")?money(tag(ib,"vCBS")):"-",346,616,150);hl(640);
 tx("VALOR TOTAL DA NFS-e",13,644,5,true);const v=tag(inf,"vTotNF")||tag(inf,"vLiq")||n.valor_total;fld("Valor da Operação / Serviço",money(v),150,644,130);fld("Desconto Incondicionado","-",292,644,130);fld("Desconto Condicionado","-",444,644,135);fld("Total das Retenções (ISSQN / Federais)","-",13,668,150,4.1);fld("Valor Líquido da NFS-e",money(tag(inf,"vLiq")||v),180,668,150);fld("Total do IBS/CBS",tag(ib,"vTotIBSCBS")?money(tag(ib,"vTotIBSCBS")):"-",346,668,110);fld("Valor Líquido da NFS-e + IBS/CBS",money(tag(inf,"vLiq")||v),468,668,111,4.1);hl(694);
 tx("INFORMAÇÕES COMPLEMENTARES",13,698,5,true);tx("Totais aproximados dos Tributos cfe. Lei n° 12.741/2012: Federais: -; Estaduais: -; Municipais: -;",13,718,4.2,false,560);hl(760);fld("Data Cientificação","",13,764,135,4);fld("Identificação e Assinatura","",155,764,145,4);fld("N° NFS-e / Chave NFS-e",`${num} / ${ch}`,306,764,273,3.95);
 return new Uint8Array(await pdf.save());
}

Deno.serve(async req=>{if(req.method==="OPTIONS")return new Response("ok",{headers:cors});if(req.method!=="POST")return json({erro:"Método não permitido"},405);try{const {id,regenerarPadrao=false,forcarOficial=false}=await req.json();if(!id)return json({erro:"Nota não informada"},400);const sb=createClient(U,K,{auth:{persistSession:false}}),{data:n,error}=await sb.from("notas_fiscais").select("*").eq("id",id).maybeSingle();if(error||!n)throw error||new Error("Nota não encontrada");let path=n.pdf_url,origemPdf="existente";if(regenerarPadrao||forcarOficial||!path){if(!n.xml_url)throw new Error("XML fiscal não encontrado");const {data:x,error:xe}=await sb.storage.from(BUCKET).download(n.xml_url);if(xe)throw xe;const bytes=await gerarPdfLocal(await x.text(),n,sb),ano=String(n.data_emissao||new Date().toISOString()).slice(0,4);path=`financeiro/${n.empresa_id}/nfse/${ano}/${n.chave_acesso}.pdf`;const {error:ue}=await sb.storage.from(BUCKET).upload(path,bytes,{contentType:"application/pdf",upsert:true});if(ue)throw ue;await sb.from("notas_fiscais").update({pdf_url:path,updated_at:new Date().toISOString()}).eq("id",n.id);origemPdf="padrao_danfse_v2_nf106_logos"}return json({ok:true,pdfPath:path,origemPdf,numeroNf:n.numero_nf,layout:"DANFSe v2.0 - NF 106"})}catch(e){return json({ok:false,erro:e instanceof Error?e.message:String(e)},500)}});