import { useEffect, useMemo, useState } from 'react'
import { CheckCircle2, CircleDollarSign, Clock3, Edit3, Eye, FileCheck2, FileText, Download, LayoutGrid, List, Plus, RefreshCw, Search, TrendingUp } from 'lucide-react'
import { Link } from 'react-router-dom'
import { PageShell } from '../../components/ui/PageShell'
import { Modal } from '../../components/ui/Modal'
import { UserAvatar } from '../../components/users/UserAvatar'
import { supabase } from '../../services/supabase'
import { useAuth } from '../../hooks/useAuth'
import { formatValue, relationLabel } from '../../lib/format'

type Row={id:string;cliente_id:string|null;numero_proposta:string|null;solicitante_snapshot_nome:string|null;responsavel_comercial_id:string|null;valor:number|null;logistica_coleta:string|null;status:string|null;validade:string|null;data_aceite:string|null;data_recusa?:string|null;ativo:boolean|null;created_at:string;updated_at:string|null;client_name?:string|null;responsible_name?:string|null;responsible_active?:boolean|null;responsible_avatar_url?:string|null}
type PendingDecision={id:string;cliente_id:string|null;numero_proposta:string|null;status:string|null;created_at:string;updated_at:string|null}
type ScopeLink={proposta_id:string;grupo_id:string}
type ViewMode='table'|'cards'
type Opt={value:string;label:string;clientId?:string}
type ProfileOpt={value:string;label:string;active:boolean;avatarUrl:string|null}
type Lab={id:string;nome:string}
type Group={id:string;nome:string}
type ProposalStats={totalProposals:number;totalValue:number;negotiationCount:number;negotiationValue:number;awaiting:number;approvedCount:number;approvedValue:number;finalizedCount:number;approvalRate:number;approvedMonth:number;approvedWithoutDate:number}
type RpcResult={rows:Row[];total:number;stats:ProposalStats}
type QueryResult<T>={data:T[]|null;error:{message:string}|null}
const statuses=['RASCUNHO','ENVIADA','EM NEGOCIAÇÃO','APROVADA','RECUSADA','CANCELADA']
const logistics=['COLETA MINASLAB','ENTREGA/ENVIO PELO CLIENTE','TRANSPORTADORA/TERCEIRO','A DEFINIR']
const PAGE_SIZE=10
const FETCH_PAGE_SIZE=1000
const emptyStats:ProposalStats={totalProposals:0,totalValue:0,negotiationCount:0,negotiationValue:0,awaiting:0,approvedCount:0,approvedValue:0,finalizedCount:0,approvalRate:0,approvedMonth:0,approvedWithoutDate:0}
const empty={oportunidade_id:'',oportunidade_referencia:'',cliente_id:'',solicitante_contato_id:'',numero_proposta:'',responsavel_comercial_id:'',valor:'',logistica_coleta:'',status:'RASCUNHO',validade:'',data_envio:'',data_aceite:'',data_recusa:'',periodicidade_proposta:'',observacoes:'',ativo:true,laboratorios:[] as string[],escopos:[] as string[]}
async function fetchAll<T>(makeQuery:(from:number,to:number)=>PromiseLike<QueryResult<T>>){const rows:T[]=[];for(let from=0;;from+=FETCH_PAGE_SIZE){const r=await makeQuery(from,from+FETCH_PAGE_SIZE-1);if(r.error)return{data:rows,error:r.error};const batch=(r.data??[]) as T[];rows.push(...batch);if(batch.length<FETCH_PAGE_SIZE)return{data:rows,error:null}}}

export function Propostas(){
  const {profile,hasPermission}=useAuth();const canWrite=hasPermission('crm.write')
  const[rows,setRows]=useState<Row[]>([]);const[scopeLinks,setScopeLinks]=useState<ScopeLink[]>([]);const[total,setTotal]=useState(0);const[stats,setStats]=useState<ProposalStats>(emptyStats)
  const[loading,setLoading]=useState(true);const[error,setError]=useState('');const[reportOpen,setReportOpen]=useState(false);const[reportLoading,setReportLoading]=useState(false);const[pendingDecisions,setPendingDecisions]=useState<PendingDecision[]>([]);const[query,setQuery]=useState('');const[statusFilter,setStatusFilter]=useState('TODOS');const[responsibleFilter,setResponsibleFilter]=useState('TODOS');const[periodFilter,setPeriodFilter]=useState('TODOS');const[validityFilter,setValidityFilter]=useState('TODAS');const[view,setView]=useState<ViewMode>('table');const[page,setPage]=useState(1);const[open,setOpen]=useState(false);const[editingId,setEditingId]=useState<string|null>(null);const[saving,setSaving]=useState(false);const[rejectedWithoutDate,setRejectedWithoutDate]=useState(0)
  const[opps,setOpps]=useState<Opt[]>([]);const[clients,setClients]=useState<Opt[]>([]);const[contacts,setContacts]=useState<Opt[]>([]);const[profiles,setProfiles]=useState<ProfileOpt[]>([]);const[usedResponsibleIds,setUsedResponsibleIds]=useState<string[]>([]);const[labs,setLabs]=useState<Lab[]>([]);const[groups,setGroups]=useState<Group[]>([]);const[form,setForm]=useState({...empty})

  async function loadMeta(){const[o,c,ct,pr,l,g,used]=await Promise.all([
    fetchAll<any>((from,to)=>supabase.from('oportunidades').select('id,titulo').is('deleted_at',null).order('titulo').range(from,to)),
    fetchAll<any>((from,to)=>supabase.from('clientes').select('id,nome_fantasia,razao_social,cpf_cnpj_original').is('deleted_at',null).order('razao_social').range(from,to)),
    fetchAll<any>((from,to)=>supabase.from('contatos').select('id,cliente_id,nome,email,telefone').is('deleted_at',null).eq('ativo',true).order('nome').range(from,to)),
    fetchAll<any>((from,to)=>supabase.from('profiles').select('id,nome,ativo,avatar_url').order('nome').range(from,to)),
    supabase.from('laboratorios_parceiros').select('id,nome').eq('ativo',true).is('deleted_at',null).order('nome'),
    supabase.from('grupos').select('id,nome').eq('ativo',true).is('deleted_at',null).order('nome'),
    fetchAll<{responsavel_comercial_id:string|null}>((from,to)=>supabase.from('propostas').select('responsavel_comercial_id').is('deleted_at',null).not('responsavel_comercial_id','is',null).order('id').range(from,to)),
  ]);const err=o.error||c.error||ct.error||pr.error||l.error||g.error||used.error;if(err){setError(err.message);return}setOpps(o.data.map((x:any)=>({value:String(x.id),label:String(x.titulo||'Oportunidade')})));setClients(c.data.map((x:any)=>({value:String(x.id),label:relationLabel(x,['nome_fantasia','razao_social','cpf_cnpj_original'])})));setContacts(ct.data.map((x:any)=>({value:String(x.id),label:relationLabel(x,['nome','email','telefone']),clientId:String(x.cliente_id)})));setProfiles(pr.data.map((x:any)=>({value:String(x.id),label:String(x.nome||'Usuário'),active:Boolean(x.ativo),avatarUrl:x.avatar_url?String(x.avatar_url):null})));setLabs((l.data??[]) as Lab[]);setGroups((g.data??[]) as Group[]);setUsedResponsibleIds(Array.from(new Set(used.data.map(x=>x.responsavel_comercial_id).filter((id):id is string=>Boolean(id)))))}

  async function loadRows(){setLoading(true);const[{data,error:rpcError},{count:rejectedCount,error:rejectedError}]=await Promise.all([supabase.rpc('crm_propostas_list',{p_query:query,p_status:statusFilter,p_responsible:responsibleFilter,p_period:periodFilter,p_validity:validityFilter,p_page:page,p_page_size:PAGE_SIZE}),supabase.from('propostas').select('id',{count:'exact',head:true}).is('deleted_at',null).eq('status','RECUSADA').is('data_recusa',null)]);if(rpcError||rejectedError){setLoading(false);setError(rpcError?.message||rejectedError?.message||'Erro ao verificar datas das propostas.');return}setRejectedWithoutDate(rejectedCount??0);const result=(data??{}) as unknown as Partial<RpcResult>;const nextRows=Array.isArray(result.rows)?result.rows:[];let nextScopes:ScopeLink[]=[];if(nextRows.length){const pg=await supabase.from('proposta_grupos').select('proposta_id,grupo_id').in('proposta_id',nextRows.map(row=>row.id));if(pg.error){setLoading(false);setError(pg.error.message);return}nextScopes=(pg.data??[]) as ScopeLink[]}setRows(nextRows);setScopeLinks(nextScopes);setTotal(Number(result.total??0));setStats({...emptyStats,...(result.stats??{})});setError('');setLoading(false)}

  useEffect(()=>{void loadMeta()},[])
  useEffect(()=>{const timer=window.setTimeout(()=>{void loadRows()},query?250:0);return()=>window.clearTimeout(timer)},[query,statusFilter,responsibleFilter,periodFilter,validityFilter,page])
  useEffect(()=>setPage(1),[query,statusFilter,responsibleFilter,periodFilter,validityFilter,view])

  const pages=Math.max(1,Math.ceil(total/PAGE_SIZE));const paged=rows
  const clientName=(id:string|null)=>clients.find(item=>item.value===id)?.label||rows.find(row=>row.cliente_id===id)?.client_name||'Cliente não identificado'
  const responsible=(id:string|null)=>profiles.find(item=>item.value===id)||{value:id||'',label:rows.find(row=>row.responsavel_comercial_id===id)?.responsible_name||'Sem responsável',active:Boolean(rows.find(row=>row.responsavel_comercial_id===id)?.responsible_active),avatarUrl:rows.find(row=>row.responsavel_comercial_id===id)?.responsible_avatar_url||null}
  const scopeName=(id:string)=>groups.find(item=>item.id===id)?.nome||''
  const proposalScopes=(id:string)=>scopeLinks.filter(item=>item.proposta_id===id).map(item=>scopeName(item.grupo_id)).filter(Boolean)
  const availableContacts=useMemo(()=>form.cliente_id?contacts.filter(c=>c.clientId===form.cliente_id):contacts,[contacts,form.cliente_id])
  const assignmentProfiles=useMemo(()=>profiles.filter(p=>p.active||p.value===form.responsavel_comercial_id),[profiles,form.responsavel_comercial_id])
  const usedResponsibleSet=useMemo(()=>new Set(usedResponsibleIds),[usedResponsibleIds])
  const filterProfiles=useMemo(()=>profiles.filter(p=>p.active||usedResponsibleSet.has(p.value)),[profiles,usedResponsibleSet])

  function newProposal(){setEditingId(null);setForm({...empty,laboratorios:[],escopos:[]});setOpen(true)}
  async function editProposal(row:Row){setError('');const [p,labLinks,scopeLinks]=await Promise.all([supabase.from('propostas').select('*').eq('id',row.id).single(),supabase.from('proposta_laboratorios').select('laboratorio_id').eq('proposta_id',row.id),supabase.from('proposta_grupos').select('grupo_id').eq('proposta_id',row.id)]);if(p.error||labLinks.error||scopeLinks.error){setError(p.error?.message||labLinks.error?.message||scopeLinks.error?.message||'Erro ao carregar proposta.');return}const x=p.data;setEditingId(row.id);setForm({oportunidade_id:String(x.oportunidade_id??''),oportunidade_referencia:String(x.oportunidade_referencia??opps.find(o=>o.value===String(x.oportunidade_id??''))?.label??''),cliente_id:String(x.cliente_id??''),solicitante_contato_id:String(x.solicitante_contato_id??''),numero_proposta:String(x.numero_proposta??''),responsavel_comercial_id:String(x.responsavel_comercial_id??''),valor:x.valor==null?'':String(x.valor),logistica_coleta:String(x.logistica_coleta??''),status:String(x.status??'RASCUNHO'),validade:String(x.validade??''),data_envio:toLocal(x.data_envio),data_aceite:toLocal(x.data_aceite),data_recusa:toLocal(x.data_recusa),periodicidade_proposta:String(x.periodicidade_proposta??''),observacoes:String(x.observacoes??''),ativo:Boolean(x.ativo),laboratorios:(labLinks.data??[]).map(z=>String(z.laboratorio_id)),escopos:(scopeLinks.data??[]).map(z=>String(z.grupo_id))});setOpen(true)}
  function changeOpportunityReference(value:string){const normalized=value.trim().toLocaleLowerCase('pt-BR');const opportunity=opps.find(o=>o.label.trim().toLocaleLowerCase('pt-BR')===normalized);setForm(f=>({...f,oportunidade_id:opportunity?.value||'',oportunidade_referencia:value}))}
  function toggleLab(id:string){setForm(f=>({...f,laboratorios:f.laboratorios.includes(id)?f.laboratorios.filter(x=>x!==id):[...f.laboratorios,id]}))}
  function toggleScope(id:string){setForm(f=>({...f,escopos:f.escopos.includes(id)?f.escopos.filter(x=>x!==id):[...f.escopos,id]}))}
  async function save(e:React.FormEvent){e.preventDefault();if(!canWrite)return;if(form.status==='APROVADA'&&!form.data_aceite){setError('Informe a data de aceite para uma proposta aprovada.');return}if(form.status==='RECUSADA'&&!form.data_recusa){setError('Informe a data de recusa para uma proposta recusada.');return}if(form.laboratorios.length===0){setError('Assinale ao menos um laboratório da Rede de Laboratórios Parceiros.');return}if(form.escopos.length===0){setError('Assinale ao menos um item do Escopo Analítico.');return}setSaving(true);setError('');const selectedContact=contacts.find(c=>c.value===form.solicitante_contato_id);const payload={oportunidade_id:form.oportunidade_id||null,oportunidade_referencia:form.oportunidade_referencia.trim()||null,cliente_id:form.cliente_id||null,solicitante_contato_id:form.solicitante_contato_id||null,solicitante_snapshot_nome:selectedContact?.label||null,numero_proposta:form.numero_proposta||null,responsavel_comercial_id:form.responsavel_comercial_id||null,valor:form.valor===''?null:Number(form.valor),logistica_coleta:form.logistica_coleta||null,status:form.status||null,validade:form.validade||null,data_envio:form.data_envio?new Date(form.data_envio).toISOString():null,data_aceite:form.status==='APROVADA'&&form.data_aceite?new Date(form.data_aceite).toISOString():null,data_recusa:form.status==='RECUSADA'&&form.data_recusa?new Date(form.data_recusa).toISOString():null,periodicidade_proposta:form.periodicidade_proposta||null,observacoes:form.observacoes||null,ativo:form.ativo}
    let proposalId=editingId
    let createdNow=false
    let previousProposal:any=null
    let previousLabs:string[]=[]
    let previousScopes:string[]=[]
    if(editingId){
      const [before,labBefore,scopeBefore]=await Promise.all([
        supabase.from('propostas').select('oportunidade_id,oportunidade_referencia,cliente_id,solicitante_contato_id,solicitante_snapshot_nome,numero_proposta,responsavel_comercial_id,valor,logistica_coleta,status,validade,data_envio,data_aceite,data_recusa,periodicidade_proposta,observacoes,ativo').eq('id',editingId).single(),
        supabase.from('proposta_laboratorios').select('laboratorio_id').eq('proposta_id',editingId),
        supabase.from('proposta_grupos').select('grupo_id').eq('proposta_id',editingId),
      ])
      if(before.error||labBefore.error||scopeBefore.error){setError(before.error?.message||labBefore.error?.message||scopeBefore.error?.message||'Não foi possível preparar a edição segura da proposta.');setSaving(false);return}
      previousProposal=before.data;previousLabs=(labBefore.data??[]).map(x=>String(x.laboratorio_id));previousScopes=(scopeBefore.data??[]).map(x=>String(x.grupo_id))
      const r=await supabase.from('propostas').update({...payload,updated_by:profile?.id??null}).eq('id',editingId);if(r.error){setError(r.error.message);setSaving(false);return}
    }else{
      const r=await supabase.from('propostas').insert({...payload,created_by:profile?.id??null}).select('id').single();if(r.error){setError(r.error.message);setSaving(false);return}proposalId=String(r.data.id);createdNow=true
    }
    if(proposalId){
      const rollback=async(reason:string)=>{
        const rollbackErrors:string[]=[]
        await supabase.from('proposta_laboratorios').delete().eq('proposta_id',proposalId)
        await supabase.from('proposta_grupos').delete().eq('proposta_id',proposalId)
        if(createdNow){const rr=await supabase.from('propostas').delete().eq('id',proposalId);if(rr.error)rollbackErrors.push(rr.error.message)}
        else{
          if(previousLabs.length){const rr=await supabase.from('proposta_laboratorios').insert(previousLabs.map(laboratorio_id=>({proposta_id:proposalId,laboratorio_id})));if(rr.error)rollbackErrors.push(rr.error.message)}
          if(previousScopes.length){const rr=await supabase.from('proposta_grupos').insert(previousScopes.map(grupo_id=>({proposta_id:proposalId,grupo_id})));if(rr.error)rollbackErrors.push(rr.error.message)}
          const rr=await supabase.from('propostas').update({...previousProposal,updated_by:profile?.id??null}).eq('id',proposalId);if(rr.error)rollbackErrors.push(rr.error.message)
        }
        setError(rollbackErrors.length?`A proposta ficou em estado inconsistente após uma falha e a reversão automática também encontrou erro. ${reason} · Rollback: ${rollbackErrors.join(' · ')}`:`A proposta não foi salva parcialmente: a operação foi revertida com segurança. ${reason}`)
      }
      const [dl,dg]=await Promise.all([supabase.from('proposta_laboratorios').delete().eq('proposta_id',proposalId),supabase.from('proposta_grupos').delete().eq('proposta_id',proposalId)])
      if(dl.error||dg.error){await rollback(dl.error?.message||dg.error?.message||'Erro ao atualizar vínculos.');setSaving(false);return}
      const il=await supabase.from('proposta_laboratorios').insert(form.laboratorios.map(laboratorio_id=>({proposta_id:proposalId,laboratorio_id})))
      if(il.error){await rollback(il.error.message);setSaving(false);return}
      const ig=await supabase.from('proposta_grupos').insert(form.escopos.map(grupo_id=>({proposta_id:proposalId,grupo_id})))
      if(ig.error){await rollback(ig.error.message);setSaving(false);return}
    }
    setOpen(false);await Promise.all([loadRows(),loadMeta()]);setSaving(false)
  }

  async function openDecisionReport(){setReportOpen(true);setReportLoading(true);setError('');const result=await fetchAll<PendingDecision>((from,to)=>supabase.from('propostas').select('id,cliente_id,numero_proposta,status,created_at,updated_at').is('deleted_at',null).or('and(status.eq.APROVADA,data_aceite.is.null),and(status.eq.RECUSADA,data_recusa.is.null)').order('status').order('numero_proposta').range(from,to));if(result.error)setError(result.error.message);else setPendingDecisions(result.data);setReportLoading(false)}
  function downloadDecisionReport(){const quote=(value:unknown)=>`"${String(value??'').replaceAll('"','""')}"`;const lines=[['Status','Número da proposta','Cliente','Data de cadastro','Última atualização','Data correta a informar'].map(quote).join(';'),...pendingDecisions.map(item=>[item.status,item.numero_proposta||'',clientName(item.cliente_id),new Date(item.created_at).toLocaleDateString('pt-BR'),item.updated_at?new Date(item.updated_at).toLocaleDateString('pt-BR'):'',''].map(quote).join(';'))];const blob=new Blob(['﻿'+lines.join('\n')],{type:'text/csv;charset=utf-8'});const url=URL.createObjectURL(blob);const anchor=document.createElement('a');anchor.href=url;anchor.download=`propostas-decisoes-sem-data-${new Date().toISOString().slice(0,10)}.csv`;anchor.click();URL.revokeObjectURL(url)}

  return <PageShell title="Propostas" description="Gestão completa das negociações comerciais, valores, validade e aprovações." action={canWrite?<button onClick={newProposal} className="inline-flex items-center gap-2 rounded-xl bg-teal-700 px-4 py-2.5 text-sm font-semibold text-white"><Plus className="h-4 w-4"/>Nova proposta</button>:undefined}>
    <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-5"><Kpi icon={FileText} label="Total de propostas" value={String(stats.totalProposals)} active={statusFilter==='TODOS'&&periodFilter==='TODOS'} onClick={()=>{setStatusFilter('TODOS');setPeriodFilter('TODOS')}}/><Kpi icon={Clock3} label="Em negociação" value={String(stats.negotiationCount)} active={statusFilter==='EM NEGOCIAÇÃO'} onClick={()=>{setStatusFilter(statusFilter==='EM NEGOCIAÇÃO'?'TODOS':'EM NEGOCIAÇÃO');setPeriodFilter('TODOS')}}/><Kpi icon={TrendingUp} label="Aguardando retorno" value={String(stats.awaiting)} active={statusFilter==='ENVIADA'} onClick={()=>{setStatusFilter(statusFilter==='ENVIADA'?'TODOS':'ENVIADA');setPeriodFilter('TODOS')}}/><Kpi icon={CheckCircle2} label="Aprovadas no mês (com data)" value={String(stats.approvedMonth)} active={statusFilter==='APROVADA'&&periodFilter==='MES'} onClick={()=>{const active=statusFilter==='APROVADA'&&periodFilter==='MES';setStatusFilter(active?'TODOS':'APROVADA');setPeriodFilter(active?'TODOS':'MES')}}/><Kpi icon={CircleDollarSign} label="Valor aprovado" value={formatValue(stats.approvedValue,'currency')} active={statusFilter==='APROVADA'&&periodFilter==='TODOS'} onClick={()=>{setStatusFilter(statusFilter==='APROVADA'&&periodFilter==='TODOS'?'TODOS':'APROVADA');setPeriodFilter('TODOS')}}/></section>
    {(stats.approvedWithoutDate>0||rejectedWithoutDate>0)&&<div className="rounded-2xl border border-amber-200 bg-amber-50 px-4 py-3 text-xs text-amber-800"><strong>Decisões históricas com data pendente:</strong>{stats.approvedWithoutDate>0&&<span> {stats.approvedWithoutDate} aprovada(s) sem data de aceite.</span>}{rejectedWithoutDate>0&&<span> {rejectedWithoutDate} recusada(s) sem data de recusa.</span>} Propostas enviadas, em negociação ou em rascunho não precisam dessas datas. <button type="button" onClick={()=>void openDecisionReport()} className="ml-2 inline-flex items-center gap-1 rounded-lg border border-amber-300 bg-white px-2 py-1 font-semibold text-amber-900"><FileText className="h-3.5 w-3.5"/>Abrir relatório para correção</button></div>}
    <section className="rounded-3xl border border-slate-200 bg-white p-4 shadow-sm"><div className="grid gap-3 xl:grid-cols-[minmax(280px,1fr)_165px_180px_150px_150px_auto]"><div className="relative"><Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-slate-400"/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar por nº da proposta, cliente ou solicitante..." className="w-full rounded-xl border py-2.5 pl-9 pr-3 text-sm"/></div><select value={statusFilter} onChange={e=>setStatusFilter(e.target.value)} className="rounded-xl border px-3 py-2.5 text-sm"><option value="TODOS">Todos os status</option>{statuses.map(item=><option key={item}>{item}</option>)}</select><select value={responsibleFilter} onChange={e=>setResponsibleFilter(e.target.value)} className="rounded-xl border px-3 py-2.5 text-sm"><option value="TODOS">Todos responsáveis</option>{filterProfiles.map(item=><option key={item.value} value={item.value}>{item.label}{!item.active?' (inativo)':''}</option>)}</select><select value={periodFilter} onChange={e=>setPeriodFilter(e.target.value)} className="rounded-xl border px-3 py-2.5 text-sm"><option value="TODOS">Todo período</option><option value="MES">Este mês</option><option value="ANO">Este ano</option></select><select value={validityFilter} onChange={e=>setValidityFilter(e.target.value)} className="rounded-xl border px-3 py-2.5 text-sm"><option value="TODAS">Todas validades</option><option value="30_DIAS">Vence em 30 dias</option><option value="VENCIDAS">Vencidas</option></select><div className="flex gap-2"><button onClick={()=>setView('table')} className={`inline-flex items-center gap-2 rounded-xl border px-3 py-2.5 text-sm font-semibold ${view==='table'?'border-teal-600 bg-teal-50 text-teal-700':'border-slate-200 text-slate-500'}`}><List className="h-4 w-4"/>Tabela</button><button onClick={()=>setView('cards')} className={`inline-flex items-center gap-2 rounded-xl border px-3 py-2.5 text-sm font-semibold ${view==='cards'?'border-teal-600 bg-teal-50 text-teal-700':'border-slate-200 text-slate-500'}`}><LayoutGrid className="h-4 w-4"/>Cartões</button><button onClick={()=>void loadRows()} className="rounded-xl border p-2.5 text-slate-500" title="Atualizar"><RefreshCw className={`h-4 w-4 ${loading?'animate-spin':''}`}/></button></div></div></section>
    {error&&<div className="rounded-xl border border-red-200 bg-red-50 p-3 text-sm text-red-700">{error}</div>}
    {loading?<div className="rounded-3xl border bg-white p-12 text-center text-slate-500">Carregando propostas...</div>:view==='table'?<ProposalTable rows={paged} clientName={clientName} responsible={responsible} proposalScopes={proposalScopes} canWrite={canWrite} editProposal={editProposal}/>:<ProposalCards rows={paged} clientName={clientName} responsible={responsible} proposalScopes={proposalScopes} canWrite={canWrite} editProposal={editProposal}/>}
    <div className="flex flex-col gap-3 rounded-2xl border border-slate-200 bg-white px-5 py-3 text-sm text-slate-500 sm:flex-row sm:items-center sm:justify-between"><span>Mostrando {total?((page-1)*PAGE_SIZE)+1:0} a {Math.min(page*PAGE_SIZE,total)} de {total} propostas</span><div className="flex items-center gap-2"><button disabled={page<=1||loading} onClick={()=>setPage(value=>value-1)} className="rounded-lg border px-3 py-1.5 disabled:opacity-40">Anterior</button><span>{page} / {pages}</span><button disabled={page>=pages||loading} onClick={()=>setPage(value=>value+1)} className="rounded-lg border px-3 py-1.5 disabled:opacity-40">Próxima</button></div></div>
    <section className="grid gap-4 rounded-3xl border border-slate-200 bg-white px-5 py-4 shadow-sm sm:grid-cols-2 xl:grid-cols-4"><Summary icon={CircleDollarSign} label="Valor total" value={formatValue(stats.totalValue,'currency')} hint={`${stats.totalProposals} propostas`}/><Summary icon={Clock3} label="Valor em negociação" value={formatValue(stats.negotiationValue,'currency')} hint={`${stats.negotiationCount} propostas`}/><Summary icon={FileCheck2} label="Valor aprovado" value={formatValue(stats.approvedValue,'currency')} hint={`${stats.approvedCount} propostas`}/><Summary icon={TrendingUp} label="Taxa de aprovação" value={`${stats.approvalRate}%`} hint={`${stats.approvedCount} de ${stats.finalizedCount} finalizadas`}/></section>

    <Modal open={reportOpen} onClose={()=>setReportOpen(false)} title="Propostas com decisão sem data"><div className="space-y-4"><div className="rounded-xl border border-amber-200 bg-amber-50 p-3 text-sm text-amber-900">Este relatório contém somente propostas <strong>APROVADAS sem data de aceite</strong> e <strong>RECUSADAS sem data de recusa</strong>. Os demais status estão corretos sem data de decisão.</div><div className="flex flex-wrap items-center justify-between gap-2"><span className="text-sm text-slate-600">{reportLoading?'Carregando relatório...':`${pendingDecisions.length} pendência(s) encontrada(s)`}</span><button type="button" disabled={reportLoading||pendingDecisions.length===0} onClick={downloadDecisionReport} className="inline-flex items-center gap-2 rounded-xl bg-teal-700 px-3 py-2 text-sm font-semibold text-white disabled:opacity-40"><Download className="h-4 w-4"/>Baixar CSV completo</button></div><div className="max-h-[55vh] overflow-y-auto rounded-xl border border-slate-200"><table className="w-full text-left text-sm"><thead className="sticky top-0 bg-slate-100 text-xs text-slate-600"><tr><th className="px-3 py-2">Status</th><th className="px-3 py-2">Proposta</th><th className="px-3 py-2">Cliente</th><th className="px-3 py-2">Ação</th></tr></thead><tbody>{pendingDecisions.map(item=><tr key={item.id} className="border-t border-slate-200"><td className="px-3 py-2 font-semibold">{item.status}</td><td className="px-3 py-2">{item.numero_proposta||'Sem número'}</td><td className="px-3 py-2">{clientName(item.cliente_id)}</td><td className="px-3 py-2">{canWrite?<button type="button" onClick={()=>{setReportOpen(false);void editProposal(item as Row)}} className="font-semibold text-teal-700">Corrigir data</button>:'Somente leitura'}</td></tr>)}</tbody></table></div></div></Modal>

    <Modal open={open} onClose={()=>setOpen(false)} title={editingId?'Editar proposta':'Nova proposta'}><form onSubmit={save} className="grid gap-4 sm:grid-cols-2">
      <label><span className="mb-1 block text-sm font-medium">Negociação / Oportunidade (opcional)</span><input list="propostas-oportunidades" value={form.oportunidade_referencia} onChange={e=>changeOpportunityReference(e.target.value)} placeholder="Digite ou escolha uma oportunidade" className="w-full rounded-xl border px-3 py-2.5"/><datalist id="propostas-oportunidades">{opps.map(o=><option key={o.value} value={o.label}/>)}</datalist></label><Select label="Cliente *" required value={form.cliente_id} set={v=>setForm({...form,cliente_id:v,solicitante_contato_id:''})} options={clients}/><Select label="Contato / Solicitante" value={form.solicitante_contato_id} set={v=>setForm({...form,solicitante_contato_id:v})} options={availableContacts}/><Input label="Nº proposta" value={form.numero_proposta} set={v=>setForm({...form,numero_proposta:v})}/><Select label="Responsável comercial" value={form.responsavel_comercial_id} set={v=>setForm({...form,responsavel_comercial_id:v})} options={assignmentProfiles.map(p=>({value:p.value,label:`${p.label}${!p.active?' (inativo — responsável atual)':''}`}))}/><Input label="Valor" type="number" value={form.valor} set={v=>setForm({...form,valor:v})}/><Select label="Logística de coleta" value={form.logistica_coleta} set={v=>setForm({...form,logistica_coleta:v})} options={logistics.map(v=>({value:v,label:v}))}/><Select label="Status" value={form.status} set={v=>setForm({...form,status:v})} options={statuses.map(v=>({value:v,label:v}))}/><Input label="Validade" type="date" value={form.validade} set={v=>setForm({...form,validade:v})}/><Input label="Data de envio" type="datetime-local" value={form.data_envio} set={v=>setForm({...form,data_envio:v})}/>{form.status==='APROVADA'&&<Input label="Data de aceite *" type="datetime-local" value={form.data_aceite} set={v=>setForm({...form,data_aceite:v})}/>} {form.status==='RECUSADA'&&<Input label="Data de recusa *" type="datetime-local" value={form.data_recusa} set={v=>setForm({...form,data_recusa:v})}/>}<Input label="Periodicidade" value={form.periodicidade_proposta} set={v=>setForm({...form,periodicidade_proposta:v})}/>
      <div className="sm:col-span-2"><div className="mb-2 text-sm font-semibold text-slate-800">Rede de Laboratórios Parceiros *</div><div className="grid gap-2 rounded-2xl border border-slate-200 bg-slate-50/50 p-4 sm:grid-cols-2">{labs.map(l=><label key={l.id} className="flex items-center gap-2 text-sm"><input type="checkbox" checked={form.laboratorios.includes(l.id)} onChange={()=>toggleLab(l.id)} className="h-4 w-4 rounded border-slate-300 text-teal-700"/>{l.nome}</label>)}</div><p className="mt-1 text-xs text-slate-500">Pode selecionar MinasLab e um ou vários laboratórios parceiros na mesma proposta.</p></div>
      <div className="sm:col-span-2"><div className="mb-2 text-sm font-semibold text-slate-800">Escopo Analítico *</div><div className="grid gap-2 rounded-2xl border border-slate-200 bg-slate-50/50 p-4 sm:grid-cols-2">{groups.map(g=><label key={g.id} className="flex items-center gap-2 text-sm"><input type="checkbox" checked={form.escopos.includes(g.id)} onChange={()=>toggleScope(g.id)} className="h-4 w-4 rounded border-slate-300 text-teal-700"/>{g.nome}</label>)}</div></div>
      <label className="sm:col-span-2"><span className="mb-1 block text-sm font-medium">Observações</span><textarea value={form.observacoes} onChange={e=>setForm({...form,observacoes:e.target.value})} rows={4} className="w-full rounded-xl border px-3 py-2.5"/></label><label className="sm:col-span-2 flex items-center gap-2"><input type="checkbox" checked={form.ativo} onChange={e=>setForm({...form,ativo:e.target.checked})}/><span className="text-sm font-medium">Proposta ativa</span></label><div className="sm:col-span-2 flex justify-end gap-2"><button type="button" onClick={()=>setOpen(false)} className="rounded-xl border px-4 py-2.5">Cancelar</button><button disabled={saving} className="rounded-xl bg-teal-700 px-5 py-2.5 font-semibold text-white disabled:opacity-50">{saving?'Salvando...':'Salvar proposta'}</button></div>
    </form></Modal>
  </PageShell>
}
function statusTone(status:string|null){if(status==='APROVADA')return'border-emerald-200 bg-emerald-50 text-emerald-700';if(status==='RECUSADA'||status==='CANCELADA')return'border-red-200 bg-red-50 text-red-700';if(status==='ENVIADA')return'border-slate-200 bg-blue-50 text-blue-700';if(status==='EM NEGOCIAÇÃO')return'border-amber-200 bg-amber-50 text-amber-700';return'border-slate-200 bg-slate-50 text-slate-600'}
function validityTone(value:string|null){if(!value)return'text-slate-400';const days=(new Date(value+'T12:00:00').getTime()-Date.now())/86400000;if(days<0)return'text-red-600 font-semibold';if(days<=30)return'text-amber-600 font-semibold';return'text-slate-600'}
function Responsible({person}:{person:ProfileOpt}){return <div className="flex items-center gap-2"><UserAvatar name={person.label} avatarUrl={person.avatarUrl} size="sm"/><span>{person.label}{person.value&&!person.active?' (inativo)':''}</span></div>}
function ProposalTable({rows,clientName,responsible,proposalScopes,canWrite,editProposal}:{rows:Row[];clientName:(id:string|null)=>string;responsible:(id:string|null)=>ProfileOpt;proposalScopes:(id:string)=>string[];canWrite:boolean;editProposal:(row:Row)=>void}){return <section className="overflow-hidden rounded-3xl border border-slate-200 bg-white shadow-sm"><div className="overflow-x-auto"><table className="min-w-full text-sm"><thead className="text-left text-xs uppercase text-slate-500"><tr><th className="px-4 py-3">Nº Proposta</th><th className="px-4 py-3">Cliente / Solicitante</th><th className="px-4 py-3">Escopo</th><th className="px-4 py-3">Responsável</th><th className="px-4 py-3">Valor</th><th className="px-4 py-3">Status</th><th className="px-4 py-3">Validade</th><th className="px-4 py-3">Atualização</th><th className="px-4 py-3 text-right">Ações</th></tr></thead><tbody>{rows.length===0?<tr><td colSpan={9} className="p-12 text-center text-slate-500">Nenhuma proposta encontrada.</td></tr>:rows.map(row=><tr key={row.id}><td className="whitespace-nowrap px-4 py-3.5 font-semibold">{row.numero_proposta||'Sem número'}</td><td className="px-4 py-3.5"><div className="font-semibold text-slate-800">{clientName(row.cliente_id)}</div><div className="mt-0.5 max-w-48 truncate text-xs text-slate-400">{row.solicitante_snapshot_nome||'Sem solicitante'}</div></td><td className="max-w-48 px-4 py-3.5 text-xs text-slate-600">{proposalScopes(row.id).join(', ')||'Não informado'}</td><td className="whitespace-nowrap px-4 py-3.5"><Responsible person={responsible(row.responsavel_comercial_id)}/></td><td className="whitespace-nowrap px-4 py-3.5 font-semibold">{formatValue(row.valor,'currency')}</td><td className="px-4 py-3.5"><span className={`whitespace-nowrap rounded-full border px-2.5 py-1 text-xs font-semibold ${statusTone(row.status)}`}>{row.status||'SEM STATUS'}</span></td><td className={`whitespace-nowrap px-4 py-3.5 ${validityTone(row.validade)}`}>{formatValue(row.validade,'date')}</td><td className="whitespace-nowrap px-4 py-3.5 text-xs text-slate-500">{new Date(row.updated_at||row.created_at).toLocaleString('pt-BR')}</td><td className="px-4 py-3.5"><div className="flex justify-end gap-2"><Link to={`/propostas/${row.id}`} className="rounded-lg border p-2 text-slate-600"><Eye className="h-4 w-4"/></Link>{canWrite&&<button onClick={()=>void editProposal(row)} className="rounded-lg border p-2 text-slate-600"><Edit3 className="h-4 w-4"/></button>}</div></td></tr>)}</tbody></table></div></section>}
function ProposalCards({rows,clientName,responsible,proposalScopes,canWrite,editProposal}:{rows:Row[];clientName:(id:string|null)=>string;responsible:(id:string|null)=>ProfileOpt;proposalScopes:(id:string)=>string[];canWrite:boolean;editProposal:(row:Row)=>void}){return <section className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{rows.length===0?<div className="col-span-full rounded-3xl border bg-white p-12 text-center text-slate-500">Nenhuma proposta encontrada.</div>:rows.map(row=><article key={row.id} className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-start justify-between gap-3"><div><div className="text-xs font-semibold text-teal-700">{row.numero_proposta||'SEM NÚMERO'}</div><div className="mt-1 font-bold text-slate-800">{clientName(row.cliente_id)}</div><div className="mt-1 text-xs text-slate-400">{row.solicitante_snapshot_nome||'Sem solicitante'}</div></div><span className={`rounded-full border px-2.5 py-1 text-[10px] font-semibold ${statusTone(row.status)}`}>{row.status||'SEM STATUS'}</span></div><div className="mt-4 text-2xl font-bold text-slate-900">{formatValue(row.valor,'currency')}</div><div className="mt-3 rounded-2xl bg-slate-50 p-3 text-sm"><div className="text-xs text-slate-400">Escopo</div><div className="mt-1 font-medium">{proposalScopes(row.id).join(', ')||'Não informado'}</div><div className="mt-3 text-xs text-slate-400">Responsável</div><div className="mt-1"><Responsible person={responsible(row.responsavel_comercial_id)}/></div></div><div className={`mt-4 text-xs ${validityTone(row.validade)}`}>Validade: {formatValue(row.validade,'date')}</div><div className="mt-4 flex gap-2"><Link to={`/propostas/${row.id}`} className="flex-1 rounded-xl bg-teal-700 px-3 py-2.5 text-center text-sm font-semibold text-white">Visualizar</Link>{canWrite&&<button onClick={()=>void editProposal(row)} className="rounded-xl border px-3 py-2.5"><Edit3 className="h-4 w-4"/></button>}</div></article>)}</section>}
function Kpi({icon:Icon,label,value,active=false,onClick}:{icon:typeof FileText;label:string;value:string;active?:boolean;onClick:()=>void}){return <button type="button" onClick={onClick} aria-pressed={active} className={`flex h-20 w-full items-center gap-3 rounded-3xl border bg-white p-4 text-left shadow-sm transition hover:-translate-y-0.5 hover:shadow-md focus:outline-none focus:ring-2 focus:ring-teal-600 ${active?'border-teal-600 ring-2 ring-teal-100':'border-slate-200'}`}><span className="grid h-11 w-11 shrink-0 place-items-center rounded-full bg-teal-50 text-teal-700"><Icon className="h-5 w-5"/></span><div className="min-w-0"><div className="text-xs text-slate-500">{label}</div><strong className="mt-1 block truncate text-xl text-slate-900">{value}</strong></div></button>}
function Summary({icon:Icon,label,value,hint}:{icon:typeof CircleDollarSign;label:string;value:string;hint:string}){return <div className="flex items-center gap-3"><span className="grid h-10 w-10 shrink-0 place-items-center rounded-full bg-teal-50 text-teal-700"><Icon className="h-5 w-5"/></span><div><div className="text-xs text-slate-400">{label}</div><div className="font-bold text-slate-800">{value}</div><div className="text-[10px] text-slate-400">{hint}</div></div></div>}
function Input({label,value,set,type='text'}:{label:string;value:string;set:(v:string)=>void;type?:string}){return <label><span className="mb-1 block text-sm font-medium">{label}</span><input type={type} step={type==='number'?'0.01':undefined} value={value} onChange={e=>set(e.target.value)} className="w-full rounded-xl border px-3 py-2.5"/></label>}
function Select({label,value,set,options,required=false}:{label:string;value:string;set:(v:string)=>void;options:Opt[];required?:boolean}){return <label><span className="mb-1 block text-sm font-medium">{label}</span><select required={required} value={value} onChange={e=>set(e.target.value)} className="w-full rounded-xl border bg-white px-3 py-2.5"><option value="">Selecione</option>{options.map(o=><option key={o.value} value={o.value}>{o.label}</option>)}</select></label>}
function toLocal(value:unknown){if(!value)return '';const d=new Date(String(value));if(Number.isNaN(d.getTime()))return '';const p=(n:number)=>String(n).padStart(2,'0');return `${d.getFullYear()}-${p(d.getMonth()+1)}-${p(d.getDate())}T${p(d.getHours())}:${p(d.getMinutes())}`}
