import { lerTodasPaginas } from "../_shared/financeiro-paginacao.mjs";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2.45.0";
const SUPABASE_URL=Deno.env.get("SUPABASE_URL")!,SERVICE_KEY=Deno.env.get("SB_SECRET_KEY")??Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!,TOKEN=Deno.env.get("ML_TOKEN")??"",JWT_SECRET=Deno.env.get("ML_JWT_SECRET")??"";
const sb=createClient(SUPABASE_URL,SERVICE_KEY,{auth:{persistSession:false,autoRefreshToken:false}}),enc=new TextEncoder(),dec=new TextDecoder();
const CORS={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type, x-token","Access-Control-Allow-Methods":"POST, OPTIONS"};
const resp=(d:any,s=200)=>new Response(JSON.stringify(d),{status:s,headers:{...CORS,"Content-Type":"application/json; charset=utf-8","Cache-Control":"no-store"}}),txt=(v:any)=>String(v??"").trim(),key=(s:any)=>txt(s).normalize("NFD").replace(/[\u0300-\u036f]/g,"").toUpperCase().replace(/[^A-Z0-9]/g,""),normDoc=(s:any)=>txt(s).replace(/\D/g,"");
function b64u(s:string){s=s.replace(/-/g,"+").replace(/_/g,"/");while(s.length%4)s+="=";const b=atob(s),o=new Uint8Array(b.length);for(let i=0;i<b.length;i++)o[i]=b.charCodeAt(i);return o}
async function jwt(t:string){if(!JWT_SECRET||!t)return null;const p=t.split(".");if(p.length!==3)return null;try{const k=await crypto.subtle.importKey("raw",enc.encode(JWT_SECRET),{name:"HMAC",hash:"SHA-256"},false,["verify"]);if(!await crypto.subtle.verify("HMAC",k,b64u(p[2]),enc.encode(`${p[0]}.${p[1]}`)))return null;const x=JSON.parse(dec.decode(b64u(p[1])));if(x.sis!=="minaslab"||(typeof x.exp==="number"&&x.exp<Math.floor(Date.now()/1000)))return null;return x}catch{return null}}
Deno.serve(async req=>{if(req.method==="OPTIONS")return new Response("ok",{headers:CORS});if(req.method!=="POST")return resp({erro:"Use POST."},405);let body:any={};try{body=await req.json()}catch{return resp({erro:"JSON inválido."},400)}const m=txt(req.headers.get("authorization")).match(/^Bearer\s+(.+)$/i),cr=m?await jwt(m[1]):null,maq=!!TOKEN&&req.headers.get("x-token")===TOKEN;if(!cr&&!maq)return resp({erro:"Entre no sistema.",semSessao:true},401);if(!maq&&txt(cr?.papel)!=="direcao")return resp({erro:"O financeiro é somente da direção.",semPermissao:true},403);try{const f=body?.filtros??{};let q=sb.from("servicos_gerados").select("*,empresa:empresas(id,nome)").eq("apagado",false).order("data_os",{ascending:false,nullsFirst:false}).order("created_at",{ascending:false});if(f.empresaId)q=q.eq("empresa_id",f.empresaId);if(f.statusFaturamento)q=q.eq("status_faturamento",f.statusFaturamento);if(f.statusPagamento)q=q.eq("status_pagamento",f.statusPagamento);
const [data,parts,prefs,grupos,grupoItens]=await Promise.all([
 lerTodasPaginas((i,j)=>q.order("id").range(i,j)),
 lerTodasPaginas((i,j)=>sb.from("servicos_gerados_particularidades").select("*").eq("ativo",true).order("id").range(i,j)),
 lerTodasPaginas((i,j)=>sb.from("servicos_gerados_empresa_preferencia").select("chave,empresa_id").order("chave").range(i,j)),
 lerTodasPaginas((i,j)=>sb.from("servicos_gerados_grupos_faturamento").select("*").range(i,j)),
 lerTodasPaginas((i,j)=>sb.from("servicos_gerados_grupos_itens").select("grupo_id,servico_id,valor").range(i,j))
]);
const porDoc=new Map<string,any>(),porCliente=new Map<string,any>();for(const p of parts??[]){const d=normDoc(p.cnpj_cpf);if(d&&!porDoc.has(d))porDoc.set(d,p);const c=key(p.cliente_chave||p.cliente_nome);if(c&&!porCliente.has(c))porCliente.set(c,p)}const pref=new Map<string,string>();for(const p of prefs??[])pref.set(txt(p.chave),p.empresa_id);
let brutos=(data??[]).map((x:any)=>{const d=normDoc(x.cnpj_cpf),ch=d?`DOC:${d}`:`NOME:${key(x.cliente)}`;return {...x,particularidade:porDoc.get(d)??porCliente.get(key(x.cliente))??null,empresa_preferida_id:pref.get(ch)||null}});
const resumo={total:brutos.length,aguardandoFaturamento:brutos.filter((x:any)=>["AGUARDANDO","PRONTO PARA FATURAR"].includes(x.status_faturamento)).length,faturados:brutos.filter((x:any)=>x.status_faturamento==="FATURADO").length,aguardandoPagamento:brutos.filter((x:any)=>["AGUARDANDO","A RECEBER","PARCIAL"].includes(x.status_pagamento)&&x.status_faturamento==="FATURADO").length,vencidos:brutos.filter((x:any)=>x.status_pagamento==="VENCIDO").length,divergencias:brutos.filter((x:any)=>x.status_pagamento==="DIVERGENCIA").length};
const servPorId=new Map(brutos.map((x:any)=>[x.id,x])),grupoPorId=new Map((grupos??[]).map((g:any)=>[g.id,g])),membros=new Map<string,any[]>();for(const gi of grupoItens??[]){const s=servPorId.get(gi.servico_id);if(!s)continue;const a=membros.get(gi.grupo_id)||[];a.push(s);membros.set(gi.grupo_id,a)}
const agrupados=new Set<string>();const exibicao:any[]=[];for(const [gid,ms] of membros){if(ms.length<2)continue;const g=grupoPorId.get(gid);if(!g)continue;ms.forEach((s:any)=>agrupados.add(s.id));const base=ms[0],unico=(campo:string)=>{const vs=[...new Set(ms.map((s:any)=>txt(s[campo])).filter(Boolean))];return vs.length===1?vs[0]:null};const pagamentos=[...new Set(ms.map((s:any)=>s.status_pagamento).filter(Boolean))];const statusPagamento=pagamentos.length===1?pagamentos[0]:pagamentos.includes("DIVERGENCIA")?"DIVERGENCIA":pagamentos.includes("VENCIDO")?"VENCIDO":pagamentos.includes("PARCIAL")?"PARCIAL":pagamentos.includes("A RECEBER")?"A RECEBER":pagamentos.includes("PAGO")&&pagamentos.every((x:string)=>x==="PAGO")?"PAGO":base.status_pagamento;exibicao.push({...base,id:`GRUPO:${gid}`,grupo_id:gid,grupo_faturamento:true,grupo_itens:ms,quantidade_os:ms.length,os_numero:`${ms.length} OS`,contrato_proposta:unico("contrato_proposta")||"Vários",numero_nf:unico("numero_nf"),referencia_pagamento:g.referencia_pagamento||unico("referencia_pagamento"),valor_original:Number(g.valor_total||0),valor_faturar:Number(g.valor_total||0),data_emissao:unico("data_emissao"),data_vencimento:unico("data_vencimento"),forma_pagamento:unico("forma_pagamento"),status_faturamento:g.status||base.status_faturamento,status_pagamento:statusPagamento,pagamento_origem:unico("pagamento_origem")||"AGRUPADO"})}
for(const s of brutos)if(!agrupados.has(s.id))exibicao.push(s);exibicao.sort((a:any,b:any)=>String(b.data_os||b.created_at||"").localeCompare(String(a.data_os||a.created_at||"")));
const b=txt(f.busca).toLowerCase();let itens=exibicao;if(b)itens=itens.filter((x:any)=>{const vals=[x.os_numero,x.cliente,x.cnpj_cpf,x.numero_nf,x.contrato_proposta,x.referencia_pagamento,...(x.grupo_itens||[]).flatMap((s:any)=>[s.os_numero,s.numero_nf,s.contrato_proposta,s.referencia_pagamento])];return vals.some(v=>txt(v).toLowerCase().includes(b))});return resp({itens,resumo,totalServicos:brutos.length,totalLinhas:itens.length})}catch(e){console.error(e);return resp({erro:e instanceof Error?e.message:"Falha interna."},500)}});
