import "jsr:@supabase/functions-js/edge-runtime.d.ts";
const JWT_SECRET=Deno.env.get("ML_JWT_SECRET")??"", OMIE_KEY=Deno.env.get("ML_OMIE_APP_KEY")??"", OMIE_SECRET=Deno.env.get("ML_OMIE_APP_SECRET")??"";
const enc=new TextEncoder(),dec=new TextDecoder(); const CORS={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization,content-type","Access-Control-Allow-Methods":"POST,OPTIONS"};
const resp=(d:unknown,s=200)=>new Response(JSON.stringify(d),{status:s,headers:{...CORS,"Content-Type":"application/json; charset=utf-8","Cache-Control":"no-store"}}); const texto=(v:any)=>String(v??"").trim();
function numero(v:any){if(typeof v==="number")return Number.isFinite(v)?v:0;let s=texto(v).replace(/R\$\s*/gi,"").replace(/\s/g,"");if(s.includes(","))s=s.replace(/\./g,"").replace(",",".");const n=Number(s);return Number.isFinite(n)?n:0}
function valorMov(m:any){for(const k of["nValorDocumento","nValor","nValorMovimento","nValorLancamento","nValPago","nValLiquido","nValorTitulo","valor","vValor"]){if(m?.[k]!=null&&texto(m[k])!==""){const n=numero(m[k]);if(n!==0)return n}}for(const[k,v]of Object.entries(m||{})){if(/valor|^nval/i.test(k)&&!/saldo|limite/i.test(k)){const n=numero(v);if(n!==0)return n}}for(const[k,v]of Object.entries(m||{})){if(v&&typeof v==="object"&&!Array.isArray(v)&&/resumo|detalhe|valor/i.test(k)){const n=valorMov(v);if(n!==0)return n}}return 0}
function arraysMov(obj:any,depth=0):any[]{if(!obj||typeof obj!=="object"||depth>4)return[];const preferred=["listaMovimentos","movimentos","lista_movimentos","movimentosLista","movimentos_lista","listaLancamentos","lancamentos","lista_lancamentos"];for(const k of preferred)if(Array.isArray(obj[k]))return obj[k];for(const[k,v]of Object.entries(obj)){if(Array.isArray(v)&&/mov|lanc|extrato|item/i.test(k)&&v.some((x:any)=>x&&typeof x==="object"))return v as any[]}for(const v of Object.values(obj)){if(v&&typeof v==="object"&&!Array.isArray(v)){const a=arraysMov(v,depth+1);if(a.length)return a}}return[]}
function b64u(s:string){s=s.replace(/-/g,"+").replace(/_/g,"/");while(s.length%4)s+="=";const b=atob(s),o=new Uint8Array(b.length);for(let i=0;i<b.length;i++)o[i]=b.charCodeAt(i);return o} async function auth(req:Request){const t=(req.headers.get("authorization")||"").replace(/^Bearer\s+/i,"");if(!t||!JWT_SECRET)return null;const p=t.split(".");if(p.length!==3)return null;try{const key=await crypto.subtle.importKey("raw",enc.encode(JWT_SECRET),{name:"HMAC",hash:"SHA-256"},false,["verify"]);if(!await crypto.subtle.verify("HMAC",key,b64u(p[2]),enc.encode(`${p[0]}.${p[1]}`)))return null;const x=JSON.parse(dec.decode(b64u(p[1])));return x.sis==="minaslab"&&texto(x.papel)==="direcao"&&(!x.exp||x.exp>=Math.floor(Date.now()/1000))?x:null}catch{return null}}
const br=(v:string)=>{const m=String(v||"").slice(0,10).match(/^(\d{4})-(\d{2})-(\d{2})$/);return m?`${m[3]}/${m[2]}/${m[1]}`:""}; const esperar=(ms:number)=>new Promise(r=>setTimeout(r,ms));
async function omie(mod:string,call:string,param:any){if(!OMIE_KEY||!OMIE_SECRET)throw new Error("Integração Omie não configurada.");for(let i=0;i<3;i++){const r=await fetch(`https://app.omie.com.br/api/v1/${mod}/`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({call,app_key:OMIE_KEY,app_secret:OMIE_SECRET,param:[param]})});const b=await r.json().catch(()=>({}));const f=texto(b?.faultstring||b?.message||"");if(r.ok&&!f)return b;if(/não existem registros|nao existem registros/i.test(f))return{vazio:true};if(/REDUNDANT|Consumo redundante|rate limit|limite de consumo|Too many requests/i.test(f)&&i<2){await esperar(3000);continue}throw new Error(`Omie · ${call}: ${f||r.status}`)}throw new Error(`Omie · ${call}: limite de tentativas excedido.`)}
function listaContas(r:any){return r.ListarContasCorrentes||r.conta_corrente_lista||r.contaCorrenteLista||[]}
Deno.serve(async req=>{if(req.method==="OPTIONS")return new Response("ok",{headers:CORS});if(!await auth(req))return resp({erro:"Sessão inválida ou sem permissão."},401);try{const b=await req.json(),de=texto(b.de),ate=texto(b.ate);if(!de||!ate||de>ate)return resp({erro:"Período inválido."},400);let pg=1,contas:any[]=[];for(;;){const r=await omie("geral/contacorrente","ListarContasCorrentes",{pagina:pg,registros_por_pagina:100,apenas_importado_api:"N"});if(r.vazio)break;contas.push(...listaContas(r));const pags=numero(r.total_de_paginas)||1;if(pg>=pags)break;pg++}const ativas=contas.filter(c=>{const id=texto(c.nCodCC||c.codigo),fora=texto(c.inativo).toUpperCase()==="S"||texto(c.nao_fluxo).toUpperCase()==="S"||texto(c.nao_resumo).toUpperCase()==="S"||texto(c.tipo_conta_corrente||c.tipo).toUpperCase()==="CX";return id&&!fora});let total=0,valorTotal=0,consultas=0,zeros=0;const amostra:any[]=[],diagnostico:any[]=[];const vistos=new Set<string>();for(const c of ativas){const id=texto(c.nCodCC||c.codigo),e=await omie("financas/extrato","ListarExtrato",{nCodCC:Number(id),dPeriodoInicial:br(de),dPeriodoFinal:br(ate),cExibirApenasSaldo:"N"});consultas++;if(e.vazio)continue;const movs=arraysMov(e);diagnostico.push({conta:texto(c.descricao)||id,chaves:Object.keys(e).slice(0,30),movimentos:movs.length});for(const m of movs){const v=valorMov(m);if(v===0)zeros++;const mid=texto(m.nCodLancamento||m.codigo_lancamento||m.nCodLanc)||`${id}|${texto(m.dDataLancamento||m.dData)}|${v}|${texto(m.cRazCliente||m.cDesCliente||m.cObservacoes)}`;if(vistos.has(mid))continue;vistos.add(mid);total++;valorTotal+=Math.abs(v);if(amostra.length<8)amostra.push({conta:texto(c.descricao)||id,data:texto(m.dDataLancamento||m.dData),descricao:texto(m.cRazCliente||m.cDesCliente||m.cObservacoes||m.cOrigem),valor:v,chaves:Object.keys(m).slice(0,30)})}}return resp({ok:true,tipo:"EXTRATO",totalRegistros:total,valorTotal,consultas,zeros,contasAtivas:ativas.length,diagnostico,amostra,periodoDe:de,periodoAte:ate})}catch(e){return resp({erro:e instanceof Error?e.message:String(e)},500)}});