import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import {createClient} from "https://esm.sh/@supabase/supabase-js@2.45.0";
const U=Deno.env.get("SUPABASE_URL")!,K=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!,J=Deno.env.get("ML_JWT_SECRET")||"";
const sb=createClient(U,K,{auth:{persistSession:false,autoRefreshToken:false}});const enc=new TextEncoder(),dec=new TextDecoder();
const cors={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization, content-type","Access-Control-Allow-Methods":"POST, OPTIONS"};
const json=(b:any,s=200)=>new Response(JSON.stringify(b),{status:s,headers:{...cors,"Content-Type":"application/json","Cache-Control":"no-store"}});const txt=(v:any)=>String(v??"").trim();
function b64u(s:string){s=s.replace(/-/g,"+").replace(/_/g,"/");while(s.length%4)s+="=";const b=atob(s),o=new Uint8Array(b.length);for(let i=0;i<b.length;i++)o[i]=b.charCodeAt(i);return o}
async function auth(req:Request){const t=(req.headers.get("authorization")||"").replace(/^Bearer\s+/i,"");if(!t||!J)return null;const p=t.split(".");if(p.length!==3)return null;try{const k=await crypto.subtle.importKey("raw",enc.encode(J),{name:"HMAC",hash:"SHA-256"},false,["verify"]);if(!await crypto.subtle.verify("HMAC",k,b64u(p[2]),enc.encode(`${p[0]}.${p[1]}`)))return null;const x=JSON.parse(dec.decode(b64u(p[1])));if(x.sis!=="minaslab"||(x.exp&&x.exp<Math.floor(Date.now()/1000))||txt(x.papel)!=="direcao")return null;return x}catch{return null}}
function pag(b:any){const limite=Math.min(100,Math.max(10,Number(b.limite)||25)),pagina=Math.max(1,Number(b.pagina)||1),ini=(pagina-1)*limite;return{limite,pagina,ini,fim:ini+limite-1}}
function periodoMes(b:any){let de=txt(b.de),ate=txt(b.ate);const ano=Number(b.ano),mes=Number(b.mes);if(!de&&!ate&&ano&&mes>=1&&mes<=12){const mm=String(mes).padStart(2,"0"),ultimo=new Date(ano,mes,0).getDate();de=`${ano}-${mm}-01`;ate=`${ano}-${mm}-${String(ultimo).padStart(2,"0")}`;}else if(!de&&!ate&&ano&&!mes){de=`${ano}-01-01`;ate=`${ano}-12-31`;}return{de,ate}}
function buscaLike(v:string){return v.replace(/[%_]/g,m=>`\\${m}`)}
Deno.serve(async req=>{if(req.method==="OPTIONS")return new Response("ok",{headers:cors});if(!await auth(req))return json({erro:"Sessão inválida ou sem permissão."},401);try{const b=await req.json(),a=txt(b.action),{limite,pagina,ini,fim}=pag(b),{de,ate}=periodoMes(b),empresa=txt(b.empresaId),status=txt(b.status).toUpperCase(),busca=txt(b.busca);let q:any;
if(a==="recebimentos"){q=sb.from("recebimentos").select("*,empresa:empresas(id,nome),categoria:categorias_financeiras(id,nome),conta_bancaria:contas_bancarias(id,nome),baixas:baixas_recebimentos(*)",{count:"exact"}).eq("apagado",false);if(empresa)q=q.eq("empresa_id",empresa);if(status)q=q.eq("status",status);if(de)q=q.gte("data_vencimento",de);if(ate)q=q.lte("data_vencimento",ate);if(busca){const s=buscaLike(busca);q=q.or(`cliente.ilike.%${s}%,cnpj_cpf.ilike.%${s}%,descricao.ilike.%${s}%,numero_nf.ilike.%${s}%`)}q=q.order("data_vencimento",{ascending:false,nullsFirst:false});}
else if(a==="despesas"){q=sb.from("despesas").select("*,empresa:empresas(id,nome),categoria:categorias_financeiras(id,nome),conta_bancaria:contas_bancarias(id,nome),centro:centros_custo(id,nome),baixas:baixas_despesas(*)",{count:"exact"}).eq("apagado",false);if(empresa)q=q.eq("empresa_id",empresa);if(status)q=q.eq("status",status);if(de)q=q.gte("data_vencimento",de);if(ate)q=q.lte("data_vencimento",ate);if(busca){const s=buscaLike(busca);q=q.or(`fornecedor.ilike.%${s}%,cnpj_cpf.ilike.%${s}%,descricao.ilike.%${s}%`)}q=q.order("data_vencimento",{ascending:false,nullsFirst:false});}
else if(a==="notas"){q=sb.from("notas_fiscais").select("*,empresa:empresas(id,nome)",{count:"exact"}).eq("apagado",false);if(empresa)q=q.eq("empresa_id",empresa);if(status)q=q.eq("status_fiscal",status);if(de)q=q.gte("data_emissao",de);if(ate)q=q.lte("data_emissao",ate);if(busca){const s=buscaLike(busca);q=q.or(`numero_nf.ilike.%${s}%,nome_emitente.ilike.%${s}%,nome_destinatario.ilike.%${s}%,cnpj_emitente.ilike.%${s}%,cnpj_destinatario.ilike.%${s}%`)}q=q.order("data_emissao",{ascending:false,nullsFirst:false});}
else if(a==="movimentos"){q=sb.from("movimentos_bancarios").select("*,empresa:empresas(id,nome),conta:contas_bancarias(id,nome),conciliacoes(*)",{count:"exact"});if(empresa)q=q.eq("empresa_id",empresa);if(status==="CONCILIADO")q=q.eq("conciliado",true);else if(status==="PENDENTE")q=q.eq("conciliado",false);if(de)q=q.gte("data_movimento",de);if(ate)q=q.lte("data_movimento",ate);if(busca){const s=buscaLike(busca);q=q.or(`descricao.ilike.%${s}%,documento.ilike.%${s}%,fitid.ilike.%${s}%`)}q=q.order("data_movimento",{ascending:false});}
else if(a==="clientes"){q=sb.from("clientes_financeiro").select("*",{count:"exact"});if(status==="ATIVO")q=q.eq("ativo",true);else if(status==="INATIVO")q=q.eq("ativo",false);if(busca){const s=buscaLike(busca);q=q.or(`nome.ilike.%${s}%,nome_fantasia.ilike.%${s}%,cnpj_cpf.ilike.%${s}%`)}q=q.order("nome",{ascending:true});}
else return json({erro:"Ação inválida."},400);const r=await q.range(ini,fim);if(r.error)throw r.error;const total=Number(r.count||0);return json({itens:r.data||[],pagina,limite,total,paginas:Math.max(1,Math.ceil(total/limite)),de,ate});}catch(e){return json({erro:e instanceof Error?e.message:String(e)},500)}});