const JWT_SECRET=Deno.env.get("ML_JWT_SECRET")??"";
const OMIE_KEY=Deno.env.get("ML_OMIE_APP_KEY")??"";
const OMIE_SECRET=Deno.env.get("ML_OMIE_APP_SECRET")??"";
const OMIE_URL="https://app.omie.com.br/api/v1/";
const SIS="minaslab";
const enc=new TextEncoder(),dec=new TextDecoder();
const CORS={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization,content-type","Access-Control-Allow-Methods":"POST,OPTIONS"};
const resp=(d:unknown,s=200)=>new Response(JSON.stringify(d),{status:s,headers:{...CORS,"Content-Type":"application/json; charset=utf-8","Cache-Control":"no-store"}});
const texto=(v:unknown)=>String(v??"").trim();
const n=(v:unknown)=>Number.isFinite(Number(v))?Number(v):0;
function bytesFromB64url(s:string){s=s.replace(/-/g,"+").replace(/_/g,"/");while(s.length%4)s+="=";const b=atob(s),o=new Uint8Array(b.length);for(let i=0;i<b.length;i++)o[i]=b.charCodeAt(i);return o}
async function verificarJwt(token:string){if(!JWT_SECRET||!token)return null;const p=token.split(".");if(p.length!==3)return null;try{const key=await crypto.subtle.importKey("raw",enc.encode(JWT_SECRET),{name:"HMAC",hash:"SHA-256"},false,["verify"]);if(!await crypto.subtle.verify("HMAC",key,bytesFromB64url(p[2]),enc.encode(`${p[0]}.${p[1]}`)))return null;const payload=JSON.parse(dec.decode(bytesFromB64url(p[1])));if(payload.sis!==SIS)return null;if(typeof payload.exp==="number"&&payload.exp<Math.floor(Date.now()/1000))return null;return payload}catch{return null}}
const isoParaBR=(v:unknown)=>{const s=texto(v).slice(0,10),m=s.match(/^(\d{4})-(\d{2})-(\d{2})$/);return m?`${m[3]}/${m[2]}/${m[1]}`:""};
const esperar=(ms:number)=>new Promise(resolve=>setTimeout(resolve,ms));
async function omie(modulo:string,call:string,param:Record<string,unknown>){if(!OMIE_KEY||!OMIE_SECRET)throw new Error("Integração Omie não configurada.");for(let tentativa=0;tentativa<3;tentativa++){const r=await fetch(OMIE_URL+modulo+"/",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({call,app_key:OMIE_KEY,app_secret:OMIE_SECRET,param:[param]})});const body=await r.json().catch(()=>({}));if(r.ok)return body as any;const falha=texto((body as any).faultstring||(body as any).message||r.status);if(/não existem registros|nao existem registros/i.test(falha))return{vazio:true};const redundante=/REDUNDANT|Consumo redundante|rate limit|limite de consumo|Too many requests/i.test(falha);const seg=Math.min(30,Math.max(2,Number(falha.match(/Aguarde\s+(\d+)/i)?.[1]||2)));if(redundante&&tentativa<2){await esperar((seg+1)*1000);continue}throw new Error(`Omie · ${call}: ${falha}`)}throw new Error(`Omie · ${call}: limite de tentativas excedido.`)}
const vazio=(tipo:string,pagina=1)=>({ok:true,tipo,pagina,paginas:0,lidos:0,totalRegistros:0,valorTotal:0,status:{},amostra:[]});
function resumo(tipo:string,lista:any[],pagina:number,paginas:number,total:number,valor:(x:any)=>number,statusFn:(x:any)=>string,amostraFn:(x:any)=>any){const status:Record<string,number>={};let valorTotal=0;for(const x of lista){const s=statusFn(x)||"SEM STATUS";status[s]=(status[s]||0)+1;valorTotal+=valor(x)}return{ok:true,tipo,pagina,paginas,lidos:lista.length,totalRegistros:total||lista.length,valorTotal,status,amostra:lista.slice(0,5).map(amostraFn)}}
function periodosMensais(de:string,ate:string){const out:{de:string,ate:string}[]=[];let a=new Date(`${de}T12:00:00`),fim=new Date(`${ate}T12:00:00`);while(a<=fim){const ini=a.toISOString().slice(0,10),ultimo=new Date(a.getFullYear(),a.getMonth()+1,0,12),b=ultimo<fim?ultimo:fim;out.push({de:ini,ate:b.toISOString().slice(0,10)});a=new Date(a.getFullYear(),a.getMonth()+1,1,12);if(out.length>240)throw new Error("Período do extrato excede 240 meses.")}return out}
function listaContas(r:any){return r.ListarContasCorrentes||r.conta_corrente_lista||r.contaCorrenteLista||[]}
function movimentosExtrato(r:any){return Array.isArray(r?.listaMovimentos)?r.listaMovimentos:Array.isArray(r?.movimentos)?r.movimentos:Array.isArray(r?.lista_movimentos)?r.lista_movimentos:[]}
async function previaExtrato(de:string,ate:string){let p=1,contas:any[]=[];for(;;){const c=await omie("geral/contacorrente","ListarContasCorrentes",{pagina:p,registros_por_pagina:100,apenas_importado_api:"N"});if(c.vazio)break;contas.push(...listaContas(c));const pags=n(c.total_de_paginas)||1;if(p>=pags)break;p++}const ativas=contas.filter(c=>{const id=texto(c.nCodCC||c.codigo),fora=texto(c.inativo).toUpperCase()==="S"||texto(c.nao_fluxo).toUpperCase()==="S"||texto(c.nao_resumo).toUpperCase()==="S"||texto(c.tipo_conta_corrente||c.tipo).toUpperCase()==="CX";return !!id&&!fora});const periodos=periodosMensais(de,ate),status:Record<string,number>={CONTAS:ativas.length,PERIODOS:periodos.length},amostra:any[]=[];let total=0,valorTotal=0,consultas=0;const vistos=new Set<string>();for(const per of periodos){for(const c of ativas){const id=texto(c.nCodCC||c.codigo);const e=await omie("financas/extrato","ListarExtrato",{nCodCC:Number(id),dPeriodoInicial:isoParaBR(per.de),dPeriodoFinal:isoParaBR(per.ate),cExibirApenasSaldo:"N"});consultas++;if(e.vazio)continue;for(const m of movimentosExtrato(e)){const mid=texto(m.nCodLancamento||m.codigo_lancamento||m.nCodLanc)||`${id}|${texto(m.dDataLancamento||m.dData)}|${texto(m.nValorDocumento??m.nValor)}|${texto(m.cRazCliente||m.cDesCliente||m.cObservacoes)}`;if(vistos.has(mid))continue;vistos.add(mid);const v=n(m.nValorDocumento??m.nValor??m.valor);total++;valorTotal+=Math.abs(v);const nat=texto(m.cNatureza||m.natureza).toUpperCase()||"MOVIMENTO";status[nat]=(status[nat]||0)+1;if(amostra.length<8)amostra.push({conta:texto(c.descricao)||id,data:texto(m.dDataLancamento||m.dData),descricao:texto(m.cRazCliente||m.cDesCliente||m.cObservacoes||m.cOrigem),valor:v,natureza:nat})}await esperar(40)}}return{ok:true,tipo:"EXTRATO",pagina:periodos.length,paginas:periodos.length,lidos:total,totalRegistros:total,valorTotal,status:{...status,CONSULTAS:consultas},amostra,periodos:periodos.length,contasAtivas:ativas.length,contasIgnoradas:Math.max(contas.length-ativas.length,0),periodoDe:de,periodoAte:ate}}
async function previa(tipo:string,de:string,ate:string,pagina:number){if(tipo==="CLIENTES"){const r=await omie("geral/clientes","ListarClientes",{pagina,registros_por_pagina:100,apenas_importado_api:"N"});if(r.vazio)return vazio(tipo,pagina);const lista=r.clientes_cadastro||[];return resumo(tipo,lista,pagina,n(r.total_de_paginas)||1,n(r.total_de_registros)||lista.length,()=>0,x=>texto(x.inativo).toUpperCase()==="S"?"INATIVO":"ATIVO",x=>({idOmie:texto(x.codigo_cliente_omie),nome:texto(x.razao_social)||texto(x.nome_fantasia),documento:texto(x.cnpj_cpf)}))}if(tipo==="RECEBER"||tipo==="PAGAR"){const receber=tipo==="RECEBER",modulo=receber?"financas/contareceber":"financas/contapagar",call=receber?"ListarContasReceber":"ListarContasPagar";const r=await omie(modulo,call,{pagina,registros_por_pagina:100,apenas_importado_api:"N",filtrar_por_data_de:isoParaBR(de),filtrar_por_data_ate:isoParaBR(ate)});if(r.vazio)return vazio(tipo,pagina);const lista=r[receber?"conta_receber_cadastro":"conta_pagar_cadastro"]||[];return resumo(tipo,lista,pagina,n(r.total_de_paginas)||1,n(r.total_de_registros)||lista.length,x=>n(x.valor_documento),x=>texto(x.status_titulo),x=>({idOmie:texto(x.codigo_lancamento_omie),documento:texto(x.numero_documento_fiscal)||texto(x.numero_documento),nome:texto(x.razao_social)||texto(x.nome_fantasia),vencimento:texto(x.data_vencimento),valor:n(x.valor_documento),status:texto(x.status_titulo)}))}if(tipo==="NFE"){const r=await omie("produtos/nfconsultar","ListarNF",{pagina,registros_por_pagina:100,ordenar_por:"CODIGO",dEmiInicial:isoParaBR(de),dEmiFinal:isoParaBR(ate)});if(r.vazio)return vazio(tipo,pagina);const lista=r.nfCadastro||[];return resumo(tipo,lista,pagina,n(r.total_de_paginas)||1,n(r.total_de_registros)||lista.length,x=>n(x.total?.ICMSTot?.vNF||x.total?.vNF||x.valor_total),x=>x.ide?.dCan?"CANCELADA":"EMITIDA",x=>({numero:texto(x.ide?.nNF),data:texto(x.ide?.dEmi),valor:n(x.total?.ICMSTot?.vNF||x.total?.vNF||x.valor_total),status:x.ide?.dCan?"CANCELADA":"EMITIDA"}))}if(tipo==="NFSE"){const r=await omie("servicos/nfse","ListarNFSEs",{nPagina:pagina,nRegPorPagina:100,dEmiInicial:isoParaBR(de),dEmiFinal:isoParaBR(ate)});if(r.vazio)return vazio(tipo,pagina);const lista=r.nfseEncontradas||[];return resumo(tipo,lista,pagina,n(r.nTotPaginas)||1,n(r.nTotRegistros)||lista.length,x=>n(x.Valores?.nValorTotalServicos||x.Valores?.nValorLiquido),x=>{const s=texto(x.Cabecalho?.cStatusNFSe).toUpperCase();return s==="C"?"CANCELADA":s==="F"?"AUTORIZADA":s||"SEM STATUS"},x=>({numero:texto(x.Cabecalho?.nNumeroNFSe),cliente:texto(x.Cabecalho?.cRazaoDestinatario),data:texto(x.Emissao?.cDataEmissao),valor:n(x.Valores?.nValorTotalServicos||x.Valores?.nValorLiquido),status:texto(x.Cabecalho?.cStatusNFSe)}))}if(tipo==="EXTRATO")return previaExtrato(de,ate);throw new Error("Tipo de prévia inválido.")}
Deno.serve(async(req)=>{if(req.method==="OPTIONS")return new Response("ok",{headers:CORS});if(req.method!=="POST")return resp({erro:"Use POST."},405);const m=texto(req.headers.get("authorization")).match(/^Bearer\s+(.+)$/i);const cracha=m?await verificarJwt(m[1]):null;if(!cracha)return resp({erro:"Entre no sistema.",semSessao:true},401);if(texto(cracha.papel)!=="direcao")return resp({erro:"O financeiro é somente da direção.",semPermissao:true},403);let body:any={};try{body=await req.json()}catch{return resp({erro:"JSON inválido."},400)}try{const tipo=texto(body.tipo).toUpperCase(),de=texto(body.de),ate=texto(body.ate),pagina=Math.max(1,n(body.pagina)||1);if(!["CLIENTES","RECEBER","PAGAR","NFE","NFSE","EXTRATO"].includes(tipo))return resp({erro:"Tipo inválido."},400);if(tipo!=="CLIENTES"&&(!de||!ate||de>ate))return resp({erro:"Período inválido."},400);return resp(await previa(tipo,de,ate,pagina))}catch(e){return resp({erro:e instanceof Error?e.message:"Falha interna."},500)}});