const JWT_SECRET=Deno.env.get("ML_JWT_SECRET")??"";
const OMIE_KEY=Deno.env.get("ML_OMIE_APP_KEY")??"";
const OMIE_SECRET=Deno.env.get("ML_OMIE_APP_SECRET")??"";
const OMIE_URL="https://app.omie.com.br/api/v1/";
const SIS="minaslab";
const enc=new TextEncoder(),dec=new TextDecoder();
const CORS={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization,content-type","Access-Control-Allow-Methods":"POST,OPTIONS"};
const resp=(d:unknown,s=200)=>new Response(JSON.stringify(d),{status:s,headers:{...CORS,"Content-Type":"application/json; charset=utf-8","Cache-Control":"no-store"}});
const texto=(v:unknown)=>String(v??"").trim();
const n=(v:unknown)=>Number.isFinite(Number(v))?Number(v):0;
function bytesFromB64url(s:string){s=s.replace(/-/g,"+").replace(/_/g,"/");while(s.length%4)s+="=";const b=atob(s),o=new Uint8Array(b.length);for(let i=0;i<b.length;i++)o[i]=b.charCodeAt(i);return o;}
async function verificarJwt(token:string){if(!JWT_SECRET||!token)return null;const p=token.split(".");if(p.length!==3)return null;try{const key=await crypto.subtle.importKey("raw",enc.encode(JWT_SECRET),{name:"HMAC",hash:"SHA-256"},false,["verify"]);if(!await crypto.subtle.verify("HMAC",key,bytesFromB64url(p[2]),enc.encode(`${p[0]}.${p[1]}`)))return null;const payload=JSON.parse(dec.decode(bytesFromB64url(p[1])));if(payload.sis!==SIS)return null;if(typeof payload.exp==="number"&&payload.exp<Math.floor(Date.now()/1000))return null;return payload;}catch{return null;}}
const isoParaBR=(v:unknown)=>{const s=texto(v).slice(0,10),m=s.match(/^(\d{4})-(\d{2})-(\d{2})$/);return m?`${m[3]}/${m[2]}/${m[1]}`:"";};
async function omie(modulo:string,call:string,param:Record<string,unknown>){if(!OMIE_KEY||!OMIE_SECRET)throw new Error("Integração Omie não configurada.");const r=await fetch(OMIE_URL+modulo+"/",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({call,app_key:OMIE_KEY,app_secret:OMIE_SECRET,param:[param]})});const body=await r.json().catch(()=>({}));if(!r.ok){const falha=texto((body as any).faultstring||r.status);if(/não existem registros|nao existem registros/i.test(falha))return{vazio:true};throw new Error(`Omie · ${call}: ${falha}`);}return body as any;}
Deno.serve(async(req)=>{if(req.method==="OPTIONS")return new Response("ok",{headers:CORS});if(req.method!=="POST")return resp({erro:"Use POST."},405);const m=texto(req.headers.get("authorization")).match(/^Bearer\s+(.+)$/i);const cracha=m?await verificarJwt(m[1]):null;if(!cracha)return resp({erro:"Entre no sistema.",semSessao:true},401);if(texto(cracha.papel)!=="direcao")return resp({erro:"O financeiro é somente da direção.",semPermissao:true},403);let body:any={};try{body=await req.json();}catch{return resp({erro:"JSON inválido."},400);}try{const tipo=texto(body.tipo).toUpperCase(),de=texto(body.de),ate=texto(body.ate),pagina=Math.max(1,n(body.pagina)||1);if(!["RECEBER","PAGAR"].includes(tipo))return resp({erro:"Tipo inválido."},400);if(!de||!ate||de>ate)return resp({erro:"Período inválido."},400);const receber=tipo==="RECEBER";const modulo=receber?"financas/contareceber":"financas/contapagar";const call=receber?"ListarContasReceber":"ListarContasPagar";const param:Record<string,unknown>={pagina,registros_por_pagina:100,apenas_importado_api:"N",filtrar_por_data_de:isoParaBR(de),filtrar_por_data_ate:isoParaBR(ate)};const r=await omie(modulo,call,param);if(r.vazio)return resp({ok:true,tipo,pagina,paginas:0,lidos:0,valorTotal:0,status:{},amostra:[]});const lista=(r[receber?"conta_receber_cadastro":"conta_pagar_cadastro"]??[]) as any[];const status:Record<string,number>={};let valorTotal=0;for(const x of lista){const s=texto(x.status_titulo)||"SEM STATUS";status[s]=(status[s]||0)+1;valorTotal+=n(x.valor_documento);}const amostra=lista.slice(0,5).map(x=>({idOmie:texto(x.codigo_lancamento_omie),documento:texto(x.numero_documento_fiscal)||texto(x.numero_documento),nome:texto(x.razao_social)||texto(x.nome_fantasia),vencimento:texto(x.data_vencimento),valor:n(x.valor_documento),valorPago:n(x.valor_pago),status:texto(x.status_titulo)}));return resp({ok:true,tipo,pagina,paginas:n(r.total_de_paginas)||1,lidos:lista.length,totalRegistros:n(r.total_de_registros)||lista.length,valorTotal,status,amostra});}catch(e){return resp({erro:e instanceof Error?e.message:"Falha interna."},500);}});
