import { useEffect, useState } from 'react'
import { BarChart3, Building2, ClipboardList, Download, Eye, FileArchive, FileText, FileUp, FlaskConical, LoaderCircle, RefreshCw, Users } from 'lucide-react'
import { Link, useNavigate } from 'react-router-dom'
import { supabase } from '../../services/supabase'
import { useAuth } from '../../hooks/useAuth'
import { PageShell } from '../../components/ui/PageShell'
import { parseXlsxFirstDataSheet } from '../../lib/xlsx'

type ParsedRow=Record<string,string>
type Model={name:string;header:string;note:string;source:string;title:string;description:string;icon:typeof Users}

const models:Record<string,Model>={
  GERENCIALAB_CLIENTES:{name:'MODELO-GERENCIALAB-CLIENTES.csv',header:'ID_CLIENTE;CPF_CNPJ;RAZAO_SOCIAL;NOME_FANTASIA;TELEFONE;EMAIL;STATUS',note:'Cadastro de clientes. CPF/CNPJ repetido é reconciliado com o mesmo cliente ativo.',source:'GerenciaLab →',title:'Clientes',description:'Importa clientes e dados cadastrais do GerenciaLab.',icon:Building2},
  GERENCIALAB_DASHBOARD:{name:'MODELO-GERENCIALAB-DASHBOARD.csv',header:'NUMERO_OS;CPF_CNPJ;CLIENTE;NUMERO_CONTRATO;DATA_OS;VALOR_OS;STATUS_OS',note:'OS, contratos e valores. O Nº da OS é usado para localizar e atualizar o mesmo registro.',source:'GerenciaLab →',title:'Dashboard / OS',description:'Importa ordens de serviço e dados do dashboard.',icon:ClipboardList},
  GERENCIALAB_HISTORICO_ANALITICO:{name:'MODELO-GERENCIALAB-HISTORICO-ANALITICO.csv',header:'NUMERO_OS;CPF_CNPJ;CLIENTE;NUMERO_CONTRATO;DATA_OS;VALOR_OS;STATUS_OS;AMOSTRA;GRUPO;SERVICO;LABORATORIO;PARAMETRO;METODO;UNIDADE;LQ;LD',note:'Uma OS pode aparecer em várias linhas por amostras e parâmetros; ela não é duplicada. LABORATÓRIO e LABORATORIO são normalizados para LABORATORIO.',source:'GerenciaLab →',title:'Histórico Analítico',description:'Importa histórico analítico, amostras, laboratório e parâmetros.',icon:BarChart3},
  GERENCIALAB_PROPOSTAS:{name:'MODELO-GERENCIALAB-PROPOSTAS.csv',header:'NUMERO_PROPOSTA;CPF_CNPJ;CLIENTE;SOLICITANTE;DATA_ENVIO;VALIDADE;VALOR;STATUS;RESPONSAVEL',note:'A proposta é reconciliada pelo número e pelo cliente, evitando duplicação em reenvios.',source:'GerenciaLab →',title:'Propostas',description:'Importa propostas comerciais.',icon:FileText},
  GERENCIALAB_CONTRATOS:{name:'MODELO-GERENCIALAB-CONTRATOS.csv',header:'NUMERO_CONTRATO;CPF_CNPJ;CLIENTE;NUMERO_PROPOSTA;PERIODICIDADE;STATUS;DATA_INICIO;DATA_FIM;ID_GERENCIALAB;ATIVO',note:'Contratos são reconciliados pelo número e preservam o ID GerenciaLab quando existir.',source:'GerenciaLab →',title:'Contratos',description:'Importa contratos e vigências.',icon:FileArchive},
  CATALOGO_GERENCIALAB:{name:'MODELO-CATALOGO-GERENCIALAB.csv',header:'ID;GRUPO;PARAMETRO;PRECO;PRECO_MINIMO;LABORATORIO',note:'Parâmetros são reconciliados pelo ID externo, evitando duplicação. LABORATORIO: MinasLab (ou vazio) = execução interna; Freitag, Campo Análise, Ceimic ou LaboPrime = laboratório parceiro.',source:'GerenciaLab →',title:'Catálogo',description:'Importa catálogos, parâmetros, unidades e preços.',icon:FlaskConical},
  CRM_HISTORICO:{name:'MODELO-CRM-HISTORICO.csv',header:'CPF_CNPJ;CLIENTE;DATA_HORA;TIPO;TITULO;DESCRICAO;USUARIO;NUMERO_PROPOSTA;NUMERO_OS;PROXIMA_ACAO;DATA_PROXIMA;PRIORIDADE;RESULTADO',note:'Histórico de interações com rastreabilidade por linha da importação.',source:'CRM / Histórico →',title:'Histórico CRM',description:'Importa histórico de interações e atividades anteriores.',icon:FileArchive},
  CRM_ATENDIMENTOS:{name:'MODELO-CRM-ATENDIMENTOS.csv',header:'DATA_HORA;CPF_CNPJ;CLIENTE;CONTATO;TELEFONE;EMAIL;ORIGEM;ASSUNTO;DESCRICAO;RESPONSAVEL;STATUS',note:'Atendimentos são vinculados ao cliente quando encontrado; caso contrário, um lead de importação é criado.',source:'Comercial / Histórico →',title:'Atendimentos',description:'Importa histórico de atendimentos comerciais e primeiro atendimento.',icon:Users},
}

function normalizeHeader(value:string,index:number){const key=value.normalize('NFD').replace(/[̀-ͯ]/g,'').trim().toUpperCase().replace(/[^A-Z0-9]+/g,'_').replace(/^_+|_+$/g,'');return key||`COLUNA_${index+1}`}
function normalizeRows(headers:string[],rows:ParsedRow[]){const normalizedHeaders=headers.map(normalizeHeader);return{headers:normalizedHeaders,rows:rows.map(row=>Object.fromEntries(headers.map((header,index)=>[normalizedHeaders[index],String(row[header]??'').trim()])))}}

export function parseDelimited(text:string):{headers:string[];rows:ParsedRow[]}{
  const source=text.replace(/^﻿/,'').replace(/\r\n/g,'\n').replace(/\r/g,'\n')
  const firstLine=source.split('\n',1)[0]??''
  if(!firstLine.trim())return{headers:[],rows:[]}
  const delimiter=[';','\t',','].map(candidate=>({candidate,count:firstLine.split(candidate).length})).sort((a,b)=>b.count-a.count)[0].candidate
  const records:string[][]=[];let row:string[]=[];let value='';let quoted=false
  const pushValue=()=>{row.push(value.trim());value=''}
  const pushRow=()=>{pushValue();if(row.some(cell=>cell.length>0))records.push(row);row=[]}
  for(let index=0;index<source.length;index+=1){const char=source[index]
    if(char==='"'){if(quoted&&source[index+1]==='"'){value+='"';index+=1}else quoted=!quoted}
    else if(char===delimiter&&!quoted)pushValue()
    else if(char==='\n'&&!quoted)pushRow()
    else value+=char
  }
  if(value.length||row.length)pushRow()
  if(!records.length)return{headers:[],rows:[]}
  const headers=records[0].map(normalizeHeader)
  const rows=records.slice(1).map(values=>Object.fromEntries(headers.map((header,index)=>[header,values[index]??''])))
  return{headers,rows}
}

export function Importacoes(){
  const{profile,hasPermission}=useAuth();const canManageImports=hasPermission('imports.manage');const navigate=useNavigate()
  const[history,setHistory]=useState<Array<Record<string,unknown>>>([]);const[error,setError]=useState<string|null>(null);const[file,setFile]=useState<File|null>(null);const[type,setType]=useState('GERENCIALAB_CLIENTES');const[headers,setHeaders]=useState<string[]>([]);const[parsedRows,setParsedRows]=useState<ParsedRow[]>([]);const[sourceFormat,setSourceFormat]=useState('CSV/TEXTO_DELIMITADO');const[sheetName,setSheetName]=useState<string|null>(null);const[busy,setBusy]=useState(false)
  async function load(){const{data,error}=await supabase.from('importacoes').select('*').order('created_at',{ascending:false}).limit(100);if(error)setError(error.message);else{setError(null);setHistory((data??[]) as Array<Record<string,unknown>>)}}
  useEffect(()=>{void load()},[])
  async function choose(next:File|null){setFile(next);setHeaders([]);setParsedRows([]);setError(null);setSheetName(null);if(!next)return;const extension=next.name.split('.').pop()?.toLowerCase();try{if(extension==='xlsx'){const parsed=await parseXlsxFirstDataSheet(next);const normalized=normalizeRows(parsed.headers,parsed.rows);if(!normalized.headers.length)throw new Error('Arquivo Excel sem cabeçalho legível.');if(!normalized.rows.length)throw new Error('O arquivo possui cabeçalho, mas nenhuma linha de dados.');setHeaders(normalized.headers);setParsedRows(normalized.rows);setSourceFormat('XLSX');setSheetName(parsed.sheetName);return}if(extension!=='csv')throw new Error('Formato não suportado. Use CSV ou XLSX.');const parsed=parseDelimited(await next.text());if(!parsed.headers.length)throw new Error('Arquivo CSV sem cabeçalho legível.');if(!parsed.rows.length)throw new Error('O arquivo possui cabeçalho, mas nenhuma linha de dados.');setHeaders(parsed.headers);setParsedRows(parsed.rows);setSourceFormat('CSV/TEXTO_DELIMITADO')}catch(reason){setError(reason instanceof Error?reason.message:'Não foi possível ler o arquivo.');setParsedRows([]);setHeaders([])}}
  async function register(){if(!canManageImports||!file||parsedRows.length===0)return;setBusy(true);setError(null);let importId='';try{const{data:created,error:createError}=await supabase.from('importacoes').insert({source_system:'ARQUIVO',tipo_importacao:type,nome_arquivo:file.name,status:'STAGING',total_linhas:parsedRows.length,linhas_validas:0,linhas_com_erro:0,criado_por:profile?.id??null,metadata:{size:file.size,type:file.type,formato:sourceFormat,planilha:sheetName,colunas:headers}}).select('id').single();if(createError)throw createError;importId=String(created.id);const payload=parsedRows.map((row,index)=>({importacao_id:importId,numero_linha:index+2,payload_bruto:row,payload_normalizado:row,status_validacao:'PENDENTE',erros:[]}));for(let start=0;start<payload.length;start+=200){const{error:lineError}=await supabase.from('importacao_linhas').insert(payload.slice(start,start+200));if(lineError)throw lineError}const{error:processError}=await supabase.rpc('crm_process_importacao',{p_importacao_id:importId});if(processError)throw processError;navigate(`/importacoes/${importId}`)}catch(reason){const message=reason instanceof Error?reason.message:'Falha ao processar a importação.';setError(message);if(importId)await supabase.from('importacoes').update({status:'ERRO',metadata:{size:file.size,type:file.type,formato:sourceFormat,planilha:sheetName,colunas:headers,erro_processamento:message}}).eq('id',importId)}finally{setBusy(false)}}
  function downloadModel(){const model=models[type];if(!model)return;const blob=new Blob(['﻿'+model.header+'\n'],{type:'text/csv;charset=utf-8'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=model.name;a.click();URL.revokeObjectURL(url)}
  const model=models[type]
  return <PageShell title="Importações" description="Envie o arquivo, acompanhe a validação e veja o resultado da aplicação no CRM.">
    <section className="rounded-2xl border border-teal-100 bg-teal-50/70 px-5 py-4 text-sm text-teal-900">O sistema lê, grava no staging, valida e aplica a carga. Ao terminar, o detalhe informa quantas linhas foram aplicadas e quais tiveram erro.</section>
    <section className="rounded-3xl border bg-white p-5 shadow-sm"><h3 className="mb-4 text-base font-semibold text-slate-900">Selecione o tipo de importação</h3><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{Object.entries(models).map(([key,item])=>{const Icon=item.icon;const active=type===key;return <button key={key} type="button" onClick={()=>{setType(key);setFile(null);setHeaders([]);setParsedRows([]);setError(null);setSheetName(null)}} className={`relative min-h-48 rounded-2xl border p-5 text-center transition ${active?'border-teal-500 bg-teal-50/40 shadow-sm':'border-slate-200 bg-white hover:border-teal-300 hover:shadow-sm'}`}><Icon className="mx-auto h-8 w-8 text-teal-600"/><div className="mt-4 text-xs font-semibold text-teal-700">{item.source}</div><div className="mt-1 text-lg font-bold text-slate-900">{item.title}</div><p className="mt-2 text-sm leading-5 text-slate-500">{item.description}</p></button>})}</div></section>
    <section className="rounded-3xl border bg-white p-5 shadow-sm"><div className="grid gap-5 lg:grid-cols-[1fr_auto] lg:items-end"><div><div className="text-sm font-semibold text-slate-900">{model.title}</div><p className="mt-1 text-xs text-slate-500">{model.note}</p><input type="file" accept=".csv,.xlsx" onChange={e=>void choose(e.target.files?.[0]??null)} className="mt-4 w-full rounded-xl border border-slate-200 bg-white px-3 py-2.5 text-sm"/></div><div className="flex flex-wrap gap-2"><button type="button" onClick={downloadModel} className="inline-flex items-center gap-2 rounded-xl border border-slate-200 bg-white px-4 py-2.5 text-sm font-semibold text-slate-700"><Download className="h-4 w-4"/>Baixar modelo</button><button disabled={!file||parsedRows.length===0||!canManageImports||busy} onClick={()=>void register()} className="inline-flex items-center gap-2 rounded-xl bg-teal-700 px-4 py-2.5 text-sm font-semibold text-white disabled:opacity-40">{busy?<LoaderCircle className="h-4 w-4 animate-spin"/>:<FileUp className="h-4 w-4"/>}{busy?'Importando e validando...':'Importar arquivo'}</button></div></div>{error&&<div className="mt-4 rounded-xl bg-red-50 p-3 text-sm text-red-700">{error}</div>}{file&&parsedRows.length>0&&<div className="mt-4 rounded-xl bg-slate-50 p-4 text-sm text-slate-600"><strong>{file.name}</strong> · {parsedRows.length} linhas identificadas · {headers.length} colunas{sheetName?` · planilha: ${sheetName}`:''}. Após o envio o processamento começa automaticamente.</div>}</section>
    {parsedRows.length>0&&<section className="rounded-3xl border bg-white shadow-sm"><div className="border-b p-5"><h3 className="font-semibold">Prévia local — primeiras 5 linhas</h3><p className="mt-1 text-xs text-slate-500">Confira os cabeçalhos e as primeiras linhas antes de importar.</p></div><div className="overflow-x-auto"><table className="min-w-full text-sm"><thead className="bg-slate-50 text-left text-xs uppercase text-slate-500"><tr>{headers.map(header=><th key={header} className="whitespace-nowrap px-4 py-3">{header}</th>)}</tr></thead><tbody className="divide-y">{parsedRows.slice(0,5).map((row,index)=><tr key={index}>{headers.map(header=><td key={header} className="max-w-72 truncate px-4 py-3" title={row[header]}>{row[header]||'—'}</td>)}</tr>)}</tbody></table></div></section>}
    <section className="rounded-3xl border bg-white p-5 shadow-sm"><h3 className="text-base font-semibold text-slate-900">Como importar</h3><div className="mt-4 grid gap-4 md:grid-cols-4">{[['1','Baixe o modelo','Confira as colunas esperadas.'],['2','Preencha os dados','Use CSV ou XLSX conforme o modelo.'],['3','Selecione o arquivo','O sistema mostra quantas linhas foram lidas.'],['4','Importar e conferir','A carga é validada/aplicada e o resultado é exibido.']].map(([n,t,d])=><div key={n} className="flex gap-3"><div className="grid h-9 w-9 shrink-0 place-items-center rounded-full bg-teal-600 font-bold text-white">{n}</div><div><div className="text-sm font-semibold text-slate-900">{t}</div><div className="mt-1 text-xs leading-5 text-slate-500">{d}</div></div></div>)}</div></section>
    <section className="rounded-3xl border bg-white shadow-sm"><div className="flex items-center justify-between border-b p-4"><h3 className="font-semibold">Histórico de importações</h3><button onClick={()=>void load()} className="rounded-xl border p-2"><RefreshCw className="h-4 w-4"/></button></div><div className="overflow-x-auto"><table className="min-w-full text-sm"><thead className="bg-slate-50 text-left text-xs uppercase text-slate-500"><tr><th className="px-5 py-3">Arquivo</th><th className="px-5 py-3">Tipo</th><th className="px-5 py-3">Status</th><th className="px-5 py-3">Linhas</th><th className="px-5 py-3">Criado em</th><th className="px-5 py-3">Ações</th></tr></thead><tbody className="divide-y">{history.length===0?<tr><td colSpan={6} className="p-10 text-center text-slate-500">Nenhuma importação realizada ainda.</td></tr>:history.map(r=><tr key={String(r.id)}><td className="px-5 py-4">{String(r.nome_arquivo??'—')}</td><td className="px-5 py-4">{String(r.tipo_importacao)}</td><td className="px-5 py-4 font-semibold">{String(r.status)}</td><td className="px-5 py-4">{String(r.total_linhas??0)}</td><td className="px-5 py-4">{new Date(String(r.created_at)).toLocaleString('pt-BR')}</td><td className="px-5 py-4"><Link to={`/importacoes/${String(r.id)}`} className="inline-flex rounded-lg border p-2 text-slate-500 hover:bg-slate-50" title="Abrir resultado"><Eye className="h-4 w-4"/></Link></td></tr>)}</tbody></table></div></section>
  </PageShell>
}
