import { CalendarDays, Database, MessageCircleMore, ShieldCheck, UploadCloud } from 'lucide-react'
import { Link } from 'react-router-dom'
import { PageShell } from '../../components/ui/PageShell'
import { IntegrationHealth } from './IntegrationHealth'

export function Integracoes(){return <PageShell title="Integrações" description="Conexões externas do CRM, com o status operacional conhecido e sem expor credenciais.">
  <section className="grid gap-5 lg:grid-cols-3">
    <article className="rounded-3xl border bg-white p-6 shadow-sm"><Database className="h-6 w-6 text-teal-700"/><div className="mt-4 flex items-center justify-between gap-3"><h3 className="text-lg font-semibold">GerenciaLab</h3><span className="rounded-full bg-emerald-50 px-2.5 py-1 text-xs font-semibold text-emerald-700">IMPORTAÇÃO POR ARQUIVO</span></div><p className="mt-2 text-sm text-slate-600">Clientes, OS, contratos, faturas e histórico analítico entram por exportações do GerenciaLab. Não é presumida uma API inexistente.</p><div className="mt-5 flex flex-wrap gap-2"><Link to="/integracoes/gerencialab" className="inline-flex items-center gap-2 rounded-xl bg-teal-700 px-4 py-2.5 text-sm font-semibold text-white"><UploadCloud className="h-4 w-4"/>Abrir importador</Link><Link to="/importacoes" className="inline-flex items-center gap-2 rounded-xl border bg-white px-4 py-2.5 text-sm font-semibold text-slate-600">Histórico</Link></div></article>

    <article className="rounded-3xl border bg-white p-6 shadow-sm"><MessageCircleMore className="h-6 w-6 text-teal-700"/><div className="mt-4 flex items-center justify-between gap-3"><h3 className="text-lg font-semibold">ChatPro</h3><span className="rounded-full bg-amber-50 px-2.5 py-1 text-xs font-semibold text-amber-800">WEBHOOK EXISTENTE · AUDITORIA PENDENTE</span></div><p className="mt-2 text-sm text-slate-600">O CRM já possui integração por webhook com o ChatPro para entrada de eventos. Nesta auditoria, o código da Edge Function não pôde ser lido pela conexão disponível, então a idempotência interna do endpoint não é marcada como verificada nesta tela.</p><div className="mt-5 rounded-xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-900"><strong>Estado seguro:</strong> o frontend não cria um segundo fluxo paralelo para o ChatPro. A validação de reenvios, autenticação e deduplicação do webhook deve ser feita diretamente na Edge Function antes de ampliar o comportamento para números desconhecidos.</div></article>

    <article className="rounded-3xl border bg-white p-6 shadow-sm"><CalendarDays className="h-6 w-6 text-teal-700"/><div className="mt-4 flex items-center justify-between gap-3"><h3 className="text-lg font-semibold">Google Agenda</h3><span className="rounded-full bg-emerald-50 px-2.5 py-1 text-xs font-semibold text-emerald-700">ATIVA NO CRM</span></div><p className="mt-2 text-sm text-slate-600">Agenda e Coletas já enviam agendamentos para a função de sincronização do Google Calendar. O CRM preserva o mesmo agendamento interno quando a sincronização externa falha, permitindo nova tentativa sem criar outro registro local.</p><div className="mt-5 rounded-xl border border-emerald-200 bg-emerald-50 p-4 text-sm text-emerald-900"><ShieldCheck className="mb-2 h-4 w-4"/><strong>Idempotência no CRM:</strong> a referência usada para sincronizar é sempre o <code>agendamento_id</code> já salvo. Em Coletas, falha ao vincular um agendamento recém-criado dispara rollback; falha apenas no Google mantém o agendamento para reprocessamento.</div><Link to="/agenda" className="mt-5 inline-flex rounded-xl border px-4 py-2.5 text-sm font-semibold">Abrir Agenda do CRM</Link></article>
  </section>

  <IntegrationHealth/>
</PageShell>}
