import { useEffect, useMemo, useState } from 'react'
import { AlertTriangle, CalendarDays, CheckCircle2, ChevronLeft, ChevronRight, CirclePause, DollarSign, Eye, FilePlus2, Files, LayoutGrid, List, Pencil, RefreshCw, Search, X } from 'lucide-react'
import { PageShell } from '../../components/ui/PageShell'
import { Modal } from '../../components/ui/Modal'
import { UserAvatar } from '../../components/users/UserAvatar'
import { supabase } from '../../services/supabase'
import { useAuth } from '../../hooks/useAuth'

type Contract={id:string;numero_contrato:string|null;cliente_id:string|null;proposta_origem_referencia:string|null;periodicidade:string|null;status:string|null;data_inicio:string|null;data_fim:string|null;external_id:string|null;ativo:boolean;updated_at:string}
type Client={id:string;nome_fantasia:string|null;razao_social:string|null;responsavel_comercial_id:string|null}
type OS={id:string;contrato_id:string|null;data_agendamento:string|null;valor:number|null}
type Proposal={numero_proposta:string|null;valor:number|null;responsavel_comercial_id:string|null}
type Person={id:string;nome:string|null;avatar_url:string|null;ativo:boolean}
type Row=Contract&{client:string;owner:string;ownerAvatar:string|null;ownerInactive:boolean;osCount:number;value:number;next:string|null}
type QueryResult<T>={data:T[]|null;error:{message:string}|null}
const PAGE=10,PAGE_SIZE=1000
async function fetchAll<T>(makeQuery:(from:number,to:number)=>PromiseLike<QueryResult<T>>){const rows:T[]=[];for(let from=0;;from+=PAGE_SIZE){const result=await makeQuery(from,from+PAGE_SIZE-1);if(result.error)return{data:rows,error:result.error};const batch=(result.data??[]) as T[];rows.push(...batch);if(batch.length<PAGE_SIZE)return{data:rows,error:null}}}
const statuses=['PRÉ-CADASTRO','ATIVO','SUSPENSO','ENCERRADO','CANCELADO']
const periods=['ÚNICO','SOB DEMANDA','SEMANAL','QUINZENAL','MENSAL','BIMESTRAL','TRIMESTRAL','SEMESTRAL','ANUAL']
const empty={numero_contrato:'',cliente_id:'',proposta_origem_referencia:'',periodicidade:'MENSAL',status:'PRÉ-CADASTRO',data_inicio:'',data_fim:'',external_id:'',ativo:true}

export function Contratos(){const{hasPermission}=useAuth();const canWrite=hasPermission('crm.write');const[contracts,setContracts]=useState<Contract[]>([]);const[clients,setClients]=useState<Client[]>([]);const[orders,setOrders]=useState<OS[]>([]);const[proposals,setProposals]=useState<Proposal[]>([]);const[people,setPeople]=useState<Person[]>([]);const[query,setQuery]=useState('');const[status,setStatus]=useState('TODOS');const[period,setPeriod]=useState('TODAS');const[expiry,setExpiry]=useState('TODAS');const[owner,setOwner]=useState('TODOS');const[mode,setMode]=useState<'list'|'cards'>('list');const[page,setPage]=useState(1);const[form,setForm]=useState(empty);const[editing,setEditing]=useState<string|null>(null);const[open,setOpen]=useState(false);const[view,setView]=useState<Row|null>(null);const[saving,setSaving]=useState(false);const[error,setError]=useState('')
 async function load(){const[c,cl,o,p,u]=await Promise.all([
  fetchAll<Contract>((from,to)=>supabase.from('contratos').select('id,numero_contrato,cliente_id,proposta_origem_referencia,periodicidade,status,data_inicio,data_fim,external_id,ativo,updated_at').is('deleted_at',null).order('updated_at',{ascending:false}).range(from,to)),
  fetchAll<Client>((from,to)=>supabase.from('clientes').select('id,nome_fantasia,razao_social,responsavel_comercial_id').is('deleted_at',null).order('id',{ascending:true}).range(from,to)),
  fetchAll<OS>((from,to)=>supabase.from('ordens_servico').select('id,contrato_id,data_agendamento,valor').is('deleted_at',null).order('id',{ascending:true}).range(from,to)),
  fetchAll<Proposal>((from,to)=>supabase.from('propostas').select('numero_proposta,valor,responsavel_comercial_id').is('deleted_at',null).order('id',{ascending:true}).range(from,to)),
  fetchAll<Person>((from,to)=>supabase.from('profiles').select('id,nome,avatar_url,ativo').order('nome').range(from,to))
 ]);const e=c.error||cl.error||o.error||p.error||u.error;if(e)setError(e.message);else{setError('');setContracts(c.data);setClients(cl.data);setOrders(o.data);setProposals(p.data);setPeople(u.data)}}
 useEffect(()=>{void load()},[])
 const rows=useMemo<Row[]>(()=>contracts.map(c=>{const client=clients.find(x=>x.id===c.cliente_id);const proposal=proposals.find(p=>p.numero_proposta===c.proposta_origem_referencia);const linked=orders.filter(o=>o.contrato_id===c.id);const last=linked.map(o=>o.data_agendamento).filter(Boolean).sort().at(-1)||c.data_inicio;const responsibleId=proposal?.responsavel_comercial_id||client?.responsavel_comercial_id;const person=people.find(p=>p.id===responsibleId);return{...c,client:client?.nome_fantasia||client?.razao_social||'Cliente não informado',owner:person?.nome||'Sem responsável',ownerAvatar:person?.avatar_url||null,ownerInactive:Boolean(person&&!person.ativo),osCount:linked.length,value:Number(proposal?.valor??linked.reduce((n,o)=>n+Number(o.valor||0),0)),next:nextExecution(last,c.periodicidade)}}),[contracts,clients,orders,proposals,people])
 const filtered=useMemo(()=>rows.filter(r=>`${r.numero_contrato||''} ${r.client} ${r.proposta_origem_referencia||''}`.toLowerCase().includes(query.toLowerCase())&&(status==='TODOS'||normStatus(r.status)===status)&&(period==='TODAS'||r.periodicidade===period)&&(owner==='TODOS'||r.owner===owner)&&matchExpiry(r,expiry)),[rows,query,status,period,owner,expiry]);useEffect(()=>setPage(1),[query,status,period,owner,expiry,mode]);const paged=filtered.slice((page-1)*PAGE,page*PAGE),pages=Math.max(1,Math.ceil(filtered.length/PAGE));const now=new Date();const active=rows.filter(r=>r.ativo&&normStatus(r.status)==='ATIVO').length,pre=rows.filter(r=>normStatus(r.status)==='PRÉ-CADASTRO').length,suspended=rows.filter(r=>normStatus(r.status)==='SUSPENSO').length,expiring=rows.filter(r=>r.ativo&&daysUntil(r.data_fim)>=0&&daysUntil(r.data_fim)<=30).length,revenue=rows.filter(r=>r.ativo&&normStatus(r.status)==='ATIVO').reduce((n,r)=>n+r.value,0),osTotal=filtered.reduce((n,r)=>n+r.osCount,0),noNext=filtered.filter(r=>!r.next&&!noAutomaticForecast(r.periodicidade)).length,renewal=filtered.length?Math.round(filtered.filter(r=>r.ativo&&normStatus(r.status)==='ATIVO').length/filtered.length*100):0,expMonth=filtered.filter(r=>r.data_fim&&new Date(`${r.data_fim}T00:00:00`).getMonth()===now.getMonth()).length
 function startEdit(r?:Row){if(r){setEditing(r.id);setForm({numero_contrato:r.numero_contrato||'',cliente_id:r.cliente_id||'',proposta_origem_referencia:r.proposta_origem_referencia||'',periodicidade:r.periodicidade||'MENSAL',status:normStatus(r.status)||'PRÉ-CADASTRO',data_inicio:r.data_inicio||'',data_fim:r.data_fim||'',external_id:r.external_id||'',ativo:r.ativo})}else{setEditing(null);setForm(empty)}setOpen(true)}
 async function save(e:React.FormEvent){e.preventDefault();if(!form.numero_contrato.trim()){setError('Informe o número do contrato.');return}setSaving(true);const payload={...form,status:normStatus(form.status),cliente_id:form.cliente_id||null,proposta_origem_referencia:form.proposta_origem_referencia||null,data_inicio:form.data_inicio||null,data_fim:form.data_fim||null,external_id:form.external_id||null};const result=editing?await supabase.from('contratos').update(payload).eq('id',editing):await supabase.from('contratos').insert(payload);setSaving(false);if(result.error)setError(result.error.message);else{setOpen(false);await load()}}
 return <PageShell title="Contratos" description="Gestão de vigências, recorrências e continuidade comercial."><section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-5"><Kpi icon={Files} label="Contratos ativos" value={active}/><Kpi icon={FilePlus2} label="Em pré-cadastro" value={pre} blue/><Kpi icon={CalendarDays} label="Vencem em 30 dias" value={expiring} orange/><Kpi icon={CirclePause} label="Suspensos" value={suspended} danger/><Kpi icon={DollarSign} label="Receita contratada" value={money(revenue)}/></section>
 <section className="rounded-3xl border bg-white shadow-sm"><div className="flex flex-wrap items-end gap-3 border-b p-4"><div className="relative min-w-[260px] flex-1"><Search className="absolute left-3 top-3 h-4 w-4 text-slate-400"/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar contrato, cliente ou proposta..." className="w-full rounded-xl border py-2.5 pl-9 pr-3 text-sm"/></div><Filter label="Status" value={status} set={setStatus} options={['TODOS',...statuses]}/><Filter label="Periodicidade" value={period} set={setPeriod} options={['TODAS',...periods]}/><Filter label="Vigência" value={expiry} set={setExpiry} options={['TODAS','VIGENTES','VENCE EM 30 DIAS','VENCIDOS']}/><Filter label="Responsável" value={owner} set={setOwner} options={['TODOS',...Array.from(new Set(rows.map(r=>r.owner)))]}/><button onClick={()=>void load()} className="rounded-xl border p-2.5"><RefreshCw className="h-4 w-4"/></button><div className="flex rounded-xl border p-1"><button onClick={()=>setMode('list')} className={`inline-flex items-center gap-2 rounded-lg px-3 py-2 text-sm ${mode==='list'?'bg-teal-700 text-white':'text-slate-500'}`}><List className="h-4 w-4"/>Lista</button><button onClick={()=>setMode('cards')} className={`inline-flex items-center gap-2 rounded-lg px-3 py-2 text-sm ${mode==='cards'?'bg-teal-700 text-white':'text-slate-500'}`}><LayoutGrid className="h-4 w-4"/>Cards</button></div>{canWrite&&<button onClick={()=>startEdit()} className="rounded-xl bg-teal-700 px-4 py-2.5 text-sm font-semibold text-white">+ Novo contrato</button>}</div>{error&&<div className="m-4 rounded-xl bg-red-50 p-3 text-sm text-red-700">{error}</div>}
 {mode==='list'?<div className="overflow-x-auto"><table className="w-full min-w-[1180px] text-left text-sm"><thead className="bg-slate-50 text-xs uppercase text-slate-500"><tr><th className="px-5 py-3">Contrato / Cliente</th><th>Proposta origem</th><th>Periodicidade</th><th>Vigência</th><th>Próxima execução</th><th>OS geradas</th><th>Status</th><th>Responsável</th><th>Ações</th></tr></thead><tbody className="divide-y">{paged.map(r=><tr key={r.id} className="hover:bg-slate-50"><td className="px-5 py-3"><b>{r.numero_contrato||'Sem número'}</b><div className="text-xs text-slate-500">{r.client}</div></td><td>{r.proposta_origem_referencia||'—'}</td><td><Badge value={r.periodicidade}/></td><td>{date(r.data_inicio)}<div className="text-xs text-slate-500">até {date(r.data_fim)}</div></td><td>{nextText(r)}</td><td><b>{r.osCount}</b></td><td><Status value={r.status}/></td><td><Responsible row={r}/></td><td><div className="flex gap-2"><button onClick={()=>setView(r)} className="rounded-lg border p-2"><Eye className="h-4 w-4"/></button>{canWrite&&<button onClick={()=>startEdit(r)} className="rounded-lg border p-2"><Pencil className="h-4 w-4"/></button>}</div></td></tr>)}</tbody></table></div>:<div className="grid gap-4 p-4 md:grid-cols-2 xl:grid-cols-3">{paged.map(r=><article key={r.id} className="rounded-2xl border p-5"><div className="flex justify-between"><div><b>{r.numero_contrato||'Sem número'}</b><p className="text-sm text-slate-500">{r.client}</p></div><Status value={r.status}/></div><div className="mt-4 grid grid-cols-2 gap-3 text-sm"><Small label="Periodicidade" value={r.periodicidade||'—'}/><Small label="OS geradas" value={String(r.osCount)}/><Small label="Fim da vigência" value={date(r.data_fim)}/><Small label="Próxima execução" value={nextText(r)}/></div><div className="mt-3 rounded-2xl bg-slate-50 p-3"><div className="text-xs text-slate-500">Responsável</div><div className="mt-1"><Responsible row={r}/></div></div><button onClick={()=>setView(r)} className="mt-4 w-full rounded-xl border py-2 text-sm font-semibold text-teal-700">Visualizar</button></article>)}</div>}
 {!filtered.length&&<div className="p-10 text-center text-slate-500">Nenhum contrato encontrado.</div>}<div className="flex items-center justify-between border-t px-5 py-3 text-sm text-slate-500"><span>Mostrando {filtered.length?(page-1)*PAGE+1:0} a {Math.min(page*PAGE,filtered.length)} de {filtered.length}</span><div className="flex items-center gap-2"><button disabled={page===1} onClick={()=>setPage(p=>p-1)} className="rounded-lg border p-2 disabled:opacity-40"><ChevronLeft className="h-4 w-4"/></button><span>{page} / {pages}</span><button disabled={page===pages} onClick={()=>setPage(p=>p+1)} className="rounded-lg border p-2 disabled:opacity-40"><ChevronRight className="h-4 w-4"/></button></div></div><Summary renewal={renewal} expiring={expMonth} noNext={noNext} os={osTotal}/></section>
 <Modal open={open} onClose={()=>setOpen(false)} title={editing?'Editar contrato':'Novo contrato'}><form onSubmit={save} className="grid gap-4 sm:grid-cols-2"><Input label="Nº contrato *" value={form.numero_contrato} set={v=>setForm({...form,numero_contrato:v})}/><SelectField label="Cliente" value={form.cliente_id} set={v=>setForm({...form,cliente_id:v})} options={clients.map(c=>({value:c.id,label:c.nome_fantasia||c.razao_social||'Cliente'}))}/><Input label="Proposta origem" value={form.proposta_origem_referencia} set={v=>setForm({...form,proposta_origem_referencia:v})}/><SelectField label="Periodicidade" value={form.periodicidade} set={v=>setForm({...form,periodicidade:v})} options={periods.map(x=>({value:x,label:x}))}/><SelectField label="Status" value={form.status} set={v=>setForm({...form,status:v})} options={statuses.map(x=>({value:x,label:x}))}/><Input label="ID GerenciaLab" value={form.external_id} set={v=>setForm({...form,external_id:v})}/><Input label="Data início" type="date" value={form.data_inicio} set={v=>setForm({...form,data_inicio:v})}/><Input label="Data fim" type="date" value={form.data_fim} set={v=>setForm({...form,data_fim:v})}/><div className="sm:col-span-2 flex justify-end gap-2"><button type="button" onClick={()=>setOpen(false)} className="rounded-xl border px-4 py-2.5">Cancelar</button><button disabled={saving} className="rounded-xl bg-teal-700 px-5 py-2.5 font-semibold text-white">{saving?'Salvando...':'Salvar contrato'}</button></div></form></Modal>
 {view&&<div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/40 p-4" onMouseDown={e=>{if(e.target===e.currentTarget)setView(null)}}><div className="w-full max-w-2xl rounded-3xl bg-white"><div className="flex justify-between border-b p-6"><div><p className="text-xs font-bold uppercase text-teal-700">Contrato</p><h2 className="text-2xl font-bold">{view.numero_contrato}</h2><p className="text-slate-500">{view.client}</p></div><button onClick={()=>setView(null)} className="rounded-xl border p-2"><X/></button></div><div className="grid gap-3 p-6 sm:grid-cols-3"><Small label="Status" value={normStatus(view.status)||'—'}/><Small label="Periodicidade" value={view.periodicidade||'—'}/><Small label="Proposta" value={view.proposta_origem_referencia||'—'}/><Small label="Vigência" value={`${date(view.data_inicio)} a ${date(view.data_fim)}`}/><Small label="Próxima execução" value={nextText(view)}/><Small label="OS vinculadas" value={String(view.osCount)}/><div className="rounded-2xl bg-slate-50 p-3 sm:col-span-3"><p className="text-xs text-slate-500">Responsável</p><div className="mt-1"><Responsible row={view}/></div></div></div></div></div>}</PageShell>}
function Responsible({row}:{row:Pick<Row,'owner'|'ownerAvatar'|'ownerInactive'>}){return <div className="flex items-center gap-2"><UserAvatar name={row.owner} avatarUrl={row.ownerAvatar} size="sm"/><span>{row.owner}{row.ownerInactive?' (inativo)':''}</span></div>}
function Kpi({icon:Icon,label,value,danger=false,orange=false,blue=false}:{icon:typeof Files;label:string;value:number|string;danger?:boolean;orange?:boolean;blue?:boolean}){return <article className="flex h-20 items-center gap-3 rounded-3xl border bg-white p-4 shadow-sm"><span className={`grid h-11 w-11 shrink-0 place-items-center rounded-full ${danger?'bg-red-50 text-red-600':orange?'bg-orange-50 text-orange-600':blue?'bg-blue-50 text-blue-700':'bg-teal-50 text-teal-700'}`}><Icon className="h-5 w-5"/></span><div className="min-w-0"><p className="text-xs text-slate-500">{label}</p><b className="mt-1 block truncate text-xl text-slate-900">{value}</b></div></article>}
function Filter({label,value,set,options}:{label:string;value:string;set:(v:string)=>void;options:string[]}){return <label><span className="mb-1 block text-xs font-semibold text-slate-500">{label}</span><select value={value} onChange={e=>set(e.target.value)} className="rounded-xl border bg-white px-3 py-2.5 text-sm">{options.map(x=><option key={x}>{x}</option>)}</select></label>}
function Summary({renewal,expiring,noNext,os}:{renewal:number;expiring:number;noNext:number;os:number}){return <div className="border-t p-5"><h3 className="mb-3 font-bold">Resumo de contratos</h3><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><Small label="Taxa de renovação" value={`${renewal}%`}/><Small label="Vencem este mês" value={String(expiring)}/><Small label="Sem próxima execução (quando aplicável)" value={String(noNext)}/><Small label="OS vinculadas" value={String(os)}/></div></div>}
function Small({label,value}:{label:string;value:string}){return <div className="rounded-2xl bg-slate-50 p-3"><p className="text-xs text-slate-500">{label}</p><b>{value}</b></div>}
function normStatus(value:string|null){return (value||'').trim().toLocaleUpperCase('pt-BR')}
function Status({value}:{value:string|null}){const v=normStatus(value)||'SEM STATUS';return <span className={`rounded-full px-2.5 py-1 text-[11px] font-bold ${v==='ATIVO'?'bg-emerald-100 text-emerald-700':v==='SUSPENSO'||v==='CANCELADO'?'bg-red-100 text-red-700':'bg-orange-100 text-orange-700'}`}>{v}</span>}
function Badge({value}:{value:string|null}){return <span className="rounded-full bg-teal-50 px-2.5 py-1 text-[11px] font-bold text-teal-700">{value||'—'}</span>}
function Input({label,value,set,type='text'}:{label:string;value:string;set:(v:string)=>void;type?:string}){return <label><span className="mb-1 block text-sm font-medium">{label}</span><input type={type} value={value} onChange={e=>set(e.target.value)} className="w-full rounded-xl border px-3 py-2.5"/></label>}
function SelectField({label,value,set,options}:{label:string;value:string;set:(v:string)=>void;options:{value:string;label:string}[]}){return <label><span className="mb-1 block text-sm font-medium">{label}</span><select value={value} onChange={e=>set(e.target.value)} className="w-full rounded-xl border bg-white px-3 py-2.5"><option value="">Selecione</option>{options.map(x=><option key={x.value} value={x.value}>{x.label}</option>)}</select></label>}
function date(v:string|null){return v?new Date(`${v.length===10?v+'T00:00:00':v}`).toLocaleDateString('pt-BR'):'—'}
function money(v:number){return v.toLocaleString('pt-BR',{style:'currency',currency:'BRL'})}
function daysUntil(v:string|null){if(!v)return 99999;return Math.ceil((new Date(`${v}T23:59:59`).getTime()-Date.now())/86400000)}
function matchExpiry(r:Row,f:string){if(f==='TODAS')return true;const d=daysUntil(r.data_fim);if(f==='VIGENTES')return d>=0;if(f==='VENCE EM 30 DIAS')return d>=0&&d<=30;return d<0}
function noAutomaticForecast(period:string|null){return period==='SOB DEMANDA'||period==='ÚNICO'}
function nextText(r:Pick<Row,'next'|'periodicidade'>){if(r.periodicidade==='SOB DEMANDA')return 'Sob demanda';if(r.periodicidade==='ÚNICO')return 'Execução única';return date(r.next)}
function nextExecution(base:string|null,period:string|null){if(!base||noAutomaticForecast(period))return null;const d=new Date(base);if(period==='SEMANAL'||period==='QUINZENAL'){const step=period==='SEMANAL'?7:15;while(d.getTime()<Date.now())d.setDate(d.getDate()+step);return d.toISOString()}const months=period==='MENSAL'?1:period==='BIMESTRAL'?2:period==='TRIMESTRAL'?3:period==='SEMESTRAL'?6:period==='ANUAL'?12:0;if(!months)return null;while(d.getTime()<Date.now())d.setMonth(d.getMonth()+months);return d.toISOString()}
