import { useEffect, useMemo, useState } from 'react'
import { FlaskConical, Layers3, Pencil, Plus, Power, Trash2 } from 'lucide-react'
import { PageShell } from '../../components/ui/PageShell'
import { Modal } from '../../components/ui/Modal'
import { supabase } from '../../services/supabase'
import { useAuth } from '../../hooks/useAuth'
import { CustoPreco } from './CustoPreco'

type Tab='grupos'|'servicos'|'parametros'|'parceiros'|'custos'
type Row={id:string;nome?:string;nome_canonico?:string|null;rotulo_original?:string|null;ativo:boolean;preco?:number|null;preco_minimo?:number|null;execucao_padrao?:string|null;laboratorio_parceiro_padrao_id?:string|null;cpf_cnpj?:string|null;contato?:string|null}
type Partner={id:string;nome:string;ativo:boolean}
const money=(v:number|null|undefined)=>v==null?'—':Number(v).toLocaleString('pt-BR',{style:'currency',currency:'BRL'})
const TABS:Tab[]=['grupos','servicos','parametros','parceiros','custos']
const tabLabel=(t:Tab)=>t==='grupos'?'Grupos / tipos de análise':t==='servicos'?'Serviços':t==='parametros'?'Parâmetros':t==='parceiros'?'Rede de laboratórios parceiros':'Custo × Preço'

export function Catalogo(){
 const{hasPermission}=useAuth();const canWrite=hasPermission('crm.write');const[tab,setTab]=useState<Tab>('grupos');const[rows,setRows]=useState<Row[]>([]);const[partners,setPartners]=useState<Partner[]>([]);const[open,setOpen]=useState(false);const[editing,setEditing]=useState<Row|null>(null);const[name,setName]=useState('');const[price,setPrice]=useState('');const[minPrice,setMinPrice]=useState('');const[execution,setExecution]=useState('INTERNA');const[partnerId,setPartnerId]=useState('');const[cpfCnpj,setCpfCnpj]=useState('');const[contact,setContact]=useState('');const[error,setError]=useState('');const[notice,setNotice]=useState('');const[fichaParametroId,setFichaParametroId]=useState<string|null>(null)
 const label=useMemo(()=>tab==='grupos'?'Grupos / tipos de análise':tab==='servicos'?'Serviços':tab==='parametros'?'Parâmetros':'Laboratórios parceiros',[tab])
 async function load(){setError('');if(tab==='custos')return;let q:any;if(tab==='parametros')q=supabase.from('parametros').select('id,nome_canonico,rotulo_original,ativo,preco,preco_minimo,execucao_padrao,laboratorio_parceiro_padrao_id').is('deleted_at',null).order('nome_canonico');else if(tab==='parceiros')q=supabase.from('laboratorios_parceiros').select('id,nome,cpf_cnpj,contato,ativo').is('deleted_at',null).order('nome');else q=supabase.from(tab).select('id,nome,ativo').is('deleted_at',null).order('nome');const{data,error}=await q;if(error)setError(error.message);else setRows((data??[]) as Row[]);const p=await supabase.from('laboratorios_parceiros').select('id,nome,ativo').is('deleted_at',null).eq('ativo',true).order('nome');if(!p.error)setPartners((p.data??[]) as Partner[])}
 useEffect(()=>{void load()},[tab])
 function begin(row?:Row){setEditing(row??null);setName(row?.nome||row?.nome_canonico||'');setPrice(row?.preco==null?'':String(row.preco));setMinPrice(row?.preco_minimo==null?'':String(row.preco_minimo));setExecution(row?.execucao_padrao||'INTERNA');setPartnerId(row?.laboratorio_parceiro_padrao_id||'');setCpfCnpj(row?.cpf_cnpj||'');setContact(row?.contato||'');setNotice('');setError('');setOpen(true)}
 async function save(e:React.FormEvent){e.preventDefault();if(!canWrite||!name.trim())return;const value=name.trim();let payload:any;if(tab==='parametros')payload={nome_canonico:value,rotulo_original:value,preco:price===''?null:Number(price),preco_minimo:minPrice===''?null:Number(minPrice),execucao_padrao:execution,laboratorio_parceiro_padrao_id:execution==='EXTERNA'&&partnerId?partnerId:null,ativo:true};else if(tab==='parceiros')payload={nome:value,cpf_cnpj:cpfCnpj||null,contato:contact||null,ativo:true};else payload={nome:value,ativo:true};const table=tab==='parceiros'?'laboratorios_parceiros':tab;const response=editing?await supabase.from(table).update(payload).eq('id',editing.id):await supabase.from(table).insert(payload);if(response.error)setError(response.error.message);else{setOpen(false);await load()}}
 async function toggle(row:Row){if(!canWrite)return;const table=tab==='parceiros'?'laboratorios_parceiros':tab;const{error}=await supabase.from(table).update({ativo:!row.ativo}).eq('id',row.id);if(error)setError(error.message);else await load()}
 async function remove(row:Row){if(!canWrite)return;setNotice('');if(!confirm(`Excluir ${row.nome||row.nome_canonico}?`))return;if(tab==='parametros'){const a=await supabase.from('amostra_parametros').select('id',{count:'exact',head:true}).eq('parametro_id',row.id).is('deleted_at',null);const c=await supabase.from('catalogo_grupo_parametros').select('id',{count:'exact',head:true}).eq('parametro_id',row.id).is('deleted_at',null);if((a.count??0)>0||(c.count??0)>0){setNotice('Este parâmetro já possui vínculo/histórico e não pode ser excluído. Ele pode ser inativado.');return}}if(tab==='grupos'){const c=await supabase.from('catalogo_grupo_parametros').select('id',{count:'exact',head:true}).eq('grupo_id',row.id).is('deleted_at',null);if((c.count??0)>0){setNotice('Este grupo possui parâmetros vinculados e não pode ser excluído. Ele pode ser inativado.');return}}if(tab==='servicos'){setNotice('Serviços são preservados para histórico. Use Inativar para retirá-los de novos cadastros.');return}const table=tab==='parceiros'?'laboratorios_parceiros':tab;const{error}=await supabase.from(table).update({deleted_at:new Date().toISOString(),ativo:false}).eq('id',row.id);if(error)setError(error.message);else await load()}
 // Ficha de insumos: só existe para execução INTERNA (regra também garantida no banco).
 function abrirFicha(row:Row){setFichaParametroId(row.id);setTab('custos')}
 return <PageShell title="Catálogo técnico/comercial" description="Cadastre grupos, parâmetros, preços, forma de execução e a rede de laboratórios parceiros. Método/LQ/LD continuam registrados no contexto da execução da amostra." action={canWrite&&tab!=='custos'?<button onClick={()=>begin()} className="inline-flex items-center gap-2 rounded-xl bg-teal-700 px-4 py-2.5 text-sm font-semibold text-white"><Plus className="h-4 w-4"/>Novo cadastro</button>:undefined}>
  <div className="flex flex-wrap gap-2">{TABS.map(t=><button key={t} onClick={()=>setTab(t)} className={`rounded-xl px-4 py-2 text-sm font-semibold ${tab===t?'bg-teal-700 text-white':'border bg-white text-slate-600'}`}>{tabLabel(t)}</button>)}</div>
  {tab==='custos'?<CustoPreco canWrite={canWrite} abrirParametroId={fichaParametroId} aoAbrirConsumido={()=>setFichaParametroId(null)}/>:<>
  {tab==='parametros'&&<div className="rounded-2xl border border-teal-100 bg-teal-50 p-4 text-sm text-teal-900"><strong>Importação da tabela:</strong> a planilha de Grupo + Parâmetro + Preço + Preço mínimo será usada somente quando você autorizar a importação. Nenhum dado do modelo enviado foi importado.</div>}
  {notice&&<div className="rounded-xl bg-amber-50 p-3 text-sm text-amber-800">{notice}</div>}{error&&<div className="rounded-xl bg-red-50 p-3 text-sm text-red-700">{error}</div>}
  <section className="rounded-3xl border bg-white shadow-sm"><div className="border-b p-5"><div className="flex items-center gap-2"><Layers3 className="h-5 w-5 text-teal-700"/><h3 className="font-semibold">{label}</h3></div></div><div className="divide-y">{rows.length===0?<div className="p-10 text-center text-sm text-slate-500">Sem registros.</div>:rows.map(r=><div key={r.id} className="flex flex-col gap-3 p-5 md:flex-row md:items-center md:justify-between"><div><div className="font-semibold text-slate-900">{r.nome||r.nome_canonico||r.rotulo_original||'—'}</div>{tab==='parametros'&&<div className="mt-1 text-sm text-slate-500">Preço: {money(r.preco)} · mínimo: {money(r.preco_minimo)} · execução: {r.execucao_padrao||'INTERNA'}{r.laboratorio_parceiro_padrao_id?` · parceiro: ${partners.find(p=>p.id===r.laboratorio_parceiro_padrao_id)?.nome||'cadastrado'}`:''}</div>}{tab==='parceiros'&&<div className="mt-1 text-sm text-slate-500">{[r.cpf_cnpj,r.contato].filter(Boolean).join(' · ')||'Sem dados complementares'}</div>}</div><div className="flex items-center gap-2">{tab==='parametros'&&((r.execucao_padrao||'INTERNA').toUpperCase()==='INTERNA'?<button onClick={()=>abrirFicha(r)} title="Insumos consumidos por análise e custo" className="inline-flex items-center gap-1.5 rounded-lg border px-2.5 py-1.5 text-xs font-semibold text-teal-700"><FlaskConical className="h-4 w-4"/>Insumos</button>:<span title="A ficha de insumos só vale para execução interna" className="rounded-full bg-slate-100 px-2.5 py-1 text-xs text-slate-500">Externa: sem ficha</span>)}<span className={`rounded-full px-2.5 py-1 text-xs font-semibold ${r.ativo?'bg-emerald-50 text-emerald-700':'bg-slate-100 text-slate-500'}`}>{r.ativo?'ATIVO':'INATIVO'}</span>{canWrite&&<><button onClick={()=>begin(r)} title="Editar" className="rounded-lg border p-2 text-slate-600"><Pencil className="h-4 w-4"/></button><button onClick={()=>void toggle(r)} title={r.ativo?'Inativar':'Ativar'} className="rounded-lg border p-2 text-slate-600"><Power className="h-4 w-4"/></button><button onClick={()=>void remove(r)} title="Excluir" className="rounded-lg border p-2 text-red-600"><Trash2 className="h-4 w-4"/></button></>}</div></div>)}</div></section>
  </>}
  <Modal open={open} onClose={()=>setOpen(false)} title={`${editing?'Editar':'Novo'} ${tab==='grupos'?'grupo':tab==='servicos'?'serviço':tab==='parametros'?'parâmetro':'laboratório parceiro'}`}><form onSubmit={save} className="space-y-4"><label><span className="mb-1 block text-sm font-medium">Nome</span><input required value={name} onChange={e=>setName(e.target.value)} className="w-full rounded-xl border px-3 py-2.5"/></label>{tab==='parametros'&&<><div className="grid grid-cols-2 gap-3"><label><span className="mb-1 block text-sm font-medium">Preço</span><input type="number" step="0.01" value={price} onChange={e=>setPrice(e.target.value)} className="w-full rounded-xl border px-3 py-2.5"/></label><label><span className="mb-1 block text-sm font-medium">Preço mínimo</span><input type="number" step="0.01" value={minPrice} onChange={e=>setMinPrice(e.target.value)} className="w-full rounded-xl border px-3 py-2.5"/></label></div><label><span className="mb-1 block text-sm font-medium">Execução padrão</span><select value={execution} onChange={e=>setExecution(e.target.value)} className="w-full rounded-xl border px-3 py-2.5"><option value="INTERNA">Interna — MinasLab</option><option value="EXTERNA">Externa — laboratório parceiro</option></select></label>{execution==='EXTERNA'&&editing&&(editing.execucao_padrao||'INTERNA').toUpperCase()==='INTERNA'&&<p className="rounded-xl bg-amber-50 p-3 text-xs text-amber-800">Ao passar para externa, a ficha de insumos deste parâmetro deixa de valer no custo (fica guardada e volta a valer se ele voltar a ser interno).</p>}{execution==='EXTERNA'&&<label><span className="mb-1 block text-sm font-medium">Laboratório parceiro padrão</span><select value={partnerId} onChange={e=>setPartnerId(e.target.value)} className="w-full rounded-xl border px-3 py-2.5"><option value="">Selecione</option>{partners.map(p=><option key={p.id} value={p.id}>{p.nome}</option>)}</select></label>}</>}{tab==='parceiros'&&<><label><span className="mb-1 block text-sm font-medium">CNPJ/CPF</span><input value={cpfCnpj} onChange={e=>setCpfCnpj(e.target.value)} className="w-full rounded-xl border px-3 py-2.5"/></label><label><span className="mb-1 block text-sm font-medium">Contato</span><input value={contact} onChange={e=>setContact(e.target.value)} className="w-full rounded-xl border px-3 py-2.5"/></label></>}<div className="flex justify-end gap-2"><button type="button" onClick={()=>setOpen(false)} className="rounded-xl border px-4 py-2.5">Cancelar</button><button className="rounded-xl bg-teal-700 px-4 py-2.5 font-semibold text-white">Salvar</button></div></form></Modal>
 </PageShell>
}
