import { useEffect, useMemo, useState } from 'react'
import { ArrowLeft, Plus, Trash2 } from 'lucide-react'
import { Link, useParams } from 'react-router-dom'
import { PageShell } from '../../components/ui/PageShell'
import { Modal } from '../../components/ui/Modal'
import { TimelinePanel } from '../../components/timeline/TimelinePanel'
import { supabase } from '../../services/supabase'
import { useAuth } from '../../hooks/useAuth'
import { formatValue } from '../../lib/format'

type Proposal={id:string;numero_proposta:string|null;valor:number|null;status:string|null;validade:string|null;cliente_id:string;oportunidade_id:string;observacoes:string|null;clientes?:{razao_social:string|null;nome_fantasia:string|null}|null;oportunidades?:{titulo:string}|null}
type Item={id:string;descricao:string|null;quantidade:number|null;valor_unitario:number|null;valor_total:number|null;ordem:number|null}
type Lab={id:string;nome:string;ativo:boolean}
type Group={id:string;nome:string;ativo:boolean}
export function PropostaDetalhe(){
  const {id}=useParams(); const {profile,hasPermission}=useAuth(); const canWrite=hasPermission('crm.write'); const canDeactivate=hasPermission('crm.deactivate'); const [proposal,setProposal]=useState<Proposal|null>(null);const[items,setItems]=useState<Item[]>([]);const[labs,setLabs]=useState<Lab[]>([]);const[selectedLabs,setSelectedLabs]=useState<string[]>([]);const[groups,setGroups]=useState<Group[]>([]);const[selectedGroups,setSelectedGroups]=useState<string[]>([]);const[open,setOpen]=useState(false);const[form,setForm]=useState({descricao:'',quantidade:'1',valor_unitario:''});const[error,setError]=useState('');const[savingLabs,setSavingLabs]=useState(false);const[savingGroups,setSavingGroups]=useState(false)
  async function load(){if(!id)return;const [{data:p,error:e1},{data:i,error:e2},{data:l,error:e3},{data:pl,error:e4},{data:g,error:e5},{data:pg,error:e6}]=await Promise.all([supabase.from('propostas').select('id,numero_proposta,valor,status,validade,cliente_id,oportunidade_id,observacoes,clientes(razao_social,nome_fantasia),oportunidades(titulo)').eq('id',id).single(),supabase.from('itens_proposta').select('id,descricao,quantidade,valor_unitario,valor_total,ordem').eq('proposta_id',id).is('deleted_at',null).order('ordem',{ascending:true}),supabase.from('laboratorios_parceiros').select('id,nome,ativo').eq('ativo',true).is('deleted_at',null).order('nome'),supabase.from('proposta_laboratorios').select('laboratorio_id').eq('proposta_id',id),supabase.from('grupos').select('id,nome,ativo').eq('ativo',true).order('nome'),supabase.from('proposta_grupos').select('grupo_id').eq('proposta_id',id)]);if(e1||e2||e3||e4||e5||e6)setError(e1?.message||e2?.message||e3?.message||e4?.message||e5?.message||e6?.message||'Erro');else{setProposal(p as unknown as Proposal);setItems((i??[]) as Item[]);setLabs((l??[]) as Lab[]);setSelectedLabs((pl??[]).map(x=>String(x.laboratorio_id)));setGroups((g??[]) as Group[]);setSelectedGroups((pg??[]).map(x=>String(x.grupo_id)))}}
  useEffect(()=>{void load()},[id])
  const total=useMemo(()=>items.reduce((s,i)=>s+Number(i.valor_total??0),0),[items])
  async function add(e:React.FormEvent){e.preventDefault();if(!canWrite||!id)return;const q=Number(form.quantidade||0),u=Number(form.valor_unitario||0);const {error}=await supabase.from('itens_proposta').insert({proposta_id:id,descricao:form.descricao||null,quantidade:q,valor_unitario:u,valor_total:q*u,ordem:items.length+1,created_by:profile?.id??null});if(error)setError(error.message);else{setForm({descricao:'',quantidade:'1',valor_unitario:''});setOpen(false);await load()}}
  async function remove(itemId:string){if(!canDeactivate)return;const {error}=await supabase.from('itens_proposta').update({deleted_at:new Date().toISOString(),deleted_by:profile?.id??null}).eq('id',itemId);if(error)setError(error.message);else await load()}
  function toggleLab(labId:string){setSelectedLabs(current=>current.includes(labId)?current.filter(x=>x!==labId):[...current,labId])}
  async function saveLabs(){if(!canWrite||!id)return;setSavingLabs(true);setError('');const del=await supabase.from('proposta_laboratorios').delete().eq('proposta_id',id);if(del.error){setError(del.error.message);setSavingLabs(false);return}if(selectedLabs.length){const ins=await supabase.from('proposta_laboratorios').insert(selectedLabs.map(laboratorio_id=>({proposta_id:id,laboratorio_id})));if(ins.error)setError(ins.error.message)}setSavingLabs(false)}
  function toggleGroup(groupId:string){setSelectedGroups(current=>current.includes(groupId)?current.filter(x=>x!==groupId):[...current,groupId])}
  async function saveGroups(){if(!canWrite||!id)return;setSavingGroups(true);setError('');const del=await supabase.from('proposta_grupos').delete().eq('proposta_id',id);if(del.error){setError(del.error.message);setSavingGroups(false);return}if(selectedGroups.length){const ins=await supabase.from('proposta_grupos').insert(selectedGroups.map(grupo_id=>({proposta_id:id,grupo_id})));if(ins.error)setError(ins.error.message)}setSavingGroups(false)}
  return <PageShell title={proposal?.numero_proposta?`Proposta ${proposal.numero_proposta}`:'Detalhes da proposta'} description="Negociação comercial, escopo analítico, laboratórios envolvidos, itens e histórico de relacionamento." action={<Link to="/propostas" className="inline-flex items-center gap-2 rounded-xl border border-slate-200 bg-white px-4 py-2.5 text-sm font-semibold text-slate-600"><ArrowLeft className="h-4 w-4"/>Voltar</Link>}>
    {error&&<div className="rounded-xl border border-red-200 bg-red-50 p-3 text-sm text-red-700">{error}</div>}
    {proposal&&<section className="grid gap-4 md:grid-cols-2 xl:grid-cols-4"><Card label="Cliente" value={proposal.clientes?.nome_fantasia||proposal.clientes?.razao_social||'—'}/><Card label="Oportunidade" value={proposal.oportunidades?.titulo||'—'}/><Card label="Status" value={proposal.status||'—'}/><Card label="Valor da proposta" value={formatValue(proposal.valor,'currency')}/></section>}
    <section className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><h3 className="font-semibold text-slate-900">Escopo Analítico</h3><p className="mt-1 text-sm text-slate-500">Selecione os grupos/tipos de análise que fazem parte do escopo da proposta.</p></div>{canWrite&&<button onClick={()=>void saveGroups()} disabled={savingGroups} className="rounded-xl bg-teal-700 px-4 py-2.5 text-sm font-semibold text-white disabled:opacity-50">{savingGroups?'Salvando...':'Salvar escopo'}</button>}</div>{selectedGroups.length===0&&<div className="mt-4 rounded-xl bg-amber-50 p-3 text-sm text-amber-800">Escopo ainda não cadastrado nesta proposta. O histórico importado não possui vínculo de grupos suficiente para preencher isso automaticamente com segurança.</div>}<div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{groups.map(g=><label key={g.id} className={`flex cursor-pointer items-center gap-3 rounded-2xl border p-4 ${selectedGroups.includes(g.id)?'border-teal-500 bg-teal-50':'border-slate-200'}`}><input type="checkbox" disabled={!canWrite} checked={selectedGroups.includes(g.id)} onChange={()=>toggleGroup(g.id)} className="h-5 w-5 rounded border-slate-300 text-teal-700"/><span className="font-semibold text-slate-800">{g.nome}</span></label>)}</div></section>
    <section className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><h3 className="font-semibold text-slate-900">Rede de Laboratórios Parceiros</h3><p className="mt-1 text-sm text-slate-500">Assinale todos os laboratórios que participarão desta proposta. É permitido selecionar mais de um.</p></div>{canWrite&&<button onClick={()=>void saveLabs()} disabled={savingLabs} className="rounded-xl bg-teal-700 px-4 py-2.5 text-sm font-semibold text-white disabled:opacity-50">{savingLabs?'Salvando...':'Salvar laboratórios'}</button>}</div><div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{labs.map(l=><label key={l.id} className={`flex cursor-pointer items-center gap-3 rounded-2xl border p-4 ${selectedLabs.includes(l.id)?'border-teal-500 bg-teal-50':'border-slate-200'}`}><input type="checkbox" disabled={!canWrite} checked={selectedLabs.includes(l.id)} onChange={()=>toggleLab(l.id)} className="h-5 w-5 rounded border-slate-300 text-teal-700"/><span className="font-semibold text-slate-800">{l.nome}</span></label>)}</div></section>
    <section className="rounded-3xl border border-slate-200 bg-white shadow-sm"><div className="flex items-center justify-between border-b border-slate-100 p-5"><div><h3 className="font-semibold text-slate-900">Itens da proposta</h3><p className="text-sm text-slate-500">Serviços e itens comerciais vinculados à negociação.</p></div>{canWrite&&<button onClick={()=>setOpen(true)} className="inline-flex items-center gap-2 rounded-xl bg-teal-700 px-4 py-2.5 text-sm font-semibold text-white"><Plus className="h-4 w-4"/>Adicionar item</button>}</div><div className="overflow-x-auto"><table className="min-w-full text-sm"><thead className="bg-slate-50 text-left text-xs uppercase text-slate-500"><tr><th className="px-5 py-3">Descrição</th><th className="px-5 py-3">Qtd.</th><th className="px-5 py-3">Unitário</th><th className="px-5 py-3">Total</th><th className="px-5 py-3"></th></tr></thead><tbody className="divide-y divide-slate-100">{items.length===0?<tr><td colSpan={5} className="px-5 py-10 text-center text-slate-500">Sem itens.</td></tr>:items.map(i=><tr key={i.id}><td className="px-5 py-4">{i.descricao||'—'}</td><td className="px-5 py-4">{i.quantidade??'—'}</td><td className="px-5 py-4">{formatValue(i.valor_unitario,'currency')}</td><td className="px-5 py-4 font-semibold">{formatValue(i.valor_total,'currency')}</td><td className="px-5 py-4 text-right">{canDeactivate&&<button onClick={()=>void remove(i.id)} className="rounded-lg border p-2 text-slate-500 hover:bg-red-50 hover:text-red-600"><Trash2 className="h-4 w-4"/></button>}</td></tr>)}</tbody><tfoot><tr><td colSpan={3} className="px-5 py-4 text-right font-semibold text-slate-600">Total calculado</td><td className="px-5 py-4 font-bold text-slate-900">{formatValue(total,'currency')}</td><td/></tr></tfoot></table></div></section>
    {id&&proposal&&<TimelinePanel proposalId={id} opportunityId={proposal.oportunidade_id} clientId={proposal.cliente_id}/>}<Modal open={open} onClose={()=>setOpen(false)} title="Adicionar item à proposta"><form onSubmit={add} className="grid gap-4 sm:grid-cols-2"><label className="sm:col-span-2"><span className="mb-1 block text-sm font-medium">Descrição</span><input value={form.descricao} onChange={e=>setForm({...form,descricao:e.target.value})} className="w-full rounded-xl border px-3 py-2.5"/></label><label><span className="mb-1 block text-sm font-medium">Quantidade</span><input type="number" step="0.01" value={form.quantidade} onChange={e=>setForm({...form,quantidade:e.target.value})} className="w-full rounded-xl border px-3 py-2.5"/></label><label><span className="mb-1 block text-sm font-medium">Valor unitário</span><input type="number" step="0.01" value={form.valor_unitario} onChange={e=>setForm({...form,valor_unitario:e.target.value})} className="w-full rounded-xl border px-3 py-2.5"/></label><div className="sm:col-span-2 flex justify-end gap-2"><button type="button" onClick={()=>setOpen(false)} className="rounded-xl border px-4 py-2">Cancelar</button><button className="rounded-xl bg-teal-700 px-4 py-2 font-semibold text-white">Salvar</button></div></form></Modal>
  </PageShell>
}
function Card({label,value}:{label:string;value:string}){return <article className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm"><div className="text-xs font-semibold uppercase tracking-wide text-slate-400">{label}</div><div className="mt-2 text-lg font-semibold text-slate-900">{value}</div></article>}
