import http from 'node:http';
import https from 'node:https';
import { Buffer } from 'node:buffer';
import forge from 'node-forge';

const PORT=Number(process.env.PORT||8080), HOST=process.env.HOST||'0.0.0.0';
const TOKEN=String(process.env.NFSE_GATEWAY_TOKEN||'');
const AMBIENTE=String(process.env.MLAB_NFSE_AMBIENTE||'HOMOLOGACAO').toUpperCase();
const PRODUCAO_LIBERADA=String(process.env.MLAB_NFSE_PRODUCAO_LIBERADA||'').toUpperCase()==='SIM';
const TRANSMISSAO_ATIVA=String(process.env.MLAB_NFSE_TRANSMISSAO_ATIVA||'').toUpperCase()==='SIM';
const PFX_B64=String(process.env.MLAB_NFSE_CERT_PFX_B64||'').replace(/\s/g,'');
const PFX_PASSWORD=String(process.env.MLAB_NFSE_CERT_PASSWORD||'');
const SEFIN={HOMOLOGACAO:{hostname:'sefin.producaorestrita.nfse.gov.br',basePath:'/SefinNacional'},PRODUCAO:{hostname:'sefin.nfse.gov.br',basePath:'/SefinNacional'}};
const DANFSE={HOMOLOGACAO:{hostname:'adn.producaorestrita.nfse.gov.br',basePath:'/danfse'},PRODUCAO:{hostname:'adn.nfse.gov.br',basePath:'/danfse'}};
let A1_CACHE=null;
function json(res,status,body){const data=Buffer.from(JSON.stringify(body));res.writeHead(status,{'content-type':'application/json; charset=utf-8','content-length':data.length,'cache-control':'no-store'});res.end(data)}
function autorizado(req){return !!TOKEN&&String(req.headers.authorization||'')===`Bearer ${TOKEN}`}
function abrirA1(){if(A1_CACHE)return A1_CACHE;if(!PFX_B64||!PFX_PASSWORD)throw new Error('Certificado A1 não configurado no gateway.');const bin=Buffer.from(PFX_B64,'base64').toString('binary');const asn1=forge.asn1.fromDer(forge.util.createBuffer(bin,'raw'));const p12=forge.pkcs12.pkcs12FromAsn1(asn1,false,PFX_PASSWORD);const certs=(p12.getBags({bagType:forge.pki.oids.certBag})[forge.pki.oids.certBag]||[]).map(x=>x.cert).filter(Boolean);const sh=p12.getBags({bagType:forge.pki.oids.pkcs8ShroudedKeyBag})[forge.pki.oids.pkcs8ShroudedKeyBag]||[];const pl=p12.getBags({bagType:forge.pki.oids.keyBag})[forge.pki.oids.keyBag]||[];const key=[...sh,...pl].find(x=>x.key)?.key;if(!certs.length||!key)throw new Error('Certificado/chave privada não encontrados dentro do PFX.');A1_CACHE={cert:certs.map(c=>forge.pki.certificateToPem(c)).join('\n'),key:forge.pki.privateKeyToPem(key)};return A1_CACHE}
function configuracao(){const erros=[];if(!TOKEN)erros.push('NFSE_GATEWAY_TOKEN ausente');if(!PFX_B64)erros.push('MLAB_NFSE_CERT_PFX_B64 ausente');if(!PFX_PASSWORD)erros.push('MLAB_NFSE_CERT_PASSWORD ausente');if(!SEFIN[AMBIENTE])erros.push('MLAB_NFSE_AMBIENTE inválido');let certificadoValido=false;if(PFX_B64&&PFX_PASSWORD){try{abrirA1();certificadoValido=true}catch(e){erros.push(e instanceof Error?e.message:String(e))}}return{ok:erros.length===0,erros,certificadoValido}}
function agenteMtls(){const a1=abrirA1();return new https.Agent({cert:a1.cert,key:a1.key,keepAlive:false,maxCachedSessions:0,minVersion:'TLSv1.2',ALPNProtocols:['http/1.1']})}
function requestHttps({hostname,method,path,body=null,headers={},mtls=true,timeout=30000}){const agent=mtls?agenteMtls():undefined,payload=body==null?null:Buffer.from(body);return new Promise((resolve,reject)=>{const req=https.request({hostname,port:443,path,method,agent,servername:hostname,rejectUnauthorized:true,timeout,headers:{accept:'*/*','user-agent':'MinasLab-NFSe-Gateway/1.4',connection:'close',...(payload?{'content-length':payload.length}:{}),...headers}},resp=>{const chunks=[];resp.on('data',c=>chunks.push(c));resp.on('end',()=>{if(agent)agent.destroy();const bytes=Buffer.concat(chunks),ct=String(resp.headers['content-type']||'');let bodyOut=bytes;if(ct.includes('json')){const raw=bytes.toString('utf8');try{bodyOut=raw?JSON.parse(raw):null}catch{bodyOut=raw}}resolve({status:resp.statusCode||0,headers:resp.headers,body:bodyOut,bytes})})});req.on('timeout',()=>req.destroy(new Error('Timeout ao conectar ao Sistema Nacional NFS-e.')));req.on('error',err=>{if(agent)agent.destroy();reject(err)});if(payload)req.write(payload);req.end()})}
function requestSefin({method,path,body=null,headers={}}){const alvo=SEFIN[AMBIENTE];if(!alvo)throw new Error(`Ambiente ${AMBIENTE} não suportado.`);return requestHttps({hostname:alvo.hostname,method,path:`${alvo.basePath}${path}`,body,headers,mtls:true})}
async function lerJson(req){const chunks=[];let total=0;for await(const chunk of req){total+=chunk.length;if(total>4*1024*1024)throw new Error('Corpo da requisição excede 4 MB.');chunks.push(chunk)}return chunks.length?JSON.parse(Buffer.concat(chunks).toString('utf8')):{}}
function bloqueioProducao(){if(AMBIENTE!=='PRODUCAO')return `Gateway está em ${AMBIENTE}; produção não pode ser usada.`;if(!PRODUCAO_LIBERADA)return'Produção não liberada no gateway.';if(!TRANSMISSAO_ATIVA)return'Transmissão de produção não ativada no gateway.';return null}
async function emitir({idDps,dpsXmlGZipB64,producao}){if(!idDps)return{status:400,body:{erro:'idDps é obrigatório.',transmitiu:false}};if(!dpsXmlGZipB64||typeof dpsXmlGZipB64!=='string')return{status:400,body:{erro:'dpsXmlGZipB64 é obrigatório.',transmitiu:false}};const pre=await requestSefin({method:'HEAD',path:`/dps/${encodeURIComponent(String(idDps))}`});if(pre.status===200){const consulta=await requestSefin({method:'GET',path:`/dps/${encodeURIComponent(String(idDps))}`});return{status:409,body:{ok:false,ambiente:AMBIENTE,statusHead:pre.status,existeDpsNoSefin:true,transmitiu:false,chaveAcessoExistente:consulta?.body?.chaveAcesso||null,erro:'A DPS já existe na SEFIN. POST bloqueado para evitar duplicidade.'}}}if(pre.status!==404)return{status:409,body:{ok:false,ambiente:AMBIENTE,statusHead:pre.status,transmitiu:false,erro:`Pré-checagem da SEFIN retornou HTTP ${pre.status}; transmissão bloqueada.`}};const r=await requestSefin({method:'POST',path:'/nfse',body:JSON.stringify({dpsXmlGZipB64}),headers:{'content-type':'application/json; charset=utf-8',accept:'application/json'}});return{status:200,body:{ok:r.status>=200&&r.status<300,ambiente:AMBIENTE,statusHttp:r.status,statusHead:pre.status,transmitiu:true,producao,resposta:r.body}}}
async function registrarEvento(chave,pedidoRegistroEventoXmlGZipB64){if(!/^\d{50}$/.test(String(chave||'')))return{status:400,body:{erro:'Chave de acesso inválida.',transmitiu:false}};if(!pedidoRegistroEventoXmlGZipB64||typeof pedidoRegistroEventoXmlGZipB64!=='string')return{status:400,body:{erro:'pedidoRegistroEventoXmlGZipB64 é obrigatório.',transmitiu:false}};const r=await requestSefin({method:'POST',path:`/nfse/${encodeURIComponent(chave)}/eventos`,body:JSON.stringify({pedidoRegistroEventoXmlGZipB64}),headers:{'content-type':'application/json; charset=utf-8',accept:'application/json'}});return{status:200,body:{ok:r.status>=200&&r.status<300,ambiente:AMBIENTE,statusHttp:r.status,transmitiu:true,resposta:r.body}}}
async function handle(req,res){
 if(req.method==='GET'&&req.url==='/health'){const c=configuracao();return json(res,c.ok?200:503,{ok:c.ok,ambiente:AMBIENTE,certificadoConfigurado:Boolean(PFX_B64&&PFX_PASSWORD),certificadoValido:c.certificadoValido,tokenConfigurado:Boolean(TOKEN),producaoLiberada:PRODUCAO_LIBERADA,transmissaoAtiva:TRANSMISSAO_ATIVA,producaoPronta:AMBIENTE==='PRODUCAO'&&PRODUCAO_LIBERADA&&TRANSMISSAO_ATIVA,erros:c.erros})}
 if(!autorizado(req))return json(res,401,{erro:'Não autorizado.'});
 if(req.method==='POST'&&req.url==='/v1/testar-conexao'){if(AMBIENTE!=='HOMOLOGACAO')return json(res,409,{erro:'Teste bloqueado fora de HOMOLOGAÇÃO.'});try{const{idDps}=await lerJson(req);const r=await requestSefin({method:'HEAD',path:`/dps/${encodeURIComponent(String(idDps||''))}`});return json(res,200,{ok:true,ambiente:AMBIENTE,statusHttp:r.status,existeDpsNoSefin:r.status===200,transmitiu:false})}catch(e){return json(res,502,{erro:e instanceof Error?e.message:String(e)})}}
 if(req.method==='POST'&&req.url==='/v1/emitir-homologacao'){if(AMBIENTE!=='HOMOLOGACAO')return json(res,409,{erro:'Transmissão de homologação bloqueada fora de HOMOLOGAÇÃO.',transmitiu:false});try{const r=await emitir({...await lerJson(req),producao:false});return json(res,r.status,r.body)}catch(e){return json(res,502,{erro:e instanceof Error?e.message:String(e),transmitiu:false})}}
 if(req.method==='POST'&&req.url==='/v1/emitir'){const b=bloqueioProducao();if(b)return json(res,423,{erro:b,transmitiu:false});try{const r=await emitir({...await lerJson(req),producao:true});return json(res,r.status,r.body)}catch(e){return json(res,502,{erro:e instanceof Error?e.message:String(e),transmitiu:false})}}
 const mEvento=req.method==='POST'&&req.url?.match(/^\/v1\/nfse\/([0-9]{50})\/eventos$/);if(mEvento){const b=bloqueioProducao();if(b)return json(res,423,{erro:b,transmitiu:false});try{const dados=await lerJson(req);const r=await registrarEvento(mEvento[1],dados.pedidoRegistroEventoXmlGZipB64);return json(res,r.status,r.body)}catch(e){return json(res,502,{erro:e instanceof Error?e.message:String(e),transmitiu:false})}}
 const mEventos=req.method==='GET'&&req.url?.match(/^\/v1\/nfse\/([0-9]{50})\/eventos(?:\/([0-9]{6})(?:\/([0-9]{1,3}))?)?$/);if(mEventos){const b=AMBIENTE==='PRODUCAO'?bloqueioProducao():null;if(b)return json(res,423,{erro:b});try{let path=`/nfse/${mEventos[1]}/eventos`;if(mEventos[2])path+=`/${mEventos[2]}`;if(mEventos[3])path+=`/${mEventos[3]}`;const r=await requestSefin({method:'GET',path,headers:{accept:'application/json'}});return json(res,r.status>=200&&r.status<300?200:502,{ok:r.status>=200&&r.status<300,ambiente:AMBIENTE,statusHttp:r.status,resposta:r.body})}catch(e){return json(res,502,{erro:e instanceof Error?e.message:String(e)})}}
 const mConsulta=req.method==='GET'&&req.url?.match(/^\/v1\/consultar-nfse\/([0-9]{50})$/);if(mConsulta){try{const r=await requestSefin({method:'GET',path:`/nfse/${mConsulta[1]}`,headers:{accept:'application/json'}});return json(res,r.status>=200&&r.status<300?200:502,{ok:r.status>=200&&r.status<300,ambiente:AMBIENTE,statusHttp:r.status,chaveAcesso:mConsulta[1],resposta:r.body})}catch(e){return json(res,502,{erro:e instanceof Error?e.message:String(e)})}}
 const mDanfse=req.method==='GET'&&req.url?.match(/^\/v1\/danfse\/([0-9]{50})$/);if(mDanfse){try{const alvo=DANFSE[AMBIENTE];let r=await requestHttps({hostname:alvo.hostname,method:'GET',path:`${alvo.basePath}/${mDanfse[1]}`,headers:{accept:'application/pdf'},mtls:false});if(r.status===401||r.status===403)r=await requestHttps({hostname:alvo.hostname,method:'GET',path:`${alvo.basePath}/${mDanfse[1]}`,headers:{accept:'application/pdf'},mtls:true});const ct=String(r.headers?.['content-type']||'');if(r.status<200||r.status>=300||!ct.toLowerCase().includes('pdf'))return json(res,502,{erro:`DANFSe não disponível. HTTP ${r.status}.`});return json(res,200,{ok:true,mime:'application/pdf',pdfBase64:r.bytes.toString('base64'),tamanho:r.bytes.length})}catch(e){return json(res,502,{erro:e instanceof Error?e.message:String(e)})}}
 return json(res,404,{erro:'Rota não encontrada.'});
}
const server=http.createServer((req,res)=>{handle(req,res).catch(e=>json(res,500,{erro:e instanceof Error?e.message:String(e)}))});server.listen(PORT,HOST,()=>console.log(`MinasLab NFSe Gateway ativo em ${HOST}:${PORT} (${AMBIENTE})`));
