alter table public.categorias_financeiras
  add column if not exists fluxo text,
  add column if not exists agrupamento text,
  add column if not exists grupo text,
  add column if not exists ordem_plano integer,
  add column if not exists origem_plano text;

create index if not exists idx_categorias_financeiras_plano
  on public.categorias_financeiras (empresa_id, fluxo, agrupamento, grupo, ordem_plano);

create temporary table _plano_contas_import (
  ordem integer not null,
  nome text not null,
  tipo text not null,
  fluxo text not null,
  agrupamento text not null,
  grupo text not null
) on commit drop;

insert into _plano_contas_import (ordem,nome,tipo,fluxo,agrupamento,grupo) values
(1,'SERVIÇO 01','RECEITA','01. FLUXO OPERACIONAL','01. RECEITA LÍQUIDA','01. RECEITA'),
(2,'SERVIÇO 02','RECEITA','01. FLUXO OPERACIONAL','01. RECEITA LÍQUIDA','01. RECEITA'),
(3,'SERVIÇO 03','RECEITA','01. FLUXO OPERACIONAL','01. RECEITA LÍQUIDA','01. RECEITA'),
(4,'SERVIÇOS REALIZADOS','RECEITA','01. FLUXO OPERACIONAL','01. RECEITA LÍQUIDA','01. RECEITA'),
(5,'COFINS','DESPESA','01. FLUXO OPERACIONAL','01. RECEITA LÍQUIDA','02. IMPOSTO SOBRE RECEITA'),
(6,'ISS','DESPESA','01. FLUXO OPERACIONAL','01. RECEITA LÍQUIDA','02. IMPOSTO SOBRE RECEITA'),
(7,'PIS','DESPESA','01. FLUXO OPERACIONAL','01. RECEITA LÍQUIDA','02. IMPOSTO SOBRE RECEITA'),
(8,'SIMPLES NACIONAL','DESPESA','01. FLUXO OPERACIONAL','01. RECEITA LÍQUIDA','02. IMPOSTO SOBRE RECEITA'),
(9,'ADIANTAMENTO A FORNECEDORES','DESPESA','01. FLUXO OPERACIONAL','02. CUSTOS E DESPESAS','01. CUSTOS'),
(10,'COMPRA DE SERVIÇOS','DESPESA','01. FLUXO OPERACIONAL','02. CUSTOS E DESPESAS','01. CUSTOS'),
(11,'COMPRAS DE MATERIA PRIMA','DESPESA','01. FLUXO OPERACIONAL','02. CUSTOS E DESPESAS','01. CUSTOS'),
(12,'ADIANTAMENTO','DESPESA','01. FLUXO OPERACIONAL','02. CUSTOS E DESPESAS','02. DESPESAS'),
(13,'ALUGUEL','DESPESA','01. FLUXO OPERACIONAL','02. CUSTOS E DESPESAS','02. DESPESAS'),
(14,'BENEFÍCIOS','DESPESA','01. FLUXO OPERACIONAL','02. CUSTOS E DESPESAS','02. DESPESAS'),
(15,'COMISSÃO','DESPESA','01. FLUXO OPERACIONAL','02. CUSTOS E DESPESAS','02. DESPESAS'),
(16,'COMUNICAÇÃO E INTERNET','DESPESA','01. FLUXO OPERACIONAL','02. CUSTOS E DESPESAS','02. DESPESAS'),
(17,'CONSULTORIA ,TREINAMENTOS E AUDITORIAS','DESPESA','01. FLUXO OPERACIONAL','02. CUSTOS E DESPESAS','02. DESPESAS'),
(18,'CONTABILIDADE','DESPESA','01. FLUXO OPERACIONAL','02. CUSTOS E DESPESAS','02. DESPESAS'),
(19,'CONTRIBUIÇÃO PREVIDENCIÁRIA PATRONAL','DESPESA','01. FLUXO OPERACIONAL','02. CUSTOS E DESPESAS','02. DESPESAS'),
(20,'CSLL','DESPESA','01. FLUXO OPERACIONAL','02. CUSTOS E DESPESAS','02. DESPESAS'),
(21,'CUSTO DE ALIMENTAÇÃO','DESPESA','01. FLUXO OPERACIONAL','02. CUSTOS E DESPESAS','02. DESPESAS'),
(22,'CUSTO DE TRANSPORTE','DESPESA','01. FLUXO OPERACIONAL','02. CUSTOS E DESPESAS','02. DESPESAS'),
(23,'ENERGIA','DESPESA','01. FLUXO OPERACIONAL','02. CUSTOS E DESPESAS','02. DESPESAS'),
(24,'FGTS','DESPESA','01. FLUXO OPERACIONAL','02. CUSTOS E DESPESAS','02. DESPESAS'),
(25,'FOLHA DE PAGAMENTO','DESPESA','01. FLUXO OPERACIONAL','02. CUSTOS E DESPESAS','02. DESPESAS'),
(26,'GPS - RECOLHER','DESPESA','01. FLUXO OPERACIONAL','02. CUSTOS E DESPESAS','02. DESPESAS'),
(27,'IMPOSTO DE RENDA - RECOLHER','DESPESA','01. FLUXO OPERACIONAL','02. CUSTOS E DESPESAS','02. DESPESAS'),
(28,'IPTU','DESPESA','01. FLUXO OPERACIONAL','02. CUSTOS E DESPESAS','02. DESPESAS'),
(29,'IRPJ','DESPESA','01. FLUXO OPERACIONAL','02. CUSTOS E DESPESAS','02. DESPESAS'),
(30,'JUROS','DESPESA','01. FLUXO OPERACIONAL','02. CUSTOS E DESPESAS','02. DESPESAS'),
(31,'LANCHE','DESPESA','01. FLUXO OPERACIONAL','02. CUSTOS E DESPESAS','02. DESPESAS'),
(32,'MANUTENÇÃO DE IMOBILIZADO','DESPESA','01. FLUXO OPERACIONAL','02. CUSTOS E DESPESAS','02. DESPESAS'),
(33,'MATERIAIS DE ESCRITÓRIO','DESPESA','01. FLUXO OPERACIONAL','02. CUSTOS E DESPESAS','02. DESPESAS'),
(34,'MATERIAIS E SERVIÇOS DE LIMPEZA','DESPESA','01. FLUXO OPERACIONAL','02. CUSTOS E DESPESAS','02. DESPESAS'),
(35,'OUTRAS DESP. ADMINISTRATIVAS','DESPESA','01. FLUXO OPERACIONAL','02. CUSTOS E DESPESAS','02. DESPESAS'),
(36,'OUTRAS DESP. FUNCIONÁRIOS','DESPESA','01. FLUXO OPERACIONAL','02. CUSTOS E DESPESAS','02. DESPESAS'),
(37,'OUTROS TRIBUTOS OU TAXAS','DESPESA','01. FLUXO OPERACIONAL','02. CUSTOS E DESPESAS','02. DESPESAS'),
(38,'PLANOS DE TELEFONE','DESPESA','01. FLUXO OPERACIONAL','02. CUSTOS E DESPESAS','02. DESPESAS'),
(39,'RESCISÃO CONTRATUAL','DESPESA','01. FLUXO OPERACIONAL','02. CUSTOS E DESPESAS','02. DESPESAS'),
(40,'SERVIÇO DE ÁGUA','DESPESA','01. FLUXO OPERACIONAL','02. CUSTOS E DESPESAS','02. DESPESAS'),
(41,'SERVIÇO DE ANÁLISE DE CRÉDITO','DESPESA','01. FLUXO OPERACIONAL','02. CUSTOS E DESPESAS','02. DESPESAS'),
(42,'SERVIÇOS DE SEGURANÇA','DESPESA','01. FLUXO OPERACIONAL','02. CUSTOS E DESPESAS','02. DESPESAS'),
(43,'SINDICATO - FUNCIONÁRIO','DESPESA','01. FLUXO OPERACIONAL','02. CUSTOS E DESPESAS','02. DESPESAS'),
(44,'SISTEMAS GERENCIAIS','DESPESA','01. FLUXO OPERACIONAL','02. CUSTOS E DESPESAS','02. DESPESAS'),
(45,'SOFTWARES DA OPERAÇÃO','DESPESA','01. FLUXO OPERACIONAL','02. CUSTOS E DESPESAS','02. DESPESAS'),
(46,'TARIFAS BANCÁRIAS','DESPESA','01. FLUXO OPERACIONAL','02. CUSTOS E DESPESAS','02. DESPESAS'),
(47,'COMPRA DE BENS E IMOBILIZADOS','DESPESA','02. FLUXO INVESTIMENTO','01. INVESTIMENTOS IMOBILIZADO','01. AQUISIÇÃO DE MATERIAIS'),
(48,'VENDA DE BENS E IMOBILIZADOS','RECEITA','02. FLUXO INVESTIMENTO','01. INVESTIMENTOS IMOBILIZADO','01. AQUISIÇÃO DE MATERIAIS'),
(49,'INVESTIMENTO EM MELHORIAS','DESPESA','02. FLUXO INVESTIMENTO','01. INVESTIMENTOS IMOBILIZADO','02. INVESTIMENTO EM INSTALAÇÕES'),
(50,'APLICAÇÕES REALIZADAS','DESPESA','02. FLUXO INVESTIMENTO','02. APLICAÇÕES','01. APLICAÇÕES'),
(51,'RESGATE DE TÍTULOS','RECEITA','02. FLUXO INVESTIMENTO','02. APLICAÇÕES','01. APLICAÇÕES'),
(52,'IMPOSTOS SOBRE APLICAÇÕES FINANCEIRAS IMEDIATAS','DESPESA','02. FLUXO INVESTIMENTO','02. APLICAÇÕES','02. APLICAÇÕES DE LIQUIDEZ IMEDIATA'),
(53,'RENDIMENTO SOBRE APLICAÇÕES IMEDIATAS','RECEITA','02. FLUXO INVESTIMENTO','02. APLICAÇÕES','02. APLICAÇÕES DE LIQUIDEZ IMEDIATA'),
(54,'ENTRADA EMPRÉSTIMOS BANCÁRIOS','RECEITA','03. FLUXO FINANCIAMENTO','01. SALDO EMPRÉSTIMO','02. CAPITAL TERCEIRO'),
(55,'PAGAMENTO DE EMPRÉSTIMOS BANCÁRIOS','DESPESA','03. FLUXO FINANCIAMENTO','01. SALDO EMPRÉSTIMO','02. CAPITAL TERCEIRO'),
(56,'CAPITAL SOCIAL','RECEITA','03. FLUXO FINANCIAMENTO','01. SÓCIOS','01. CAPITAL PRÓPRIO'),
(57,'DIVIDENDOS','DESPESA','03. FLUXO FINANCIAMENTO','01. SÓCIOS','01. CAPITAL PRÓPRIO'),
(58,'ENTRADA DE MÚTUOS SÓCIOS','RECEITA','03. FLUXO FINANCIAMENTO','02. SALDO MÚTUO SÓCIOS','01. CAPITAL PRÓPRIO'),
(59,'SAÍDA DE MÚTUOS SÓCIOS','DESPESA','03. FLUXO FINANCIAMENTO','02. SALDO MÚTUO SÓCIOS','01. CAPITAL PRÓPRIO'),
(60,'ENTRADA DE MÚTUOS TERCEIROS','RECEITA','03. FLUXO FINANCIAMENTO','02. SALDO MÚTUO TERCEIROS','02. CAPITAL TERCEIRO'),
(61,'SAÍDA DE MÚTUOS TERCEIROS','DESPESA','03. FLUXO FINANCIAMENTO','02. SALDO MÚTUO TERCEIROS','02. CAPITAL TERCEIRO'),
(62,'OUTRAS ENTRADAS','RECEITA','03. FLUXO FINANCIAMENTO','03. OUTROS','01. OUTROS'),
(63,'OUTRAS SAÍDAS','DESPESA','03. FLUXO FINANCIAMENTO','03. OUTROS','01. OUTROS'),
(64,'ENTRADA DE TRANSFERÊNCIA','RECEITA','04. TRANSFERÊNCIAS','01. TRANSFERÊNCIA ENTRE CONTAS','01. TRANSFERÊNCIA ENTRE CONTAS'),
(65,'SAÍDA DE TRANSFERÊNCIA','DESPESA','04. TRANSFERÊNCIAS','01. TRANSFERÊNCIA ENTRE CONTAS','01. TRANSFERÊNCIA ENTRE CONTAS'),
(66,'DESPESAS DE VIAGEM','DESPESA','01. FLUXO OPERACIONAL','02. CUSTOS E DESPESAS','02. DESPESAS'),
(67,'MANUTENÇÃO DE VEÍCULOS','DESPESA','01. FLUXO OPERACIONAL','02. CUSTOS E DESPESAS','02. DESPESAS'),
(68,'FRETE','DESPESA','01. FLUXO OPERACIONAL','02. CUSTOS E DESPESAS','02. DESPESAS'),
(69,'COMBUSTÍVEL','DESPESA','01. FLUXO OPERACIONAL','02. CUSTOS E DESPESAS','02. DESPESAS'),
(70,'ENTRADA DE TRANSFERÊNCIA ENTRE CONTAS','RECEITA','04. TRANSFERÊNCIAS','01. TRANSFERÊNCIA ENTRE CONTAS','01. TRANSFERÊNCIA ENTRE CONTAS'),
(71,'SAÍDA DE TRANSFERÊNCIA ENTRE CONTAS','DESPESA','04. TRANSFERÊNCIAS','01. TRANSFERÊNCIA ENTRE CONTAS','01. TRANSFERÊNCIA ENTRE CONTAS'),
(72,'AUDITORIAS PARTICULARES','RECEITA','01. FLUXO OPERACIONAL','01. RECEITA LÍQUIDA','01. RECEITA'),
(73,'MARKETING','DESPESA','01. FLUXO OPERACIONAL','02. CUSTOS E DESPESAS','02. DESPESAS');

update public.categorias_financeiras c
set tipo = p.tipo,
    fluxo = p.fluxo,
    agrupamento = p.agrupamento,
    grupo = p.grupo,
    ordem_plano = p.ordem,
    origem_plano = 'PLANO_DE_CONTAS_2026',
    ativa = true,
    updated_at = now()
from _plano_contas_import p
where upper(trim(c.nome)) = upper(trim(p.nome));

insert into public.categorias_financeiras
  (empresa_id,nome,tipo,ativa,fluxo,agrupamento,grupo,ordem_plano,origem_plano,created_at,updated_at)
select e.id,p.nome,p.tipo,true,p.fluxo,p.agrupamento,p.grupo,p.ordem,'PLANO_DE_CONTAS_2026',now(),now()
from public.empresas e
cross join _plano_contas_import p
where e.ativa = true
  and not exists (
    select 1 from public.categorias_financeiras c
    where c.empresa_id=e.id and upper(trim(c.nome))=upper(trim(p.nome))
  );

-- Mantém histórico, mas remove da seleção o cadastro duplicado sem vínculos.
update public.categorias_financeiras
set ativa=false, updated_at=now()
where id='438a8665-de93-440e-a3f2-7dd6e58cf337'
  and nome='Outras Entradas'
  and not exists (select 1 from recebimentos r where r.categoria_id='438a8665-de93-440e-a3f2-7dd6e58cf337' and not r.apagado)
  and not exists (select 1 from despesas d where d.categoria_id='438a8665-de93-440e-a3f2-7dd6e58cf337' and not d.apagado);
