import type { EntityConfig } from '../types/crm'

const clientRelation = { table: 'clientes', labelKeys: ['nome_fantasia','razao_social','cpf_cnpj_original'] }
const contactRelation = { table: 'contatos', labelKeys: ['nome','email','telefone'] }
const opportunityRelation = { table: 'oportunidades', labelKeys: ['titulo'] }
const proposalRelation = { table: 'propostas', labelKeys: ['numero_proposta','observacoes'] }
const contractRelation = { table: 'contratos', labelKeys: ['numero_contrato','external_id'] }
const osRelation = { table: 'ordens_servico', labelKeys: ['numero_os','external_id'] }
const profileRelation = { table: 'profiles', labelKeys: ['nome'], filter: { ativo: true } }
const originRelation = { table: 'crm_listas', valueKey: 'valor', labelKeys: ['valor'], filter: { tipo: 'ORIGEM_ATENDIMENTO', ativo: true } }
const analysisGroupRelation = { table: 'grupos', valueKey: 'nome', labelKeys: ['nome'], filter: { ativo: true } }
const analysisGroupIdRelation = { table: 'grupos', labelKeys: ['nome'], filter: { ativo: true } }
const partnerLabRelation = { table: 'laboratorios_parceiros', labelKeys: ['nome'], filter: { ativo: true } }
const addressRelation = { table: 'enderecos', labelKeys: ['nome_unidade','cidade','logradouro'] }
const leadRelation = { table: 'leads', labelKeys: ['nome','telefone_whatsapp'] }

const clientStatuses=['PROSPECT','CLIENTE ATIVO','CLIENTE INATIVO']
const leadStatuses=['NOVO CONTATO','EM ATENDIMENTO','QUALIFICADO','CONVERTIDO','ENCERRADO']
const opportunityStages=['NOVO CONTATO','QUALIFICAÇÃO','PROPOSTA','NEGOCIAÇÃO','GANHO','PERDIDO']
const opportunityStatuses=['ABERTA','GANHA','PERDIDA','CANCELADA']
const proposalStatuses=['RASCUNHO','ENVIADA','EM NEGOCIAÇÃO','APROVADA','RECUSADA','CANCELADA']
const collectionStatuses=['AGENDADA','EM COLETA','COLETADA','CANCELADA']
const scheduleStatuses=['AGENDADO','CONFIRMADO','REALIZADO','CANCELADO']
const osStatuses=['PRÉ-CADASTRO','AGENDADA','EM ANDAMENTO','CONCLUÍDA','CANCELADA']
const logisticsOptions=['COLETA MINASLAB','ENTREGA/ENVIO PELO CLIENTE','TRANSPORTADORA/TERCEIRO','A DEFINIR']

export const entities: Record<string, EntityConfig> = {
  clientes: { detailBasePath:'/clientes', table:'clientes', title:'Clientes', singular:'cliente', description:'Cadastro mestre de clientes, dados comerciais e status de relacionamento.', searchKeys:['razao_social','nome_fantasia','cpf_cnpj_original','email_principal','telefone_principal'], softDelete:true, hasCreatedBy:true, hasUpdatedBy:true, canDeactivate:true, columns:[{key:'nome_fantasia',label:'Nome fantasia'},{key:'razao_social',label:'Razão social'},{key:'cpf_cnpj_original',label:'CPF/CNPJ'},{key:'telefone_principal',label:'Telefone'},{key:'status_comercial',label:'Status do cliente',format:'status'},{key:'ativo',label:'Ativo',format:'boolean'}], fields:[{key:'tipo_pessoa',label:'Tipo de pessoa',type:'select',options:['PF','PJ']},{key:'cpf_cnpj_original',label:'CPF/CNPJ'},{key:'razao_social',label:'Razão social',required:true},{key:'nome_fantasia',label:'Nome fantasia'},{key:'telefone_principal',label:'Telefone'},{key:'email_principal',label:'E-mail'},{key:'segmento',label:'Segmento'},{key:'origem',label:'Origem',type:'relation',relation:originRelation},{key:'responsavel_comercial_id',label:'Responsável comercial',type:'relation',relation:profileRelation},{key:'status_comercial',label:'Status do cliente',type:'select',options:clientStatuses},{key:'observacoes_comerciais',label:'Observações',type:'textarea',width:'full'},{key:'ativo',label:'Ativo',type:'boolean'}] },
  contatos: { table:'contatos', title:'Contatos', singular:'contato', description:'Pessoas vinculadas aos clientes: solicitantes, responsáveis técnicos, compras e demais contatos.', searchKeys:['nome','telefone','whatsapp','email','funcao_papel'], softDelete:true, hasCreatedBy:true, hasUpdatedBy:true, canDeactivate:true, columns:[{key:'nome',label:'Nome'},{key:'email',label:'E-mail'},{key:'telefone',label:'Telefone'},{key:'whatsapp',label:'WhatsApp'},{key:'funcao_papel',label:'Papel'},{key:'ativo',label:'Ativo',format:'boolean'}], fields:[{key:'cliente_id',label:'Cliente',type:'relation',relation:clientRelation,required:true},{key:'nome',label:'Nome',required:true},{key:'telefone',label:'Telefone'},{key:'whatsapp',label:'WhatsApp'},{key:'email',label:'E-mail'},{key:'funcao_papel',label:'Função / papel'},{key:'principal',label:'Contato principal',type:'boolean'},{key:'ativo',label:'Ativo',type:'boolean'},{key:'observacoes',label:'Observações',type:'textarea',width:'full'}] },
  leads: { detailBasePath:'/leads', table:'leads', title:'Atendimentos comerciais', singular:'atendimento', description:'Entrada única do comercial: primeiro contato, necessidade e evolução até virar oportunidade.', searchKeys:['nome','telefone_whatsapp','origem','assunto','status','tipo_analise'], softDelete:true, hasCreatedBy:true, hasUpdatedBy:true, canDeactivate:true, columns:[{key:'nome',label:'Nome'},{key:'telefone_whatsapp',label:'WhatsApp'},{key:'origem',label:'Origem'},{key:'assunto',label:'Assunto'},{key:'status',label:'Situação',format:'status'},{key:'data_primeiro_atendimento',label:'Primeiro atendimento',format:'datetime'}], fields:[{key:'nome',label:'Nome'},{key:'telefone_whatsapp',label:'WhatsApp'},{key:'origem',label:'Origem',type:'relation',relation:originRelation},{key:'assunto',label:'Assunto'},{key:'status',label:'Situação do atendimento',type:'select',options:leadStatuses},{key:'tipo_analise',label:'Tipo / grupo de análise',type:'relation',relation:analysisGroupRelation},{key:'data_primeiro_atendimento',label:'Primeiro atendimento',type:'datetime'},{key:'resumo',label:'Resumo',type:'textarea',width:'full'},{key:'ativo',label:'Ativo',type:'boolean'}] },
  atendimentos: { table:'atendimentos', title:'Interações', singular:'interação', description:'Histórico cronológico de conversas e contatos. O local principal de consulta é a Timeline do Cliente 360.', searchKeys:['canal','assunto','resumo'], hasCreatedBy:true, canDeactivate:false, columns:[{key:'ocorrido_em',label:'Data/hora',format:'datetime'},{key:'canal',label:'Canal'},{key:'assunto',label:'Assunto'},{key:'resumo',label:'Resumo'}], fields:[{key:'lead_id',label:'Atendimento comercial',type:'relation',relation:leadRelation},{key:'cliente_id',label:'Cliente',type:'relation',relation:clientRelation},{key:'contato_id',label:'Contato',type:'relation',relation:contactRelation},{key:'ocorrido_em',label:'Data/hora',type:'datetime',required:true},{key:'canal',label:'Canal',type:'select',options:['WHATSAPP','TELEFONE','E-MAIL','PRESENCIAL','OUTRO']},{key:'assunto',label:'Assunto'},{key:'resumo',label:'Resumo',type:'textarea',width:'full'},{key:'usuario_id',label:'Usuário',type:'relation',relation:profileRelation}] },
  oportunidades: { detailBasePath:'/oportunidades', table:'oportunidades', title:'Oportunidades', singular:'oportunidade', description:'Negociações qualificadas que avançam pelo pipeline até proposta e fechamento.', searchKeys:['titulo','origem','estagio','status','observacoes'], softDelete:true, hasCreatedBy:true, hasUpdatedBy:true, canDeactivate:true, columns:[{key:'titulo',label:'Oportunidade'},{key:'valor_estimado',label:'Valor estimado',format:'currency'},{key:'estagio',label:'Etapa do pipeline',format:'status'},{key:'logistica_coleta',label:'Logística'},{key:'status',label:'Status',format:'status'}], fields:[{key:'cliente_id',label:'Cliente',type:'relation',relation:clientRelation,required:true},{key:'contato_id',label:'Contato',type:'relation',relation:contactRelation},{key:'titulo',label:'Título',required:true},{key:'responsavel_id',label:'Responsável',type:'relation',relation:profileRelation},{key:'origem',label:'Origem',type:'relation',relation:originRelation},{key:'valor_estimado',label:'Valor estimado',type:'number'},{key:'estagio',label:'Etapa do pipeline',type:'select',options:opportunityStages},{key:'logistica_coleta',label:'Logística de coleta',type:'select',options:logisticsOptions},{key:'previsao_fechamento',label:'Previsão de fechamento',type:'date'},{key:'status',label:'Status da oportunidade',type:'select',options:opportunityStatuses},{key:'observacoes',label:'Observações',type:'textarea',width:'full'},{key:'ativo',label:'Ativo',type:'boolean'}] },
  propostas: { detailBasePath:'/propostas', table:'propostas', title:'Propostas', singular:'proposta', description:'Negociação comercial: proposta, solicitante, valor, logística de coleta, validade e aceite.', searchKeys:['numero_proposta','solicitante_snapshot_nome','status','observacoes'], softDelete:true, hasCreatedBy:true, hasUpdatedBy:true, canDeactivate:true, columns:[{key:'numero_proposta',label:'Nº proposta'},{key:'solicitante_snapshot_nome',label:'Solicitante'},{key:'valor',label:'Valor',format:'currency'},{key:'logistica_coleta',label:'Logística'},{key:'status',label:'Status',format:'status'},{key:'validade',label:'Validade',format:'date'}], fields:[{key:'oportunidade_id',label:'Oportunidade',type:'relation',relation:opportunityRelation,required:true},{key:'cliente_id',label:'Cliente',type:'relation',relation:clientRelation,required:true},{key:'solicitante_contato_id',label:'Solicitante',type:'relation',relation:contactRelation},{key:'numero_proposta',label:'Nº proposta'},{key:'responsavel_comercial_id',label:'Responsável comercial',type:'relation',relation:profileRelation},{key:'valor',label:'Valor',type:'number'},{key:'logistica_coleta',label:'Logística de coleta',type:'select',options:logisticsOptions},{key:'status',label:'Status',type:'select',options:proposalStatuses},{key:'validade',label:'Validade',type:'date'},{key:'data_envio',label:'Data de envio',type:'datetime'},{key:'data_aceite',label:'Data de aceite',type:'datetime'},{key:'periodicidade_proposta',label:'Periodicidade'},{key:'laboratorios_parceiros',label:'Rede de Laboratórios Parceiros',type:'multi_relation',relation:partnerLabRelation,junction:{table:'proposta_laboratorios',parentKey:'proposta_id',relationKey:'laboratorio_id'},width:'full'},{key:'escopo_analitico',label:'Escopo Analítico',type:'multi_relation',relation:analysisGroupIdRelation,junction:{table:'proposta_grupos',parentKey:'proposta_id',relationKey:'grupo_id'},width:'full'},{key:'observacoes',label:'Observações',type:'textarea',width:'full'},{key:'ativo',label:'Ativo',type:'boolean'}] },
  contratos: { table:'contratos', title:'Contratos', singular:'contrato', description:'Continuidade comercial e vínculo com contratos do GerenciaLab.', canCreate:false, canEdit:false, canDeactivate:false, writePermission:'operational.import', searchKeys:['numero_contrato','proposta_origem_referencia','periodicidade','status','external_id'], softDelete:true, columns:[{key:'numero_contrato',label:'Contrato'},{key:'proposta_origem_referencia',label:'Proposta origem'},{key:'periodicidade',label:'Periodicidade'},{key:'status',label:'Status',format:'status'},{key:'data_inicio',label:'Início',format:'date'},{key:'data_fim',label:'Fim',format:'date'}], fields:[{key:'numero_contrato',label:'Nº contrato'},{key:'cliente_id',label:'Cliente',type:'relation',relation:clientRelation},{key:'proposta_origem_referencia',label:'Proposta origem'},{key:'periodicidade',label:'Periodicidade'},{key:'status',label:'Status'},{key:'data_inicio',label:'Data início',type:'date'},{key:'data_fim',label:'Data fim',type:'date'},{key:'external_id',label:'ID GerenciaLab'},{key:'ativo',label:'Ativo',type:'boolean'}] },
  ordens: { detailBasePath:'/ordens-servico', table:'ordens_servico', title:'Ordens de Serviço', singular:'ordem de serviço', description:'Pré-cadastre a OS para programar a coleta. A futura importação do GerenciaLab localizará pelo Nº OS e complementará o mesmo registro, sem duplicar.', canCreate:true, canEdit:true, canDeactivate:false, writePermission:'crm.write', searchKeys:['numero_os','status_os','external_id'], softDelete:true, columns:[{key:'numero_os',label:'Nº OS'},{key:'valor',label:'Valor da OS',format:'currency'},{key:'status_os',label:'Status',format:'status'},{key:'data_agendamento',label:'Data prevista',format:'datetime'},{key:'data_recepcao',label:'Recepção',format:'datetime'},{key:'origem_cadastro',label:'Origem'}], fields:[{key:'numero_os',label:'Nº OS',required:true},{key:'cliente_id',label:'Cliente',type:'relation',relation:clientRelation,required:true},{key:'contrato_id',label:'Contrato (opcional)',type:'relation',relation:contractRelation},{key:'valor',label:'Valor da OS',type:'number'},{key:'status_os',label:'Status da OS',type:'select',options:osStatuses},{key:'data_agendamento',label:'Data prevista',type:'datetime'},{key:'observacoes',label:'Observações',type:'textarea',width:'full'}] },
  agenda: { table:'agendamentos', title:'Agenda', singular:'agendamento', description:'Agenda de coletas, compromissos e execuções relacionadas a clientes e OS.', searchKeys:['titulo','status','descricao'], softDelete:true, columns:[{key:'inicio',label:'Início',format:'datetime'},{key:'fim',label:'Fim',format:'datetime'},{key:'titulo',label:'Título'},{key:'status',label:'Status',format:'status'},{key:'descricao',label:'Descrição'}], fields:[{key:'ordem_servico_id',label:'Ordem de serviço',type:'relation',relation:osRelation},{key:'cliente_id',label:'Cliente',type:'relation',relation:clientRelation},{key:'endereco_id',label:'Endereço',type:'relation',relation:addressRelation},{key:'responsavel_id',label:'Responsável / coletor',type:'relation',relation:profileRelation},{key:'inicio',label:'Início',type:'datetime',required:true},{key:'fim',label:'Fim',type:'datetime'},{key:'status',label:'Status',type:'select',options:scheduleStatuses},{key:'titulo',label:'Título'},{key:'descricao',label:'Descrição',type:'textarea',width:'full'}] },
  coletas: { table:'coletas', title:'Coletas', singular:'coleta', description:'Programação e acompanhamento da coleta vinculada diretamente à Ordem de Serviço.', searchKeys:['status','observacoes'], softDelete:true, columns:[{key:'ocorrida_em',label:'Data/hora',format:'datetime'},{key:'status',label:'Status',format:'status'},{key:'observacoes',label:'Observações'}], fields:[{key:'ordem_servico_id',label:'Ordem de serviço',type:'relation',relation:osRelation,required:true},{key:'coletor_id',label:'Coletor',type:'relation',relation:profileRelation},{key:'ocorrida_em',label:'Data/hora',type:'datetime',required:true},{key:'status',label:'Status da coleta',type:'select',options:collectionStatuses},{key:'observacoes',label:'Observações',type:'textarea',width:'full'}] },
  tarefas: { table:'tarefas', title:'Tarefas', singular:'tarefa', description:'Follow-ups, pendências e ações comerciais vinculadas ao contexto CRM.', searchKeys:['titulo','descricao','status','prioridade'], softDelete:true, hasCreatedBy:true, hasUpdatedBy:false, canDeactivate:true, columns:[{key:'titulo',label:'Tarefa'},{key:'prazo',label:'Prazo',format:'datetime'},{key:'status',label:'Status',format:'status'},{key:'prioridade',label:'Prioridade',format:'status'}], fields:[{key:'cliente_id',label:'Cliente',type:'relation',relation:clientRelation},{key:'oportunidade_id',label:'Oportunidade',type:'relation',relation:opportunityRelation},{key:'proposta_id',label:'Proposta',type:'relation',relation:proposalRelation},{key:'responsavel_id',label:'Responsável',type:'relation',relation:profileRelation},{key:'titulo',label:'Título',required:true},{key:'descricao',label:'Descrição',type:'textarea',width:'full'},{key:'prazo',label:'Prazo',type:'datetime'},{key:'status',label:'Status',type:'select',options:['PENDENTE','EM ANDAMENTO','CONCLUÍDA','CANCELADA']},{key:'prioridade',label:'Prioridade',type:'select',options:['BAIXA','NORMAL','ALTA','URGENTE']},{key:'ativo',label:'Ativo',type:'boolean'}] },
}
