import { useCallback, useEffect, useMemo, useState } from 'react'
import { AlertTriangle, ArrowLeft, CheckCircle2, Clock3, GitCompareArrows, LoaderCircle, PlayCircle, RotateCcw } from 'lucide-react'
import { Link, useParams } from 'react-router-dom'
import { PageShell } from '../../components/ui/PageShell'
import { supabase } from '../../services/supabase'

type ImportRow={id:string;numero_linha:number;status_validacao:string;classificacao_conflito:string|null;entidade_alvo:string|null;erros:unknown;diff:unknown;payload_normalizado:unknown}
type ImportMeta=Record<string,unknown>

function getDiagnostic(meta:ImportMeta|null){const metadata=meta?.metadata;if(!metadata||typeof metadata!=='object'||Array.isArray(metadata))return '';const record=metadata as Record<string,unknown>;const value=record.diagnostico||record.erro_processamento||record.erro_staging;return typeof value==='string'?value:''}
function StatusNotice({meta,rows}:{meta:ImportMeta|null;rows:ImportRow[]}){const status=String(meta?.status??'');const total=Number(meta?.total_linhas??0);const diagnostic=getDiagnostic(meta);const errors=Number(meta?.linhas_com_erro??0)
  if(status==='ERRO'&&(rows.length>0||total>0))return <div className="rounded-2xl border border-red-200 bg-red-50 p-4 text-sm text-red-900"><div className="flex items-start gap-3"><AlertTriangle className="mt-0.5 h-5 w-5 shrink-0"/><div><div className="font-semibold">Importação com erro — revise antes de reenviar</div><p className="mt-1">O arquivo foi recebido, mas a aplicação não terminou. {errors>0?`${errors} linha(s) apresentam erro.`:'Consulte o diagnóstico abaixo.'}</p>{diagnostic&&<p className="mt-2 rounded-lg bg-white/70 p-2 text-xs">{diagnostic}</p>}</div></div></div>
  if(status==='ERRO'||(total===0&&rows.length===0))return <div className="rounded-2xl border border-red-200 bg-red-50 p-4 text-sm text-red-900"><div className="flex items-start gap-3"><AlertTriangle className="mt-0.5 h-5 w-5 shrink-0"/><div><div className="font-semibold">Importação não concluída — reenvie o arquivo</div><p className="mt-1">Nenhuma linha foi gravada no staging. Este arquivo não foi aplicado ao cadastro.</p>{diagnostic&&<p className="mt-2 rounded-lg bg-white/70 p-2 text-xs">{diagnostic}</p>}<Link to="/importacoes" className="mt-3 inline-flex items-center gap-2 rounded-lg border border-red-200 bg-white px-3 py-2 font-semibold"><RotateCcw className="h-4 w-4"/>Voltar e reenviar</Link></div></div></div>
  if(status==='PROCESSANDO')return <div className="rounded-2xl border border-slate-200 bg-blue-50 p-4 text-sm text-blue-900"><div className="flex items-center gap-3"><LoaderCircle className="h-5 w-5 animate-spin"/><div><div className="font-semibold">Processando importação</div><p className="mt-1">A validação e a aplicação estão em andamento.</p></div></div></div>
  if(status==='STAGING')return <div className="rounded-2xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-900"><div className="flex items-start gap-3"><Clock3 className="mt-0.5 h-5 w-5 shrink-0"/><div><div className="font-semibold">Arquivo recebido — processamento pendente</div><p className="mt-1">As linhas estão no staging e ainda não foram aplicadas. Não reenvie o arquivo.</p></div></div></div>
  if(status==='VALIDADA')return <div className="rounded-2xl border border-slate-200 bg-blue-50 p-4 text-sm text-blue-900"><div className="flex items-start gap-3"><CheckCircle2 className="mt-0.5 h-5 w-5 shrink-0"/><div><div className="font-semibold">Arquivo validado</div><p className="mt-1">A validação terminou e a carga está pronta para aplicação.</p></div></div></div>
  if(status==='APLICADA'||status==='APLICADA_PARCIAL')return <div className={`rounded-2xl border p-4 text-sm ${status==='APLICADA'?'border-emerald-200 bg-emerald-50 text-emerald-900':'border-amber-200 bg-amber-50 text-amber-900'}`}><div className="flex items-start gap-3"><CheckCircle2 className="mt-0.5 h-5 w-5 shrink-0"/><div><div className="font-semibold">{status==='APLICADA'?'Importação aplicada com sucesso':'Importação aplicada parcialmente'}</div><p className="mt-1">{status==='APLICADA'?'Os dados desta carga já foram aplicados. Não envie o mesmo arquivo novamente.':'As linhas válidas foram aplicadas. Revise somente as linhas com erro; não reenvie o arquivo inteiro.'}</p></div></div></div>
  return null}

export function ImportacaoDetalhe(){const{id}=useParams();const[meta,setMeta]=useState<ImportMeta|null>(null);const[rows,setRows]=useState<ImportRow[]>([]);const[error,setError]=useState('');const[busy,setBusy]=useState(false)
  const load=useCallback(async()=>{if(!id)return;const[a,b]=await Promise.all([supabase.from('importacoes').select('*').eq('id',id).single(),supabase.from('importacao_linhas').select('id,numero_linha,status_validacao,classificacao_conflito,entidade_alvo,erros,diff,payload_normalizado').eq('importacao_id',id).order('numero_linha',{ascending:true}).limit(1000)]);if(a.error||b.error)setError(a.error?.message||b.error?.message||'Erro');else{setError('');setMeta(a.data as ImportMeta);setRows((b.data??[]) as ImportRow[])}},[id]);useEffect(()=>{void load()},[load])
  const counts=useMemo(()=>({pendentes:rows.filter(r=>r.status_validacao==='PENDENTE').length,validas:rows.filter(r=>['VALIDA','VALIDO'].includes(r.status_validacao)).length,erros:rows.filter(r=>r.status_validacao==='ERRO').length}),[rows])
  async function process(){if(!id)return;setBusy(true);setError('');const{error:rpcError}=await supabase.rpc('crm_process_importacao',{p_importacao_id:id});if(rpcError)setError(rpcError.message);await load();setBusy(false)}
  const status=String(meta?.status??'')
  return <PageShell title={String(meta?.nome_arquivo??'Detalhes da importação')} description="Status real da carga, validação, aplicação e erros por linha." action={<div className="flex gap-2">{status==='STAGING'&&<button disabled={busy} onClick={()=>void process()} className="inline-flex items-center gap-2 rounded-xl bg-teal-700 px-4 py-2.5 text-sm font-semibold text-white disabled:opacity-50">{busy?<LoaderCircle className="h-4 w-4 animate-spin"/>:<PlayCircle className="h-4 w-4"/>}{busy?'Processando...':'Processar agora'}</button>}<Link to="/importacoes" className="inline-flex items-center gap-2 rounded-xl border bg-white px-4 py-2.5 text-sm font-semibold text-slate-600"><ArrowLeft className="h-4 w-4"/>Voltar</Link></div>}>
    {error&&<div className="rounded-xl bg-red-50 p-3 text-sm text-red-700">{error}</div>}<StatusNotice meta={meta} rows={rows}/>
    <section className="grid gap-4 md:grid-cols-5"><Card label="Status" value={status||'—'}/><Card label="Total" value={String(meta?.total_linhas??0)}/><Card label="Aplicadas/Válidas" value={String(meta?.linhas_validas??counts.validas)}/><Card label="Com erro" value={String(meta?.linhas_com_erro??counts.erros)}/><Card label="Pendentes exibidas" value={String(counts.pendentes)}/></section>
    <section className="rounded-3xl border bg-white shadow-sm"><div className="flex items-center gap-2 border-b p-5"><GitCompareArrows className="h-5 w-5 text-teal-700"/><div><h3 className="font-semibold">Resultado por linha</h3>{Number(meta?.total_linhas??0)>1000&&<p className="mt-1 text-xs text-slate-500">Exibindo as primeiras 1.000 linhas. Os totais acima consideram a carga inteira.</p>}</div></div><div className="overflow-x-auto"><table className="min-w-full text-sm"><thead className="bg-slate-50 text-left text-xs uppercase text-slate-500"><tr><th className="px-5 py-3">Linha</th><th className="px-5 py-3">Validação</th><th className="px-5 py-3">Conflito</th><th className="px-5 py-3">Entidade</th><th className="px-5 py-3">Erro / Diff</th></tr></thead><tbody className="divide-y">{rows.length===0?<tr><td colSpan={5} className="p-10 text-center text-slate-500">Nenhuma linha de staging registrada.</td></tr>:rows.map(r=><tr key={r.id}><td className="px-5 py-4">{r.numero_linha}</td><td className="px-5 py-4">{r.status_validacao}</td><td className="px-5 py-4">{r.classificacao_conflito||'—'}</td><td className="px-5 py-4">{r.entidade_alvo||'—'}</td><td className="max-w-md px-5 py-4"><pre className="max-h-28 overflow-auto whitespace-pre-wrap text-xs text-slate-500">{r.erros&&JSON.stringify(r.erros)!=='[]'?JSON.stringify(r.erros,null,2):r.diff?JSON.stringify(r.diff,null,2):'—'}</pre></td></tr>)}</tbody></table></div></section>
  </PageShell>}
function Card({label,value}:{label:string;value:string}){return <article className="rounded-3xl border bg-white p-5 shadow-sm"><div className="text-xs font-semibold uppercase text-slate-400">{label}</div><div className="mt-2 text-xl font-semibold">{value}</div></article>}
