import {useEffect,useMemo,useState} from 'react'
import {CalendarDays,History,MessageSquare,Search,Smile} from 'lucide-react'
import {Link} from 'react-router-dom'
import {PageShell} from '../../components/ui/PageShell'
import {supabase} from '../../services/supabase'

type Hist={id:string;recorrencia_id:string;tipo:string;descricao:string|null;ocorrido_em:string;usuario_id:string|null}
type Rec={id:string;cliente_id:string}
type Nps={id:string;cliente_id:string;nota:number;comentario:string|null;respondido_em:string;responsavel_id:string|null}
type Client={id:string;razao_social:string|null;nome_fantasia:string|null}
type Person={id:string;nome:string|null}
type Event={id:string;cliente_id:string;cliente:string;tipo:string;descricao:string;quando:string;usuario_id:string|null}
type QueryResult<T>={data:T[]|null;error:{message:string}|null}
const PAGE_SIZE=1000
async function fetchAll<T>(makeQuery:(from:number,to:number)=>PromiseLike<QueryResult<T>>){const rows:T[]=[];for(let from=0;;from+=PAGE_SIZE){const result=await makeQuery(from,from+PAGE_SIZE-1);if(result.error)return{data:rows,error:result.error};const batch=(result.data??[]) as T[];rows.push(...batch);if(batch.length<PAGE_SIZE)return{data:rows,error:null}}}

export function PosVendaHistorico(){const[events,setEvents]=useState<Event[]>([]),[people,setPeople]=useState<Person[]>([]),[q,setQ]=useState(''),[type,setType]=useState('TODOS'),[loading,setLoading]=useState(true),[error,setError]=useState('');async function load(){setLoading(true);const[a,b,c,d,e]=await Promise.all([
 fetchAll<Hist>((from,to)=>supabase.from('recorrencias_historico').select('id,recorrencia_id,tipo,descricao,ocorrido_em,usuario_id').order('ocorrido_em',{ascending:false}).range(from,to)),
 fetchAll<Rec>((from,to)=>supabase.from('recorrencias_clientes').select('id,cliente_id').order('id').range(from,to)),
 fetchAll<Nps>((from,to)=>supabase.from('satisfacao_nps').select('id,cliente_id,nota,comentario,respondido_em,responsavel_id').is('deleted_at',null).order('respondido_em',{ascending:false}).range(from,to)),
 fetchAll<Person>((from,to)=>supabase.from('profiles').select('id,nome').order('nome').range(from,to)),
 fetchAll<Client>((from,to)=>supabase.from('clientes').select('id,razao_social,nome_fantasia').is('deleted_at',null).order('id').range(from,to))
]);if(a.error||b.error||c.error||d.error||e.error)setError(a.error?.message||b.error?.message||c.error?.message||d.error?.message||e.error?.message||'Erro ao carregar histórico');else{const recMap=new Map(b.data.map(r=>[r.id,r])),clientMap=new Map(e.data.map(client=>[client.id,client]));const clientName=(id:string)=>{const client=clientMap.get(id);return client?.nome_fantasia||client?.razao_social||'Cliente'};const hist=a.data.map(h=>{const r=recMap.get(h.recorrencia_id);const clienteId=r?.cliente_id||'';return{id:h.id,cliente_id:clienteId,cliente:clientName(clienteId),tipo:h.tipo,descricao:h.descricao||'Ação de pós-venda',quando:h.ocorrido_em,usuario_id:h.usuario_id}});const nps=c.data.map(n=>({id:`nps-${n.id}`,cliente_id:n.cliente_id,cliente:clientName(n.cliente_id),tipo:'NPS',descricao:`Nota ${n.nota}${n.comentario?` — ${n.comentario}`:''}`,quando:n.respondido_em,usuario_id:n.responsavel_id}));setEvents([...hist,...nps].sort((x,y)=>y.quando.localeCompare(x.quando)));setPeople(d.data);setError('')}setLoading(false)}useEffect(()=>{void load()},[])
const filtered=useMemo(()=>events.filter(e=>(type==='TODOS'||e.tipo===type)&&(!q||`${e.cliente} ${e.descricao} ${e.tipo}`.toLowerCase().includes(q.toLowerCase()))),[events,q,type]);const types=Array.from(new Set(events.map(e=>e.tipo))).sort()
return <PageShell title="Pós-venda — Histórico" description="Linha do tempo consolidada de contatos, ajustes, agendamentos e satisfação dos clientes.">{loading?<div className="rounded-3xl border bg-white p-8 text-center text-slate-500">Carregando...</div>:<>{error&&<div className="rounded-xl bg-red-50 p-3 text-red-700">{error}</div>}<section className="rounded-3xl border bg-white p-4 shadow-sm"><div className="grid gap-3 md:grid-cols-[1.4fr_.6fr]"><div className="relative"><Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-slate-400"/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Buscar cliente, ação ou observação..." className="w-full rounded-xl border py-2.5 pl-9 pr-3 text-sm"/></div><select value={type} onChange={e=>setType(e.target.value)} className="rounded-xl border bg-white px-3 py-2.5 text-sm"><option value="TODOS">Todos os tipos</option>{types.map(t=><option key={t}>{t}</option>)}</select></div></section><section className="rounded-3xl border bg-white p-5 shadow-sm"><div className="mb-4 flex items-center gap-2"><History className="h-5 w-5 text-teal-700"/><h3 className="font-bold">Linha do tempo</h3></div>{filtered.length?<div className="space-y-3">{filtered.map(e=><article key={e.id} className="grid gap-3 rounded-2xl border p-4 md:grid-cols-[44px_1fr_auto]"><span className="grid h-11 w-11 place-items-center rounded-full bg-teal-50 text-teal-700">{icon(e.tipo)}</span><div><div className="flex flex-wrap items-center gap-2"><Link to={e.cliente_id?`/clientes/${e.cliente_id}`:'#'} className="font-semibold text-slate-900">{e.cliente}</Link><span className="rounded-full bg-slate-100 px-2 py-1 text-[11px] font-bold text-slate-600">{e.tipo}</span></div><p className="mt-1 text-sm text-slate-600">{e.descricao}</p><p className="mt-1 text-xs text-slate-400">{people.find(p=>p.id===e.usuario_id)?.nome||'Equipe / sistema'}</p></div><time className="text-sm text-slate-500">{new Date(e.quando).toLocaleString('pt-BR')}</time></article>)}</div>:<div className="rounded-2xl bg-slate-50 p-8 text-center text-sm text-slate-500">Nenhum evento encontrado.</div>}</section></>}</PageShell>}
function icon(t:string){if(t==='NPS')return <Smile className="h-5 w-5"/>;if(/AGENDA/i.test(t))return <CalendarDays className="h-5 w-5"/>;if(/CONTATO/i.test(t))return <MessageSquare className="h-5 w-5"/>;return <History className="h-5 w-5"/>}
